import { PrismaClient } from "@prisma/client";
import { seedPremiumRatesStandard } from "./seedPremiumRatesStandard";
import { seedPremiumRates881 } from "./seedPremiumRates881";
import { seedPremiumRates774 } from "./seedPremiumRates774";
import { seedPremiumRates888 } from "./seedPremiumRates888";
import { seedPremiumRates889 } from "./seedPremiumRates889";
import { seedPlan912PremiumRates } from "./seedPremiumRate912";
import { seedPremiumRates887 } from "./seedPremiumRates887";
import { seedRiderPremium714 } from "./seedRiderPremiumRates";
import { seedPPT714 } from "./seedPPT714";
import { seedPPT715 } from "./seedPPT715";
import { seedPPT717 } from "./seedPPT717";
import { seedPPT733 } from "./seedPPT733";
import { seedPPT736 } from "./seedPPT736";
import { seedPPT760 } from "./seedPPT760";
import { seedPPT888 } from "./seedPPT888";
import { seedPPT748 } from "./seedPPT748";
import { seedPPT720 } from "./seedPPT720";
import { seedPPT721 } from "./seedPPT721";
import { seedPPT881 } from "./seedPPT881";
import { seedPPT745 } from "./seedPPT745";
import { seedPPT771 } from "./seedPPT771";
import { seedPPT883 } from "./seedPPT883";
import { seedPPT887 } from "./seedPPT887";
import { seedPPT751 } from "./seedPPT751";
import { seedPPT880 } from "./seedPPT880";

export const seedPremiumRates = async (prisma: PrismaClient) => {
  console.log("Starting Premium Rates seeding...");

  await seedPremiumRatesStandard(prisma);
  await seedPremiumRates881(prisma);
  await seedPremiumRates774(prisma);
  await seedPremiumRates888(prisma);
  await seedPremiumRates889(prisma);
  await seedPlan912PremiumRates(prisma);
  await seedPremiumRates887(prisma);
  await seedRiderPremium714(prisma);
  await seedPPT714(prisma);
  await seedPPT715(prisma);
  await seedPPT717(prisma);
  await seedPPT733(prisma);
  await seedPPT736(prisma);
  await seedPPT760(prisma);
  await seedPPT888(prisma);
  await seedPPT748(prisma);
  await seedPPT720(prisma);
  await seedPPT721(prisma);
  await seedPPT881(prisma);
  await seedPPT745(prisma);
  await seedPPT771(prisma);
  await seedPPT883(prisma);
  await seedPPT887(prisma);
  await seedPPT751(prisma);
  await seedPPT880(prisma);

  console.log("Finished Premium Rates seeding.");
};