import { PrismaClient } from "@prisma/client";

export const seedPPT880 = async (prisma: PrismaClient) => {
    const planNumber = "880";

    try {
        console.log("\n==============================================");
        console.log("       PLAN 880 PPT SEEDER");
        console.log("==============================================\n");

        // --------------------------------------------------
        // 1. Find Product
        // --------------------------------------------------

        const product = await prisma.productMaster.findFirst({
            where: {
                planNumber,
            },
        });

        if (!product) {
            console.log(
                `❌ Plan ${planNumber} not found in ProductMaster`
            );
            return;
        }

        console.log(`✔ Product    : ${product.productName}`);
        console.log(`✔ Product ID : ${product.id}`);

        // --------------------------------------------------
        // 2. Plan 880 Rules
        // --------------------------------------------------
        //
        // Policy Term : 12 - 20
        //
        // PPT:
        //
        // Term 12 -> PPT 7
        // Term 13 -> PPT 8
        // Term 14 -> PPT 9
        // Term 15 -> PPT 10
        // Term 16 -> PPT 11
        // Term 17 -> PPT 12
        // Term 18 -> PPT 13
        // Term 19 -> PPT 14
        // Term 20 -> PPT 15
        //
        // Formula:
        //
        // PPT = Policy Term - 5
        //
        // --------------------------------------------------

        const minTerm = 12;
        const maxTerm = 20;

        let totalInserted = 0;
        let totalSkipped = 0;

        // --------------------------------------------------
        // 3. Get existing Plan 880 rates
        // --------------------------------------------------

        const existingRates =
            await prisma.productPremiumRate.findMany({
                where: {
                    productId: product.id,
                },
                select: {
                    id: true,
                    entryAge: true,
                    secondaryAge: true,
                    gender: true,
                    smoker: true,
                    policyTerm: true,
                    premiumPayingTerm: true,
                    option: true,
                    tabularRate: true,
                },
                orderBy: [
                    {
                        entryAge: "asc",
                    },
                    {
                        policyTerm: "asc",
                    },
                ],
            });

        console.log(
            `✔ Existing Plan 880 records: ${existingRates.length}`
        );

        // --------------------------------------------------
        // 4. Only use original records
        // --------------------------------------------------
        //
        // PPT must be NULL in the source record.
        //
        // This prevents the seeder from using records that
        // were already generated by this seeder.
        //
        // --------------------------------------------------

        const sourceRates = existingRates.filter(
            (rate) =>
                rate.premiumPayingTerm === null &&
                rate.policyTerm >= minTerm &&
                rate.policyTerm <= maxTerm
        );

        console.log(
            `✔ Source records found: ${sourceRates.length}`
        );

        // --------------------------------------------------
        // 5. Process every source record
        // --------------------------------------------------

        for (const sourceRate of sourceRates) {
            const policyTerm = sourceRate.policyTerm;

            // ------------------------------------------------
            // PPT = Policy Term - 5
            // ------------------------------------------------

            const premiumPayingTerm =
                policyTerm - 5;

            // Safety validation
            if (
                premiumPayingTerm < 7 ||
                premiumPayingTerm > 15
            ) {
                console.log(
                    `⚠️ Invalid PPT mapping | Term ${policyTerm} | PPT ${premiumPayingTerm}`
                );

                continue;
            }

            // ------------------------------------------------
            // Check duplicate
            // ------------------------------------------------

            const existing =
                await prisma.productPremiumRate.findFirst({
                    where: {
                        productId: product.id,

                        entryAge:
                            sourceRate.entryAge,

                        secondaryAge:
                            sourceRate.secondaryAge,

                        gender:
                            sourceRate.gender,

                        smoker:
                            sourceRate.smoker,

                        policyTerm,

                        premiumPayingTerm,

                        option:
                            sourceRate.option,
                    },
                });

            if (existing) {
                totalSkipped++;
                continue;
            }

            // ------------------------------------------------
            // Insert PPT record
            // ------------------------------------------------

            await prisma.productPremiumRate.create({
                data: {
                    productId: product.id,

                    entryAge:
                        sourceRate.entryAge,

                    secondaryAge:
                        sourceRate.secondaryAge,

                    gender:
                        sourceRate.gender,

                    smoker:
                        sourceRate.smoker,

                    policyTerm,

                    premiumPayingTerm,

                    option:
                        sourceRate.option,

                    // Preserve original tabular rate
                    tabularRate:
                        sourceRate.tabularRate,
                },
            });

            totalInserted++;

            const smokerLabel =
                sourceRate.smoker === true
                    ? "Smoker"
                    : sourceRate.smoker === false
                        ? "Non-Smoker"
                        : "Smoker NULL";

            console.log(
                `✔ Age ${sourceRate.entryAge} | Term ${policyTerm} | PPT ${premiumPayingTerm} | ${smokerLabel}`
            );
        }

        // --------------------------------------------------
        // 6. Final Summary
        // --------------------------------------------------

        console.log("\n==============================================");
        console.log("       PLAN 880 PPT SEEDING COMPLETE");
        console.log("==============================================");

        console.log(`Plan Number : ${planNumber}`);
        console.log(`Product     : ${product.productName}`);
        console.log(`Product ID  : ${product.id}`);

        console.log("\nRules:");
        console.log("Policy Term : 12 - 20");
        console.log("PPT         : 7 - 15");
        console.log("Formula     : PPT = Policy Term - 5");

        console.log("\nMapping:");

        for (
            let term = minTerm;
            term <= maxTerm;
            term++
        ) {
            console.log(
                `Term ${term} → PPT ${term - 5}`
            );
        }

        console.log("\nResults:");
        console.log(`Inserted    : ${totalInserted}`);
        console.log(`Skipped     : ${totalSkipped}`);

        console.log(
            "\n✔ Smoker and Non-Smoker records are processed separately."
        );

        console.log("==============================================\n");
    } catch (error) {
        console.error(
            `❌ Error while seeding PPT for Plan ${planNumber}:`,
            error
        );

        throw error;
    }
};
