export const absliProducts = [
    {
      productName: "ABSLI DigiShield Plan",
      productCode: "109N108V02",
      planNumber: "ABSLI001",
      providerCode: "ABSLI",
      productType: "Protection",
    },
    {
      productName: "ABSLI Salaried Term Plan",
      productCode: "109N126V01",
      planNumber: "ABSLI002",
      providerCode: "ABSLI",
      productType: "Protection",
    },
    {
      productName: "ABSLI Super Term Plan",
      productCode: "109N115V00",
      planNumber: "ABSLI003",
      providerCode: "ABSLI",
      productType: "Protection",
    },
    {
      productName: "ABSLI Life Shield Plan",
      productCode: "109N147V01",
      planNumber: "ABSLI004",
      providerCode: "ABSLI",
      productType: "Protection",
    },
    {
      productName: "ABSLI Saral Jeevan Bima",
      productCode: "109N112V03",
      planNumber: "ABSLI005",
      providerCode: "ABSLI",
      productType: "Protection",
    },
    {
      productName: "ABSLI Protect @ Ease",
      productCode: "109N113V00",
      planNumber: "ABSLI006",
      providerCode: "ABSLI",
      productType: "Protection",
    },
    {
      productName: "ABSLI Assured Income Plan",
      productCode: "109N080V01",
      planNumber: "ABSLI007",
      providerCode: "ABSLI",
      productType: "Savings",
    },
    {
      productName: "ABSLI Assured Savings Plan",
      productCode: "109N097V02",
      planNumber: "ABSLI008",
      providerCode: "ABSLI",
      productType: "Savings",
    },
    {
      productName: "ABSLI Nishchit Aayush Plan",
      productCode: "109N129V01",
      planNumber: "ABSLI009",
      providerCode: "ABSLI",
      productType: "Savings",
    },
    {
      productName: "ABSLI Guaranteed Milestone Plan",
      productCode: "109N136V02",
      planNumber: "ABSLI010",
      providerCode: "ABSLI",
      productType: "Savings",
    },
    {
      productName: "ABSLI Vision LifeIncome Plus",
      productCode: "109N105V02",
      planNumber: "ABSLI011",
      providerCode: "ABSLI",
      productType: "Savings & Guaranteed Income",
    },
    {
      productName: "ABSLI Vision Endowment Plus",
      productCode: "109N077V02",
      planNumber: "ABSLI012",
      providerCode: "ABSLI",
      productType: "Savings",
    },
    {
      productName: "ABSLI Vision Star Plan",
      productCode: "109N079V02",
      planNumber: "ABSLI013",
      providerCode: "ABSLI",
      productType: "Child / Savings",
    },
    {
      productName: "ABSLI Income Suraksha Plan",
      productCode: "109N099V01",
      planNumber: "ABSLI014",
      providerCode: "ABSLI",
      productType: "Savings & Income",
    },
    {
      productName: "ABSLI Bachat Plus",
      productCode: "109N119V00",
      planNumber: "ABSLI015",
      providerCode: "ABSLI",
      productType: "Savings",
    },
    {
      productName: "ABSLI Anmol Akshaya Plan",
      productCode: "109N149V01",
      planNumber: "ABSLI016",
      providerCode: "ABSLI",
      productType: "Guaranteed Income",
    },
    {
      productName: "ABSLI Sukanya Kanya Plan",
      productCode: "109N083V01",
      planNumber: "ABSLI017",
      providerCode: "ABSLI",
      productType: "Child Plan",
    },
    {
      productName: "ABSLI Vision MoneyBack Plus Plan",
      productCode: "109N095V02",
      planNumber: "ABSLI018",
      providerCode: "ABSLI",
      productType: "Money Back",
    },
    {
      productName: "ABSLI Monthly Income Plan",
      productCode: "To Be Verified",
      planNumber: "ABSLI019",
      providerCode: "ABSLI",
      productType: "Income plan",
    },
    {
      productName: "ABSLI Dream Endowment Plan",
      productCode: "109N076V02",
      planNumber: "ABSLI020",
      providerCode: "ABSLI",
      productType: "Endowment",
    },
    {
      productName: "ABSLI SecurePlus Plan",
      productCode: "109N094V02",
      planNumber: "ABSLI021",
      providerCode: "ABSLI",
      productType: "Saving &Protection",
    },
    {
      productName: "ABSLI Wealth Smart Plus",
      productCode: "109L082V01",
      planNumber: "ABSLI022",
      providerCode: "ABSLI",
      productType: "ULIP",
    },
    {
      productName: "ABSLI Salaried Suraksha ULIP",
      productCode: "109L090V02",
      planNumber: "ABSLI023",
      providerCode: "ABSLI",
      productType: "ULIP",
    },
    {
      productName: "ABSLI Fortune Wealth Plan",
      productCode: "109L090V02",
      planNumber: "ABSLI024",
      providerCode: "ABSLI",
      productType: "ULIP",
    },
    {
      productName: "ABSLI Platinum Gain Plan",
      productCode: "109L072V02",
      planNumber: "ABSLI025",
      providerCode: "ABSLI",
      productType: "ULIP",
    },
    {
      productName: "ABSLI Wealth Aspire Plan",
      productCode: "109L067V02",
      planNumber: "ABSLI026",
      providerCode: "ABSLI",
      productType: "ULIP",
    },
    {
      productName: "ABSLI Wealth Secure Plan",
      productCode: "109L070V02",
      planNumber: "ABSLI027",
      providerCode: "ABSLI",
      productType: "ULIP",
    },
    {
      productName: "ABSLI Wealth Max Plan",
      productCode: "109L071V02",
      planNumber: "ABSLI028",
      providerCode: "ABSLI",
      productType: "ULIP",
    },
    {
      productName: "ABSLI Wealth Infinia",
      productCode: "109L069V02",
      planNumber: "ABSLI029",
      providerCode: "ABSLI",
      productType: "ULIP",
    },
    {
      productName: "ABSLI Wealth Assure Plus",
      productCode: "109L134V01",
      planNumber: "ABSLI030",
      providerCode: "ABSLI",
      productType: "ULIP",
    },
    {
      productName: "ABSLI Wealth Creator Plan",
      productCode: "109L063V02",
      planNumber: "ABSLI031",
      providerCode: "ABSLI",
      productType: "ULIP",
    },
    {
      productName: "ABSLI Wealth Premier Plan",
      productCode: "109L066V02",
      planNumber: "ABSLI032",
      providerCode: "ABSLI",
      productType: "ULIP",
    },
    {
      productName: "ABSLI Dream Plan",
      productCode: "109L135V01",
      planNumber: "ABSLI033",
      providerCode: "ABSLI",
      productType: "ULIP",
    },
    {
      productName: "ABSLI Flexi Save Plus Plan",
      productCode: "109L075V02",
      planNumber: "ABSLI034",
      providerCode: "ABSLI",
      productType: "ULIP",
    },
    {
      productName: "ABSLI Wealth Plus",
      productCode: "109L068V02",
      planNumber: "ABSLI035",
      providerCode: "ABSLI",
      productType: "ULIP",
    },
    {
      productName: "ABSLI Wealth Protect Plan",
      productCode: "109L058V00",
      planNumber: "ABSLI036",
      providerCode: "ABSLI",
      productType: "ULIP",
    },
    {
      productName: "ABSLI Wealth 25 Plan",
      productCode: "109L062V02",
      planNumber: "ABSLI037",
      providerCode: "ABSLI",
      productType: "ULIP",
    },
    {
      productName: "ABSLI Wealth Advantage Plan",
      productCode: "109L074V02",
      planNumber: "ABSLI038",
      providerCode: "ABSLI",
      productType: "ULIP",
    },
    {
      productName: "ABSLI Wealth Insurance Plan",
      productCode: "109L106V02",
      planNumber: "ABSLI039",
      providerCode: "ABSLI",
      productType: "ULIP",
    },
    {
      productName: "ABSLI Empower Pension ULIP Plan",
      productCode: "109L065V02",
      planNumber: "ABSLI040",
      providerCode: "ABSLI",
      productType: "Pension",
    },
    {
      productName: "ABSLI Future Gain Plan",
      productCode: "109L078V02",
      planNumber: "ABSLI041",
      providerCode: "ABSLI",
      productType: "ULIP",
    },
    {
      productName: "ABSLI Vision Plan",
      productCode: "109L037V03",
      planNumber: "ABSLI042",
      providerCode: "ABSLI",
      productType: "Savings",
    },
    {
      productName: "ABSLI Foresight Plan",
      productCode: "109L038V02",
      planNumber: "ABSLI043",
      providerCode: "ABSLI",
      productType: "Savings",
    },
    {
      productName: "ABSLI Children's Future Plan",
      productCode: "109L042V02",
      planNumber: "ABSLI044",
      providerCode: "ABSLI",
      productType: "Child Plan",
    },
    {
      productName: "ABSLI Children's Dream Plan",
      productCode: "109N067V03",
      planNumber: "ABSLI045",
      providerCode: "ABSLI",
      productType: "Child Plan",
    },
    {
      productName: "ABSLI Children's Future Solutions Plan",
      productCode: "109N086V03",
      planNumber: "ABSLI046",
      providerCode: "ABSLI",
      productType: "Child Plan",
    },
    {
      productName: "ABSLI Guaranteed Annuity Plus",
      productCode: "109N132V17",
      planNumber: "ABSLI047",
      providerCode: "ABSLI",
      productType: "Retirement / Pension",
    },
    {
      productName: "ABSLI Empower Pension Plan",
      productCode: "109L078V03",
      planNumber: "ABSLI048",
      providerCode: "ABSLI",
      productType: "Retirement / Pension",
    },
    {
      productName: "ABSLI Saral Pension",
      productCode: "109N144V02",
      planNumber: "ABSLI049",
      providerCode: "ABSLI",
      productType: "Retirement / Pension",
    },
    {
      productName: "ABSLI Nishchit Pension Plan",
      productCode: "109N151V04",
      planNumber: "ABSLI050",
      providerCode: "ABSLI",
      productType: "Retirement / Pension",
    },
    {
      productName: "ABSLI Immediate Annuity Plan",
      productCode: "109N056V06",
      planNumber: "ABSLI051",
      providerCode: "ABSLI",
      productType: "Retirement / Pension",
    },
    {
      productName: "ABSLI Pension Plus Plan",
      productCode: "109L026V04",
      planNumber: "ABSLI052",
      providerCode: "ABSLI",
      productType: "Retirement / Pension",
    },
    {
      productName: "ABSLI Retirement Fund Plan",
      productCode: "109N043V02",
      planNumber: "ABSLI053",
      providerCode: "ABSLI",
      productType: "Retirement / Pension",
    },
    {
      productName: "ABSLI Dream Pension Plan",
      productCode: "109N050V02",
      planNumber: "ABSLI054",
      providerCode: "ABSLI",
      productType: "Retirement / Pension",
    },
    {
      productName: "ABSLI Empower Pension ULIP Plan",
      productCode: "109L094V02",
      planNumber: "ABSLI055",
      providerCode: "ABSLI",
      productType: "Retirement ULIP",
    },
    {
      productName: "ABSLI SecureLife Pension Plan",
      productCode: "109L016V03",
      planNumber: "ABSLI056",
      providerCode: "ABSLI",
      productType: "Retirement / Pension",
    },
    {
      productName: "ABSLI Flexi SecureLife Retirement Plan",
      productCode: "109L022V03",
      planNumber: "ABSLI057",
      providerCode: "ABSLI",
      productType: "Retirement / Pension",
    },
    {
      productName: "ABSLI Forever Life Pension Plan",
      productCode: "109N046V03",
      planNumber: "ABSLI058",
      providerCode: "ABSLI",
      productType: "Retirement / pension",
    },
    {
      productName: "ABSLI Sunrise Pension Plan",
      productCode: "109N052V02",
      planNumber: "ABSLI059",
      providerCode: "ABSLI",
      productType: "Retirement / Pension",
    },
    {
      productName: "ABSLI Immediate Annuity Plan",
      productCode: "To Verify",
      planNumber: "ABSLI060",
      providerCode: "ABSLI",
      productType: "Retirement / Annuity",
    },
    {
      productName: "Group Protection Solutions",
      productCode: "To Verify",
      planNumber: "ABSLI061",
      providerCode: "ABSLI",
      productType: "Group Insurance",
    },
    {
      productName: "Group Credit Life Plan",
      productCode: "109N087V01",
      planNumber: "ABSLI062",
      providerCode: "ABSLI",
      productType: "Group Insurance",
    },
    {
      productName: "Group Gratuity Plan",
      productCode: "109N061V01",
      planNumber: "ABSLI063",
      providerCode: "ABSLI",
      productType: "Group Insurance",
    },
    {
      productName: "Group Superannuation Plan",
      productCode: "109N060V01",
      planNumber: "ABSLI064",
      providerCode: "ABSLI",
      productType: "Group Retirement",
    },
    {
      productName: "Group Leave Encashment Plan",
      productCode: "To verify",
      planNumber: "ABSLI065",
      providerCode: "ABSLI",
      productType: "Group Employee Benefit",
    },
    {
      productName: "Group Term Insurance Plan",
      productCode: "109N088V01",
      planNumber: "ABSLI066",
      providerCode: "ABSLI",
      productType: "Group Insurance",
    },
      {
    productName: "ABSLI Fortune Elite Plan",
    productCode: "109L090V05",
    planNumber: "ABSLI067",
    providerCode: "ABSLI",
  },
  {
    productName: "ABSLI Group Assured Pension Plan",
    productCode: "109L119V02",
    planNumber: "ABSLI068",
    providerCode: "ABSLI",
  },
  {
    productName: "ABSLI Accidental Death And Disability Rider",
    productCode: "109B018V03",
    planNumber: "ABSLI069",
    providerCode: "ABSLI",
  },
  {
    productName: "ABSLI Critical Illness Rider",
    productCode: "109B019V03",
    planNumber: "ABSLI070",
    providerCode: "ABSLI",
  },
  {
    productName: "ABSLI Surgical Care Rider",
    productCode: "109B015V03",
    planNumber: "ABSLI071",
    providerCode: "ABSLI",
  },
  {
    productName: "ABSLI Hospital Care Rider",
    productCode: "109B016V03",
    planNumber: "ABSLI072",
    providerCode: "ABSLI",
  },
  {
    productName: "ABSLI Waiver Of Premium Rider",
    productCode: "109A039V01",
    planNumber: "ABSLI073",
    providerCode: "ABSLI",
  },
  {
    productName: "ABSLI Accidental Death Benefit Rider Plus",
    productCode: "109A024V01",
    planNumber: "ABSLI074",
    providerCode: "ABSLI",
  },
  {
    productName: "ABSLI Wealth Aspire Plan",
    productCode: "109L100V03",
    planNumber: "ABSLI075",
    providerCode: "ABSLI",
  },
  {
    productName: "ABSLI Wealth Aspire Plan",
    productCode: "109L100V04",
    planNumber: "ABSLI076",
    providerCode: "ABSLI",
  },
  {
    productName: "ABSLI Group Assured Pension Plan",
    productCode: "109L119V01",
    planNumber: "ABSLI077",
    providerCode: "ABSLI",
  },
  {
    productName: "ABSLI Wealth Assure Plus",
    productCode: "109L120V01",
    planNumber: "ABSLI078",
    providerCode: "ABSLI",
  },

  ];