export const aegonProducts = [
    
  //Aegon Bandhan Life Insurance

  {
    productName: "Bandhan Life iTerm Elite	",
    productCode: "138N095V01",
    planNumber: "BANDHAN001	",
    providerCode: "AEGON",
    productType: "Term Insurance",
  },
  {
    productName: "Bandhan Life iTerm Prime	",
    productCode: "138N084V03",
    planNumber: "BANDHAN002	",
    providerCode: "AEGON",
    productType: "Term Insurance",
  },
  {
    productName: "Bandhan Life iTerm Return of Premium	",
    productCode: "138N094V01",
    planNumber: "BANDHAN003	",
    providerCode: "AEGON",
    productType: "Term Insurance",
  },
  {
    productName: "Bandhan Life iTerm Comfort	",
    productCode: "138N082V01",
    planNumber: "BANDHAN004	",
    providerCode: "AEGON",
    productType: "Term Insurance",
  },
  {
    productName: "Bandhan Life Saral Jeevan Bima	",
    productCode: "138N077V01",
    planNumber: "BANDHAN005	",
    providerCode: "AEGON",
    productType: "Term Insurance",
  },
  {
    productName: "Bandhan Life iInvest Advantage	",
    productCode: "138L090V01",
    planNumber: "BANDHAN006	",
    providerCode: "AEGON",
    productType: "Unit linked insurance plan",
  },
  {
    productName: "Bandhan Life iInvest Ultima	",
    productCode: "138L098V01",
    planNumber: "BANDHAN007	",
    providerCode: "AEGON",
    productType: "Unit linked insurance plan",
  },
  {
    productName: "Bandhan Life iInvest II	",
    productCode: "138L089V01",
    planNumber: "BANDHAN008	",
    providerCode: "AEGON",
    productType: "Unit linked insurance plan",
  },
  {
    productName: "Bandhan Life ULIP Plus	",
    productCode: "138L091V01",
    planNumber: "BANDHAN009	",
    providerCode: "AEGON",
    productType: "Unit linked insurance plan",
  },
  {
    productName: "Bandhan Life Secure ‘N’ Grow	",
    productCode: "138N096V04 & 138N089V01(combine plan)",
    planNumber: "BANDHAN010	",
    providerCode: "AEGON",
    productType: "Savings",
  },
  {
    productName: "Bandhan Life iGuarantee Assurance	",
    productCode: "138N121V01",
    planNumber: "BANDHAN011	",
    providerCode: "AEGON",
    productType: "Savings",
  },
  {
    productName: "Bandhan Life iIncome Wealth	",
    productCode: "138N119V01",
    planNumber: "BANDHAN012	",
    providerCode: "AEGON",
    productType: "Savings",
  },
  {
    productName: "Bandhan Life Guaranteed Income Plan	",
    productCode: "138N118V02",
    planNumber: "BANDHAN013	",
    providerCode: "AEGON",
    productType: "Savings",
  },
  {
    productName: "Bandhan Life Shubh Samriddhi	",
    productCode: "138N097V01",
    planNumber: "BANDHAN014	",
    providerCode: "AEGON",
    productType: "Savings",
  },
  {
    productName: "Bandhan Life iGuarantee Vishwas	",
    productCode: "138N096V04",
    planNumber: "BANDHAN015	",
    providerCode: "AEGON",
    productType: "Savings",
  },
  {
    productName: "Bandhan Life iRetire	",
    productCode: "138N120V01",
    planNumber: "BANDHAN016	",
    providerCode: "AEGON",
    productType: "Retirement",
  },
  {
    productName: "Bandhan Life iInvest Pension	",
    productCode: "138L092V01",
    planNumber: "BANDHAN017	",
    providerCode: "AEGON",
    productType: "Retirement",
  },
  {
    productName: "Bandhan Life Insta Pension Insurance Plan	",
    productCode: "138N011V03",
    planNumber: "BANDHAN018	",
    providerCode: "AEGON",
    productType: "Retirement",
  },
  {
    productName: "Bandhan Life Saral Pension	",
    productCode: "138N078V01",
    planNumber: "BANDHAN019	",
    providerCode: "AEGON",
    productType: "Retirement",
  },
  {
    productName: "Bandhan Life Pradhan Mantri Jeevan Jyoti Bima Yojana	",
    productCode: "138G093V01",
    planNumber: "BANDHAN020	",
    providerCode: "AEGON",
    productType: "Group plan",
  },
  {
    productName: "Bandhan Life Group Care Micro Insurance Plan	",
    productCode: "138N088V01",
    planNumber: "BANDHAN021	",
    providerCode: "AEGON",
    productType: "Group plan",
  },
  {
    productName: "Bandhan Life Group iCredit Insurance Plan	",
    productCode: "138N087V01",
    planNumber: "BANDHAN022	",
    providerCode: "AEGON",
    productType: "Group plan",
  },
  {
    productName: "Bandhan Life Group Credit Protection Insurance Plan	",
    productCode: "138N079V01",
    planNumber: "BANDHAN023	",
    providerCode: "AEGON",
    productType: "Group plan",
  },
  {
    productName: "Bandhan Life Group Term Plus Insurance Plan	",
    productCode: "138N062V01",
    planNumber: "BANDHAN024	",
    providerCode: "AEGON",
    productType: "Group plan",
  },
  {
    productName: "Bandhan Life Akhil Bharat Term Plan	",
    productCode: "138N086V01",
    planNumber: "BANDHAN025	",
    providerCode: "AEGON",
    productType: "Others",
  },
  {
    productName: "Bandhan Life Rural Term Plan	",
    productCode: "138N048V02",
    planNumber: "BANDHAN026	",
    providerCode: "AEGON",
    productType: "Others",
  },
  
];