//Total 204 plans active and withdrawn

export const aegonProducts = [
    
  //Aegon Bandhan Life Insurance Active (26 plans)

  {
    productName: "Bandhan Life iTerm Elite	",
    productCode: "138N095V01",
    planNumber: "BANDHAN001	",
    providerCode: "AEGON",
    productType: "Term Insurance",
  },
  {
    productName: "Bandhan Life iTerm Prime	",
    productCode: "138N084V03",
    planNumber: "BANDHAN002	",
    providerCode: "AEGON",
    productType: "Term Insurance",
  },
  {
    productName: "Bandhan Life iTerm Return of Premium	",
    productCode: "138N094V01",
    planNumber: "BANDHAN003	",
    providerCode: "AEGON",
    productType: "Term Insurance",
  },
  {
    productName: "Bandhan Life iTerm Comfort	",
    productCode: "138N082V01",
    planNumber: "BANDHAN004	",
    providerCode: "AEGON",
    productType: "Term Insurance",
  },
  {
    productName: "Bandhan Life Saral Jeevan Bima	",
    productCode: "138N077V01",
    planNumber: "BANDHAN005	",
    providerCode: "AEGON",
    productType: "Term Insurance",
  },
  {
    productName: "Bandhan Life iInvest Advantage	",
    productCode: "138L090V01",
    planNumber: "BANDHAN006	",
    providerCode: "AEGON",
    productType: "Unit linked insurance plan",
  },
  {
    productName: "Bandhan Life iInvest Ultima	",
    productCode: "138L098V01",
    planNumber: "BANDHAN007	",
    providerCode: "AEGON",
    productType: "Unit linked insurance plan",
  },
  {
    productName: "Bandhan Life iInvest II	",
    productCode: "138L089V01",
    planNumber: "BANDHAN008	",
    providerCode: "AEGON",
    productType: "Unit linked insurance plan",
  },
  {
    productName: "Bandhan Life ULIP Plus	",
    productCode: "138L091V01",
    planNumber: "BANDHAN009	",
    providerCode: "AEGON",
    productType: "Unit linked insurance plan",
  },
  {
    productName: "Bandhan Life Secure ‘N’ Grow	",
    productCode: "138N096V04 & 138N089V01(combine plan)",
    planNumber: "BANDHAN010	",
    providerCode: "AEGON",
    productType: "Savings",
  },
  {
    productName: "Bandhan Life iGuarantee Assurance	",
    productCode: "138N121V01",
    planNumber: "BANDHAN011	",
    providerCode: "AEGON",
    productType: "Savings",
  },
  {
    productName: "Bandhan Life iIncome Wealth	",
    productCode: "138N119V01",
    planNumber: "BANDHAN012	",
    providerCode: "AEGON",
    productType: "Savings",
  },
  {
    productName: "Bandhan Life Guaranteed Income Plan	",
    productCode: "138N118V02",
    planNumber: "BANDHAN013	",
    providerCode: "AEGON",
    productType: "Savings",
  },
  {
    productName: "Bandhan Life Shubh Samriddhi	",
    productCode: "138N097V01",
    planNumber: "BANDHAN014	",
    providerCode: "AEGON",
    productType: "Savings",
  },
  {
    productName: "Bandhan Life iGuarantee Vishwas	",
    productCode: "138N096V04",
    planNumber: "BANDHAN015	",
    providerCode: "AEGON",
    productType: "Savings",
  },
  {
    productName: "Bandhan Life iRetire	",
    productCode: "138N120V01",
    planNumber: "BANDHAN016	",
    providerCode: "AEGON",
    productType: "Retirement",
  },
  {
    productName: "Bandhan Life iInvest Pension	",
    productCode: "138L092V01",
    planNumber: "BANDHAN017	",
    providerCode: "AEGON",
    productType: "Retirement",
  },
  {
    productName: "Bandhan Life Insta Pension Insurance Plan	",
    productCode: "138N011V03",
    planNumber: "BANDHAN018	",
    providerCode: "AEGON",
    productType: "Retirement",
  },
  {
    productName: "Bandhan Life Saral Pension	",
    productCode: "138N078V01",
    planNumber: "BANDHAN019	",
    providerCode: "AEGON",
    productType: "Retirement",
  },
  {
    productName: "Bandhan Life Pradhan Mantri Jeevan Jyoti Bima Yojana	",
    productCode: "138G093V01",
    planNumber: "BANDHAN020	",
    providerCode: "AEGON",
    productType: "Group plan",
  },
  {
    productName: "Bandhan Life Group Care Micro Insurance Plan	",
    productCode: "138N088V01",
    planNumber: "BANDHAN021	",
    providerCode: "AEGON",
    productType: "Group plan",
  },
  {
    productName: "Bandhan Life Group iCredit Insurance Plan	",
    productCode: "138N087V01",
    planNumber: "BANDHAN022	",
    providerCode: "AEGON",
    productType: "Group plan",
  },
  {
    productName: "Bandhan Life Group Credit Protection Insurance Plan	",
    productCode: "138N079V01",
    planNumber: "BANDHAN023	",
    providerCode: "AEGON",
    productType: "Group plan",
  },
  {
    productName: "Bandhan Life Group Term Plus Insurance Plan	",
    productCode: "138N062V01",
    planNumber: "BANDHAN024	",
    providerCode: "AEGON",
    productType: "Group plan",
  },
  {
    productName: "Bandhan Life Akhil Bharat Term Plan	",
    productCode: "138N086V01",
    planNumber: "BANDHAN025	",
    providerCode: "AEGON",
    productType: "Others",
  },
  {
    productName: "Bandhan Life Rural Term Plan	",
    productCode: "138N048V02",
    planNumber: "BANDHAN026	",
    providerCode: "AEGON",
    productType: "Others",
  },

  //Withdrawn Plan from Aegon/Bandhan Site (150 plans)

{productName :'Bandhan Life Protect Gain Plan	',productCode : '138L001V01'	,planNumber : 'BANDHAN027	',providerCode : 'AEGON'},
{productName :'Bandhan Life Protect Gain Plan_EMP	',productCode : '138L001V01'	,planNumber : 'BANDHAN028	',providerCode : 'AEGON'},
{productName :'Bandhan Life Protect Gain Plan	',productCode : '138L001V02'	,planNumber : 'BANDHAN029	',providerCode : 'AEGON'},
{productName :'Bandhan Life Protect Gain Plan_EMP	',productCode : '138L001V02'	,planNumber : 'BANDHAN030	',providerCode : 'AEGON'},
{productName :'Bandhan Life Star Child Plan	',productCode : '138L005V01'	,planNumber : 'BANDHAN031	',providerCode : 'AEGON'},
{productName :'Bandhan Life Star Child Plan_EMP	',productCode : '138L005V01'	,planNumber : 'BANDHAN032	',providerCode : 'AEGON'},
{productName :'Bandhan Life Star Child Plan	',productCode : '138L005V02'	,planNumber : 'BANDHAN033	',providerCode : 'AEGON'},
{productName :'Bandhan Life Star Child Plan_EMP	',productCode : '138L005V02'	,planNumber : 'BANDHAN034	',providerCode : 'AEGON'},
{productName :'Bandhan Life Premium Gain Plan	',productCode : '138L006V01'	,planNumber : 'BANDHAN035	',providerCode : 'AEGON'},
{productName :'Bandhan Life Pension Plan	',productCode : '138L010V01'	,planNumber : 'BANDHAN036	',providerCode : 'AEGON'},
{productName :'Bandhan Life Pension Plan_EMP	',productCode : '138L010V01'	,planNumber : 'BANDHAN037	',providerCode : 'AEGON'},
{productName :'Bandhan Life Pension Plan	',productCode : '138L010V02'	,planNumber : 'BANDHAN038	',providerCode : 'AEGON'},
{productName :'Bandhan Life Pension Plan_EMP	',productCode : '138L010V02'	,planNumber : 'BANDHAN039	',providerCode : 'AEGON'},
{productName :'Bandhan Life Premium Gain Plus Plan	',productCode : '138L013V01'	,planNumber : 'BANDHAN040	',providerCode : 'AEGON'},
{productName :'Bandhan Life Premium Gain Plus Plan_EMP	',productCode : '138L013V01'	,planNumber : 'BANDHAN041	',providerCode : 'AEGON'},
{productName :'Bandhan Life Premium Gain Plus Plan	',productCode : '138L013V02'	,planNumber : 'BANDHAN042	',providerCode : 'AEGON'},
{productName :'Bandhan Life Wealth Protect Plan	',productCode : '138L014V01'	,planNumber : 'BANDHAN043	',providerCode : 'AEGON'},
{productName :'Bandhan Life Wealth Protect Plan_EMP	',productCode : '138L014V01'	,planNumber : 'BANDHAN044	',providerCode : 'AEGON'},
{productName :'Bandhan Life Wealth Protect Plan	',productCode : '138L014V02'	,planNumber : 'BANDHAN045	',providerCode : 'AEGON'},
{productName :'Bandhan Life Wealth Protect Plan_EMP	',productCode : '138L014V02'	,planNumber : 'BANDHAN046	',providerCode : 'AEGON'},
{productName :'Bandhan Life Invest Maximiser Plan	',productCode : '138L015V01'	,planNumber : 'BANDHAN047	',providerCode : 'AEGON'},
{productName :'Bandhan Life Invest Maximiser Plan_EMP	',productCode : '138L015V01'	,planNumber : 'BANDHAN048	',providerCode : 'AEGON'},
{productName :'Bandhan Life Wealth Protect Plus Plan	',productCode : '138L019V01'	,planNumber : 'BANDHAN049	',providerCode : 'AEGON'},
{productName :'Bandhan Life Wealth Protect Plus Plan_EMP	',productCode : '138L019V01'	,planNumber : 'BANDHAN050	',providerCode : 'AEGON'},
{productName :'Bandhan Life Growth Plan	',productCode : '138L020V01'	,planNumber : 'BANDHAN051	',providerCode : 'AEGON'},
{productName :'Bandhan Life Growth Plan_EMP	',productCode : '138L020V01'	,planNumber : 'BANDHAN052	',providerCode : 'AEGON'},
{productName :'Bandhan Life Future Protect Plan	',productCode : '138L023V01'	,planNumber : 'BANDHAN053	',providerCode : 'AEGON'},
{productName :'Bandhan Life Future Protect Insurance Plan_30th Jun’21	',productCode : '138L023V02'	,planNumber : 'BANDHAN054	',providerCode : 'AEGON'},
{productName :'Bandhan Life Future Protect Insurance Plan_25th Feb’20	',productCode : '138L023V02'	,planNumber : 'BANDHAN055	',providerCode : 'AEGON'},
{productName :'Bandhan Life Future Protect Insurance Plan	',productCode : '138L023V02'	,planNumber : 'BANDHAN056	',providerCode : 'AEGON'},
{productName :'Bandhan Life Future Protect Plus Plan	',productCode : '138L024V01'	,planNumber : 'BANDHAN057	',providerCode : 'AEGON'},
{productName :'Bandhan Life Future Protect Plus Insurance Plan	',productCode : '138L024V02'	,planNumber : 'BANDHAN058	',providerCode : 'AEGON'},
{productName :'Bandhan Life Future Protect Plus Insurance Plan	',productCode : '138L024V04'	,planNumber : 'BANDHAN059	',providerCode : 'AEGON'},
{productName :'Bandhan Life Assure Plan	',productCode : '138L025V01'	,planNumber : 'BANDHAN060	',providerCode : 'AEGON'},
{productName :'Bandhan Life Rising Star Plan	',productCode : '138L026V01'	,planNumber : 'BANDHAN061	',providerCode : 'AEGON'},
{productName :'Bandhan Life Rising Star Insurance Plan	',productCode : '138L026V02'	,planNumber : 'BANDHAN062	',providerCode : 'AEGON'},
{productName :'Bandhan Life Rising Star Insurance Plan_30th Jun’21	',productCode : '138L026V02'	,planNumber : 'BANDHAN063	',providerCode : 'AEGON'},
{productName :'Bandhan Life Rising Star Insurance Plan_25th Feb’20	',productCode : '138L026V02'	,planNumber : 'BANDHAN064	',providerCode : 'AEGON'},
{productName :'Bandhan Life Future Protect Premier Plan	',productCode : '138L027V01'	,planNumber : 'BANDHAN065	',providerCode : 'AEGON'},
{productName :'Bandhan Life Assure Plus Plan	',productCode : '138L028V01'	,planNumber : 'BANDHAN066	',providerCode : 'AEGON'},
{productName :'Bandhan Life iMaximize Plan	',productCode : '138L030V01'	,planNumber : 'BANDHAN067	',providerCode : 'AEGON'},
{productName :'Bandhan Life iMaximize Plan	',productCode : '138L030V02'	,planNumber : 'BANDHAN068	',providerCode : 'AEGON'},
{productName :'Bandhan Life iMaximize Insurance Plan	',productCode : '138L030V03'	,planNumber : 'BANDHAN069	',providerCode : 'AEGON'},
{productName :'Bandhan Life iMaximize Insurance Plan_28th Nov’19	',productCode : '138L030V04'	,planNumber : 'BANDHAN070	',providerCode : 'AEGON'},
{productName :'Bandhan Life iMaximize Insurance Plan	',productCode : '138L030V04'	,planNumber : 'BANDHAN071	',providerCode : 'AEGON'},
{productName :'Bandhan Life Group Gratuity Plan	',productCode : '138L033V01'	,planNumber : 'BANDHAN072	',providerCode : 'AEGON'},
{productName :'Bandhan Life Group Gratuity Plan	',productCode : '138L033V02'	,planNumber : 'BANDHAN073	',providerCode : 'AEGON'},
{productName :'Bandhan Life Group Leave encashment Plan	',productCode : '138L037V01'	,planNumber : 'BANDHAN074	',providerCode : 'AEGON'},
{productName :'Bandhan Life Group Leave Encashment Plan	',productCode : '138L037V02'	,planNumber : 'BANDHAN075	',providerCode : 'AEGON'},
{productName :'Bandhan Life iMaximize Single Premium Insurance Plan	',productCode : '138L049V01'	,planNumber : 'BANDHAN076	',providerCode : 'AEGON'},
{productName :'Bandhan Life iMaximize Insurance Single premium Plan	',productCode : '138L049V02'	,planNumber : 'BANDHAN077	',providerCode : 'AEGON'},
{productName :'Bandhan Life iInvest Insurance Plan	',productCode : '138L059V01'	,planNumber : 'BANDHAN078	',providerCode : 'AEGON'},
{productName :'Bandhan Life iInvest Insurance Plan	',productCode : '138L059V02'	,planNumber : 'BANDHAN079	',providerCode : 'AEGON'},
{productName :'Bandhan Life iInvest Insurance Plan_28th Nov’19	',productCode : '138L059V02'	,planNumber : 'BANDHAN080	',providerCode : 'AEGON'},
{productName :'Bandhan Life Increasing Term Plan_EMP	',productCode : '138N002V01'	,planNumber : 'BANDHAN081	',providerCode : 'AEGON'},
{productName :'Bandhan Life Increasing Term Plan	',productCode : '138N002V01'	,planNumber : 'BANDHAN082	',providerCode : 'AEGON'},
{productName :'Bandhan Life Level Term Plan	',productCode : '138N003V01'	,planNumber : 'BANDHAN083	',providerCode : 'AEGON'},
{productName :'Bandhan Life Level Term Plan_EMP	',productCode : '138N003V01'	,planNumber : 'BANDHAN084	',providerCode : 'AEGON'},
{productName :'Bandhan Life Decreasing Term Plan	',productCode : '138N004V01'	,planNumber : 'BANDHAN085	',providerCode : 'AEGON'},
{productName :'Bandhan Life Decreasing Term Plan_EMP	',productCode : '138N004V01'	,planNumber : 'BANDHAN086	',providerCode : 'AEGON'},
{productName :'Bandhan Life Guaranteed Return Plan	',productCode : '138N007V01'	,planNumber : 'BANDHAN087	',providerCode : 'AEGON'},
{productName :'Bandhan Life Guaranteed Return Plan_EMP	',productCode : '138N007V01'	,planNumber : 'BANDHAN088	',providerCode : 'AEGON'},
{productName :'Bandhan Life Rural Term Plan	',productCode : '138N008V01'	,planNumber : 'BANDHAN089	',providerCode : 'AEGON'},
{productName :'Bandhan Life Group Term Plan	',productCode : '138N009V01'	,planNumber : 'BANDHAN090	',providerCode : 'AEGON'},
{productName :'Bandhan Life Group Term Plan	',productCode : '138N009V02'	,planNumber : 'BANDHAN091	',providerCode : 'AEGON'},
{productName :'Bandhan Life Insta Pension Plan	',productCode : '138N011V01'	,planNumber : 'BANDHAN092	',providerCode : 'AEGON'},
{productName :'Bandhan Life Insta Pension Insurance Plan	',productCode : '138N011V02'	,planNumber : 'BANDHAN093	',providerCode : 'AEGON'},
{productName :'Bandhan Life Guaranteed Return Plan - 3	',productCode : '138N012V01'	,planNumber : 'BANDHAN094	',providerCode : 'AEGON'},
{productName :'Bandhan Life Guaranteed Return Plan - 3_EMP	',productCode : '138N012V01'	,planNumber : 'BANDHAN095	',providerCode : 'AEGON'},
{productName :'Bandhan Life iTerm Plan	',productCode : '138N016V01'	,planNumber : 'BANDHAN096	',providerCode : 'AEGON'},
{productName :'Bandhan Life iTerm Plan	',productCode : '138N016V02'	,planNumber : 'BANDHAN097	',providerCode : 'AEGON'},
{productName :'Bandhan Life iTerm Insurance Plan	',productCode : '138N016V03'	,planNumber : 'BANDHAN098	',providerCode : 'AEGON'},
{productName :'Bandhan Life iTerm Insurance Plan	',productCode : '138N016V04'	,planNumber : 'BANDHAN099	',providerCode : 'AEGON'},
{productName :'Bandhan Life iTerm Insurance Plan	',productCode : '138N016V05'	,planNumber : 'BANDHAN100	',providerCode : 'AEGON'},
{productName :'Bandhan Life iTerm Insurance Plan	',productCode : '138N016V06'	,planNumber : 'BANDHAN101	',providerCode : 'AEGON'},
{productName :'Bandhan Life iTerm Insurance Plan_Life Protect	',productCode : '138N016V07'	,planNumber : 'BANDHAN102	',providerCode : 'AEGON'},
{productName :'Bandhan Life iTerm Insurance Plan_Protect Plus	',productCode : '138N016V07'	,planNumber : 'BANDHAN103	',providerCode : 'AEGON'},
{productName :'Bandhan Life iTerm Insurance Plan_Dual Protect	',productCode : '138N016V07'	,planNumber : 'BANDHAN104	',providerCode : 'AEGON'},
{productName :'Bandhan Life AL iTerm Insurance Plan Life Protect Policy Contract 31th Dec 2021	',productCode : '138N016V08'	,planNumber : 'BANDHAN105	',providerCode : 'AEGON'},
{productName :'Bandhan Life AL iTerm Insurance Plan Dual Protect Policy Contract 31th Dec 2021	',productCode : '138N016V08'	,planNumber : 'BANDHAN106	',providerCode : 'AEGON'},
{productName :'Bandhan Life AL iTerm Insurance Plan Protect Plus Policy Contract 31th Dec 2021	',productCode : '138N016V08'	,planNumber : 'BANDHAN107	',providerCode : 'AEGON'},
{productName :'Bandhan Life Group Credit Life	',productCode : '138N017V01'	,planNumber : 'BANDHAN108	',providerCode : 'AEGON'},
{productName :'Bandhan Life Group Credit Life	',productCode : '138N017V02'	,planNumber : 'BANDHAN109	',providerCode : 'AEGON'},
{productName :'Bandhan Life Money Back Plan	',productCode : '138N018V01'	,planNumber : 'BANDHAN110	',providerCode : 'AEGON'},
{productName :'Bandhan Life Money Back Plan_EMP	',productCode : '138N018V01'	,planNumber : 'BANDHAN111	',providerCode : 'AEGON'},
{productName :'Bandhan Life Health Plan	',productCode : '138N021V01'	,planNumber : 'BANDHAN112	',providerCode : 'AEGON'},
{productName :'Bandhan Life Money Back Plus Plan	',productCode : '138N022V01'	,planNumber : 'BANDHAN113	',providerCode : 'AEGON'},
{productName :'Bandhan Life Pension Plan	',productCode : '138N029V01'	,planNumber : 'BANDHAN114	',providerCode : 'AEGON'},
{productName :'Bandhan Life Endowment Plan	',productCode : '138N031V01'	,planNumber : 'BANDHAN115	',providerCode : 'AEGON'},
{productName :'Bandhan Life Endowment Advantage Plan	',productCode : '138N032V01'	,planNumber : 'BANDHAN116	',providerCode : 'AEGON'},
{productName :'Bandhan Life Guaranteed Income Plan	',productCode : '138N034V01'	,planNumber : 'BANDHAN117	',providerCode : 'AEGON'},
{productName :'Bandhan Life Flexi Money Back Plan	',productCode : '138N035V01'	,planNumber : 'BANDHAN118	',providerCode : 'AEGON'},
{productName :'Bandhan Life Educare Plan	',productCode : '138N036V01'	,planNumber : 'BANDHAN119	',providerCode : 'AEGON'},
{productName :'Bandhan Life iHealth Plan	',productCode : '138N038V01'	,planNumber : 'BANDHAN120	',providerCode : 'AEGON'},
{productName :'Bandhan Life iHealth Insurance Plan	',productCode : '138N038V02'	,planNumber : 'BANDHAN121	',providerCode : 'AEGON'},
{productName :'Bandhan Life Term Plan	',productCode : '138N039V01'	,planNumber : 'BANDHAN122	',providerCode : 'AEGON'},
{productName :'Bandhan Life Term Plan	',productCode : '138N039V02'	,planNumber : 'BANDHAN123	',providerCode : 'AEGON'},
{productName :'Bandhan Life Guaranteed Income Plus Plan	',productCode : '138N040V01'	,planNumber : 'BANDHAN124	',providerCode : 'AEGON'},
{productName :'Bandhan Life Guaranteed Income Advantage Insurance Plan	',productCode : '138N040V02'	,planNumber : 'BANDHAN125	',providerCode : 'AEGON'},
{productName :'Bandhan Life EduCare Plus Plan	',productCode : '138N041V01'	,planNumber : 'BANDHAN126	',providerCode : 'AEGON'},
{productName :'Bandhan Life Educare Advantage Insurance Plan	',productCode : '138N041V02'	,planNumber : 'BANDHAN127	',providerCode : 'AEGON'},
{productName :'Bandhan Life Save Guard Plan	',productCode : '138N042V01'	,planNumber : 'BANDHAN128	',providerCode : 'AEGON'},
{productName :'Bandhan Life Assured Returns Plan	',productCode : '138N043V01'	,planNumber : 'BANDHAN129	',providerCode : 'AEGON'},
{productName :'Bandhan Life Flexi Money Back Plus Plan	',productCode : '138N044V01'	,planNumber : 'BANDHAN130	',providerCode : 'AEGON'},
{productName :'Bandhan Life Flexi Money Back Advantage Insurance Plan	',productCode : '138N044V02'	,planNumber : 'BANDHAN131	',providerCode : 'AEGON'},
{productName :'Bandhan Life Easy Protect insurance Plan	',productCode : '138N045V01'	,planNumber : 'BANDHAN132	',providerCode : 'AEGON'},
{productName :'Bandhan Life Guaranteed Growth Insurance Plan	',productCode : '138N046V01'	,planNumber : 'BANDHAN133	',providerCode : 'AEGON'},
{productName :'Bandhan Life iGuarantee Insurance Plan	',productCode : '138N047V01'	,planNumber : 'BANDHAN134	',providerCode : 'AEGON'},
{productName :'Bandhan Life iReturn Insurance Plan	',productCode : '138N050V01'	,planNumber : 'BANDHAN135	',providerCode : 'AEGON'},
{productName :'Bandhan Life Premier Endowment Insurance Plan	',productCode : '138N051V01'	,planNumber : 'BANDHAN136	',providerCode : 'AEGON'},
{productName :'Bandhan Life iSpouse Insurance Plan	',productCode : '138N052V01'	,planNumber : 'BANDHAN137	',providerCode : 'AEGON'},
{productName :'Bandhan Life iCancer Insurance Plan	',productCode : '138N053V01'	,planNumber : 'BANDHAN138	',providerCode : 'AEGON'},
{productName :'Bandhan Life iIncome Insurance Plan	',productCode : '138N054V01'	,planNumber : 'BANDHAN139	',providerCode : 'AEGON'},
{productName :'Bandhan Life Jeevan Shanti Insurance Plan	',productCode : '138N055V01'	,planNumber : 'BANDHAN140	',providerCode : 'AEGON'},
{productName :'Bandhan Life Regular Money Back Income Plan_12th Nov 2019	',productCode : '138N056V01'	,planNumber : 'BANDHAN141	',providerCode : 'AEGON'},
{productName :'Bandhan Life Regular Money Back Insurance Plan	',productCode : '138N056V01'	,planNumber : 'BANDHAN142	',providerCode : 'AEGON'},
{productName :'Bandhan Life Group Credit Shield Insurance Plan	',productCode : '138N057V01'	,planNumber : 'BANDHAN143	',providerCode : 'AEGON'},
{productName :'Bandhan Life Group Credit Shield Insurance Plan_27th Feb’20	',productCode : '138N057V03'	,planNumber : 'BANDHAN144	',providerCode : 'AEGON'},
{productName :'Bandhan Life Group Credit Shield Plan	',productCode : '138N057V03'	,planNumber : 'BANDHAN145	',providerCode : 'AEGON'},
{productName :'Bandhan Life Group Credit Shield Insurance Plan 27th oct 2021	',productCode : '138N057V04'	,planNumber : 'BANDHAN146	',providerCode : 'AEGON'},
{productName :'Bandhan Life Jeevan Riddhi Insurance Plan	',productCode : '138N058V01'	,planNumber : 'BANDHAN147	',providerCode : 'AEGON'},
{productName :'Bandhan Life Jeevan Riddhi Bonus Rates	',productCode : '138N058V01'	,planNumber : 'BANDHAN148	',providerCode : 'AEGON'},
{productName :'Bandhan Life Jeevan Riddhi Insurance Plan	',productCode : '138N058V02'	,planNumber : 'BANDHAN149	',providerCode : 'AEGON'},
{productName :'Bandhan Life iTerm Plus Life Health Plus Option	',productCode : '138N060V01'	,planNumber : 'BANDHAN150	',providerCode : 'AEGON'},
{productName :'Bandhan Life iTerm Plus Life Option	',productCode : '138N060V01'	,planNumber : 'BANDHAN151	',providerCode : 'AEGON'},
{productName :'Bandhan Life iTerm Plus Life and Health Option	',productCode : '138N060V01'	,planNumber : 'BANDHAN152	',providerCode : 'AEGON'},
{productName :'Bandhan Life iTerm Plus Life Health Option	',productCode : '138N060V01'	,planNumber : 'BANDHAN153	',providerCode : 'AEGON'},
{productName :'Bandhan Life iTerm Plus Life & Health Plus Life Policy_12th Nov 2019	',productCode : '138N060V02'	,planNumber : 'BANDHAN154	',providerCode : 'AEGON'},
{productName :'Bandhan Life iTerm Plus Life Plus 29th April’21	',productCode : '138N060V02'	,planNumber : 'BANDHAN155	',providerCode : 'AEGON'},
{productName :'Bandhan Life iTerm Plus Life Plus Policy_12th Nov 2019	',productCode : '138N060V02'	,planNumber : 'BANDHAN156	',providerCode : 'AEGON'},
{productName :'Bandhan Life iTerm Plus Life Health Plus 29th April’21	',productCode : '138N060V02'	,planNumber : 'BANDHAN157	',providerCode : 'AEGON'},
{productName :'Bandhan Life iTerm Plus Life Health 29th April’21	',productCode : '138N060V02'	,planNumber : 'BANDHAN158	',providerCode : 'AEGON'},
{productName :'Bandhan Life iTerm Plus_Life_Policy_12th Nov 2019	',productCode : '138N060V02'	,planNumber : 'BANDHAN159	',providerCode : 'AEGON'},
{productName :'Bandhan Life iTerm Plus Life 29th April’21	',productCode : '138N060V02'	,planNumber : 'BANDHAN160	',providerCode : 'AEGON'},
{productName :'Bandhan Life iTerm Plus Life & Health Policy_12th Nov 2019	',productCode : '138N060V02'	,planNumber : 'BANDHAN161	',providerCode : 'AEGON'},
{productName :'Bandhan Life iTermForever Insurance Plan	',productCode : '138N061V01'	,planNumber : 'BANDHAN162	',providerCode : 'AEGON'},
{productName :'Bandhan Life Group Health Plan	',productCode : '138N063V01'	,planNumber : 'BANDHAN163	',providerCode : 'AEGON'},
{productName :'Bandhan Life POS Guaranteed Return Insurance Plan	',productCode : '138N076V01'	,planNumber : 'BANDHAN164	',providerCode : 'AEGON'},
{productName :'Bandhan Life POS Guaranteed Return Insurance Plan	',productCode : '138N076V02'	,planNumber : 'BANDHAN165	',providerCode : 'AEGON'},
{productName :'Bandhan Life Group Micro Insurance Plan	',productCode : '138N081V01'	,planNumber : 'BANDHAN166	',providerCode : 'AEGON'},
{productName :'Bandhan Life iGuarantee Max Savings	',productCode : '138N083V01'	,planNumber : 'BANDHAN167	',providerCode : 'AEGON'},
{productName :'Bandhan Life iGuarantee Max Savings	',productCode : '138N083V02'	,planNumber : 'BANDHAN168	',providerCode : 'AEGON'},
{productName :'Bandhan Life iGuarantee Max Savings	',productCode : '138N083V03'	,planNumber : 'BANDHAN169	',providerCode : 'AEGON'},
{productName :'Bandhan Life iTerm Prime	',productCode : '138N084V01'	,planNumber : 'BANDHAN170	',providerCode : 'AEGON'},
{productName :'Bandhan Life iTerm Prime	',productCode : '138N084V02'	,planNumber : 'BANDHAN171	',providerCode : 'AEGON'},
{productName :'Bandhan Life Group Credit Safety Insurance Plan	',productCode : '138N085V01'	,planNumber : 'BANDHAN172	',providerCode : 'AEGON'},
{productName :'Bandhan Life iGuarantee Vishwas	',productCode : '138N096V01'	,planNumber : 'BANDHAN173	',providerCode : 'AEGON'},
{productName :'Bandhan Life iGuarantee Vishwas	',productCode : '138N096V02'	,planNumber : 'BANDHAN174	',providerCode : 'AEGON'},
{productName :'Bandhan Life iGuarantee Vishwas	',productCode : '138N096V03'	,planNumber : 'BANDHAN175	',providerCode : 'AEGON'},
{productName :'Bandhan Life Guaranteed Income Plan	',productCode : '138N118V01'	,planNumber : 'BANDHAN176	',providerCode : 'AEGON'},

//Rider plans (28 plans)

{productName :'Bandhan Life CI Rider	',productCode : '138B001V02'	,planNumber : 'BANDHAN177	',providerCode : 'AEGON'},
{productName :'Bandhan Life ADDD Rider	',productCode : '138B002V02'	,planNumber : 'BANDHAN178	',providerCode : 'AEGON'},
{productName :'Bandhan Life Women CI Rider	',productCode : '138B005V01'	,planNumber : 'BANDHAN179	',providerCode : 'AEGON'},
{productName :'Bandhan Life Women CI Rider	',productCode : '138B005V02'	,planNumber : 'BANDHAN180	',providerCode : 'AEGON'},
{productName :'Bandhan Life AD Rider	',productCode : '138B006V01'	,planNumber : 'BANDHAN181	',providerCode : 'AEGON'},
{productName :'Bandhan Life AD Rider	',productCode : '138B006V02'	,planNumber : 'BANDHAN182	',providerCode : 'AEGON'},
{productName :'Bandhan Life AD Rider	',productCode : '138B006V03'	,planNumber : 'BANDHAN183	',providerCode : 'AEGON'},
{productName :'Bandhan Life AD Rider	',productCode : '138B006V04'	,planNumber : 'BANDHAN184	',providerCode : 'AEGON'},
{productName :'Bandhan Life WOP Rider on CI	',productCode : '138B007V01'	,planNumber : 'BANDHAN185	',providerCode : 'AEGON'},
{productName :'Bandhan Life WOP on CI Rider	',productCode : '138B007V02'	,planNumber : 'BANDHAN186	',providerCode : 'AEGON'},
{productName :'Bandhan Life Health CI Rider	',productCode : '138B008V01'	,planNumber : 'BANDHAN187	',providerCode : 'AEGON'},
{productName :'Bandhan Life Health CI Rider	',productCode : '138B008V02'	,planNumber : 'BANDHAN188	',providerCode : 'AEGON'},
{productName :'Bandhan Life Health CI Rider	',productCode : '138B008V02'	,planNumber : 'BANDHAN189	',providerCode : 'AEGON'},
{productName :'Bandhan Life Women Care Rider	',productCode : '138B009V01'	,planNumber : 'BANDHAN190	',providerCode : 'AEGON'},
{productName :'Bandhan Life Women Care Rider	',productCode : '138B009V02'	,planNumber : 'BANDHAN191	',providerCode : 'AEGON'},
{productName :'Bandhan Life TPD Rider	',productCode : '138B010V01'	,planNumber : 'BANDHAN192	',providerCode : 'AEGON'},
{productName :'Bandhan Life TPD Rider	',productCode : '138B010V02'	,planNumber : 'BANDHAN193	',providerCode : 'AEGON'},
{productName :'Bandhan Life iCI Rider	',productCode : '138B011V01'	,planNumber : 'BANDHAN194	',providerCode : 'AEGON'},
{productName :'Bandhan Life WoP on CI Joint Life Rider	',productCode : '138B012V01'	,planNumber : 'BANDHAN195	',providerCode : 'AEGON'},
{productName :'Premium Shield Rider_12th Nov 2019	',productCode : '138B013V01'	,planNumber : 'BANDHAN196	',providerCode : 'AEGON'},
{productName :'Bandhan Life Premium Shield Rider	',productCode : '138B013V01'	,planNumber : 'BANDHAN197	',providerCode : 'AEGON'},
{productName :'Bandhan Life iDisability Rider	',productCode : '138B014V01'	,planNumber : 'BANDHAN198	',providerCode : 'AEGON'},
{productName :'Bandhan Life CI Care Rider	',productCode : '138B016V01'	,planNumber : 'BANDHAN199	',providerCode : 'AEGON'},
{productName :'Bandhan Life CI Rider	',productCode : '138C001V01'	,planNumber : 'BANDHAN200	',providerCode : 'AEGON'},
{productName :'Bandhan Life ADDD Rider	',productCode : '138C002V01'	,planNumber : 'BANDHAN201	',providerCode : 'AEGON'},
{productName :'Bandhan Life ADDD Rider	',productCode : '138C002V01'	,planNumber : 'BANDHAN202	',providerCode : 'AEGON'},
{productName :'Bandhan Life Waiver of premium Rider	',productCode : '138C003V01'	,planNumber : 'BANDHAN203	',providerCode : 'AEGON'},
{productName :'Bandhan Life Term Rider	',productCode : '138C004V01'	,planNumber : 'BANDHAN204	',providerCode : 'AEGON'},
  
  
];