export const ageasProducts = [
// AGEAS_FEDERAL
  {
    productName: "Super Protect Plus Plan",
    productCode: "135N102V01",
    planNumber: "AF-LI-001",
    providerCode: "AGEAS_FEDERAL",
    productType: "Online Plans",
  },
  {
    productName: "Super Protect Plan",
    productCode: "SPP",
    planNumber: "AF-LI-002",
    providerCode: "AGEAS_FEDERAL",
    productType: "Online Plans",
  },
  {
    productName: "Magic Savings Plan",
    productCode: "135N098V04",
    planNumber: "AF-LI-003",
    providerCode: "AGEAS_FEDERAL",
    productType: "Online Plans",
  },
  {
    productName: "Life Advantage Plus Plan",
    productCode: "135N078V02",
    planNumber: "AF-LI-004",
    providerCode: "AGEAS_FEDERAL",
    productType: "Online Plans",
  },
  {
    productName: "Wealth Gain Insurance Plan",
    productCode: "135L047V05",
    planNumber: "AF-LI-005",
    providerCode: "AGEAS_FEDERAL",
    productType: "Online Plans",
  },
  {
    productName: "Wealthsurance Growth Insurance Plan Sp-II",
    productCode: "135L082V02",
    planNumber: "AF-LI-006",
    providerCode: "AGEAS_FEDERAL",
    productType: "Online Plans",
  },
  {
    productName: "Super Cash Plan",
    productCode: "135N099V02",
    planNumber: "AF-LI-007",
    providerCode: "AGEAS_FEDERAL",
    productType: "Online Plans",
  },
  {
    productName: "Assured Income Plan",
    productCode: "135N083V05",
    planNumber: "AF-LI-008",
    providerCode: "AGEAS_FEDERAL",
    productType: "Online Plans",
  },
  {
    productName: "iSecure Plan",
    productCode: "135N088V02",
    planNumber: "AF-LI-009",
    providerCode: "AGEAS_FEDERAL",
    productType: "Online Plans",
  },
  {
    productName: "Young Star Plus Plan",
    productCode: "135N076V03",
    planNumber: "AF-LI-010",
    providerCode: "AGEAS_FEDERAL",
    productType: "Child Insurance Plans",
  },
  {
    productName: "Guaranteed Wealth Plan",
    productCode: "135N048V09",
    planNumber: "AF-LI-011",
    providerCode: "AGEAS_FEDERAL",
    productType: "Saving Insurance Plans",
  },
  {
    productName: "Super Cash Supreme Plan",
    productCode: "135N121V01",
    planNumber: "AF-LI-012",
    providerCode: "AGEAS_FEDERAL",
    productType: "Saving Insurance Plans",
  },
  {
    productName: "Guaranteed Income Plan",
    productCode: "135N050V05",
    planNumber: "AF-LI-013",
    providerCode: "AGEAS_FEDERAL",
    productType: "Saving Insurance Plans",
  },
  {
    productName: "Easy Save Plan",
    productCode: "135N122V01",
    planNumber: "AF-LI-014",
    providerCode: "AGEAS_FEDERAL",
    productType: "Saving Insurance Plans",
  },
  {
    productName: "Saral Jeevan Bima",
    productCode: "135N079V01",
    planNumber: "AF-LI-015",
    providerCode: "AGEAS_FEDERAL",
    productType: "Term Insurance Plans",
  },
  {
    productName: "Termsurance Life Protection Insurance Plan",
    productCode: "135N040V03",
    planNumber: "AF-LI-016",
    providerCode: "AGEAS_FEDERAL",
    productType: "Term Insurance Plans",
  },
  {
    productName: "ProGrow Plan",
    productCode: "135L101V01",
    planNumber: "AF-LI-017",
    providerCode: "AGEAS_FEDERAL",
    productType: "ULIP Insurance Plans",
  },
  {
    productName: "Platinum Wealth Builder Plan",
    productCode: "135L089V02",
    planNumber: "AF-LI-018",
    providerCode: "AGEAS_FEDERAL",
    productType: "ULIP Insurance Plans",
  },
  {
    productName: "Smart Growth Plan",
    productCode: "135L053V07",
    planNumber: "AF-LI-019",
    providerCode: "AGEAS_FEDERAL",
    productType: "ULIP Insurance Plans",
  },
  {
    productName: "Criti Care Plan",
    productCode: "135N085V02",
    planNumber: "AF-LI-020",
    providerCode: "AGEAS_FEDERAL",
    productType: "Health Insurance Plans",
  },
  {
    productName: "Retire Smart Plan",
    productCode: "135N123V01",
    planNumber: "AF-LI-021",
    providerCode: "AGEAS_FEDERAL",
    productType: "Retirement Plan",
  },
  {
    productName: "Saral Pension",
    productCode: "135N080V02",
    planNumber: "AF-LI-022",
    providerCode: "AGEAS_FEDERAL",
    productType: "Retirement Plan",
  },
  {
    productName: "Golden Years Pension Plan",
    productCode: "135L100V01",
    planNumber: "AF-LI-023",
    providerCode: "AGEAS_FEDERAL",
    productType: "Retirement Plan",
  },
  {
    productName: "Group Credit shield Plan II",
    productCode: "135N087V03",
    planNumber: "AF-LI-024",
    providerCode: "AGEAS_FEDERAL",
    productType: "Group Insurance Plans",
  },
  {
    productName: "Group Loan Secure Plan II",
    productCode: "135N081V02",
    planNumber: "AF-LI-025",
    providerCode: "AGEAS_FEDERAL",
    productType: "Group Insurance Plans",
  },
  {
    productName: "Group Term Life Plan II",
    productCode: "135N091V03",
    planNumber: "AF-LI-026",
    providerCode: "AGEAS_FEDERAL",
    productType: "Group Insurance Plans",
  },
  {
    productName: "Group Employee Benefit Plan",
    productCode: "135L052V04",
    planNumber: "AF-LI-027",
    providerCode: "AGEAS_FEDERAL",
    productType: "Group Insurance Plans",
  },
  {
    productName: "Group Microsurance Plan II",
    productCode: "135N086V03",
    planNumber: "AF-LI-028",
    providerCode: "AGEAS_FEDERAL",
    productType: "Group Insurance Plans",
  },
  {
    productName: "Pradhan Mantri Jeevan Jyoti Bima Yojana",
    productCode: "135G090V01",
    planNumber: "AF-LI-029",
    providerCode: "AGEAS_FEDERAL",
    productType: "Group Insurance Plans",
  },

];