export const avivaProducts = [
    

  //AVIVA  Life Insurance

  {
    productName: "Aviva Signature 3D Term Plan - Platinum	",
    productCode: "122N148V02",
    planNumber: "AVIVA001	",
    providerCode: "AVIVA",
    productType: "Term",
  },
  {
    productName: "Aviva Signature 3D Term Plan	",
    productCode: "122N148V02",
    planNumber: "AVIVA002	",
    providerCode: "AVIVA",
    productType: "Term",
  },
  {
    productName: "Aviva Saral Jeevan Bima Plan	",
    productCode: "122N135V01",
    planNumber: "AVIVA003	",
    providerCode: "AVIVA",
    productType: "Term",
  },
  {
    productName: "Aviva LifeShield Advantage	",
    productCode: "ALA",
    planNumber: "AVIVA004	",
    providerCode: "AVIVA",
    productType: "Term",
  },
  {
    productName: "Aviva LifeShield Premium	",
    productCode: "ALP",
    planNumber: "AVIVA005	",
    providerCode: "AVIVA",
    productType: "Term",
  },
  {
    productName: "Aviva Jana Suraksha	",
    productCode: "122N021V02",
    planNumber: "AVIVA006	",
    providerCode: "AVIVA",
    productType: "Term",
  },
  {
    productName: "Aviva Smart Monthly Income Plan	",
    productCode: "122N181V01",
    planNumber: "AVIVA007	",
    providerCode: "AVIVA",
    productType: "Savings",
  },
  {
    productName: "Aviva Signature Guaranteed Income Plan	",
    productCode: "122N146V03",
    planNumber: "AVIVA008	",
    providerCode: "AVIVA",
    productType: "Savings",
  },
  {
    productName: "Aviva Signature Increasing Income Plan	",
    productCode: "122N158V01",
    planNumber: "AVIVA009	",
    providerCode: "AVIVA",
    productType: "Savings",
  },
  {
    productName: "POS Aviva Dhan Suraksha	",
    productCode: "122N132V03",
    planNumber: "AVIVA010	",
    providerCode: "AVIVA",
    productType: "Savings",
  },
  {
    productName: "Aviva Guaranteed Income Plan	",
    productCode: "122N130V01",
    planNumber: "AVIVA011	",
    providerCode: "AVIVA",
    productType: "Savings",
  },
  {
    productName: "Aviva Bharat Parivar Vikas Yojana	",
    productCode: "122N179V02",
    planNumber: "AVIVA012	",
    providerCode: "AVIVA",
    productType: "Life",
  },
  {
    productName: "Aviva Bharat Bal Vikas Yojana	",
    productCode: "122N180V01",
    planNumber: "AVIVA013	",
    providerCode: "AVIVA",
    productType: "Child",
  },
  {
    productName: "Aviva Young Scholar Secure Plan	",
    productCode: "122N092V03",
    planNumber: "AVIVA014	",
    providerCode: "AVIVA",
    productType: "Child",
  },
  {
    productName: "Aviva Affluence	",
    productCode: "122L111V03",
    planNumber: "AVIVA015	",
    providerCode: "AVIVA",
    productType: "ULIP",
  },
  {
    productName: "Aviva Signature Investment Plan	",
    productCode: "122L144V02",
    planNumber: "AVIVA016	",
    providerCode: "AVIVA",
    productType: "ULIP",
  },
  {
    productName: "Aviva Signature Investment Plan - Platinum	",
    productCode: "122L151V01",
    planNumber: "AVIVA017	",
    providerCode: "AVIVA",
    productType: "ULIP",
  },
  {
    productName: "Aviva Signature Investment Plan - Limited Pay	",
    productCode: "122L150V03	",
    planNumber: "AVIVA018	",
    providerCode: "AVIVA",
    productType: "ULIP",
  },
  {
    productName: "Aviva Fortune Plus	",
    productCode: "122L137V02",
    planNumber: "AVIVA019	",
    providerCode: "AVIVA",
    productType: "ULIP",
  },
  {
    productName: "Aviva i-Growth	",
    productCode: "122L106V01",
    planNumber: "AVIVA020	",
    providerCode: "AVIVA",
    productType: "ULIP",
  },
  {
    productName: "Aviva Smart Vitals	",
    productCode: "122N159V02",
    planNumber: "AVIVA021	",
    providerCode: "AVIVA",
    productType: "Health",
  },
  {
    productName: "Aviva Critical Illness Insurance	",
    productCode: "ACII",
    planNumber: "AVIVA022	",
    providerCode: "AVIVA",
    productType: "Health",
  },
  {
    productName: "Aviva Secure Nest Annuity Plan	",
    productCode: "122N182V01",
    planNumber: "AVIVA023	",
    providerCode: "AVIVA",
    productType: "Pension",
  },
  {
    productName: "Aviva Saral Pension Plan	",
    productCode: "122N138V03",
    planNumber: "AVIVA024	",
    providerCode: "AVIVA",
    productType: "Pension",
  },
  {
    productName: "Aviva Affinity Group Term Life	",
    productCode: "122N160V01",
    planNumber: "AVIVA025	",
    providerCode: "AVIVA",
    productType: "Life",
  },
  {
    productName: "Aviva New Corporate Life	",
    productCode: "122N149V01",
    planNumber: "AVIVA026	",
    providerCode: "AVIVA",
    productType: "Life",
  },
  {
    productName: "Aviva Pradhan Mantri Jeevan Jyoti Bima Yojana	",
    productCode: "122G140V01",
    planNumber: "AVIVA027	",
    providerCode: "AVIVA",
    productType: "Life",
  },
  {
    productName: "Aviva Pravasi Bhartiya Jeevan Bima Yojana	",
    productCode: "122N147V02",
    planNumber: "AVIVA028	",
    providerCode: "AVIVA",
    productType: "Life",
  },
  {
    productName: "Aviva Credit Suraksha	",
    productCode: "122N041V02",
    planNumber: "AVIVA029	",
    providerCode: "AVIVA",
    productType: "Life",
  },
  {
    productName: "Aviva Group Life Protect	",
    productCode: "122N080V02",
    planNumber: "AVIVA030	",
    providerCode: "AVIVA",
    productType: "Life",
  },
  {
    productName: "Aviva Group Gratuity Advantage	",
    productCode: "122L090V03",
    planNumber: "AVIVA031	",
    providerCode: "AVIVA",
    productType: "Life",
  },
  {
    productName: "Aviva New Group Leave Encashment Plan	",
    productCode: "122L091V03",
    planNumber: "AVIVA032	",
    providerCode: "AVIVA",
    productType: "Life",
  },
  {
    productName: "Aviva New Traditional Employee Benefit Plan	",
    productCode: "122N102V02",
    planNumber: "AVIVA033	",
    providerCode: "AVIVA",
    productType: "Life",
  },
  {
    productName: "Aviva i-Life Secure",
    productCode: "122N104V02",
    planNumber: "AVIVA034",
    providerCode: "AVIVA",
  },
  {
    productName: "Aviva i-Life",
    productCode: "122N093V02",
    planNumber: "AVIVA035",
    providerCode: "AVIVA",
  },
  {
    productName: "Aviva i-Term Smart",
    productCode: "122N131V01",
    planNumber: "AVIVA036",
    providerCode: "AVIVA",
  },
];