export const axismaxProducts = [
  //AXIS MAX LIFE

  {
    productName: "Axis Max Life Smart Term Plan Plus",
    productCode: "104N127V05",
    planNumber: "AX001",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Smart Secure Plus Plan",
    productCode: "104N118V13",
    planNumber: "AX002",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Smart Term with Additional Returns",
    productCode: "104L128V01",
    planNumber: "AX003",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Flexi Wealth Plan",
    productCode: "104L115V04",
    planNumber: "AX004",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Platinum Wealth Plan",
    productCode: "104L090V07",
    planNumber: "AX005",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Fast Track Super",
    productCode: "104L082V05",
    planNumber: "AX006",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Flexi Wealth Advantage Plan",
    productCode: "104L121V04",
    planNumber: "AX007",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Guaranteed LifeTime Income Plan",
    productCode: "104N076V22",
    planNumber: "AX008",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Saral Pension Plan",
    productCode: "104N119V04",
    planNumber: "AX009",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Online Savings Plan",
    productCode: "104L098V06",
    planNumber: "AX010",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Smart Wealth Advantage Guarantee Plan",
    productCode: "104N124V17",
    planNumber: "AX011",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Smart Wealth Advantage Growth PAR Plan",
    productCode: "104N135V03",
    planNumber: "AX012",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Smart Wealth Income Plan",
    productCode: "104N120V04",
    planNumber: "AX013",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Smart Wealth Plan",
    productCode: "104N116V15",
    planNumber: "AX014",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Savings Advantage Plan",
    productCode: "104N111V04",
    planNumber: "AX015",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Smart Wealth Advantage Guarantee ELITE",
    productCode: "104N138V04",
    planNumber: "AX016",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Smart Value Income & Benefit Enhancer Plan",
    productCode: "104N159V04",
    planNumber: "AX017",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Monthly Income Advantage Plan",
    productCode: "104N091V07",
    planNumber: "AX018",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Secure Earnings & Wellness Advantage Plan",
    productCode: "104N136V03",
    planNumber: "AX019",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Group Saral Suraksha Plan",
    productCode: "104N114V03",
    planNumber: "AX020",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Niva Bupa ReAssure",
    productCode: "NBHHLIP23107V022223",
    planNumber: "AX021",
    providerCode: "NIVA_BUPA",
  },
  {
    productName: "Axis Max Life Smart Wealth Annuity Guaranteed Pension Plan",
    productCode: "104N137V13",
    planNumber: "AX022",
    providerCode: "AXIS_MAX",
    productType: "Pension / Annuity",
  },
  {
    productName: "Axis Max Life Smart Guaranteed Pension Plan",
    productCode: "104N122V25",
    planNumber: "AX023",
    providerCode: "AXIS_MAX",
    productType: "Pension / Retirement",
  },
  {
    productName:
      "Axis Max Life Smart Retirement Income with Sustained Earnings Plan",
    productCode: "104N160V01",
    planNumber: "AX024",
    providerCode: "AXIS_MAX",
    productType: "Retirement / Income",
  },
  {
    productName: "Axis Max Life Saral Jeevan Bima",
    productCode: "",
    planNumber: "AX025",
    providerCode: "AXIS_MAX",
    productType: "Term Insurance",
  },
  {
    productName: "Axis Max Life Smart Total Elite Protection Term Plan",
    productCode: "104N125V09",
    planNumber: "AX026",
    providerCode: "AXIS_MAX",
    productType: "Term Insurance",
  },
  {
    productName: "Axis Max Life Shiksha Plus Super Plan",
    productCode: "104L084V17",
    planNumber: "AX027",
    providerCode: "AXIS_MAX",
    productType: "Child Plan",
  },
  //AXIS BANK LIFE - WITHDRAWN POLICIES (OFFICIAL WITHDRAWN LIST)
  {
    productName: "Axis Max Life Smart Fixed-return Digital Plan",
    productCode: "104N123V06",
    planNumber: "AX028",
    providerCode: "AXIS_MAX",
    productType: "Withdrawn",
  },
  {
    productName: "Axis Max Life Assured Wealth Plan",
    productCode: "104N096V04",
    planNumber: "AX029",
    providerCode: "AXIS_MAX",
    productType: "Withdrawn",
  },
  {
    productName: "Axis Max Life Forever Young Pension Plan",
    productCode: "104L075V04",
    planNumber: "AX030",
    providerCode: "AXIS_MAX",
    productType: "Withdrawn",
  },
  {
    productName: "Axis Max Life MAXIS Super",
    productCode: "104L081V02",
    planNumber: "AX031",
    providerCode: "AXIS_MAX",
    productType: "Withdrawn",
  },
  {
    productName: "Axis Max Life Life Gain Premier",
    productCode: "104N079V03",
    planNumber: "AX032",
    providerCode: "AXIS_MAX",
    productType: "Withdrawn",
  },
  {
    productName: "Axis Max Life Premium Return Protection Plan",
    productCode: "104N079V01",
    planNumber: "AX033",
    providerCode: "AXIS_MAX",
    productType: "Withdrawn",
  },
];
