export const bajajProducts = [
      //BAJAJ LIFE INSURANCE - ACTIVE POLICIES
  {
    productName: "Bajaj Life eTouch II",
    productCode: "116N198V05",
    planNumber: "BJA001",
    providerCode: "BAJAJ_ALLIANZ",
    productType: "Term Insurance",
  },
  {
    productName: "Bajaj Life iSecure II",
    productCode: "116N208V03",
    planNumber: "BJA002",
    providerCode: "BAJAJ_ALLIANZ",
    productType: "Term Insurance",
  },
  {
    productName: "Bajaj Life Smart Secure ROP",
    productCode: "-",
    planNumber: "BJA003",
    providerCode: "BAJAJ_ALLIANZ",
    productType: "Term Insurance",
  },
  {
    productName: "Bajaj Life Superwoman Term",
    productCode: "-",
    planNumber: "BJA004",
    providerCode: "BAJAJ_ALLIANZ",
    productType: "Term Insurance",
  },
  {
    productName: "Bajaj Life Diabetic Term Plan II (Sub 8 HbA1c)",
    productCode: "116N183V01",
    planNumber: "BJA005",
    providerCode: "BAJAJ_ALLIANZ",
    productType: "Term Insurance",
  },
  {
    productName: "Bajaj Life Goal Assure IV",
    productCode: "116L204V01",
    planNumber: "BJA006",
    providerCode: "BAJAJ_ALLIANZ",
    productType: "ULIP",
  },
  {
    productName: "Bajaj Life Smart Wealth Goal VI",
    productCode: "-",
    planNumber: "BJA007",
    providerCode: "BAJAJ_ALLIANZ",
    productType: "ULIP",
  },
  {
    productName: "Bajaj Life Smart Wealth Goal V",
    productCode: "116L201V04",
    planNumber: "BJA008",
    providerCode: "BAJAJ_ALLIANZ",
    productType: "ULIP",
  },
  {
    productName: "Bajaj Life Future Wealth Gain IV",
    productCode: "116L202V01",
    planNumber: "BJA009",
    providerCode: "BAJAJ_ALLIANZ",
    productType: "ULIP",
  },
  {
    productName: "Bajaj Life Invest Protect Goal III",
    productCode: "116L205V01",
    planNumber: "BJA010",
    providerCode: "BAJAJ_ALLIANZ",
    productType: "ULIP",
  },
  {
    productName: "Bajaj Life LongLife Goal III",
    productCode: "116L203V01",
    planNumber: "BJA011",
    providerCode: "BAJAJ_ALLIANZ",
    productType: "ULIP",
  },
  {
    productName: "Bajaj Life Magnum Fortune Plus III",
    productCode: "116L207V02",
    planNumber: "BJA012",
    providerCode: "BAJAJ_ALLIANZ",
    productType: "ULIP",
  },
  {
    productName: "Bajaj Life Goal Based Saving III",
    productCode: "116L206V01",
    planNumber: "BJA013",
    providerCode: "BAJAJ_ALLIANZ",
    productType: "ULIP",
  },
  {
    productName: "Bajaj Life Fortune Gain II",
    productCode: "116L196V04",
    planNumber: "BJA014",
    providerCode: "BAJAJ_ALLIANZ",
    productType: "ULIP",
  },
  {
    productName: "Bajaj Life GAIN",
    productCode: "-",
    planNumber: "BJA015",
    providerCode: "BAJAJ_ALLIANZ",
    productType: "ULIP",
  },
  {
    productName: "Bajaj Life Supreme (Gold variant)",
    productCode: "-",
    planNumber: "BJA016",
    providerCode: "BAJAJ_ALLIANZ",
    productType: "ULIP",
  },
  {
    productName: "Bajaj Life ACE",
    productCode: "116N186V03",
    planNumber: "BJA017",
    providerCode: "BAJAJ_ALLIANZ",
    productType: "Savings / Endowment",
  },
  {
    productName: "Bajaj Life Assured Wealth Goal",
    productCode: "-",
    planNumber: "BJA018",
    providerCode: "BAJAJ_ALLIANZ",
    productType: "Savings / Endowment",
  },
  {
    productName: "Bajaj Life Assured Wealth Goal Platinum",
    productCode: "-",
    planNumber: "BJA019",
    providerCode: "BAJAJ_ALLIANZ",
    productType: "Savings / Endowment",
  },
  {
    productName: "Bajaj Life Guaranteed Wealth Goal",
    productCode: "-",
    planNumber: "BJA020",
    providerCode: "BAJAJ_ALLIANZ",
    productType: "Savings / Endowment",
  },
  {
    productName: "Bajaj Life POS Goal Suraksha",
    productCode: "116N155V13",
    planNumber: "BJA021",
    providerCode: "BAJAJ_ALLIANZ",
    productType: "Savings / Endowment",
  },
  {
    productName: "Bajaj Life Flexi Income Goal Plus (Enhanced Benefit)",
    productCode: "-",
    planNumber: "BJA022",
    providerCode: "BAJAJ_ALLIANZ",
    productType: "Savings / Endowment",
  },
  {
    productName: "Bajaj Life Young Achiever Plan",
    productCode: "-",
    planNumber: "BJA023",
    providerCode: "BAJAJ_ALLIANZ",
    productType: "Child Plan",
  },
  {
    productName: "Bajaj Life Smart Pension",
    productCode: "116L209V03",
    planNumber: "BJA024",
    providerCode: "BAJAJ_ALLIANZ",
    productType: "Retirement / Pension",
  },
  {
    productName: "Bajaj Life Guaranteed Pension Goal II",
    productCode: "116N187V01",
    planNumber: "BJA025",
    providerCode: "BAJAJ_ALLIANZ",
    productType: "Retirement / Pension",
  },
  {
    productName: "Bajaj Life Saral Pension",
    productCode: "-",
    planNumber: "BJA026",
    providerCode: "BAJAJ_ALLIANZ",
    productType: "Retirement / Pension",
  },
  {
    productName: "Bajaj Life Group Secure Shield",
    productCode: "-",
    planNumber: "BJA027",
    providerCode: "BAJAJ_ALLIANZ",
    productType: "Group Life Insurance",
  },
  {
    productName: "Bajaj Life Group Secure Return",
    productCode: "-",
    planNumber: "BJA028",
    providerCode: "BAJAJ_ALLIANZ",
    productType: "Group Life Insurance",
  },
  {
    productName: "Bajaj Life Group Employee Care",
    productCode: "-",
    planNumber: "BJA029",
    providerCode: "BAJAJ_ALLIANZ",
    productType: "Group Life Insurance",
  },
  {
    productName: "Bajaj Life Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY)",
    productCode: "-",
    planNumber: "BJA030",
    providerCode: "BAJAJ_ALLIANZ",
    productType: "Government Scheme",
  },
  {
    productName: "Bajaj Life Family Protect Rider",
    productCode: "116B056V01",
    planNumber: "BJA031",
    providerCode: "BAJAJ_ALLIANZ",
    productType: "Rider",
  },
  {
    productName: "Bajaj Life Accidental Death Benefit Rider",
    productCode: "116B034V02",
    planNumber: "BJA032",
    providerCode: "BAJAJ_ALLIANZ",
    productType: "Rider",
  },
  {
    productName:
      "Bajaj Accidental Permanent Total/Partial Disability Benefit Rider",
    productCode: "116B036V02",
    planNumber: "BJA033",
    providerCode: "BAJAJ_ALLIANZ",
    productType: "Rider",
  },
  {
    productName: "Bajaj Life New Critical Illness Benefit Rider",
    productCode: "116B058V01",
    planNumber: "BJA034",
    providerCode: "BAJAJ_ALLIANZ",
    productType: "Rider",
  },
  //BAJAJ LIFE INSURANCE - INACTIVE / WITHDRAWN POLICIES
  {
    productName: "Bajaj Allianz Lifelong Assure",
    productCode: "116N122V02",
    planNumber: "BJA035",
    providerCode: "BAJAJ_ALLIANZ",
    productType: "Inactive",
  },
  {
    productName: "Bajaj Allianz Life Income Assure",
    productCode: "116N139V02",
    planNumber: "BJA036",
    providerCode: "BAJAJ_ALLIANZ",
    productType: "Inactive",
  },
  {
    productName: "Bajaj Life ACE (Earlier Version)",
    productCode: "116N186V01",
    planNumber: "BJA037",
    providerCode: "BAJAJ_ALLIANZ",
    productType: "Inactive",
  },
];