export const canarahsbcProducts = [
      //CANARA HSBC LIFE INSURANCE
  {
    productName: "Canara HSBC Life Insurance Alpha Wealth",
    productCode: "136L088V01",
    planNumber: "CHI001",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Assured Nivesh",
    productCode: "136N040V01",
    planNumber: "CHI002",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Assured Nivesh",
    productCode: "136N040V02",
    planNumber: "CHI003",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Corporate Group Term Plan",
    productCode: "136N020V02",
    planNumber: "CHI004",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Corporate Group Term Plan",
    productCode: "136N020V03",
    planNumber: "CHI005",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Dream Smart Plan",
    productCode: "136L015V01",
    planNumber: "CHI006",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Dream Smart Plan",
    productCode: "136L015V02",
    planNumber: "CHI007",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Dream Smart Plan",
    productCode: "136L015V03",
    planNumber: "CHI008",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Dream Smart Plan",
    productCode: "136L015V04",
    planNumber: "CHI009",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Easy Bachat Plan",
    productCode: "136N068V01",
    planNumber: "CHI010",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Easy Bachat Plan",
    productCode: "136N068V02",
    planNumber: "CHI011",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Flexi Edge Plan",
    productCode: "136N079V01",
    planNumber: "CHI012",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Future Smart Plan",
    productCode: "136L018V01",
    planNumber: "CHI013",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Future Smart Plan",
    productCode: "136L018V02",
    planNumber: "CHI014",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Future Smart Plan",
    productCode: "136L018V03",
    planNumber: "CHI015",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Future Smart Plan",
    productCode: "136L018V04",
    planNumber: "CHI016",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Group Advantage Term Plan",
    productCode: "136N058V01",
    planNumber: "CHI017",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Group Advantage Term Plus",
    productCode: "136N077V01",
    planNumber: "CHI018",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Group Asset Secure",
    productCode: "136N082V01",
    planNumber: "CHI019",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Group Credit Secure Plan",
    productCode: "136N065V01",
    planNumber: "CHI020",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Group Credit Secure Plan",
    productCode: "136N065V02",
    planNumber: "CHI021",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Group Credit Secure Plan",
    productCode: "136N065V03",
    planNumber: "CHI022",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Group Loan Protection Plan",
    productCode: "136N007V02",
    planNumber: "CHI023",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Group Secure",
    productCode: "136N024V01",
    planNumber: "CHI024",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Group Secure",
    productCode: "136N024V02",
    planNumber: "CHI025",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Group Secure",
    productCode: "136N024V03",
    planNumber: "CHI026",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Group Secure",
    productCode: "136N024V04",
    planNumber: "CHI027",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Group Secure",
    productCode: "136N024V05",
    planNumber: "CHI028",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Group Secure",
    productCode: "136N024V06",
    planNumber: "CHI029",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Group Superannuation Plan",
    productCode: "136N026V01",
    planNumber: "CHI030",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Group Superannuation Plan",
    productCode: "136N026V02",
    planNumber: "CHI031",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Group Term Edge Plan",
    productCode: "136N070V01",
    planNumber: "CHI032",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Group Traditional Benefit Plan",
    productCode: "136N027V01",
    planNumber: "CHI033",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Group Traditional Benefit Plan",
    productCode: "136N027V02",
    planNumber: "CHI034",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Group Traditional Plan",
    productCode: "136N014V01",
    planNumber: "CHI035",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Group Traditional Plan",
    productCode: "136N014V02",
    planNumber: "CHI036",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Grow Smart Plan",
    productCode: "136L016V01",
    planNumber: "CHI037",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Grow Smart Plan",
    productCode: "136L016V02",
    planNumber: "CHI038",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Grow Smart Plan",
    productCode: "136L016V03",
    planNumber: "CHI039",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Grow Smart Plan",
    productCode: "136L016V04",
    planNumber: "CHI040",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Guaranteed Assured Income",
    productCode: "136N097V01",
    planNumber: "CHI041",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Guaranteed Assured Income",
    productCode: "136N097V02",
    planNumber: "CHI042",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Guaranteed Assured Income",
    productCode: "136N097V03",
    planNumber: "CHI043",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Guaranteed Fortune Plan",
    productCode: "136N084V01",
    planNumber: "CHI044",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Guaranteed Fortune Plan",
    productCode: "136N084V02",
    planNumber: "CHI045",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Guaranteed Fortune Plan",
    productCode: "136N084V03",
    planNumber: "CHI046",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Guaranteed Income Advantage Plan",
    productCode: "136N069V01",
    planNumber: "CHI047",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Guaranteed Income Advantage Plan",
    productCode: "136N069V02",
    planNumber: "CHI048",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Guaranteed Income Advantage Plan",
    productCode: "136N069V03",
    planNumber: "CHI049",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Guaranteed Income Plan",
    productCode: "136N067V01",
    planNumber: "CHI050",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Guaranteed Income Plan",
    productCode: "136N067V02",
    planNumber: "CHI051",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Guaranteed Income4Life",
    productCode: "136N074V01",
    planNumber: "CHI052",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Guaranteed One Pay Advantage",
    productCode: "136N083V01",
    planNumber: "CHI053",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Guaranteed Savings Plan",
    productCode: "136N066V01",
    planNumber: "CHI054",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Guaranteed Savings Plan",
    productCode: "136N066V02",
    planNumber: "CHI055",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Guaranteed Suraksha Kavach",
    productCode: "136N078V01",
    planNumber: "CHI056",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Guaranteed Suraksha Kavach",
    productCode: "136N078V02",
    planNumber: "CHI057",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Health First Plan",
    productCode: "136N051V01",
    planNumber: "CHI058",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Health First Plan",
    productCode: "136N051V02",
    planNumber: "CHI059",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Health First Plan",
    productCode: "136N051V03",
    planNumber: "CHI060",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Immediate Pension Plan",
    productCode: "136N003V01",
    planNumber: "CHI061",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Insurance eSmart Term Plan",
    productCode: "136N023V01",
    planNumber: "CHI062",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Insure Smart Plan",
    productCode: "136L019V01",
    planNumber: "CHI063",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Insure Smart Plan",
    productCode: "136L019V02",
    planNumber: "CHI064",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Insure Smart Plan",
    productCode: "136L019V03",
    planNumber: "CHI065",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Insure Smart Plan",
    productCode: "136L019V04",
    planNumber: "CHI066",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Insure Smart Plan",
    productCode: "136L019V05",
    planNumber: "CHI067",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Invest 4G",
    productCode: "136L064V01",
    planNumber: "CHI068",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Invest 4G",
    productCode: "136L064V02",
    planNumber: "CHI069",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Invest 4G",
    productCode: "136L064V03",
    planNumber: "CHI070",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance InvestShield Plan",
    productCode: "136L041V01",
    planNumber: "CHI071",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance InvestShield Plan",
    productCode: "136L041V02",
    planNumber: "CHI072",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance InvestShield Plan",
    productCode: "136L041V03",
    planNumber: "CHI073",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Jeevan Nivesh Plan",
    productCode: "136N047V01",
    planNumber: "CHI074",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Jeevan Nivesh Plan",
    productCode: "136N047V02",
    planNumber: "CHI075",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Money Back Advantage Plan",
    productCode: "136N048V01",
    planNumber: "CHI076",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Money Back Advantage Plan",
    productCode: "136N048V02",
    planNumber: "CHI077",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance POS Easy Bima Plan",
    productCode: "136N049V01",
    planNumber: "CHI078",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance POS Easy Bima Plan",
    productCode: "136N049V02",
    planNumber: "CHI079",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Pension4Life",
    productCode: "136N071V01",
    planNumber: "CHI080",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Pension4Life",
    productCode: "136N071V02",
    planNumber: "CHI081",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Pension4Life",
    productCode: "136N071V03",
    planNumber: "CHI082",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Pension4Life",
    productCode: "136N071V04",
    planNumber: "CHI083",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Pension4Life",
    productCode: "136N071V05",
    planNumber: "CHI084",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Pension4Life",
    productCode: "136N071V06",
    planNumber: "CHI085",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Pension4Life",
    productCode: "136N071V07",
    planNumber: "CHI086",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Pension4Life",
    productCode: "136N071V08",
    planNumber: "CHI087",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Pension4Life",
    productCode: "136N071V09",
    planNumber: "CHI088",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Pension4Life",
    productCode: "136N071V10",
    planNumber: "CHI089",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Platinum Plus Plan",
    productCode: "136L044V01",
    planNumber: "CHI090",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Platinum Plus Plan",
    productCode: "136L044V02",
    planNumber: "CHI091",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName:
      "Canara HSBC Life Insurance Pradhan Mantri Jeevan Jyoti Bima Yojana",
    productCode: "136G046V00",
    planNumber: "CHI092",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Promise4Growth",
    productCode: "136L089V01",
    planNumber: "CHI093",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Pure Term Plan",
    productCode: "136N006V01",
    planNumber: "CHI094",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Retire Smart Plan",
    productCode: "136L013V01",
    planNumber: "CHI095",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Sampoorna Kavach Plan",
    productCode: "136N022V02",
    planNumber: "CHI096",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Samridh Bhavishya",
    productCode: "136N038V01",
    planNumber: "CHI097",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Samridh Bhavishya",
    productCode: "136N038V02",
    planNumber: "CHI098",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Samridh Bhavishya",
    productCode: "136N038V03",
    planNumber: "CHI099",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Saral Bima Plan",
    productCode: "136L010V01",
    planNumber: "CHI100",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Saral Bima Plus",
    productCode: "136L011V01",
    planNumber: "CHI101",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Saral Jeevan Bima",
    productCode: "136N075V01",
    planNumber: "CHI102",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Saral Pension",
    productCode: "136N076V01",
    planNumber: "CHI103",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Saral Pension",
    productCode: "136N076V02",
    planNumber: "CHI104",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Secure Bhavishya Plan",
    productCode: "136L042V01",
    planNumber: "CHI105",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Secure Bhavishya Plan",
    productCode: "136L042V02",
    planNumber: "CHI106",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Secure Bhavishya Plan",
    productCode: "136L042V03",
    planNumber: "CHI107",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Secure Bhavishya Plan",
    productCode: "136L042V04",
    planNumber: "CHI108",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Secure Smart Plan",
    productCode: "136N017V01",
    planNumber: "CHI109",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Secure Smart Plan",
    productCode: "136N0V01",
    planNumber: "CHI110",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Secure Smart Plan",
    productCode: "136N0V02",
    planNumber: "CHI111",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance SecureInvest",
    productCode: "136L092V01",
    planNumber: "CHI112",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Shubh Labh Plan",
    productCode: "136L025V01",
    planNumber: "CHI113",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Shubh Labh Plan",
    productCode: "136L025V02",
    planNumber: "CHI114",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Shubh Labh Plan",
    productCode: "136L025V03",
    planNumber: "CHI115",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Future Income Plan",
    productCode: "136N036V01",
    planNumber: "CHI116",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Future Income Plan",
    productCode: "136N036V02",
    planNumber: "CHI117",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Future Income Plan",
    productCode: "136N036V03",
    planNumber: "CHI118",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Future Plan",
    productCode: "136L037V01",
    planNumber: "CHI119",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Future Plan",
    productCode: "136L037V02",
    planNumber: "CHI120",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Future Plan",
    productCode: "136L037V03",
    planNumber: "CHI121",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Future Plan",
    productCode: "136L037V04",
    planNumber: "CHI122",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Future Plan",
    productCode: "136L037V05",
    planNumber: "CHI123",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Goals Plan",
    productCode: "136L031V01",
    planNumber: "CHI124",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Goals Plan",
    productCode: "136L031V02",
    planNumber: "CHI125",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Goals Plan",
    productCode: "136L031V03",
    planNumber: "CHI126",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Goals Plan",
    productCode: "136L031V04",
    planNumber: "CHI127",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Goals Plan",
    productCode: "136L031V05",
    planNumber: "CHI128",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Guaranteed Pension",
    productCode: "136N086V01",
    planNumber: "CHI129",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Guaranteed Pension",
    productCode: "136N086V02",
    planNumber: "CHI130",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Immediate Income Plan",
    productCode: "136N034V01",
    planNumber: "CHI131",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Immediate Income Plan",
    productCode: "136N034V02",
    planNumber: "CHI132",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Immediate Income Plan",
    productCode: "136N034V03",
    planNumber: "CHI133",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Immediate Income Plan",
    productCode: "136N034V04",
    planNumber: "CHI134",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Junior Plan",
    productCode: "136N043V01",
    planNumber: "CHI135",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Junior Plan",
    productCode: "136N043V02",
    planNumber: "CHI136",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Junior Plan",
    productCode: "136N043V03",
    planNumber: "CHI137",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Lifelong Plan",
    productCode: "136L032V01",
    planNumber: "CHI138",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Lifelong Plan",
    productCode: "136L032V02",
    planNumber: "CHI139",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Lifelong Plan",
    productCode: "136L032V03",
    planNumber: "CHI140",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Lifelong Plan",
    productCode: "136L032V04",
    planNumber: "CHI141",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Lifelong Plan",
    productCode: "136L032V05",
    planNumber: "CHI142",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Monthly Income Plan",
    productCode: "136N029V01",
    planNumber: "CHI143",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Monthly Income Plan",
    productCode: "136N029V02",
    planNumber: "CHI144",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Monthly Income Plan",
    productCode: "136N029V03",
    planNumber: "CHI145",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Monthly Income Plan",
    productCode: "136N029V04",
    planNumber: "CHI146",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart One Pay Plan",
    productCode: "136L030V01",
    planNumber: "CHI147",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart One Pay Plan",
    productCode: "136L030V02",
    planNumber: "CHI148",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Stage Money Back Plan",
    productCode: "136N028V01",
    planNumber: "CHI149",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Suraksha Plan",
    productCode: "136N039V01",
    planNumber: "CHI150",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Suraksha Plan",
    productCode: "136N039V02",
    planNumber: "CHI151",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Suraksha Plan",
    productCode: "136N039V03",
    planNumber: "CHI152",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Suraksha Plan",
    productCode: "136N039V04",
    planNumber: "CHI153",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Vriddhi Plan",
    productCode: "136N035V01",
    planNumber: "CHI154",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Stay Smart Plan",
    productCode: "136L012V01",
    planNumber: "CHI155",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Titanium Plus Plan",
    productCode: "136L063V01",
    planNumber: "CHI156",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Titanium Plus Plan",
    productCode: "136L063V02",
    planNumber: "CHI157",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Titanium Plus Plan",
    productCode: "136L063V03",
    planNumber: "CHI158",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Unit Linked Child Plan",
    productCode: "136L009V01",
    planNumber: "CHI159",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Unit Linked Endowment Plan",
    productCode: "136L002V01",
    planNumber: "CHI160",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName:
      "Canara HSBC Life Insurance Unit Linked Limited Pay Endowment Plan",
    productCode: "136L004V01",
    planNumber: "CHI161",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Unit Linked Pension Plan",
    productCode: "136L005V01",
    planNumber: "CHI162",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Unit Linked Whole Life Plan",
    productCode: "136L001V01",
    planNumber: "CHI163",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Wealth Edge",
    productCode: "136L085V01",
    planNumber: "CHI164",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Wealth Edge",
    productCode: "136L085V02",
    planNumber: "CHI165",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Wealth Edge",
    productCode: "136L085V03",
    planNumber: "CHI166",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Young Term Plan",
    productCode: "136N087V01",
    planNumber: "CHI167",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance Young Term Plan",
    productCode: "136N087V02",
    planNumber: "CHI168",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance iSelect Guaranteed Future",
    productCode: "136N081V01",
    planNumber: "CHI169",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance iSelect Guaranteed Future",
    productCode: "136N081V02",
    planNumber: "CHI170",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance iSelect Guaranteed Future",
    productCode: "136N081V03",
    planNumber: "CHI171",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance iSelect Guaranteed Future",
    productCode: "136N081V04",
    planNumber: "CHI172",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance iSelect Guaranteed Future",
    productCode: "136N081V05",
    planNumber: "CHI173",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance iSelect Guaranteed Future",
    productCode: "136N081V06",
    planNumber: "CHI174",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance iSelect Guaranteed Future Plus",
    productCode: "136N098V01",
    planNumber: "CHI175",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance iSelect Guaranteed Future Plus",
    productCode: "136N098V02",
    planNumber: "CHI176",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance iSelect Guaranteed Future Plus",
    productCode: "136N098V03",
    planNumber: "CHI177",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance iSelect Smart360 Term Plan",
    productCode: "136N080V01",
    planNumber: "CHI178",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance iSelect Star Term Plan",
    productCode: "136N073V01",
    planNumber: "CHI179",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance iSelect Star Term Plan",
    productCode: "136N073V02",
    planNumber: "CHI180",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance iSelect Term Plan",
    productCode: "136N045V01",
    planNumber: "CHI181",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance iSelect Term Plan",
    productCode: "136N045V02",
    planNumber: "CHI182",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance iSelect Term Plan",
    productCode: "136N045V03",
    planNumber: "CHI183",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },
  {
    productName: "Canara HSBC Life Insurance iSelect+ Term Plan",
    productCode: "136N072V01",
    planNumber: "CHI184",
    providerCode: "CANARA_HSBC",
    productType: "Inactive",
  },

];