export const dhflProducts = [
      // DHFL Pramerica Life Insurance Products
  {
    productName: "Pramerica Life U-Protect Plan",
    productCode: "PL-TERM-001",
    planNumber: "PL-TERM-001",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life TruShield Term Plan",
    productCode: "PL-TERM-002",
    planNumber: "PL-TERM-002",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Saral Jeevan Bima",
    productCode: "PL-TERM-003",
    planNumber: "PL-TERM-003",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Family Income Plan",
    productCode: "PL-TERM-004",
    planNumber: "PL-TERM-004",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Family First Plan",
    productCode: "PL-TERM-005",
    planNumber: "PL-TERM-005",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Secure Savings Plan",
    productCode: "PL-SAV-001",
    planNumber: "PL-SAV-001",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Smart Income Plan",
    productCode: "PL-SAV-002",
    planNumber: "PL-SAV-002",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Smart Assure",
    productCode: "PL-SAV-003",
    planNumber: "PL-SAV-003",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Flexi Cash Plan",
    productCode: "PL-SAV-004",
    planNumber: "PL-SAV-004",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Smart Cash Protect",
    productCode: "PL-SAV-005",
    planNumber: "PL-SAV-005",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Roz Sanchay",
    productCode: "PL-SAV-006",
    planNumber: "PL-SAV-006",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Magnum Assure",
    productCode: "PL-SAV-007",
    planNumber: "PL-SAV-007",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Flexi Income Plan",
    productCode: "PL-SAV-008",
    planNumber: "PL-SAV-008",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Signature Wealth",
    productCode: "PL-SAV-009",
    planNumber: "PL-SAV-009",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life RockSolid Future",
    productCode: "PL-SAV-010",
    planNumber: "PL-SAV-010",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Wealth Maximiser",
    productCode: "PL-SAV-011",
    planNumber: "PL-SAV-011",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Wealth+ Ace",
    productCode: "PL-ULIP-001",
    planNumber: "PL-ULIP-001",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Smart Wealth+",
    productCode: "PL-ULIP-002",
    planNumber: "PL-ULIP-002",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Super Investment Plan",
    productCode: "PL-ULIP-003",
    planNumber: "PL-ULIP-003",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Smart Invest",
    productCode: "PL-ULIP-004",
    planNumber: "PL-ULIP-004",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Wealth Enhancer",
    productCode: "PL-ULIP-005",
    planNumber: "PL-ULIP-005",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Wealth Maximiser (ULIP)",
    productCode: "PL-ULIP-006",
    planNumber: "PL-ULIP-006",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Cancer + Heart Shield",
    productCode: "PL-HLTH-001",
    planNumber: "PL-HLTH-001",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Rakshak Smart",
    productCode: "PL-CHLD-001",
    planNumber: "PL-CHLD-001",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Rakshak Gold",
    productCode: "PL-CHLD-002",
    planNumber: "PL-CHLD-002",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Smart Fee Protect Plan",
    productCode: "PL-CHLD-003",
    planNumber: "PL-CHLD-003",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Saral Pension",
    productCode: "PL-RET-001",
    planNumber: "PL-RET-001",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life NextGen Pension Plan",
    productCode: "PL-RET-002",
    planNumber: "PL-RET-002",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Aajeevan Samriddhi",
    productCode: "PL-RET-003",
    planNumber: "PL-RET-003",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Group Total Protection",
    productCode: "PL-GRP-001",
    planNumber: "PL-GRP-001",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Group Credit Shield",
    productCode: "PL-GRP-002",
    planNumber: "PL-GRP-002",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Group Term Plan",
    productCode: "PL-GRP-003",
    planNumber: "PL-GRP-003",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Sarv Suraksha (Group Micro)",
    productCode: "PL-GRP-004",
    planNumber: "PL-GRP-004",
    providerCode: "DHFL_PRAMERICA",
  },

  //Withdrawn plans

  {productName :'Pramerica Life Smart Wealth Plus',productCode : '140L041V03',planNumber : 'DHFL_034',providerCode : 'DHFL_PRAMERICA'},
  {productName :'Pramerica Life Smart Invest 1 Up',productCode : '140L084V01',planNumber : 'DHFL_035',providerCode : 'DHFL_PRAMERICA'},
  {productName :'Pramerica Life Smart Income',productCode : '140N044V03',planNumber : 'DHFL_036',providerCode : 'DHFL_PRAMERICA'},
  {productName :'Pramerica Life Ezee Wealth+',productCode : '140L023V01',planNumber : 'DHFL_037',providerCode : 'DHFL_PRAMERICA'},
  {productName :'Pramerica Life Flexi E-Term',productCode : '140N055V02',planNumber : 'DHFL_038',providerCode : 'DHFL_PRAMERICA'},
  {productName :'Corona Rakshak Policy, Pramerica Life',productCode : '140N063V01',planNumber : 'DHFL_039',providerCode : 'DHFL_PRAMERICA'},
  {productName :'Pramerica Life Dengue Shield',productCode : '140N051V02',planNumber : 'DHFL_040',providerCode : 'DHFL_PRAMERICA'},
  {productName :'Pramerica Life Group Health Kavach',productCode : '140N061V01',planNumber : 'DHFL_041',providerCode : 'DHFL_PRAMERICA'},
  {productName :'Pramerica Life Guaranteed Return on Wealth',productCode : '140N077V01',planNumber : 'DHFL_042',providerCode : 'DHFL_PRAMERICA'},
  {productName :'Pramerica Life Sampoorna Suraksha',productCode : '140N058V02',planNumber : 'DHFL_043',providerCode : 'DHFL_PRAMERICA'},
  {productName :'Pramerica Life TruShield',productCode : '140N052V03',planNumber : 'DHFL_044',providerCode : 'DHFL_PRAMERICA'},
  {productName :'Pramerica Life Group COVID-19 Shield',productCode : '140N062V01',planNumber : 'DHFL_045',providerCode : 'DHFL_PRAMERICA'},
  {productName :'Pramerica Life Group Traditional Employee Benefit Plan',productCode : '140N072V01',planNumber : 'DHFL_046',providerCode : 'DHFL_PRAMERICA'},
];