export const dhflProducts = [
      // DHFL Pramerica Life Insurance Products
  {
    productName: "Pramerica Life U-Protect Plan",
    productCode: "PL-TERM-001",
    planNumber: "PL-TERM-001",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life TruShield Term Plan",
    productCode: "PL-TERM-002",
    planNumber: "PL-TERM-002",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Saral Jeevan Bima",
    productCode: "PL-TERM-003",
    planNumber: "PL-TERM-003",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Family Income Plan",
    productCode: "PL-TERM-004",
    planNumber: "PL-TERM-004",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Family First Plan",
    productCode: "PL-TERM-005",
    planNumber: "PL-TERM-005",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Secure Savings Plan",
    productCode: "PL-SAV-001",
    planNumber: "PL-SAV-001",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Smart Income Plan",
    productCode: "PL-SAV-002",
    planNumber: "PL-SAV-002",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Smart Assure",
    productCode: "PL-SAV-003",
    planNumber: "PL-SAV-003",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Flexi Cash Plan",
    productCode: "PL-SAV-004",
    planNumber: "PL-SAV-004",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Smart Cash Protect",
    productCode: "PL-SAV-005",
    planNumber: "PL-SAV-005",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Roz Sanchay",
    productCode: "PL-SAV-006",
    planNumber: "PL-SAV-006",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Magnum Assure",
    productCode: "PL-SAV-007",
    planNumber: "PL-SAV-007",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Flexi Income Plan",
    productCode: "PL-SAV-008",
    planNumber: "PL-SAV-008",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Signature Wealth",
    productCode: "PL-SAV-009",
    planNumber: "PL-SAV-009",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life RockSolid Future",
    productCode: "PL-SAV-010",
    planNumber: "PL-SAV-010",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Wealth Maximiser",
    productCode: "PL-SAV-011",
    planNumber: "PL-SAV-011",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Wealth+ Ace",
    productCode: "PL-ULIP-001",
    planNumber: "PL-ULIP-001",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Smart Wealth+",
    productCode: "PL-ULIP-002",
    planNumber: "PL-ULIP-002",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Super Investment Plan",
    productCode: "PL-ULIP-003",
    planNumber: "PL-ULIP-003",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Smart Invest",
    productCode: "PL-ULIP-004",
    planNumber: "PL-ULIP-004",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Wealth Enhancer",
    productCode: "PL-ULIP-005",
    planNumber: "PL-ULIP-005",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Wealth Maximiser (ULIP)",
    productCode: "PL-ULIP-006",
    planNumber: "PL-ULIP-006",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Cancer + Heart Shield",
    productCode: "PL-HLTH-001",
    planNumber: "PL-HLTH-001",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Rakshak Smart",
    productCode: "PL-CHLD-001",
    planNumber: "PL-CHLD-001",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Rakshak Gold",
    productCode: "PL-CHLD-002",
    planNumber: "PL-CHLD-002",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Smart Fee Protect Plan",
    productCode: "PL-CHLD-003",
    planNumber: "PL-CHLD-003",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Saral Pension",
    productCode: "PL-RET-001",
    planNumber: "PL-RET-001",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life NextGen Pension Plan",
    productCode: "PL-RET-002",
    planNumber: "PL-RET-002",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Aajeevan Samriddhi",
    productCode: "PL-RET-003",
    planNumber: "PL-RET-003",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Group Total Protection",
    productCode: "PL-GRP-001",
    planNumber: "PL-GRP-001",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Group Credit Shield",
    productCode: "PL-GRP-002",
    planNumber: "PL-GRP-002",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Group Term Plan",
    productCode: "PL-GRP-003",
    planNumber: "PL-GRP-003",
    providerCode: "DHFL_PRAMERICA",
  },
  {
    productName: "Pramerica Life Sarv Suraksha (Group Micro)",
    productCode: "PL-GRP-004",
    planNumber: "PL-GRP-004",
    providerCode: "DHFL_PRAMERICA",
  },
];