export const edelweissProducts = [

  //Edelweiss Tokio  Life Insurance

  {
    productName: "Edelweiss Tokio Zindagi Protect Plus	",
    productCode: "147N080V01",
    planNumber: "EDELWEISS001	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Term Insurance ",
  },
  {
    productName: "Edelweiss Tokio Saral Jeeeven Bima	",
    productCode: "147N069V02",
    planNumber: "EDELWEISS002	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Term Insurance ",
  },
  {
    productName: "Edelweiss Tokio Wealth Rise+	",
    productCode: "147L076V02",
    planNumber: "EDELWEISS003	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Wealth Creation",
  },
  {
    productName: "Edelweiss Tokio Wealth Plus	",
    productCode: "147L055V04",
    planNumber: "EDELWEISS004	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Wealth Creation",
  },
  {
    productName: "Edelweiss Tokio Wealth Premier	",
    productCode: "147L066V03",
    planNumber: "EDELWEISS005	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Wealth Creation",
  },
  {
    productName: "Edelweiss Tokio Wealth Ultima	",
    productCode: "147L037V04",
    planNumber: "EDELWEISS006	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Wealth Creation",
  },
  {
    productName: "Edelweiss Tokio Group Wealth Accumulation	",
    productCode: "147L014V02",
    planNumber: "EDELWEISS007	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Wealth Creation",
  },
  {
    productName: "Edelweiss Tokio Guaranteed STAR Pro	",
    productCode: "147N115V02",
    planNumber: "EDELWEISS008	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Guaranteed Income Plans",
  },
  {
    productName: "Edelweiss Tokio Flexi-Dream Plan	",
    productCode: "147N114V01",
    planNumber: "EDELWEISS009	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Guaranteed Income Plans",
  },
  {
    productName: "Edelweiss Tokio Flexi Savings Plan	",
    productCode: "147N075V04",
    planNumber: "EDELWEISS010	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Guaranteed Income Plans",
  },
  {
    productName: "Edelweiss Tokio Premier Guaranteed STAR	",
    productCode: "147N077V05",
    planNumber: "EDELWEISS011	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Guaranteed Income Plans",
  },
  {
    productName: "Edelweiss Tokio Guaranteed Income Star	",
    productCode: "147N073V03",
    planNumber: "EDELWEISS012	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Guaranteed Income Plans",
  },
  {
    productName: "Edelweiss Tokio Bharat Savings STAR	",
    productCode: "147N088V03",
    planNumber: "EDELWEISS013	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Guaranteed Income Plans",
  },
  {
    productName: "Edelweiss Tokio Guaranteed Flexi STAR	",
    productCode: "147N112V01",
    planNumber: "EDELWEISS014	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Guaranteed Income Plans",
  },
  {
    productName: "Edelweiss Tokio Premier Guaranteed STAR Pro	",
    productCode: "147N115V02",
    planNumber: "EDELWEISS015	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Retirement plans",
  },
  {
    productName: "Edelweiss Tokio Flexi-Savings Plan	",
    productCode: "147N075V04",
    planNumber: "EDELWEISS016	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Retirement plans",
  },
  {
    productName: "Edelweiss Tokio premier guaranteed STAR	",
    productCode: "147N077V05",
    planNumber: "EDELWEISS017	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Retirement plans",
  },
  {
    productName: "Edelweiss Tokio Easy Pension	",
    productCode: "147L034V04",
    planNumber: "EDELWEISS018	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Retirement plans",
  },
  {
    productName: "Edelweiss Tokio saral pension	",
    productCode: "147N070V02",
    planNumber: "EDELWEISS019	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Retirement plans",
  },
  {
    productName: "Edelweiss Tokio bharat savings STAR	",
    productCode: "147N088V03",
    planNumber: "EDELWEISS020	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Retirement plans",
  },
  {
    productName: "Edelweiss Tokio Active Pension Plus Advantage	",
    productCode: "147N113V02",
    planNumber: "EDELWEISS021	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Retirement plans",
  },
  {
    productName: "Edelweiss Tokio Pradhan Mantri Jeevan Jyoti Bima Yojana	",
    productCode: "147N082V01",
    planNumber: "EDELWEISS022	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Group Solutions",
  },
  {
    productName: "Edelweiss Tokio Group Life Protection Plan	",
    productCode: "147N008V05",
    planNumber: "EDELWEISS023	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Group Solutions",
  },
  {
    productName: "Edelweiss Tokio Group Total Secure	",
    productCode: "147N059V03",
    planNumber: "EDELWEISS024	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Group Solutions",
  },
  {
    productName: "Edelweiss Tokio Group Employee Benefit Plus	",
    productCode: "147N064V01",
    planNumber: "EDELWEISS025	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Group Solutions",
  },
  {
    productName: "Edelweiss Tokio Suraksha Kavach Bima Yojana	",
    productCode: "147N083V01",
    planNumber: "EDELWEISS026	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Micro Insurance Plan",
  },
  {
    productName: "Edelweiss Tokio Jan Suraksha	",
    productCode: "147N058V02",
    planNumber: "EDELWEISS027	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Micro Insurance Plan",
  },

  //Rider plans
  {
    productName: "Edelweiss Tokio Accidental Death Benefit Rider	",
    productCode: "147B002V03",
    planNumber: "EDELWEISS028	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Rider Plan",
  },
  {
    productName:
      "Edelweiss Tokio Accidental Total and Permanent Disability Rider 	",
    productCode: "147B001V03",
    planNumber: "EDELWEISS029	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Rider Plan",
  },
  {
    productName: "Edelweiss Tokio Critical Illness Rider 	",
    productCode: "147B005V03",
    planNumber: "EDELWEISS030	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Rider Plan",
  },
  {
    productName: "Edelweiss Tokio Group Critical Illness Rider	",
    productCode: "147B013V03",
    planNumber: "EDELWEISS031	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Rider Plan",
  },
  {
    productName: "Edelweiss Tokio Group Extended Critical Illness Rider	",
    productCode: "147B009V03",
    planNumber: "EDELWEISS032	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Rider Plan",
  },
  {
    productName: "Edelweiss Tokio Hospital Cash Benefit Rider 	",
    productCode: "147B006V03",
    planNumber: "EDELWEISS033	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Rider Plan",
  },
  {
    productName: "Edelweiss Tokio Income Benefit Rider	",
    productCode: "147B015V01",
    planNumber: "EDELWEISS034	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Rider Plan",
  },
  {
    productName: "Edelweiss Tokio Payor Waiver Benefit Rider 	",
    productCode: "147B014V04",
    planNumber: "EDELWEISS035	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Rider Plan",
  },
  {
    productName: "Edelweiss Tokio Waiver of Premium Rider 	",
    productCode: "147B003V04",
    planNumber: "EDELWEISS036	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Rider Plan",
  },
];