//Total 371 plans including active and withdrawn 

export const edelweissProducts = [

  //Edelweiss Tokio  Life Insurance Active (36 plans)

  {
    productName: "Edelweiss Tokio Zindagi Protect Plus	",
    productCode: "147N080V01",
    planNumber: "EDELWEISS001	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Term Insurance ",
  },
  {
    productName: "Edelweiss Tokio Saral Jeeeven Bima	",
    productCode: "147N069V02",
    planNumber: "EDELWEISS002	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Term Insurance ",
  },
  {
    productName: "Edelweiss Tokio Wealth Rise+	",
    productCode: "147L076V02",
    planNumber: "EDELWEISS003	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Wealth Creation",
  },
  {
    productName: "Edelweiss Tokio Wealth Plus	",
    productCode: "147L055V04",
    planNumber: "EDELWEISS004	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Wealth Creation",
  },
  {
    productName: "Edelweiss Tokio Wealth Premier	",
    productCode: "147L066V03",
    planNumber: "EDELWEISS005	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Wealth Creation",
  },
  {
    productName: "Edelweiss Tokio Wealth Ultima	",
    productCode: "147L037V04",
    planNumber: "EDELWEISS006	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Wealth Creation",
  },
  {
    productName: "Edelweiss Tokio Group Wealth Accumulation	",
    productCode: "147L014V02",
    planNumber: "EDELWEISS007	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Wealth Creation",
  },
  {
    productName: "Edelweiss Tokio Guaranteed STAR Pro	",
    productCode: "147N115V02",
    planNumber: "EDELWEISS008	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Guaranteed Income Plans",
  },
  {
    productName: "Edelweiss Tokio Flexi-Dream Plan	",
    productCode: "147N114V01",
    planNumber: "EDELWEISS009	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Guaranteed Income Plans",
  },
  {
    productName: "Edelweiss Tokio Flexi Savings Plan	",
    productCode: "147N075V04",
    planNumber: "EDELWEISS010	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Guaranteed Income Plans",
  },
  {
    productName: "Edelweiss Tokio Premier Guaranteed STAR	",
    productCode: "147N077V05",
    planNumber: "EDELWEISS011	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Guaranteed Income Plans",
  },
  {
    productName: "Edelweiss Tokio Guaranteed Income Star	",
    productCode: "147N073V03",
    planNumber: "EDELWEISS012	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Guaranteed Income Plans",
  },
  {
    productName: "Edelweiss Tokio Bharat Savings STAR	",
    productCode: "147N088V03",
    planNumber: "EDELWEISS013	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Guaranteed Income Plans",
  },
  {
    productName: "Edelweiss Tokio Guaranteed Flexi STAR	",
    productCode: "147N112V01",
    planNumber: "EDELWEISS014	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Guaranteed Income Plans",
  },
  {
    productName: "Edelweiss Tokio Premier Guaranteed STAR Pro	",
    productCode: "147N115V02",
    planNumber: "EDELWEISS015	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Retirement plans",
  },
  {
    productName: "Edelweiss Tokio Flexi-Savings Plan	",
    productCode: "147N075V04",
    planNumber: "EDELWEISS016	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Retirement plans",
  },
  {
    productName: "Edelweiss Tokio premier guaranteed STAR	",
    productCode: "147N077V05",
    planNumber: "EDELWEISS017	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Retirement plans",
  },
  {
    productName: "Edelweiss Tokio Easy Pension	",
    productCode: "147L034V04",
    planNumber: "EDELWEISS018	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Retirement plans",
  },
  {
    productName: "Edelweiss Tokio saral pension	",
    productCode: "147N070V02",
    planNumber: "EDELWEISS019	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Retirement plans",
  },
  {
    productName: "Edelweiss Tokio bharat savings STAR	",
    productCode: "147N088V03",
    planNumber: "EDELWEISS020	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Retirement plans",
  },
  {
    productName: "Edelweiss Tokio Active Pension Plus Advantage	",
    productCode: "147N113V02",
    planNumber: "EDELWEISS021	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Retirement plans",
  },
  {
    productName: "Edelweiss Tokio Pradhan Mantri Jeevan Jyoti Bima Yojana	",
    productCode: "147N082V01",
    planNumber: "EDELWEISS022	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Group Solutions",
  },
  {
    productName: "Edelweiss Tokio Group Life Protection Plan	",
    productCode: "147N008V05",
    planNumber: "EDELWEISS023	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Group Solutions",
  },
  {
    productName: "Edelweiss Tokio Group Total Secure	",
    productCode: "147N059V03",
    planNumber: "EDELWEISS024	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Group Solutions",
  },
  {
    productName: "Edelweiss Tokio Group Employee Benefit Plus	",
    productCode: "147N064V01",
    planNumber: "EDELWEISS025	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Group Solutions",
  },
  {
    productName: "Edelweiss Tokio Suraksha Kavach Bima Yojana	",
    productCode: "147N083V01",
    planNumber: "EDELWEISS026	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Micro Insurance Plan",
  },
  {
    productName: "Edelweiss Tokio Jan Suraksha	",
    productCode: "147N058V02",
    planNumber: "EDELWEISS027	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Micro Insurance Plan",
  },

  //Rider plans
  {
    productName: "Edelweiss Tokio Accidental Death Benefit Rider	",
    productCode: "147B002V03",
    planNumber: "EDELWEISS028	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Rider Plan",
  },
  {
    productName:
      "Edelweiss Tokio Accidental Total and Permanent Disability Rider 	",
    productCode: "147B001V03",
    planNumber: "EDELWEISS029	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Rider Plan",
  },
  {
    productName: "Edelweiss Tokio Critical Illness Rider 	",
    productCode: "147B005V03",
    planNumber: "EDELWEISS030	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Rider Plan",
  },
  {
    productName: "Edelweiss Tokio Group Critical Illness Rider	",
    productCode: "147B013V03",
    planNumber: "EDELWEISS031	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Rider Plan",
  },
  {
    productName: "Edelweiss Tokio Group Extended Critical Illness Rider	",
    productCode: "147B009V03",
    planNumber: "EDELWEISS032	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Rider Plan",
  },
  {
    productName: "Edelweiss Tokio Hospital Cash Benefit Rider 	",
    productCode: "147B006V03",
    planNumber: "EDELWEISS033	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Rider Plan",
  },
  {
    productName: "Edelweiss Tokio Income Benefit Rider	",
    productCode: "147B015V01",
    planNumber: "EDELWEISS034	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Rider Plan",
  },
  {
    productName: "Edelweiss Tokio Payor Waiver Benefit Rider 	",
    productCode: "147B014V04",
    planNumber: "EDELWEISS035	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Rider Plan",
  },
  {
    productName: "Edelweiss Tokio Waiver of Premium Rider 	",
    productCode: "147B003V04",
    planNumber: "EDELWEISS036	",
    providerCode: "EDELWEISS_TOKIO",
    productType: "Rider Plan",
  },

  //Withdrawn Plans from Edelweiss Site (124 plans)


  {productName :'Edelweiss Life - Gramin Bima  	',productCode : '147N079V01'	,planNumber : 'EDELWEISS037	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Guaranteed Savings STAR  	',productCode : '147N074V03'	,planNumber : 'EDELWEISS038	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Income Builder  	',productCode : '147N057V03'	,planNumber : 'EDELWEISS039	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Jan Suraksha  	',productCode : '147N058V02'	,planNumber : 'EDELWEISS040	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Legacy Plus  	',productCode : '147N090V02'	,planNumber : 'EDELWEISS041	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - PGI  	',productCode : '147N072V03'	,planNumber : 'EDELWEISS042	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - POS Saral Nivesh  	',productCode : '147N038V05'	,planNumber : 'EDELWEISS043	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Pradhan Mantri Jeevan Jyoti Bima Yojana Broucher 	',productCode : '147G039V01'	,planNumber : 'EDELWEISS044	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Raksha Kavach  	',productCode : '147N012V02'	,planNumber : 'EDELWEISS045	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Single Pay Endowment Assurance Plan  	',productCode : '147N018V04'	,planNumber : 'EDELWEISS046	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Smart Life style Cover  	',productCode : '147N040V03'	,planNumber : 'EDELWEISS047	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life Wealth Gain Plus  	',productCode : '147L061V03'	,planNumber : 'EDELWEISS048	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Wealth Secure Plus  	',productCode : '147L062V02'	,planNumber : 'EDELWEISS049	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Zindagi Protect  	',productCode : '147N078V02'	,planNumber : 'EDELWEISS050	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Accidental Death Benefit Rider 	',productCode : '147B002V04'	,planNumber : 'EDELWEISS051	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Accidental Total and Permanent Disability Rider  	',productCode : '147B001V04'	,planNumber : 'EDELWEISS052	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Active Income Plan  	',productCode : '147N065V02'	,planNumber : 'EDELWEISS053	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Bharat Savings Star  	',productCode : '147N088V03'	,planNumber : 'EDELWEISS054	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Cashflow Protection Plus  	',productCode : '147N028V03'	,planNumber : 'EDELWEISS055	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Criti Care Plus  	',productCode : '147N030V02'	,planNumber : 'EDELWEISS056	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Dhan Labh  	',productCode : '147N033V03'	,planNumber : 'EDELWEISS057	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Easy Pension  	',productCode : '147L034V03'	,planNumber : 'EDELWEISS058	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Flexi Savings Plan  	',productCode : '147N075V03'	,planNumber : 'EDELWEISS059	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Forever Pension  	',productCode : '147N075V03'	,planNumber : 'EDELWEISS060	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - GCAP  	',productCode : '147N031V03'	,planNumber : 'EDELWEISS061	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Group Credit Protection  	',productCode : '147N002V03'	,planNumber : 'EDELWEISS062	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Group Critical Illness Rider 	',productCode : '147B013V04'	,planNumber : 'EDELWEISS063	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Group Employee Benefit Plus  	',productCode : '147N064V01'	,planNumber : 'EDELWEISS064	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Group Extended Critical IllnessRider 	',productCode : '147B009V04'	,planNumber : 'EDELWEISS065	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Group Life Protection  	',productCode : '147N008V05'	,planNumber : 'EDELWEISS066	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Group Total Secure  	',productCode : '147N059V02'	,planNumber : 'EDELWEISS067	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Group Wealth Accumulation  	',productCode : '147L014V02'	,planNumber : 'EDELWEISS068	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Guaranteed Growth Plan  	',productCode : '147N089V02'	,planNumber : 'EDELWEISS069	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Guaranteed Income STAR  	',productCode : '147N073V03'	,planNumber : 'EDELWEISS070	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Hospital Cash Benefit Rider 	',productCode : '147B006V03'	,planNumber : 'EDELWEISS071	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Pay or Waiver Benefit Rider 	',productCode : '147B014V06'	,planNumber : 'EDELWEISS072	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Waiver of Premium Rider 	',productCode : '147B003V06'	,planNumber : 'EDELWEISS073	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life 	',productCode : '147N072V01'	,planNumber : 'EDELWEISS074	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life COVID	',productCode : 'ETCS'	,planNumber : 'EDELWEISS075	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life CritiCarePlus	',productCode : 'ETCCP'	,planNumber : 'EDELWEISS076	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Cash Income -	',productCode : '147N023V01'	,planNumber : 'EDELWEISS077	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Dhan Labh -	',productCode : '147N033V01'	,planNumber : 'EDELWEISS078	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Easy Pension -	',productCode : '147L034V01'	,planNumber : 'EDELWEISS079	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - EduSave -	',productCode : '147N022V01'	,planNumber : 'EDELWEISS080	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Elite Plus -  -	',productCode : '147N060V01'	,planNumber : 'EDELWEISS081	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - GCAP -	',productCode : '147N031V01'	,planNumber : 'EDELWEISS082	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Group Accidental Total and Permanent Disability  -	',productCode : '147B008V02'	,planNumber : 'EDELWEISS083	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Group Critical Illness Rider - Sales Literature -	',productCode : '147B013V02'	,planNumber : 'EDELWEISS084	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life – Group Employee Benefit Plan -	',productCode : '147N029V01'	,planNumber : 'EDELWEISS085	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life – Group Employee Benefit Plan -	',productCode : '147N029V02'	,planNumber : 'EDELWEISS086	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Group Total Secure -  -	',productCode : '147N059V01'	,planNumber : 'EDELWEISS087	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Group TPD Rider -	',productCode : '147B007V02'	,planNumber : 'EDELWEISS088	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Guaranteed Income Plan -	',productCode : '147N021V01'	,planNumber : 'EDELWEISS089	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Income Benefit Rider -	',productCode : '147B015V01'	,planNumber : 'EDELWEISS090	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Income Builder -  -	',productCode : '147N057V01'	,planNumber : 'EDELWEISS091	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Jan Suraksha -  -	',productCode : '147N058V01'	,planNumber : 'EDELWEISS092	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Milestones Plan -	',productCode : '147N024V01'	,planNumber : 'EDELWEISS093	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - POS Saral Nivesh - Product  -	',productCode : '147N038V01'	,planNumber : 'EDELWEISS094	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Raksha Kavach - SalesLiterature -	',productCode : '147N012V02'	,planNumber : 'EDELWEISS095	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - SmartLifestyle -	',productCode : '147N040V01'	,planNumber : 'EDELWEISS096	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Total Secure -  -	',productCode : '147N036V01'	,planNumber : 'EDELWEISS097	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Triple Advantage Plan -	',productCode : '147N032V01'	,planNumber : 'EDELWEISS098	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Wealth Plus  -	',productCode : '147L055V02'	,planNumber : 'EDELWEISS099	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Wealth Ultima -	',productCode : '147L037V01'	,planNumber : 'EDELWEISS100	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - WealthGainplus -  -	',productCode : '147L061V01'	,planNumber : 'EDELWEISS101	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss_Tokio_Life_Cashflow_Protection_	',productCode : 'ETLCPB'	,planNumber : 'EDELWEISS102	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss_Tokio_Life_Dhan_Nivesh_Bima_Yojana_	',productCode : 'ETLDNBYB'	,planNumber : 'EDELWEISS103	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss_Tokio_Life_Education_	',productCode : 'ETLEB'	,planNumber : 'EDELWEISS104	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss_Tokio_Life_Group_Credit_Protection_	',productCode : 'ETLGCPB'	,planNumber : 'EDELWEISS105	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss_Tokio_Life_Group_Wealth_Accumulation_V01_	',productCode : 'ETLGWAVB'	,planNumber : 'EDELWEISS106	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss_Tokio_Life_Income_Replacement_V01_	',productCode : 'ETLIRVB'	,planNumber : 'EDELWEISS107	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss_Tokio_Life_Multigain_Plan_WA_	',productCode : 'ETLMPWB'	,planNumber : 'EDELWEISS108	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss_Tokio_Life_Protection_V02_	',productCode : 'ETLPVB'	,planNumber : 'EDELWEISS109	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss_Tokio_Life_Raksha_Kavach_	',productCode : 'ETLRKB'	,planNumber : 'EDELWEISS110	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss_Tokio_Life_Safe_n_Sure_Plan_	',productCode : 'ETLSnSPB'	,planNumber : 'EDELWEISS111	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss_Tokio_Life_Save_n_Grow_Plan_	',productCode : 'ETLSnGPB'	,planNumber : 'EDELWEISS112	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss_Tokio_Life_Save_N_Prosper_WA_	',productCode : 'ETLSNPWB'	,planNumber : 'EDELWEISS113	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss_Tokio_Life_Single_Pay_Endowment_Assurance_Plan_	',productCode : 'ETLSPEAPB'	,planNumber : 'EDELWEISS114	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss_Tokio_Life_Wealth_Accumulation_AcceleratedCover_V01_	',productCode : 'ETLWAAVB'	,planNumber : 'EDELWEISS115	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss_Tokio_Life_Wealth_Accumulation_Comprehensive_Cover_	',productCode : 'ETLWACCB'	,planNumber : 'EDELWEISS116	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss_Tokio_Life_Wealth_Accumulation_Cover_Plus_V01_	',productCode : 'ETLWACPVB'	,planNumber : 'EDELWEISS117	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss_Tokio_Life_Wealth_Accumulation_Privilege_	',productCode : 'ETLWAPB'	,planNumber : 'EDELWEISS118	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss_Tokio_Life_Wealth_Enhancement_Ace_V01_	',productCode : 'ETLWEAVB'	,planNumber : 'EDELWEISS119	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'EdelweissTokioLifeAccidentalDeathBenefitRider	',productCode : '147C002V01'	,planNumber : 'EDELWEISS120	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'EdelweissTokioLife-AccidentalDeathBenefitRider	',productCode : '147B002V02'	,planNumber : 'EDELWEISS121	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'EdelweissTokioLifeAccidentaltotalandPermanentDisabilityRider	',productCode : '147C001V01'	,planNumber : 'EDELWEISS122	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'EdelweissTokioLifeCriticalIllnessRider	',productCode : '147C005V01'	,planNumber : 'EDELWEISS123	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'EdelweissTokioLifeGroupAccidentalDeathBenefitRider	',productCode : '147B010V01'	,planNumber : 'EDELWEISS124	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'EdelweissTokioLifeGroupCriticalIllnessRider	',productCode : '147B013V01'	,planNumber : 'EDELWEISS125	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'EdelweissTokioLifeGroupHospitalCashBenefitRider	',productCode : '147B012V01'	,planNumber : 'EDELWEISS126	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'EdelweissTokioLife-GroupHospitalCashBenefitRider	',productCode : '147B012V02'	,planNumber : 'EDELWEISS127	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'EdelweissTokioLifeGroupLifeProtection	',productCode : '147N008V02'	,planNumber : 'EDELWEISS128	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'EdelweissTokioLifeGroupLifeProtection	',productCode : '147N008V03'	,planNumber : 'EDELWEISS129	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'EdelweissTokioLifeGroupTotalandPermanentDisabilityRider	',productCode : '147B007V01'	,planNumber : 'EDELWEISS130	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'EdelweissTokioLife-HealthShieldPlus	',productCode : '147N041V01'	,planNumber : 'EDELWEISS131	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'EdelweissTokioLifeHospitalCashBenefitRider	',productCode : '147C006V01'	,planNumber : 'EDELWEISS132	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'EdelweissTokioLifeImmediateAnnuity	',productCode : '147N019V01'	,planNumber : 'EDELWEISS133	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'EdelweissTokioLifeMyLife	',productCode : '147N027V01'	,planNumber : 'EDELWEISS134	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'EdelweissTokioLife-PayorWaiverBenefit	',productCode : '147B014V01'	,planNumber : 'EDELWEISS135	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'EdelweissTokioLife-PayorWaiverBenefit	',productCode : '147B014V02'	,planNumber : 'EDELWEISS136	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'EdelweissTokioLifeProtection	',productCode : '147N007V02'	,planNumber : 'EDELWEISS137	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'EdelweissTokioLifeTermRider	',productCode : '147C004V01'	,planNumber : 'EDELWEISS138	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'EdelweissTokioLifeWaiverofPremiumRider	',productCode : '147C003V01'	,planNumber : 'EDELWEISS139	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'EdelweissTokioLife-WealthAccumulation-AcceleratedCover	',productCode : '147L003V02'	,planNumber : 'EDELWEISS140	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'EdelweissTokioLife-WealthAccumulationCoverPlus	',productCode : '147L004V02'	,planNumber : 'EDELWEISS141	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'EdelweissTokioLife-WealthAccumulationPrivilege	',productCode : '147L011V02'	,planNumber : 'EDELWEISS142	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'ETLI_WealthPremier_ProductBroc	',productCode : '147L066V02'	,planNumber : 'EDELWEISS143	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'ETLI-GroupAccidentalDeathandDismembermentBenefitRider-	',productCode : '147B011V01'	,planNumber : 'EDELWEISS144	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'ETLI-GroupExtendedCriticalIllnessRider-	',productCode : '147B009V01'	,planNumber : 'EDELWEISS145	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'ETLI-GroupLifeProtection-	',productCode : '147N008V01'	,planNumber : 'EDELWEISS146	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'ETLI-Safe-n-Sure	',productCode : '147N015V02'	,planNumber : 'EDELWEISS147	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'ETLISinglePayEndowmentAssurancePlan	',productCode : '147N018V02'	,planNumber : 'EDELWEISS148	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'ETLIWealthBuilder	',productCode : '147N026V01'	,planNumber : 'EDELWEISS149	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'ETLI-ZindagiPlus	',productCode : '147N056V03'	,planNumber : 'EDELWEISS150	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'ETMyterm_	',productCode : 'ETMB'	,planNumber : 'EDELWEISS151	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'ETPension_plan_discontinued_15.11.18	',productCode : 'ETPpd1'	,planNumber : 'EDELWEISS152	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'ETProtection_	',productCode : 'ETPB'	,planNumber : 'EDELWEISS153	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'ETSimplyProtect_	',productCode : 'ETSB'	,planNumber : 'EDELWEISS154	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'ETTPP_	',productCode : 'ETTB'	,planNumber : 'EDELWEISS155	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'ETZindagiPlus_	',productCode : 'ETZb'	,planNumber : 'EDELWEISS156	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Active Pension Plus-Product 	',productCode : '147N091V01'	,planNumber : 'EDELWEISS157	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Premier Guaranteed STAR  	',productCode : '147N077V04'	,planNumber : 'EDELWEISS158	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Raksha Kavach BimaYojana  	',productCode : '147N081V01'	,planNumber : 'EDELWEISS159	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Premier Guaranteed STAR PRO 	',productCode : '147N115V01'	,planNumber : 'EDELWEISS160	',providerCode : 'EDELWEISS_TOKIO'},

//IRDAI Site plans - (total 211)
//  Count - 161

{productName :'Edelweiss  Tokio Life - Education 	',productCode : '147N001V01'	,planNumber : 'EDELWEISS161	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss  Tokio Life Group Credit Protection	',productCode : '147N002V01'	,planNumber : 'EDELWEISS162	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss  Tokio Life Group Credit Protection	',productCode : '147N002V02'	,planNumber : 'EDELWEISS163	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss  Tokio Life Group Credit Protection	',productCode : '147N002V03'	,planNumber : 'EDELWEISS164	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Income Replacement	',productCode : '147N006V01'	,planNumber : 'EDELWEISS165	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Income Replacement	',productCode : '147N006V02'	,planNumber : 'EDELWEISS166	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Protection	',productCode : '147N007V01'	,planNumber : 'EDELWEISS167	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Protection	',productCode : '147N007V02'	,planNumber : 'EDELWEISS168	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Protection	',productCode : '147N007V03'	,planNumber : 'EDELWEISS169	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss   Tokio Life - Group Life Protection	',productCode : '147N008V01'	,planNumber : 'EDELWEISS170	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss   Tokio Life - Group Life Protection	',productCode : '147N008V02'	,planNumber : 'EDELWEISS171	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss   Tokio Life - Group Life Protection	',productCode : '147N008V03'	,planNumber : 'EDELWEISS172	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss   Tokio Life - Group Life Protection	',productCode : '147N008V04'	,planNumber : 'EDELWEISS173	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss   Tokio Life - Group Life Protection	',productCode : '147N008V05'	,planNumber : 'EDELWEISS174	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Cashflow Protection 	',productCode : '147N009V01'	,planNumber : 'EDELWEISS175	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Raksha Kavach (Micro Insurance Plan)	',productCode : '147N012V01'	,planNumber : 'EDELWEISS176	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Raksha Kavach (Micro Insurance Plan)	',productCode : '147N012V02'	,planNumber : 'EDELWEISS177	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Dhan Nivesh	',productCode : '147N013V01'	,planNumber : 'EDELWEISS178	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Dhan Nivesh Bima Yojana	',productCode : '147N013V02'	,planNumber : 'EDELWEISS179	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Safe n Sure Plan 	',productCode : '147N015V01'	,planNumber : 'EDELWEISS180	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Safe n Sure Plan 	',productCode : '147N015V02'	,planNumber : 'EDELWEISS181	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Save n Grow Plan 	',productCode : '147N016V01'	,planNumber : 'EDELWEISS182	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - MultiGain Plan (WA)	',productCode : '147N017V01'	,planNumber : 'EDELWEISS183	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Single Pay Endowment Assurance Plan	',productCode : '147N018V01'	,planNumber : 'EDELWEISS184	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Single Pay Endowment Assurance Plan	',productCode : '147N018V02'	,planNumber : 'EDELWEISS185	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Single Pay Endowment Assurance Plan	',productCode : '147N018V03'	,planNumber : 'EDELWEISS186	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Single Pay Endowment Assurance Plan	',productCode : '147N018V04'	,planNumber : 'EDELWEISS187	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Immediate Annuity Plan	',productCode : '147N019V01'	,planNumber : 'EDELWEISS188	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Immediate Annuity Plan	',productCode : '147N019V02'	,planNumber : 'EDELWEISS189	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Save n Prosper (WA)	',productCode : '147N020V01'	,planNumber : 'EDELWEISS190	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Guaranteed Income Plan (WE)	',productCode : '147N021V01'	,planNumber : 'EDELWEISS191	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - EduSave	',productCode : '147N022V01'	,planNumber : 'EDELWEISS192	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Cash Income	',productCode : '147N023V01'	,planNumber : 'EDELWEISS193	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Milestone Plan (WA)	',productCode : '147N024V01'	,planNumber : 'EDELWEISS194	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Pension Plan	',productCode : '147N025V01'	,planNumber : 'EDELWEISS195	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Wealth Builder	',productCode : '147N026V01'	,planNumber : 'EDELWEISS196	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Wealth Builder	',productCode : '147N026V02'	,planNumber : 'EDELWEISS197	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Wealth Builder	',productCode : '147N026V03'	,planNumber : 'EDELWEISS198	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - My Life+	',productCode : '147N027V01'	,planNumber : 'EDELWEISS199	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - My Life+	',productCode : '147N027V02'	,planNumber : 'EDELWEISS200	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Cashflow Protection Plus	',productCode : '147N028V01'	,planNumber : 'EDELWEISS201	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Cashflow Protection Plus	',productCode : '147N028V02'	,planNumber : 'EDELWEISS202	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Cashflow Protection Plus	',productCode : '147N028V03'	,planNumber : 'EDELWEISS203	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Group Employee Benefit	',productCode : '147N029V01'	,planNumber : 'EDELWEISS204	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Group Employee Benefit	',productCode : '147N029V02'	,planNumber : 'EDELWEISS205	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life  - CritiCare+	',productCode : '147N030V01'	,planNumber : 'EDELWEISS206	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life  - CritiCare+	',productCode : '147N030V02'	,planNumber : 'EDELWEISS207	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life – GCAP	',productCode : '147N031V01'	,planNumber : 'EDELWEISS208	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life – GCAP	',productCode : '147N031V02'	,planNumber : 'EDELWEISS209	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life – GCAP	',productCode : '147N031V03'	,planNumber : 'EDELWEISS210	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life – Triple Advantage Plan	',productCode : '147N032V01'	,planNumber : 'EDELWEISS211	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life – Dhan Labh	',productCode : '147N033V01'	,planNumber : 'EDELWEISS212	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life – Dhan Labh	',productCode : '147N033V02'	,planNumber : 'EDELWEISS213	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life – Dhan Labh	',productCode : '147N033V03'	,planNumber : 'EDELWEISS214	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Simply Protect 	',productCode : '147N035V01'	,planNumber : 'EDELWEISS215	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Simply Protect 	',productCode : '147N035V02'	,planNumber : 'EDELWEISS216	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - TotalSecure+	',productCode : '147N036V01'	,planNumber : 'EDELWEISS217	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life -POS Saral Nivesh	',productCode : '147N038V01'	,planNumber : 'EDELWEISS218	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life -POS Saral Nivesh	',productCode : '147N038V02'	,planNumber : 'EDELWEISS219	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life -POS Saral Nivesh	',productCode : '147N038V03'	,planNumber : 'EDELWEISS220	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life -POS Saral Nivesh	',productCode : '147N038V04'	,planNumber : 'EDELWEISS221	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - POS Saral Nivesh	',productCode : '147N038V05'	,planNumber : 'EDELWEISS222	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life Pradhan Mantri Jeevan Jyoti Bima Yojana	',productCode : '147G039V01'	,planNumber : 'EDELWEISS223	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Smart Lifestyle	',productCode : '147N040V01'	,planNumber : 'EDELWEISS224	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Smart Lifestyle	',productCode : '147N040V02'	,planNumber : 'EDELWEISS225	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Smart Lifestyle	',productCode : '147N040V03'	,planNumber : 'EDELWEISS226	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - HealthShield+	',productCode : '147N041V01'	,planNumber : 'EDELWEISS227	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life- Zindagi Plus 	',productCode : '147N056V01'	,planNumber : 'EDELWEISS228	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Zindagi Plus 	',productCode : '147N056V02'	,planNumber : 'EDELWEISS229	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Zindagi Plus 	',productCode : '147N056V03'	,planNumber : 'EDELWEISS230	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Zindagi Plus 	',productCode : '147N056V04'	,planNumber : 'EDELWEISS231	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life- Income Builder	',productCode : '147N057V01'	,planNumber : 'EDELWEISS232	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life- Income Builder	',productCode : '147N057V02'	,planNumber : 'EDELWEISS233	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life- Income Builder	',productCode : '147N057V03'	,planNumber : 'EDELWEISS234	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Jan Suraksha	',productCode : '147N058V01'	,planNumber : 'EDELWEISS235	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Jan Suraksha	',productCode : '147N058V02'	,planNumber : 'EDELWEISS236	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Slife - Group Total Secure	',productCode : '147N059V01'	,planNumber : 'EDELWEISS237	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Slife - Group Total Secure	',productCode : '147N059V02'	,planNumber : 'EDELWEISS238	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Group Total Secure	',productCode : '147N059V03'	,planNumber : 'EDELWEISS239	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Elite Plus	',productCode : '147N060V01'	,planNumber : 'EDELWEISS240	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - My Term+	',productCode : '147N063V01'	,planNumber : 'EDELWEISS241	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Group Employee Benefit Plus	',productCode : '147N064V01'	,planNumber : 'EDELWEISS242	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life – Active Income	',productCode : '147N065V01'	,planNumber : 'EDELWEISS243	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life – Active Income	',productCode : '147N065V02'	,planNumber : 'EDELWEISS244	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life – Covid Shield+	',productCode : '147N067V01'	,planNumber : 'EDELWEISS245	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life – Forever Pension	',productCode : '147N068V01'	,planNumber : 'EDELWEISS246	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life – Forever Pension	',productCode : '147N068V02'	,planNumber : 'EDELWEISS247	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life – Saral Jeevan Bima	',productCode : '147N069V01'	,planNumber : 'EDELWEISS248	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life – Saral Jeevan Bima	',productCode : '147N069V02'	,planNumber : 'EDELWEISS249	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life – Saral Pension	',productCode : '147N070V01'	,planNumber : 'EDELWEISS250	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life – Saral Pension	',productCode : '147N070V02'	,planNumber : 'EDELWEISS251	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Total Protect Plus	',productCode : '147N071V01'	,planNumber : 'EDELWEISS252	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Premier Guaranteed Income	',productCode : '147N072V01'	,planNumber : 'EDELWEISS253	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Premier Guaranteed Income	',productCode : '147N072V02'	,planNumber : 'EDELWEISS254	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Premier Guaranteed Income	',productCode : '147N072V03'	,planNumber : 'EDELWEISS255	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life – Guaranteed Income STAR	',productCode : '147N073V01'	,planNumber : 'EDELWEISS256	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life – Guaranteed Income STAR	',productCode : '147N073V02'	,planNumber : 'EDELWEISS257	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Guaranteed Income STAR	',productCode : '147N073V03'	,planNumber : 'EDELWEISS258	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life – Guaranteed Savings STAR 	',productCode : '147N074V01'	,planNumber : 'EDELWEISS259	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life – Guaranteed Savings STAR 	',productCode : '147N074V02'	,planNumber : 'EDELWEISS260	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Guaranteed Savings STAR	',productCode : '147N074V03'	,planNumber : 'EDELWEISS261	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life – Flexi-Savings Plan	',productCode : '147N075V01'	,planNumber : 'EDELWEISS262	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life – Flexi-Savings Plan	',productCode : '147N075V02'	,planNumber : 'EDELWEISS263	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Flexi-Savings Plan	',productCode : '147N075V03'	,planNumber : 'EDELWEISS264	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Flexi-Savings Plan	',productCode : '147N075V04'	,planNumber : 'EDELWEISS265	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life – Premier Guaranteed STAR	',productCode : '147N077V01'	,planNumber : 'EDELWEISS266	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life – Premier Guaranteed STAR	',productCode : '147N077V02'	,planNumber : 'EDELWEISS267	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Premier Guaranteed STAR	',productCode : '147N077V03'	,planNumber : 'EDELWEISS268	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Premier Guaranteed STAR	',productCode : '147N077V04'	,planNumber : 'EDELWEISS269	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Premier Guaranteed STAR	',productCode : '147N077V05'	,planNumber : 'EDELWEISS270	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life – Zindagi Protect	',productCode : '147N078V01'	,planNumber : 'EDELWEISS271	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life – Zindagi Protect	',productCode : '147N078V02'	,planNumber : 'EDELWEISS272	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Gramin Bima	',productCode : '147N079V01'	,planNumber : 'EDELWEISS273	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Zindagi Protect Plus	',productCode : '147N080V01'	,planNumber : 'EDELWEISS274	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Raksha Kavach Bima Yojana (Micro Insurance Plan)	',productCode : '147N081V01'	,planNumber : 'EDELWEISS275	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life – Pradhan Mantri Jeevan Jyoti Bima Yojana	',productCode : '147N082V01'	,planNumber : 'EDELWEISS276	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Bharat Savings STAR	',productCode : '147N088V01'	,planNumber : 'EDELWEISS277	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Bharat Savings STAR	',productCode : '147N088V02'	,planNumber : 'EDELWEISS278	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Bharat Savings STAR	',productCode : '147N088V03'	,planNumber : 'EDELWEISS279	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life – Guaranteed Growth Plan	',productCode : '147N089V01'	,planNumber : 'EDELWEISS280	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life – Legacy Plus	',productCode : '147N090V01'	,planNumber : 'EDELWEISS281	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Legacy Plus	',productCode : '147N090V02'	,planNumber : 'EDELWEISS282	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Active Pension Plus	',productCode : '147N091V01'	,planNumber : 'EDELWEISS283	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Guaranteed Flexi STAR	',productCode : '147N112V01'	,planNumber : 'EDELWEISS284	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Active Pension Plus Advantage	',productCode : '147N113V01'	,planNumber : 'EDELWEISS285	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Active Pension Plus Advantage	',productCode : '147N113V02'	,planNumber : 'EDELWEISS286	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Flexi Dream Plan	',productCode : '147N114V01'	,planNumber : 'EDELWEISS287	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Premier Guaranteed Star Pro	',productCode : '147N115V01'	,planNumber : 'EDELWEISS288	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Wealth Accumulation (Accelerated Cover) - Unit Linked Insurance Plan	',productCode : '147L003V01'	,planNumber : 'EDELWEISS289	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Wealth Accumulation (Accelerated Cover) - Unit Linked Insurance Plan	',productCode : '147L003V02'	,planNumber : 'EDELWEISS290	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Wealth Accumulation (cover Plus) - Unit Linked Insurance Plan	',productCode : '147L004V01'	,planNumber : 'EDELWEISS291	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Wealth Accumulation (cover Plus) - Unit Linked Insurance Plan	',productCode : '147L004V02'	,planNumber : 'EDELWEISS292	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Wealth Accumulation (Comprehensive Cover) - Unit Linked Insurance Plan	',productCode : '147L005V01'	,planNumber : 'EDELWEISS293	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Wealth Enhancement Ace	',productCode : '147L010V01'	,planNumber : 'EDELWEISS294	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Wealth Enhancement Ace	',productCode : '147L010V02'	,planNumber : 'EDELWEISS295	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Wealth Accumulation (Previlege)	',productCode : '147L011V01'	,planNumber : 'EDELWEISS296	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Wealth Accumulation (Previlege)	',productCode : '147L011V02'	,planNumber : 'EDELWEISS297	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Group Wealth Accumulation Plan 	',productCode : '147L014V01'	,planNumber : 'EDELWEISS298	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Group Wealth Accumulation Plan 	',productCode : '147L014V02'	,planNumber : 'EDELWEISS299	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life -Easy Pension 	',productCode : '147L034V01'	,planNumber : 'EDELWEISS300	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life -Easy Pension 	',productCode : '147L034V02'	,planNumber : 'EDELWEISS301	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life -Easy Pension 	',productCode : '147L034V03'	,planNumber : 'EDELWEISS302	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Easy Pension	',productCode : '147L034V04'	,planNumber : 'EDELWEISS303	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life -Wealth Ultima 	',productCode : '147L037V01'	,planNumber : 'EDELWEISS304	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life -Wealth Ultima 	',productCode : '147L037V02'	,planNumber : 'EDELWEISS305	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life -Wealth Ultima 	',productCode : '147L037V03'	,planNumber : 'EDELWEISS306	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Wealth Ultima	',productCode : '147L037V04'	,planNumber : 'EDELWEISS307	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life -Wealth Plus	',productCode : '147L055V01'	,planNumber : 'EDELWEISS308	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life -Wealth Plus	',productCode : '147L055V02'	,planNumber : 'EDELWEISS309	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life -Wealth Plus	',productCode : '147L055V03'	,planNumber : 'EDELWEISS310	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life -Wealth Plus	',productCode : '147L055V04'	,planNumber : 'EDELWEISS311	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life -Wealth Gain+	',productCode : '147L061V01'	,planNumber : 'EDELWEISS312	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life -Wealth Gain+	',productCode : '147L061V02'	,planNumber : 'EDELWEISS313	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life -Wealth Gain+	',productCode : '147L061V03'	,planNumber : 'EDELWEISS314	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life -Wealth Secure+	',productCode : '147L062V01'	,planNumber : 'EDELWEISS315	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life -Wealth Secure+	',productCode : '147L062V02'	,planNumber : 'EDELWEISS316	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life – Wealth Premier	',productCode : '147L066V01'	,planNumber : 'EDELWEISS317	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life – Wealth Premier	',productCode : '147L066V02'	,planNumber : 'EDELWEISS318	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life – Wealth Premier	',productCode : '147L066V03'	,planNumber : 'EDELWEISS319	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life – Wealth Rise+ 	',productCode : '147L076V01'	,planNumber : 'EDELWEISS320	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life – Wealth Rise+ 	',productCode : '147L076V02'	,planNumber : 'EDELWEISS321	',providerCode : 'EDELWEISS_TOKIO'},

//Rider Plans - Count - 50

{productName :'Edelweiss Tokio Life - Accidental total and Permanent Disability Rider	',productCode : '147C001V01'	,planNumber : 'EDELWEISS322	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Accidental total and Permanent Disability Rider	',productCode : '147B001V02'	,planNumber : 'EDELWEISS323	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Accidental total and Permanent Disability Rider	',productCode : '147B001V03'	,planNumber : 'EDELWEISS324	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Accidental Total and Permanent Disability Rider	',productCode : '147B001V04'	,planNumber : 'EDELWEISS325	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Accidental total and Permanent Disability Rider	',productCode : '147B001V05'	,planNumber : 'EDELWEISS326	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Accidental Death Benefit Rider	',productCode : '147C002V01'	,planNumber : 'EDELWEISS327	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Accidental Death Benefit Rider	',productCode : '147B002V02'	,planNumber : 'EDELWEISS328	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Accidental Death Benefit Rider	',productCode : '147B002V03'	,planNumber : 'EDELWEISS329	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Accidental Death Benefit Rider	',productCode : '147B002V04'	,planNumber : 'EDELWEISS330	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Accidental Death Benefit Rider	',productCode : '147B002V05'	,planNumber : 'EDELWEISS331	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Waiver of Premium Rider	',productCode : '147C003V01'	,planNumber : 'EDELWEISS332	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Waiver of Premium Rider	',productCode : '147B003V02'	,planNumber : 'EDELWEISS333	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Waiver of Premium Rider	',productCode : '147B003V03'	,planNumber : 'EDELWEISS334	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Waiver of Premium Rider	',productCode : '147B003V04'	,planNumber : 'EDELWEISS335	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Waiver of Premium Rider	',productCode : '147B003V05'	,planNumber : 'EDELWEISS336	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Waiver of Premium Rider	',productCode : '147B003V06'	,planNumber : 'EDELWEISS337	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Term Rider 	',productCode : '147C004V01'	,planNumber : 'EDELWEISS338	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Term Rider 	',productCode : '147B004V02'	,planNumber : 'EDELWEISS339	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Critical Illness Rider	',productCode : '147C005V01'	,planNumber : 'EDELWEISS340	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Critical Illness Rider	',productCode : '147B005V02'	,planNumber : 'EDELWEISS341	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Critical Illness Rider	',productCode : '147B005V03'	,planNumber : 'EDELWEISS342	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Critical Illness Rider	',productCode : '147B005V04'	,planNumber : 'EDELWEISS343	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Critical Illness Rider	',productCode : '147B005V05'	,planNumber : 'EDELWEISS344	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Hospital Cash Benefit Rider	',productCode : '147C006V01'	,planNumber : 'EDELWEISS345	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Hospital Cash Benefit Rider	',productCode : '147B006V02'	,planNumber : 'EDELWEISS346	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Hospital Cash Benefit Rider	',productCode : '147B006V03'	,planNumber : 'EDELWEISS347	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Group Total and permanent Disability Rider	',productCode : '147B007V01'	,planNumber : 'EDELWEISS348	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Group Total and permanent Disability Rider	',productCode : '147B007V02'	,planNumber : 'EDELWEISS349	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Group Accidental Total and Permanent Disability Rider	',productCode : '147B008V01'	,planNumber : 'EDELWEISS350	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Group Accidental Total and Permanent Disability Rider	',productCode : '147B008V02'	,planNumber : 'EDELWEISS351	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Group extended Critical Illness Rider 	',productCode : '147B009V01'	,planNumber : 'EDELWEISS352	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Group extended Critical Illness Rider 	',productCode : '147B009V02'	,planNumber : 'EDELWEISS353	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Group extended Critical Illness Rider 	',productCode : '147B009V03'	,planNumber : 'EDELWEISS354	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss  Tokio Life - Group Accidental Death Benefit Rider	',productCode : '147B010V01'	,planNumber : 'EDELWEISS355	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss  Tokio Life - Group Accidental Death Benefit Rider	',productCode : '147B010V02'	,planNumber : 'EDELWEISS356	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss  Tokio Life - Group Accidental Death and Dismemberment Benefit Rider	',productCode : '147B011V01'	,planNumber : 'EDELWEISS357	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss  Tokio Life - Group Accidental Death and Dismemberment Benefit Rider	',productCode : '147B011V02'	,planNumber : 'EDELWEISS358	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss  Tokio Life - Group Hospital Cash Benefit Rider 	',productCode : '147B012V01'	,planNumber : 'EDELWEISS359	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss  Tokio Life - Group Hospital Cash Benefit Rider 	',productCode : '147B012V02'	,planNumber : 'EDELWEISS360	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss  Tokio Life - Group Critical Illness Rider	',productCode : '147B013V01'	,planNumber : 'EDELWEISS361	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss  Tokio Life - Group Critical Illness Rider	',productCode : '147B013V02'	,planNumber : 'EDELWEISS362	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss  Tokio Life - Group Critical Illness Rider	',productCode : '147B013V03'	,planNumber : 'EDELWEISS363	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Payor Waiver Benefit Rider	',productCode : '147B014V01'	,planNumber : 'EDELWEISS364	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Payor Waiver Benefit Rider	',productCode : '147B014V02'	,planNumber : 'EDELWEISS365	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Payor Waiver Benefit Rider	',productCode : '147B014V03'	,planNumber : 'EDELWEISS366	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Payor Waiver Benefit Rider	',productCode : '147B014V04'	,planNumber : 'EDELWEISS367	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Payor Waiver Benefit Rider	',productCode : '147B014V05'	,planNumber : 'EDELWEISS368	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Life - Payor Waiver Benefit Rider	',productCode : '147B014V06'	,planNumber : 'EDELWEISS369	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Income Benefit Rider 	',productCode : '147B015V01'	,planNumber : 'EDELWEISS370	',providerCode : 'EDELWEISS_TOKIO'},
{productName :'Edelweiss Tokio Life - Income Benefit Rider 	',productCode : '147B015V02'	,planNumber : 'EDELWEISS371	',providerCode : 'EDELWEISS_TOKIO'},


];