export const futuregeneraliProducts = [
    
  // Future Generali Products
  {
    productName: "Accident Suraksha",
    productCode: "GCIPAIP18040V021718",
    planNumber: "FG001",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName:
      "Arogya Sanjeevani Policy, Generali Central Insurance Company Limited",
    productCode: "GCIHLIP20160V011920",
    planNumber: "FG002",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Aarogya Bima",
    productCode: "GCIHLIP23052V032223",
    planNumber: "FG003",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Advantage Top-Up",
    productCode: "GCIHLIP23053V032223",
    planNumber: "FG004",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Criticare",
    productCode: "GCIHLIP22104V022122",
    planNumber: "FG005",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Health Suraksha",
    productCode: "GCIHLIP25017V052425",
    planNumber: "FG006",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Hospicash",
    productCode: "GCIHLIP22105V022122",
    planNumber: "FG007",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Varishta Bima",
    productCode: "GCIHLIP24138V042324",
    planNumber: "FG008",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Health Total",
    productCode: "GCIHLIP25037V062425",
    planNumber: "FG009",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName:
      "Saral Suraksha Bima, Generali Central Insurance Company Limited",
    productCode: "GCIPAIP21623V012021",
    planNumber: "FG010",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Sukshma Hospi-Cash (Micro-Insurance Product)",
    productCode: "GCIHMIP22106V032122",
    planNumber: "FG011",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Surakshit Loan Bima",
    productCode: "GCIHLIP22112V032122",
    planNumber: "FG012",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Health Elite",
    productCode: "GCIHLIP22234V012122",
    planNumber: "FG013",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Health Absolute",
    productCode: "GCIHLIP26043V032526",
    planNumber: "FG014",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName:
      "HIV & Disability Suraksha, Generali Central Insurance Company Limited",
    productCode: "GCIHLIP23198V012223",
    planNumber: "FG015",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "D.I.Y HEALTH",
    productCode: "GCIHLIP24025V012324",
    planNumber: "FG016",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Surrogacy Health Cover",
    productCode: "GCIHLIP24147V012324",
    planNumber: "FG017",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Health PowHER",
    productCode: "GCIHLIP24180V012324",
    planNumber: "FG018",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Health Vital",
    productCode: "GCIHLIP25038V022425",
    planNumber: "FG019",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName:
      "Corona Kavach Policy, Generali Central Insurance Company Limited",
    productCode: "GCIHLIP21076V012021",
    planNumber: "FG020",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName:
      "Corona Rakshak Policy, Generali Central Insurance Company Limited",
    productCode: "GCIHLIP21075V012021",
    planNumber: "FG021",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Health Protect – Group",
    productCode: "GCIHLGP22109V032122",
    planNumber: "FG022",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Poorna Suraksha – Group",
    productCode: "GCIHLGP26042V052526",
    planNumber: "FG023",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Group Health Insurance (Revised)",
    productCode: "GCIHLGP21165V022021",
    planNumber: "FG024",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Group Health Insurance (Small and Mid-Size groups)",
    productCode: "GCIHLGP21164V022021",
    planNumber: "FG025",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName:
      "Group Arogya Sanjeevani Policy, Generali Central Insurance Company Limited",
    productCode: "GCIHLGP21490V012021",
    planNumber: "FG026",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Alpa Bima – Group",
    productCode: "GCIHLGP22108V022122",
    planNumber: "FG027",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Advantage Top-Up – Group",
    productCode: "GCIHLGP21154V022021",
    planNumber: "FG028",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Travel Suraksha",
    productCode: "IRDA/NL-HLT/GCI/P-T/V.I/76/13-14",
    planNumber: "FG029",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Shubh Yatra",
    productCode: "GCITIDP20115V011920",
    planNumber: "FG030",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Easy Travel Schengen",
    productCode: "IRDAI/HLT/GCI/P-T/V.I/2/16-17",
    planNumber: "FG031",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Easy Travel Worldwide",
    productCode: "IRDAI/HLT/GCI/P-T/V. I/1/16-17",
    planNumber: "FG032",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Travel Suraksha – Schengen Travel",
    productCode: "IRDA/NL-HLT/GCI/P-T/V.II/78/13-14",
    planNumber: "FG033",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Travel Suraksha Select",
    productCode: "IRDAI/HLT/GCI/P-T/V.I/30/16-17",
    planNumber: "FG034",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Student Suraksha",
    productCode: "GCITIDP21520V022021",
    planNumber: "FG035",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Jet Set Secure",
    productCode: "GCITIOP24165V012324",
    planNumber: "FG036",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Motor Protect Private Car Package Policy",
    productCode: "IRDAN132RPMT0001V06201213",
    planNumber: "FG037",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Motor Protect Two-Wheeler Package Policy",
    productCode: "IRDAN132RPMT0016V03200708",
    planNumber: "FG038",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Motor Protect Commercial Vehicle Package Policy",
    productCode: "IRDAN132RPMT0015V03200708",
    planNumber: "FG039",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Standalone Motor Secure OD Private Car Policy",
    productCode: "IRDAN132RPMT0001V02201920",
    planNumber: "FG040",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Standalone Motor Protect OD Two Wheeler Policy",
    productCode: "IRDAN132RPMT0002V02201920",
    planNumber: "FG041",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Home Secure Policy",
    productCode: "IRDAN132RPMS0005V02200809",
    planNumber: "FG042",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "GC Bharat Griha Raksha",
    productCode: "IRDAN132RPPR0005V02202021",
    planNumber: "FG043",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Standard Fire & Special Perils Policy",
    productCode: "IRDAN132RPPR0002V01200708",
    planNumber: "FG044",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Fire Suraksha Policy",
    productCode: "IRDAN132RPPR0084V01202425",
    planNumber: "FG045",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "GC Bharat Laghu Udyam Suraksha",
    productCode: "IRDAN132RPPR0003V02202021",
    planNumber: "FG046",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "GC Bharat Sookshma Udyam Suraksha",
    productCode: "IRDAN132RPPR0004V02202021",
    planNumber: "FG047",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Marine Insurance – Cargo (Retail)",
    productCode: "IRDAN132RPMR0013V01200708",
    planNumber: "FG048",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Business Suraksha",
    productCode: "IRDAN132RPMS0005V01200910",
    planNumber: "FG049",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Public Liability Policy – Industrial Risks",
    productCode: "IRDAN132RPLB0018V01202223",
    planNumber: "FG050",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Cyber Risks Insurance",
    productCode: "IRDAN132CPLB0023V01201920",
    planNumber: "FG051",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Personal Cyber Risks Policy",
    productCode: "IRDAN132RPLB0001V01202021",
    planNumber: "FG052",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Contractors All Risk Insurance",
    productCode: "IRDAN132RPEN0006V02200708",
    planNumber: "FG053",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Industrial All Risk Policy",
    productCode: "IRDAN132CPPR0004V01200708",
    planNumber: "FG054",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Group Personal Accident (Revised)",
    productCode: "GCIHLGP21545V022021",
    planNumber: "FG055",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Employee Compensation Insurance Policy",
    productCode: "IRDAN132RPMS0003V02201213",
    planNumber: "FG056",
    providerCode: "FUTURE_GENERALI",
  },
];