export const hdfcProducts = [
      //HDFC Life Insurance

  {
    productName: "HDFC Life Income Benefit on Accidental Disability Rider	",
    productCode: "101B013V03",
    planNumber: "HDFC_LIFE001	",
    providerCode: "HDFC_LIFE",
    productType: "Protection Plans",
  },
  {
    productName: "HDFC Group Term Insurance	",
    productCode: "101N005V08",
    planNumber: "HDFC_LIFE002	",
    providerCode: "HDFC_LIFE",
    productType: "Protection Plans",
  },
  {
    productName: "HDFC Life Click 2 Protect Elite Plus	",
    productCode: "101N182V01",
    planNumber: "HDFC_LIFE003	",
    providerCode: "HDFC_LIFE",
    productType: "Protection Plans",
  },
  {
    productName: "HDFC Life Click 2 Protect Life	",
    productCode: "101N139V08",
    planNumber: "HDFC_LIFE004	",
    providerCode: "HDFC_LIFE",
    productType: "Protection Plans",
  },
  {
    productName: "HDFC Life Sanchay Legacy	",
    productCode: "101N177V04",
    planNumber: "HDFC_LIFE005	",
    providerCode: "HDFC_LIFE",
    productType: "Protection Plans",
  },
  {
    productName: "HDFC Life Click 2 Protect Ultimate	",
    productCode: "101N179V01",
    planNumber: "HDFC_LIFE006	",
    providerCode: "HDFC_LIFE",
    productType: "Protection Plans",
  },
  {
    productName: "HDFC Life Pradhan Mantri Jeevan Jyoti Bima Yojana	",
    productCode: "101G107V02",
    planNumber: "HDFC_LIFE007	",
    providerCode: "HDFC_LIFE",
    productType: "Protection Plans",
  },
  {
    productName: "HDFC Life Group Jeevan Suraksha (Micro Insurance Product)	",
    productCode: "101N113V06",
    planNumber: "HDFC_LIFE008	",
    providerCode: "HDFC_LIFE",
    productType: "Protection Plans",
  },
  {
    productName: "HDFC Life Group Suraksha (Micro-Insurance Product)	",
    productCode: "101N135V03",
    planNumber: "HDFC_LIFE009	",
    providerCode: "HDFC_LIFE",
    productType: "Protection Plans",
  },
  {
    productName: "Hdfc Life Group Term Life	",
    productCode: "101N169V03",
    planNumber: "HDFC_LIFE010	",
    providerCode: "HDFC_LIFE",
    productType: "Protection Plans",
  },
  {
    productName: "HDFC Life Group Poorna Credit Suraksha	",
    productCode: "101N138V03",
    planNumber: "HDFC_LIFE011	",
    providerCode: "HDFC_LIFE",
    productType: "Protection Plans",
  },
  {
    productName: "HDFC Life Click 2 Protect Supreme Plus	",
    productCode: "101N189V03",
    planNumber: "HDFC_LIFE012	",
    providerCode: "HDFC_LIFE",
    productType: "Protection Plans",
  },
  {
    productName: "HDFC Life Protect Plus Rider	",
    productCode: "101B016V01",
    planNumber: "HDFC_LIFE013	",
    providerCode: "HDFC_LIFE",
    productType: "Protection Plans",
  },
  {
    productName: "HDFC Total and Partial Permanent Disability Benefit	",
    productCode: "101B005V04",
    planNumber: "HDFC_LIFE014	",
    providerCode: "HDFC_LIFE",
    productType: "Protection Plans",
  },
  {
    productName: "HDFC Total Permanent Disability Benefit	",
    productCode: "101B006V04",
    planNumber: "HDFC_LIFE015	",
    providerCode: "HDFC_LIFE",
    productType: "Protection Plans",
  },
  {
    productName: "HDFC  Accident Death Benefit	",
    productCode: "101B008V04",
    planNumber: "HDFC_LIFE016	",
    providerCode: "HDFC_LIFE",
    productType: "Protection Plans",
  },
  {
    productName: "HDFC  HPR (Health plus rider) Rider	",
    productCode: "101NB031V01",
    planNumber: "HDFC_LIFE017	",
    providerCode: "HDFC_LIFE",
    productType: "Protection Plans",
  },
  {
    productName: "HDFC Life Sampoorn Nivesh Plus	",
    productCode: "101L180V01",
    planNumber: "HDFC_LIFE018	",
    providerCode: "HDFC_LIFE",
    productType: "ULIP Plans",
  },
  {
    productName: "HDFC Life Click 2 Invest Plus	",
    productCode: "101L191V01",
    planNumber: "HDFC_LIFE019	",
    providerCode: "HDFC_LIFE",
    productType: "ULIP Plans",
  },
  {
    productName: "HDFC Life Click 2 Wealth	",
    productCode: "101L133V03",
    planNumber: "HDFC_LIFE020	",
    providerCode: "HDFC_LIFE",
    productType: "ULIP Plans",
  },
  {
    productName: "HDFC Life Smart Protect Plus	",
    productCode: "101L187V03",
    planNumber: "HDFC_LIFE021	",
    providerCode: "HDFC_LIFE",
    productType: "ULIP Plans",
  },
  {
    productName: "HDFC Life Uday	",
    productCode: "101N105V05",
    planNumber: "HDFC_LIFE022	",
    providerCode: "HDFC_LIFE",
    productType: "Savings Plans",
  },
  {
    productName: "HDFC Life Sanchay Fixed Maturity Plan	",
    productCode: "101N142V09",
    planNumber: "HDFC_LIFE023	",
    providerCode: "HDFC_LIFE",
    productType: "Savings Plans",
  },
  {
    productName: "HDFC Life Guaranteed Wealth Plus	",
    productCode: "101N165V13",
    planNumber: "HDFC_LIFE024	",
    providerCode: "HDFC_LIFE",
    productType: "Savings Plans",
  },
  {
    productName: "HDFC Life Sampoorna Jeevan	",
    productCode: "101N158V06",
    planNumber: "HDFC_LIFE025	",
    providerCode: "HDFC_LIFE",
    productType: "Savings Plans",
  },
  {
    productName: "HDFC Life Saral Jeevan	",
    productCode: "101N160V05",
    planNumber: "HDFC_LIFE026	",
    providerCode: "HDFC_LIFE",
    productType: "Savings Plans",
  },
  {
    productName: "HDFC Life Click 2 Achieve Par Advantage Plan	",
    productCode: "101N207V01",
    planNumber: "HDFC_LIFE027	",
    providerCode: "HDFC_LIFE",
    productType: "Savings Plans",
  },
  {
    productName: "HDFC Life Guaranteed Savings Plan	",
    productCode: "101N131V04",
    planNumber: "HDFC_LIFE028	",
    providerCode: "HDFC_LIFE",
    productType: "Savings Plans",
  },
  {
    productName: "HDFC Life Smart Income Plan	",
    productCode: "101N166V03",
    planNumber: "HDFC_LIFE029	",
    providerCode: "HDFC_LIFE",
    productType: "Savings Plans",
  },
  {
    productName: "HDFC Life Assured Gain Plus	",
    productCode: "101N151V04",
    planNumber: "HDFC_LIFE030	",
    providerCode: "HDFC_LIFE",
    productType: "Savings Plans",
  },
  {
    productName: "HDFC Life Guaranteed Income Insurance Plan	",
    productCode: "101N146V10",
    planNumber: "HDFC_LIFE031	",
    providerCode: "HDFC_LIFE",
    productType: "Savings Plans",
  },
  {
    productName: "HDFC Life Click 2 Achieve	",
    productCode: "101N186V08",
    planNumber: "HDFC_LIFE032	",
    providerCode: "HDFC_LIFE",
    productType: "Savings Plans",
  },
  {
    productName: "HDFC Life Systematic Pension Plan	",
    productCode: "101N144V05",
    planNumber: "HDFC_LIFE033	",
    providerCode: "HDFC_LIFE",
    productType: "Annuity Plans",
  },
  {
    productName: "HDFC Life Pension Guaranteed Plan	",
    productCode: "101N118V13",
    planNumber: "HDFC_LIFE034	",
    providerCode: "HDFC_LIFE",
    productType: "Annuity Plans",
  },
  {
    productName: "HDFC Life Smart Pension Plus	",
    productCode: "101N173V13",
    planNumber: "HDFC_LIFE035	",
    providerCode: "HDFC_LIFE",
    productType: "Annuity Plans",
  },
  {
    productName: "HDFC Life Systematic Income Plan	",
    productCode: "101N210V03",
    planNumber: "HDFC_LIFE036	",
    providerCode: "HDFC_LIFE",
    productType: "Annuity Plans",
  },
  {
    productName: "HDFC Life Systematic Retirement Plan	",
    productCode: "101N143V10",
    planNumber: "HDFC_LIFE037	",
    providerCode: "HDFC_LIFE",
    productType: "Annuity Plans",
  },
  {
    productName: "HDFC Life Group Traditional Secure Plan	",
    productCode: "101N174V02",
    planNumber: "HDFC_LIFE038	",
    providerCode: "HDFC_LIFE",
    productType: "Pension Plans",
  },
  {
    productName: "HDFC Life New Group Unit Linked Plan	",
    productCode: "101L094V03",
    planNumber: "HDFC_LIFE039	",
    providerCode: "HDFC_LIFE",
    productType: "Pension Plans",
  },
  {
    productName: "HDFC Life Group Gratuity Product	",
    productCode: "101L170V02",
    planNumber: "HDFC_LIFE040	",
    providerCode: "HDFC_LIFE",
    productType: "Pension Plans",
  },
  {
    productName: "HDFC Life Group Unit Linked Pension Plan	",
    productCode: "101L093V02",
    planNumber: "HDFC_LIFE041	",
    providerCode: "HDFC_LIFE",
    productType: "Pension Plans",
  },
  {
    productName: "HDFC SL Group Traditional Plan	",
    productCode: "101N075V03",
    planNumber: "HDFC_LIFE042	",
    providerCode: "HDFC_LIFE",
    productType: "Pension Plans",
  },
  {
    productName: "HDFC Life Group Variable Employee Benefit Plan	",
    productCode: "101N095V04",
    planNumber: "HDFC_LIFE043	",
    providerCode: "HDFC_LIFE",
    productType: "Pension Plans",
  },
  {
    productName: "HDFC Life Group Unit Linked Future Secure Plan	",
    productCode: "101L185V02",
    planNumber: "HDFC_LIFE044	",
    providerCode: "HDFC_LIFE",
    productType: "Pension Plans",
  },
  {
    productName: "HDFC Life Guaranteed Pension Plan	",
    productCode: "101N092V16",
    planNumber: "HDFC_LIFE045	",
    providerCode: "HDFC_LIFE",
    productType: "Pension Plans",
  },
  {
    productName: "HDFC Life Sanchay Aajeevan Guaranteed Advantage Plan	",
    productCode: "101N208V03",
    planNumber: "HDFC_LIFE046	",
    providerCode: "HDFC_LIFE",
    productType: "Pension Plans",
  },
  {
    productName: "HDFC Life Aajeevan Growth Nivesh and Income	",
    productCode: "101N209V01",
    planNumber: "HDFC_LIFE047	",
    providerCode: "HDFC_LIFE",
    productType: "Pension Plans",
  },
  {
    productName: "HDFC Life Smart Pension Plan	",
    productCode: "101L164V08",
    planNumber: "HDFC_LIFE048	",
    providerCode: "HDFC_LIFE",
    productType: "Pension Plans",
  },
  {
    productName: "HDFC Life Group Credit Protect Plus Insurance Plan	",
    productCode: "101N096V07",
    planNumber: "HDFC_LIFE049	",
    providerCode: "HDFC_LIFE",
    productType: "Pension Plans",
  },
  {
    productName: "HDFC Life Group Health Shield	",
    productCode: "101N116V05",
    planNumber: "HDFC_LIFE050	",
    providerCode: "HDFC_LIFE",
    productType: "Health Plans",
  },
  {
    productName: "HDFC Life Group Critical Illness Plus Rider	",
    productCode: "101B015V04",
    planNumber: "HDFC_LIFE051	",
    providerCode: "HDFC_LIFE",
    productType: "Health Plans",
  },
  {
    productName: "HDFC Life Critical Illness Plus Rider	",
    productCode: "101B014V02",
    planNumber: "HDFC_LIFE052	",
    providerCode: "HDFC_LIFE",
    productType: "Health Plans",
  },
];