export const iciciPruProducts = [
    {
      productName: "ICICI Pru Signature Secure",
      productCode: "105L210V01",
      planNumber: "ICICIPRU001",
      providerCode: "ICICI_PRU",
      productType: "ULIP",
    },
    {
      productName: "ICICI Pru Protect N Gain Whole Life",
      productCode: "105L208V01",
      planNumber: "ICICIPRU002",
      providerCode: "ICICI_PRU",
      productType: "NM",
    },
    {
      productName: "ICICI Pru iProtect Care",
      productCode: "105N209V02",
      planNumber: "ICICIPRU003",
      providerCode: "ICICI_PRU",
      productType: "Term Insurance",
    },
    {
      productName: "ICICI Pru SmartKid 360",
      productCode: "105N225V02",
      planNumber: "ICICIPRU004",
      providerCode: "ICICI_PRU",
      productType: "Child Plans",
    },
    {
      productName: "ICICI Pru Wealth Elite Pro",
      productCode: "105L207V01",
      planNumber: "ICICIPRU005",
      providerCode: "ICICI_PRU",
      productType: "ULIP",
    },
    {
      productName: "ICICI Pru Wealth Forever",
      productCode: "105N206V01",
      planNumber: "ICICIPRU006",
      providerCode: "ICICI_PRU",
      productType: "Legacy Plans",
    },
    {
      productName: "ICICI Pru iProtect Smart Plus",
      productCode: "105N205V05",
      planNumber: "ICICIPRU007",
      providerCode: "ICICI_PRU",
      productType: "Term Insurance",
    },
    {
      productName: "ICICI Pru Gift Select",
      productCode: "105N233V05",
      planNumber: "ICICIPRU008",
      providerCode: "ICICI_PRU",
      productType: "Guaranteed Savings Plans",
    },
    {
      productName: "ICICI Pru Smart Goal Assure",
      productCode: "105L199V01",
      planNumber: "ICICIPRU009",
      providerCode: "ICICI_PRU",
      productType: "ULIP",
    },
    {
      productName: "ICICI Pru iProtect Super",
      productCode: "105N197V03",
      planNumber: "ICICIPRU010",
      providerCode: "ICICI_PRU",
      productType: "Term Insurance",
    },
    {
      productName: "ICICI Pru Saral Jeevan Bima",
      productCode: "105N183V03",
      planNumber: "ICICIPRU011",
      providerCode: "ICICI_PRU",
      productType: "NM",
    },
    {
      productName: "ICICI PRU Signature Assure",
      productCode: "105L196V01",
      planNumber: "ICICIPRU012",
      providerCode: "ICICI_PRU",
      productType: "ULIP",
    },
    {
      productName: "ICICI Pru iProtect Smart Return of Premium",
      productCode: "105N195V02",
      planNumber: "ICICIPRU013",
      providerCode: "ICICI_PRU",
      productType: "Term Insurance with Returns",
    },
    {
      productName: "ICICI Pru Guaranteed Pension Plan",
      productCode: "105N181V05",
      planNumber: "ICICIPRU014",
      providerCode: "ICICI_PRU",
      productType: "Retirement and Pension Plans",
    },
    {
      productName: "ICICI Pru Signature Pension",
      productCode: "105L194V03",
      planNumber: "ICICIPRU015",
      providerCode: "ICICI_PRU",
      productType: "ULIP",
    },
    {
      productName: "ICICI Pru iProtect Supreme",
      productCode: "105N193V03",
      planNumber: "ICICIPRU016",
      providerCode: "ICICI_PRU",
      productType: "NM",
    },
    {
      productName: "ICICI Pru Savings Suraksha",
      productCode: "105N135V05",
      planNumber: "ICICIPRU017",
      providerCode: "ICICI_PRU",
      productType: "Savings Plans",
    },
    {
      productName: "ICICI Pru Assured Savings Insurance Plan",
      productCode: "105N144V13",
      planNumber: "ICICIPRU018",
      providerCode: "ICICI_PRU",
      productType: "Guaranteed Savings Plans",
    },
    {
      productName: "ICICI Pru iProtect Smart",
      productCode: "105N151V16",
      planNumber: "ICICIPRU019",
      providerCode: "ICICI_PRU",
      productType: "Health Insurance Plans",
    },
    {
      productName: "ICICI Pru Sarv Jana Suraksha",
      productCode: "105N081V06",
      planNumber: "ICICIPRU020",
      providerCode: "ICICI_PRU",
      productType: "NM",
    },
    {
      productName: "ICICI Pru Future Perfect",
      productCode: "105N153V05",
      planNumber: "ICICIPRU021",
      providerCode: "ICICI_PRU",
      productType: "Savings Plans",
    },
    {
      productName: "ICICI Pru Life Time Classic",
      productCode: "105L155V10",
      planNumber: "ICICIPRU022",
      providerCode: "ICICI_PRU",
      productType: "ULIP",
    },
    {
      productName: "ICICI Pru1 Wealth",
      productCode: "105L175V10",
      planNumber: "ICICIPRU023",
      providerCode: "ICICI_PRU",
      productType: "ULIP",
    },
    {
      productName: "ICICI Pru Signature",
      productCode: "105L177V12",
      planNumber: "ICICIPRU024",
      providerCode: "ICICI_PRU",
      productType: "ULIP",
    },
    {
      productName: "ICICI Pru Guaranteed Income For Tomorrow",
      productCode: "105N182V13",
      planNumber: "ICICIPRU025",
      providerCode: "ICICI_PRU",
      productType: "Guaranteed Savings Plans",
    },
    {
      productName: "ICICI Pru Saral Pension",
      productCode: "105N184V09",
      planNumber: "ICICIPRU026",
      providerCode: "ICICI_PRU",
      productType: "Retirement and Pension Plans",
    },
    {
      productName: "ICICI Pru Guaranteed Income For Tomorrow (Long-term)",
      productCode: "105N185V17",
      planNumber: "ICICIPRU027",
      providerCode: "ICICI_PRU",
      productType: "NM",
    },
    {
      productName: "ICICI Pru Guaranteed Pension Plan Flexi",
      productCode: "105N185V03",
      planNumber: "ICICIPRU028",
      providerCode: "ICICI_PRU",
      productType: "Retirement and Pension Plans",
    },
    {
      productName: "ICICI Pru Sukh Samruddhi",
      productCode: "105N188V03",
      planNumber: "ICICIPRU029",
      providerCode: "ICICI_PRU",
      productType: "NM",
    },
    {
      productName: "ICICI Pru Ezy Grow",
      productCode: "105L202V02",
      planNumber: "ICICIPRU030",
      providerCode: "ICICI_PRU",
      productType: "ULIP",
    },
    {
      productName: "ICICI Pru Gold",
      productCode: "105N190V06",
      planNumber: "ICICIPRU031",
      providerCode: "ICICI_PRU",
      productType: "Guaranteed Savings Plans",
    },
    {
      productName: "ICICI Pru Protect N Gain",
      productCode: "105L191V06",
      planNumber: "ICICIPRU032",
      providerCode: "ICICI_PRU",
      productType: "Term Insurance with Returns",
    },
    {
      productName: "ICICI Pru GIFT Pro",
      productCode: "105N201V05",
      planNumber: "ICICIPRU033",
      providerCode: "ICICI_PRU",
      productType: "Guaranteed Savings Plans",
    },
    {
      productName: "ICICI Pru Gold Pension Savings",
      productCode: "105N202V03",
      planNumber: "ICICIPRU034",
      providerCode: "ICICI_PRU",
      productType: "Retirement and Pension Plans",
    },
    {
      productName: "ICICI Pru Platinum",
      productCode: "105L192V04",
      planNumber: "ICICIPRU035",
      providerCode: "ICICI_PRU",
      productType: "ULIP",
    },
    {
      productName: "ICICI Pru Wish",
      productCode: "105N198V01",
      planNumber: "ICICIPRU036",
      providerCode: "ICICI_PRU",
      productType: "Health Insurance Plans",
    },
    {
      productName: "ICICI Pru Smart Insurance Plan Plus",
      productCode: "105L204V03",
      planNumber: "ICICIPRU037",
      providerCode: "ICICI_PRU",
      productType: "ULIP",
    },
    {
      productName: "ICICI Pru GIFT Assure",
      productCode: "105N224V02",
      planNumber: "ICICIPRU038",
      providerCode: "ICICI_PRU",
      productType: "Guaranteed Savings Plans",
    },
    {
      productName: "ICICI Pru Group Unit Linked Superannuation Plus",
      productCode: "105L200V02",
      planNumber: "ICICIPRU039",
      providerCode: "ICICI_PRU",
      productType: "Group Insurance Plans",
    },
    {
      productName: "ICICI Pru Immediate Annuity",
      productCode: "105N009V26",
      planNumber: "ICICIPRU040",
      providerCode: "ICICI_PRU",
      productType: "Group Insurance Plans",
    },
    {
      productName: "ICICI Pru Group Unit Linked Superannuation",
      productCode: "105L136V03",
      planNumber: "ICICIPRU041",
      providerCode: "ICICI_PRU",
      productType: "Group Insurance Plans",
    },
    {
      productName: "ICICI Pru Group Suraksha Plus Superannuation",
      productCode: "105N148V03",
      planNumber: "ICICIPRU042",
      providerCode: "ICICI_PRU",
      productType: "Group Insurance Plans",
    },
    {
      productName: "ICICI Pru Group Unit Linked Employee Benefit Plan",
      productCode: "105L137V04",
      planNumber: "ICICIPRU043",
      providerCode: "ICICI_PRU",
      productType: "Group Insurance Plans",
    },
    {
      productName:
        "ICICI Pru Group Insurance Scheme for Pradhan Mantri Jeevan Jyoti Bima Yojana",
      productCode: "105G146V02",
      planNumber: "ICICIPRU044",
      providerCode: "ICICI_PRU",
      productType: "Group Insurance Plans",
    },
    {
      productName: "ICICI Pru Group Suraksha Plus",
      productCode: "105N147V03",
      planNumber: "ICICIPRU045",
      providerCode: "ICICI_PRU",
      productType: "Group Insurance Plans",
    },
    {
      productName: "ICICI Pru Group Term Plus",
      productCode: "105N119V08",
      planNumber: "ICICIPRU046",
      providerCode: "ICICI_PRU",
      productType: "Group Insurance Plans",
    },
    {
      productName: "ICICI Pru Group Loan Secure",
      productCode: "105N152V04",
      planNumber: "ICICIPRU047",
      providerCode: "ICICI_PRU",
      productType: "Group Insurance Plans",
    },
    {
      productName: "ICICI Pru Shubh Raksha Credit",
      productCode: "105N159V03",
      planNumber: "ICICIPRU048",
      providerCode: "ICICI_PRU",
      productType: "Group Insurance Plans",
    },
    {
      productName: "ICICI Pru Shubh Raksha One",
      productCode: "105N158V03",
      planNumber: "ICICIPRU049",
      providerCode: "ICICI_PRU",
      productType: "Group Insurance Plans",
    },
    {
      productName: "ICICI Pru Shubh Raksha Life",
      productCode: "105N160V03",
      planNumber: "ICICIPRU050",
      providerCode: "ICICI_PRU",
      productType: "Group Insurance Plans",
    },
    {
      productName: "ICICI Pru Super Protect - Credit",
      productCode: "105N176V03",
      planNumber: "ICICIPRU051",
      providerCode: "ICICI_PRU",
      productType: "Group Insurance Plans",
    },
    {
      productName: "ICICI Pru Super Protect life",
      productCode: "105N180V02",
      planNumber: "ICICIPRU052",
      providerCode: "ICICI_PRU",
      productType: "Group Insurance Plans",
    },
    {
      productName: "ICICI Pru Group Nischit Aay Yojna",
      productCode: "105N203V02",
      planNumber: "ICICIPRU053",
      providerCode: "ICICI_PRU",
      productType: "Group Insurance Plans",
    },
  ];