export const iciciPruProducts = [
    {
      productName: "ICICI Pru Signature Secure",
      productCode: "105L210V01",
      planNumber: "ICICIPRU001",
      providerCode: "ICICI_PRU",
      productType: "ULIP",
    },
    {
      productName: "ICICI Pru Protect N Gain Whole Life",
      productCode: "105L208V01",
      planNumber: "ICICIPRU002",
      providerCode: "ICICI_PRU",
      productType: "NM",
    },
    {
      productName: "ICICI Pru iProtect Care",
      productCode: "105N209V02",
      planNumber: "ICICIPRU003",
      providerCode: "ICICI_PRU",
      productType: "Term Insurance",
    },
    {
      productName: "ICICI Pru SmartKid 360",
      productCode: "105N225V02",
      planNumber: "ICICIPRU004",
      providerCode: "ICICI_PRU",
      productType: "Child Plans",
    },
    {
      productName: "ICICI Pru Wealth Elite Pro",
      productCode: "105L207V01",
      planNumber: "ICICIPRU005",
      providerCode: "ICICI_PRU",
      productType: "ULIP",
    },
    {
      productName: "ICICI Pru Wealth Forever",
      productCode: "105N206V01",
      planNumber: "ICICIPRU006",
      providerCode: "ICICI_PRU",
      productType: "Legacy Plans",
    },
    {
      productName: "ICICI Pru iProtect Smart Plus",
      productCode: "105N205V05",
      planNumber: "ICICIPRU007",
      providerCode: "ICICI_PRU",
      productType: "Term Insurance",
    },
    {
      productName: "ICICI Pru Gift Select",
      productCode: "105N233V05",
      planNumber: "ICICIPRU008",
      providerCode: "ICICI_PRU",
      productType: "Guaranteed Savings Plans",
    },
    {
      productName: "ICICI Pru Smart Goal Assure",
      productCode: "105L199V01",
      planNumber: "ICICIPRU009",
      providerCode: "ICICI_PRU",
      productType: "ULIP",
    },
    {
      productName: "ICICI Pru iProtect Super",
      productCode: "105N197V03",
      planNumber: "ICICIPRU010",
      providerCode: "ICICI_PRU",
      productType: "Term Insurance",
    },
    {
      productName: "ICICI Pru Saral Jeevan Bima",
      productCode: "105N183V03",
      planNumber: "ICICIPRU011",
      providerCode: "ICICI_PRU",
      productType: "NM",
    },
    {
      productName: "ICICI PRU Signature Assure",
      productCode: "105L196V01",
      planNumber: "ICICIPRU012",
      providerCode: "ICICI_PRU",
      productType: "ULIP",
    },
    {
      productName: "ICICI Pru iProtect Smart Return of Premium",
      productCode: "105N195V02",
      planNumber: "ICICIPRU013",
      providerCode: "ICICI_PRU",
      productType: "Term Insurance with Returns",
    },
    {
      productName: "ICICI Pru Guaranteed Pension Plan",
      productCode: "105N181V05",
      planNumber: "ICICIPRU014",
      providerCode: "ICICI_PRU",
      productType: "Retirement and Pension Plans",
    },
    {
      productName: "ICICI Pru Signature Pension",
      productCode: "105L194V03",
      planNumber: "ICICIPRU015",
      providerCode: "ICICI_PRU",
      productType: "ULIP",
    },
    {
      productName: "ICICI Pru iProtect Supreme",
      productCode: "105N193V03",
      planNumber: "ICICIPRU016",
      providerCode: "ICICI_PRU",
      productType: "NM",
    },
    {
      productName: "ICICI Pru Savings Suraksha",
      productCode: "105N135V05",
      planNumber: "ICICIPRU017",
      providerCode: "ICICI_PRU",
      productType: "Savings Plans",
    },
    {
      productName: "ICICI Pru Assured Savings Insurance Plan",
      productCode: "105N144V13",
      planNumber: "ICICIPRU018",
      providerCode: "ICICI_PRU",
      productType: "Guaranteed Savings Plans",
    },
    {
      productName: "ICICI Pru iProtect Smart",
      productCode: "105N151V16",
      planNumber: "ICICIPRU019",
      providerCode: "ICICI_PRU",
      productType: "Health Insurance Plans",
    },
    {
      productName: "ICICI Pru Sarv Jana Suraksha",
      productCode: "105N081V06",
      planNumber: "ICICIPRU020",
      providerCode: "ICICI_PRU",
      productType: "NM",
    },
    {
      productName: "ICICI Pru Future Perfect",
      productCode: "105N153V05",
      planNumber: "ICICIPRU021",
      providerCode: "ICICI_PRU",
      productType: "Savings Plans",
    },
    {
      productName: "ICICI Pru Life Time Classic",
      productCode: "105L155V10",
      planNumber: "ICICIPRU022",
      providerCode: "ICICI_PRU",
      productType: "ULIP",
    },
    {
      productName: "ICICI Pru1 Wealth",
      productCode: "105L175V10",
      planNumber: "ICICIPRU023",
      providerCode: "ICICI_PRU",
      productType: "ULIP",
    },
    {
      productName: "ICICI Pru Signature",
      productCode: "105L177V12",
      planNumber: "ICICIPRU024",
      providerCode: "ICICI_PRU",
      productType: "ULIP",
    },
    {
      productName: "ICICI Pru Guaranteed Income For Tomorrow",
      productCode: "105N182V13",
      planNumber: "ICICIPRU025",
      providerCode: "ICICI_PRU",
      productType: "Guaranteed Savings Plans",
    },
    {
      productName: "ICICI Pru Saral Pension",
      productCode: "105N184V09",
      planNumber: "ICICIPRU026",
      providerCode: "ICICI_PRU",
      productType: "Retirement and Pension Plans",
    },
    {
      productName: "ICICI Pru Guaranteed Income For Tomorrow (Long-term)",
      productCode: "105N185V17",
      planNumber: "ICICIPRU027",
      providerCode: "ICICI_PRU",
      productType: "NM",
    },
    {
      productName: "ICICI Pru Guaranteed Pension Plan Flexi",
      productCode: "105N185V03",
      planNumber: "ICICIPRU028",
      providerCode: "ICICI_PRU",
      productType: "Retirement and Pension Plans",
    },
    {
      productName: "ICICI Pru Sukh Samruddhi",
      productCode: "105N188V03",
      planNumber: "ICICIPRU029",
      providerCode: "ICICI_PRU",
      productType: "NM",
    },
    {
      productName: "ICICI Pru Ezy Grow",
      productCode: "105L202V02",
      planNumber: "ICICIPRU030",
      providerCode: "ICICI_PRU",
      productType: "ULIP",
    },
    {
      productName: "ICICI Pru Gold",
      productCode: "105N190V06",
      planNumber: "ICICIPRU031",
      providerCode: "ICICI_PRU",
      productType: "Guaranteed Savings Plans",
    },
    {
      productName: "ICICI Pru Protect N Gain",
      productCode: "105L191V06",
      planNumber: "ICICIPRU032",
      providerCode: "ICICI_PRU",
      productType: "Term Insurance with Returns",
    },
    {
      productName: "ICICI Pru GIFT Pro",
      productCode: "105N201V05",
      planNumber: "ICICIPRU033",
      providerCode: "ICICI_PRU",
      productType: "Guaranteed Savings Plans",
    },
    {
      productName: "ICICI Pru Gold Pension Savings",
      productCode: "105N202V03",
      planNumber: "ICICIPRU034",
      providerCode: "ICICI_PRU",
      productType: "Retirement and Pension Plans",
    },
    {
      productName: "ICICI Pru Platinum",
      productCode: "105L192V04",
      planNumber: "ICICIPRU035",
      providerCode: "ICICI_PRU",
      productType: "ULIP",
    },
    {
      productName: "ICICI Pru Wish",
      productCode: "105N198V01",
      planNumber: "ICICIPRU036",
      providerCode: "ICICI_PRU",
      productType: "Health Insurance Plans",
    },
    {
      productName: "ICICI Pru Smart Insurance Plan Plus",
      productCode: "105L204V03",
      planNumber: "ICICIPRU037",
      providerCode: "ICICI_PRU",
      productType: "ULIP",
    },
    {
      productName: "ICICI Pru GIFT Assure",
      productCode: "105N224V02",
      planNumber: "ICICIPRU038",
      providerCode: "ICICI_PRU",
      productType: "Guaranteed Savings Plans",
    },
    {
      productName: "ICICI Pru Group Unit Linked Superannuation Plus",
      productCode: "105L200V02",
      planNumber: "ICICIPRU039",
      providerCode: "ICICI_PRU",
      productType: "Group Insurance Plans",
    },
    {
      productName: "ICICI Pru Immediate Annuity",
      productCode: "105N009V26",
      planNumber: "ICICIPRU040",
      providerCode: "ICICI_PRU",
      productType: "Group Insurance Plans",
    },
    {
      productName: "ICICI Pru Group Unit Linked Superannuation",
      productCode: "105L136V03",
      planNumber: "ICICIPRU041",
      providerCode: "ICICI_PRU",
      productType: "Group Insurance Plans",
    },
    {
      productName: "ICICI Pru Group Suraksha Plus Superannuation",
      productCode: "105N148V03",
      planNumber: "ICICIPRU042",
      providerCode: "ICICI_PRU",
      productType: "Group Insurance Plans",
    },
    {
      productName: "ICICI Pru Group Unit Linked Employee Benefit Plan",
      productCode: "105L137V04",
      planNumber: "ICICIPRU043",
      providerCode: "ICICI_PRU",
      productType: "Group Insurance Plans",
    },
    {
      productName:
        "ICICI Pru Group Insurance Scheme for Pradhan Mantri Jeevan Jyoti Bima Yojana",
      productCode: "105G146V02",
      planNumber: "ICICIPRU044",
      providerCode: "ICICI_PRU",
      productType: "Group Insurance Plans",
    },
    {
      productName: "ICICI Pru Group Suraksha Plus",
      productCode: "105N147V03",
      planNumber: "ICICIPRU045",
      providerCode: "ICICI_PRU",
      productType: "Group Insurance Plans",
    },
    {
      productName: "ICICI Pru Group Term Plus",
      productCode: "105N119V08",
      planNumber: "ICICIPRU046",
      providerCode: "ICICI_PRU",
      productType: "Group Insurance Plans",
    },
    {
      productName: "ICICI Pru Group Loan Secure",
      productCode: "105N152V04",
      planNumber: "ICICIPRU047",
      providerCode: "ICICI_PRU",
      productType: "Group Insurance Plans",
    },
    {
      productName: "ICICI Pru Shubh Raksha Credit",
      productCode: "105N159V03",
      planNumber: "ICICIPRU048",
      providerCode: "ICICI_PRU",
      productType: "Group Insurance Plans",
    },
    {
      productName: "ICICI Pru Shubh Raksha One",
      productCode: "105N158V03",
      planNumber: "ICICIPRU049",
      providerCode: "ICICI_PRU",
      productType: "Group Insurance Plans",
    },
    {
      productName: "ICICI Pru Shubh Raksha Life",
      productCode: "105N160V03",
      planNumber: "ICICIPRU050",
      providerCode: "ICICI_PRU",
      productType: "Group Insurance Plans",
    },
    {
      productName: "ICICI Pru Super Protect - Credit",
      productCode: "105N176V03",
      planNumber: "ICICIPRU051",
      providerCode: "ICICI_PRU",
      productType: "Group Insurance Plans",
    },
    {
      productName: "ICICI Pru Super Protect life",
      productCode: "105N180V02",
      planNumber: "ICICIPRU052",
      providerCode: "ICICI_PRU",
      productType: "Group Insurance Plans",
    },
    {
      productName: "ICICI Pru Group Nischit Aay Yojna",
      productCode: "105N203V02",
      planNumber: "ICICIPRU053",
      providerCode: "ICICI_PRU",
      productType: "Group Insurance Plans",
    },
    // withdrawn policies
    {
  productName: "ICICI Pru Guaranteed Pension Plan Flexi",
  productCode: "105N187V10",
  planNumber: "ICICIPRU054",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Signature Pension",
  productCode: "105L194V02",
  planNumber: "ICICIPRU055",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru1 Wealth",
  productCode: "105L175V09",
  planNumber: "ICICIPRU056",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru GIFT Assure",
  productCode: "105N224V01",
  planNumber: "ICICIPRU057",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru iProtect Care",
  productCode: "105N209V01",
  planNumber: "ICICIPRU058",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru iProtect Smart Plus",
  productCode: "105N205V04",
  planNumber: "ICICIPRU059",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru1 Wealth",
  productCode: "105L175V08",
  planNumber: "ICICIPRU060",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Pension Plan Flexi",
  productCode: "105N187V09",
  planNumber: "ICICIPRU061",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru iProtect Smart Return of Premium",
  productCode: "105N195V01",
  planNumber: "ICICIPRU062",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru SmartKid 360",
  productCode: "105N225V01",
  planNumber: "ICICIPRU063",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Pension Plan",
  productCode: "105N181V04",
  planNumber: "ICICIPRU064",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Signature",
  productCode: "105L177V11",
  planNumber: "ICICIPRU065",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Gift Select",
  productCode: "105N223V03",
  planNumber: "ICICIPRU066",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Gift Select",
  productCode: "105N223V04",
  planNumber: "ICICIPRU067",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru iProtect Smart Plus",
  productCode: "105N205V03",
  planNumber: "ICICIPRU068",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru iProtect Supreme",
  productCode: "105N193V02",
  planNumber: "ICICIPRU069",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Gold",
  productCode: "105N190V05",
  planNumber: "ICICIPRU070",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru1 Wealth",
  productCode: "105L175V07",
  planNumber: "ICICIPRU071",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Signature",
  productCode: "105L177V10",
  planNumber: "ICICIPRU072",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Income For Tomorrow (Long-term)",
  productCode: "105N185V16",
  planNumber: "ICICIPRU073",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru GIFT Pro",
  productCode: "105N201V06",
  planNumber: "ICICIPRU074",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru GIFT Pro",
  productCode: "105N201V05",
  planNumber: "ICICIPRU075",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Pension Plan Flexi",
  productCode: "105N187V08",
  planNumber: "ICICIPRU076",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru POS iProtect Smart",
  productCode: "105N173V04",
  planNumber: "ICICIPRU077",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru POS iProtect Smart",
  productCode: "105N173V03",
  planNumber: "ICICIPRU078",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Future Perfect",
  productCode: "105N153V03",
  planNumber: "ICICIPRU079",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Future Perfect",
  productCode: "105N153V04",
  planNumber: "ICICIPRU080",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Savings Suraksha",
  productCode: "105N135V04",
  planNumber: "ICICIPRU081",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru iProtect Smart Plus",
  productCode: "105N205V01",
  planNumber: "ICICIPRU082",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru iProtect Smart Plus",
  productCode: "105N205V02",
  planNumber: "ICICIPRU083",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Gold",
  productCode: "105N190V04",
  planNumber: "ICICIPRU084",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Smart Insurance plan",
  productCode: "105L204V02",
  planNumber: "ICICIPRU085",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Smart Insurance plan",
  productCode: "105L204V01",
  planNumber: "ICICIPRU086",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Ezy Grow",
  productCode: "105L189V06",
  planNumber: "ICICIPRU087",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Signature",
  productCode: "105L177V09",
  planNumber: "ICICIPRU088",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Platinum",
  productCode: "105L192V03",
  planNumber: "ICICIPRU089",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Pension Plan Flexi",
  productCode: "105N187V07",
  planNumber: "ICICIPRU090",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru iProtect Super",
  productCode: "105N197V02",
  planNumber: "ICICIPRU091",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru iProtect Super",
  productCode: "105N197V01",
  planNumber: "ICICIPRU092",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Assured Savings Insurance Plan",
  productCode: "105N144V12",
  planNumber: "ICICIPRU093",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Assured Savings Insurance Plan",
  productCode: "105N144V11",
  planNumber: "ICICIPRU094",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru iProtect Supreme",
  productCode: "105N193V01",
  planNumber: "ICICIPRU095",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Gift Select",
  productCode: "105N223V02",
  planNumber: "ICICIPRU096",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Saral Pension",
  productCode: "105N184V08",
  planNumber: "ICICIPRU097",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Signature",
  productCode: "105L177V07",
  planNumber: "ICICIPRU098",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru iProtect Smart",
  productCode: "105N151V15",
  planNumber: "ICICIPRU099",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru iProtect Smart",
  productCode: "105N151V14",
  planNumber: "ICICIPRU100",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru iProtect Smart",
  productCode: "105N151V13",
  planNumber: "ICICIPRU101",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru iProtect Smart",
  productCode: "105N151V12",
  planNumber: "ICICIPRU102",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Pension Plan Flexi",
  productCode: "105N187V06",
  planNumber: "ICICIPRU103",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Income For Tomorrow",
  productCode: "105N182V12",
  planNumber: "ICICIPRU104",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Income For Tomorrow",
  productCode: "105N182V11",
  planNumber: "ICICIPRU105",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Income For Tomorrow",
  productCode: "105N182V10",
  planNumber: "ICICIPRU106",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Ezy Grow",
  productCode: "105L189V05",
  planNumber: "ICICIPRU107",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Easy Retirement",
  productCode: "105L133V03",
  planNumber: "ICICIPRU108",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Easy Retirement SP",
  productCode: "105L138V03",
  planNumber: "ICICIPRU109",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Loan Protect",
  productCode: "105N142V02",
  planNumber: "ICICIPRU110",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru iCare II",
  productCode: "105N140V03",
  planNumber: "ICICIPRU111",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Smart Life",
  productCode: "105L145V08",
  planNumber: "ICICIPRU112",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Life Raksha",
  productCode: "105N149V02",
  planNumber: "ICICIPRU113",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Anmol Bachat",
  productCode: "105N139V03",
  planNumber: "ICICIPRU114",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Heart/Cancer Protect",
  productCode: "105N154V03",
  planNumber: "ICICIPRU115",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Loan Protect Plus",
  productCode: "105N150V03",
  planNumber: "ICICIPRU116",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru POS Life Raksha",
  productCode: "105N174V02",
  planNumber: "ICICIPRU117",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Precious Life",
  productCode: "105N178V01",
  planNumber: "ICICIPRU118",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Wealth Protector",
  productCode: "105L143V02",
  planNumber: "ICICIPRU119",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Pension Plan",
  productCode: "105N181V03",
  planNumber: "ICICIPRU120",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Saral Jeevan Bima",
  productCode: "105N183V01",
  planNumber: "ICICIPRU121",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Saral Jeevan Bima",
  productCode: "105N183V02",
  planNumber: "ICICIPRU122",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru iProtect Return of Premium",
  productCode: "105N186V01",
  planNumber: "ICICIPRU123",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Gold",
  productCode: "105N190V02",
  planNumber: "ICICIPRU124",
  providerCode: "ICICI_PRU",
},
{
  productName: "iShield",
  productCode: "ICIHLIP24082V022324",
  planNumber: "ICICIPRU125",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Savings Suraksha",
  productCode: "105N135V03",
  planNumber: "ICICIPRU126",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Assured Savings Insurance Plan",
  productCode: "105N144V10",
  planNumber: "ICICIPRU127",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru iProtect Smart",
  productCode: "105N151V11",
  planNumber: "ICICIPRU128",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Sarv Jana Suraksha",
  productCode: "105N081V05",
  planNumber: "ICICIPRU129",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Future Perfect",
  productCode: "105N153V02",
  planNumber: "ICICIPRU130",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Life Time Classic",
  productCode: "105L155V09",
  planNumber: "ICICIPRU131",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru1 Wealth",
  productCode: "105L175V06",
  planNumber: "ICICIPRU132",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru1 Wealth",
  productCode: "105L175V05",
  planNumber: "ICICIPRU133",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Signature",
  productCode: "105L177V06",
  planNumber: "ICICIPRU134",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Income For Tomorrow",
  productCode: "105N182V09",
  planNumber: "ICICIPRU135",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Saral Pension",
  productCode: "105N184V07",
  planNumber: "ICICIPRU136",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Income For Tomorrow (Long-term)",
  productCode: "105N185V15",
  planNumber: "ICICIPRU137",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Pension Plan Flexi",
  productCode: "105N187V05",
  planNumber: "ICICIPRU138",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Sukh Samruddhi",
  productCode: "105N188V01",
  planNumber: "ICICIPRU139",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Sukh Samruddhi",
  productCode: "105N188V02",
  planNumber: "ICICIPRU140",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Ezy Grow",
  productCode: "105L189V04",
  planNumber: "ICICIPRU141",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru GIFT Pro",
  productCode: "105N201V04",
  planNumber: "ICICIPRU142",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Gold Pension Savings",
  productCode: "105N202V02",
  planNumber: "ICICIPRU143",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Gold Pension Savings",
  productCode: "105N202V01",
  planNumber: "ICICIPRU144",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Platinum",
  productCode: "105L192V02",
  planNumber: "ICICIPRU145",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICIPru Forever Life -Regular Premium Deferred Pension",
  productCode: "105N001V01",
  planNumber: "ICICIPRU146",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICIPru Forever Life -Regular Premium",
  productCode: "105N001V02",
  planNumber: "ICICIPRU147",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICIPru Forever Life -Single Premium Deferred Pension",
  productCode: "105N002V01",
  planNumber: "ICICIPRU148",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICIPru Single Premium Bond - Single Premium Endowment Bond with Guaranteed Additions",
  productCode: "105N003V01",
  planNumber: "ICICIPRU149",
  providerCode: "ICICI_PRU",
},
{
  productName: "Save \"n'\" Protect",
  productCode: "105N004V01",
  planNumber: "ICICIPRU150",
  providerCode: "ICICI_PRU",
},
{
  productName: "Save \"n'\" Protect",
  productCode: "105N004V02",
  planNumber: "ICICIPRU151",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICIPru Cashbak -Anticipated Endowment Assurance with Deferred Participation in profits",
  productCode: "105N005V01",
  planNumber: "ICICIPRU152",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICIPru Cashbak",
  productCode: "105N005V02",
  planNumber: "ICICIPRU153",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICIPru Life Guard -Level Term Assurance with Return of Premiums",
  productCode: "105N006V01",
  planNumber: "ICICIPRU154",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICIPru Life Guard -Level Term Assurance with Return of Premiums",
  productCode: "105N006V02",
  planNumber: "ICICIPRU155",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICIPru Life Guard -Single Premium Level Term Assurance",
  productCode: "105N007V01",
  planNumber: "ICICIPRU156",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICIPru Life Guard -Single Premium Level Term Assurance",
  productCode: "105N007V02",
  planNumber: "ICICIPRU157",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Salaam Zindagi",
  productCode: "105N008V01",
  planNumber: "ICICIPRU158",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Immediate Annuity",
  productCode: "105N009V01",
  planNumber: "ICICIPRU159",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Immediate Annuity",
  productCode: "105N009V02",
  planNumber: "ICICIPRU160",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Immediate Annuity",
  productCode: "105N009V03",
  planNumber: "ICICIPRU161",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Immediate Annuity",
  productCode: "105N009V04",
  planNumber: "ICICIPRU162",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Immediate Annuity",
  productCode: "105N009V05",
  planNumber: "ICICIPRU163",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICIPru-ReAssure",
  productCode: "105N010V01",
  planNumber: "ICICIPRU164",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICIPru-ReAssure",
  productCode: "105N010V02",
  planNumber: "ICICIPRU165",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICIPRu-Assure Invest",
  productCode: "105N011V01",
  planNumber: "ICICIPRU166",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICIPRu-Assure Invest",
  productCode: "105N011V02",
  planNumber: "ICICIPRU167",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Life Link",
  productCode: "105L012V01",
  planNumber: "ICICIPRU168",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI-Pru Life Time",
  productCode: "105L013V01",
  planNumber: "ICICIPRU169",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI-Pru Smart Kid",
  productCode: "105N014V01",
  planNumber: "ICICIPRU170",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI-Pru Smart Kid",
  productCode: "105N014V02",
  planNumber: "ICICIPRU171",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI-Pru Life Time Pension",
  productCode: "105L015V01",
  planNumber: "ICICIPRU172",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI-Pru Life Link Pension",
  productCode: "105L016V01",
  planNumber: "ICICIPRU173",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru LifeGuard Level Term Assurance",
  productCode: "105N017V01",
  planNumber: "ICICIPRU174",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru LifeGuard Level Term Assurance",
  productCode: "105N017V02",
  planNumber: "ICICIPRU175",
  providerCode: "ICICI_PRU",
},
{
  productName: "Easy Life",
  productCode: "105N018V01",
  planNumber: "ICICIPRU176",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Suraksha - Single Premium",
  productCode: "105N020V01",
  planNumber: "ICICIPRU177",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Suraksha - Regular Premium",
  productCode: "105N021V01",
  planNumber: "ICICIPRU178",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICIPru Mitr - Regular Premium Without Profit Endowment Plan (Save N Protect)",
  productCode: "105N022V01",
  planNumber: "ICICIPRU179",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Secure Plus",
  productCode: "105L025V01",
  planNumber: "ICICIPRU180",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Cash Plus",
  productCode: "105L026V01",
  planNumber: "ICICIPRU181",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Secure Plus Pension",
  productCode: "105L027V01",
  planNumber: "ICICIPRU182",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Smart Kid - Unit Linked(RP)",
  productCode: "105L028V01",
  planNumber: "ICICIPRU183",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Smart Kid - Unit Linked(SP)",
  productCode: "105L029V01",
  planNumber: "ICICIPRU184",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru LifeTime II",
  productCode: "105L031V01",
  planNumber: "ICICIPRU185",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Life Time Pension-II",
  productCode: "105L032V01",
  planNumber: "ICICIPRU186",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru LifeLink II",
  productCode: "105L033V01",
  planNumber: "ICICIPRU187",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru LifeLink Pension II",
  productCode: "105L034V01",
  planNumber: "ICICIPRU188",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Smart Kid (SP) II",
  productCode: "105L035V01",
  planNumber: "ICICIPRU189",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Smart Kid (RP) II",
  productCode: "105L036V01",
  planNumber: "ICICIPRU190",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Premier Life",
  productCode: "105L037V01",
  planNumber: "ICICIPRU191",
  providerCode: "ICICI_PRU",
},
{
  productName: "Suraksha Kavach",
  productCode: "105N038V01",
  planNumber: "ICICIPRU192",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Invest Shield Gold",
  productCode: "105L040V01",
  planNumber: "ICICIPRU193",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Invest Shield Cash",
  productCode: "105L041V01",
  planNumber: "ICICIPRU194",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Invest Shield Life",
  productCode: "105L042V01",
  planNumber: "ICICIPRU195",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Invest Shield Pension",
  productCode: "105L043V01",
  planNumber: "ICICIPRU196",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Golden Years",
  productCode: "105L047V01",
  planNumber: "ICICIPRU197",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Health Assure",
  productCode: "105N050V01",
  planNumber: "ICICIPRU198",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Health Assure Plus",
  productCode: "105N051V01",
  planNumber: "ICICIPRU199",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Cancer Care",
  productCode: "105N052V01",
  planNumber: "ICICIPRU200",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Life Link Super",
  productCode: "105L053V01",
  planNumber: "ICICIPRU201",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Life Time Plus",
  productCode: "105L054V01",
  planNumber: "ICICIPRU202",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Lifetime Super Pension",
  productCode: "105L055V01",
  planNumber: "ICICIPRU203",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Lifetime Super",
  productCode: "105L056V01",
  planNumber: "ICICIPRU204",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Life Link Super Pension",
  productCode: "105L057V01",
  planNumber: "ICICIPRU205",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Smartkid New UL RP",
  productCode: "105L058V01",
  planNumber: "ICICIPRU206",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Smartkid New Unit Linked Single Premium",
  productCode: "105L059V01",
  planNumber: "ICICIPRU207",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Cash plus",
  productCode: "105L060V01",
  planNumber: "ICICIPRU208",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Premier Life Gold",
  productCode: "105L061V01",
  planNumber: "ICICIPRU209",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Investsheild Cashbak",
  productCode: "105L062V01",
  planNumber: "ICICIPRU210",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Investsheild Life - New",
  productCode: "105L063V01",
  planNumber: "ICICIPRU211",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Diabetes Care (Critical Illness Insurance)",
  productCode: "105N064V01",
  planNumber: "ICICIPRU212",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Diabetes Care Plus (Critical Illness + Life Insurance)",
  productCode: "105N065V01",
  planNumber: "ICICIPRU213",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Cancer Care Plus",
  productCode: "105N067V01",
  planNumber: "ICICIPRU214",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Hospital Care",
  productCode: "105N068V01",
  planNumber: "ICICIPRU215",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Crisis Cover",
  productCode: "105N072V01",
  planNumber: "ICICIPRU216",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru LifeStage RP",
  productCode: "105L073V01",
  planNumber: "ICICIPRU217",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Premier Life Pension",
  productCode: "105L074V01",
  planNumber: "ICICIPRU218",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru LifeStage Pension",
  productCode: "105L075V01",
  planNumber: "ICICIPRU219",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Diabetes Assure",
  productCode: "105N076V01",
  planNumber: "ICICIPRU220",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru LifeTime Gold",
  productCode: "105L077V01",
  planNumber: "ICICIPRU221",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Diabetes Care Active",
  productCode: "105N078V01",
  planNumber: "ICICIPRU222",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Diabetes Care Active",
  productCode: "105N078V02",
  planNumber: "ICICIPRU223",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Sarv Jana Suraksha",
  productCode: "105N081V01",
  planNumber: "ICICIPRU224",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Sarv Jana Suraksha",
  productCode: "105N081V02",
  planNumber: "ICICIPRU225",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Anmol Bachat",
  productCode: "105N139V02",
  planNumber: "ICICIPRU226",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Life MediAssure",
  productCode: "105N082V01",
  planNumber: "ICICIPRU227",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Life Stage Assure",
  productCode: "105L083V01",
  planNumber: "ICICIPRU228",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Pure Protect",
  productCode: "105N084V01",
  planNumber: "ICICIPRU229",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Pure Protect",
  productCode: "105N084V02",
  planNumber: "ICICIPRU230",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Wealth Advantage",
  productCode: "105L085V01",
  planNumber: "ICICIPRU231",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Anmol Nivesh",
  productCode: "105L086V01",
  planNumber: "ICICIPRU232",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Health Saver",
  productCode: "105L087V01",
  planNumber: "ICICIPRU233",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru SecureSave",
  productCode: "105L088V01",
  planNumber: "ICICIPRU234",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Life Stage Assure Pension",
  productCode: "105L092V01",
  planNumber: "ICICIPRU235",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Assure Life",
  productCode: "105L093V01",
  planNumber: "ICICIPRU236",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Elite Pension",
  productCode: "105L094V01",
  planNumber: "ICICIPRU237",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Pinnacle",
  productCode: "105L095V01",
  planNumber: "ICICIPRU238",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Life Time Maxima",
  productCode: "105L096V01",
  planNumber: "ICICIPRU239",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru premier Wealth",
  productCode: "105L097V01",
  planNumber: "ICICIPRU240",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Assure Wealth",
  productCode: "105L098V01",
  planNumber: "ICICIPRU241",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Elite pension II",
  productCode: "105L099V01",
  planNumber: "ICICIPRU242",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Life Stage Pension Advantage",
  productCode: "105L100V01",
  planNumber: "ICICIPRU243",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Life Time pension Maxima",
  productCode: "105L101V01",
  planNumber: "ICICIPRU244",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Assure Pension",
  productCode: "105L102V01",
  planNumber: "ICICIPRU245",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Life Stage Wealth",
  productCode: "105L103V01",
  planNumber: "ICICIPRU246",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Smart Kid Maxima",
  productCode: "105L104V01",
  planNumber: "ICICIPRU247",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Ace",
  productCode: "105L105V01",
  planNumber: "ICICIPRU248",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Smart Kid Assure",
  productCode: "105L106V01",
  planNumber: "ICICIPRU249",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Hospital Care II",
  productCode: "105N108V01",
  planNumber: "ICICIPRU250",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Save 'n' Protect - Single Premium",
  productCode: "105N109V01",
  planNumber: "ICICIPRU251",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru iProtect",
  productCode: "105N110V01",
  planNumber: "ICICIPRU252",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru iProtect",
  productCode: "105N110V02",
  planNumber: "ICICIPRU253",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Savings insurance Plan",
  productCode: "105N114V01",
  planNumber: "ICICIPRU254",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Savings insurance Plan",
  productCode: "105N114V02",
  planNumber: "ICICIPRU255",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI pru Whole Life",
  productCode: "105N116V01",
  planNumber: "ICICIPRU256",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Future Secure",
  productCode: "105N117V01",
  planNumber: "ICICIPRU257",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru iCare",
  productCode: "105N122V01",
  planNumber: "ICICIPRU258",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru iCare",
  productCode: "105N122V02",
  planNumber: "ICICIPRU259",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru iAssure Single premium",
  productCode: "105N123V01",
  planNumber: "ICICIPRU260",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Home Protect",
  productCode: "105N127V01",
  planNumber: "ICICIPRU261",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Cash Advantage",
  productCode: "105N132V01",
  planNumber: "ICICIPRU262",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Savings Suraksha",
  productCode: "105N135V01",
  planNumber: "ICICIPRU263",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Anmol Bachat",
  productCode: "105N139V01",
  planNumber: "ICICIPRU264",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Future Perfect",
  productCode: "105N153V01",
  planNumber: "ICICIPRU265",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru iCare II",
  productCode: "105N140V01",
  planNumber: "ICICIPRU266",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Loan Protect",
  productCode: "105N142V01",
  planNumber: "ICICIPRU267",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Easy Retirement",
  productCode: "105L133V01",
  planNumber: "ICICIPRU268",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Easy Retirement SP",
  productCode: "105L138V01",
  planNumber: "ICICIPRU269",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Heart/Cancer Protect",
  productCode: "105N154V01",
  planNumber: "ICICIPRU270",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Sarv Jana Suraksha",
  productCode: "105N081V03",
  planNumber: "ICICIPRU271",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Life Raksha",
  productCode: "105N149V01",
  planNumber: "ICICIPRU272",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru LifeLink Wealth SP",
  productCode: "105L111V01",
  planNumber: "ICICIPRU273",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Life Time Premier",
  productCode: "105L112V01",
  planNumber: "ICICIPRU274",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Life Time Premier",
  productCode: "105L112V02",
  planNumber: "ICICIPRU275",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Life Link Pension SP",
  productCode: "105L113V01",
  planNumber: "ICICIPRU276",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pinnacle II",
  productCode: "105L115V01",
  planNumber: "ICICIPRU277",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pinnacle II",
  productCode: "105L115V02",
  planNumber: "ICICIPRU278",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Life Stage Wealth II",
  productCode: "105L118V01",
  planNumber: "ICICIPRU279",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Life Stage Wealth II",
  productCode: "105L118V02",
  planNumber: "ICICIPRU280",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Smart Kid Premier",
  productCode: "105L120V01",
  planNumber: "ICICIPRU281",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Pinnacle Super",
  productCode: "105L121V01",
  planNumber: "ICICIPRU282",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Pinnacle Super",
  productCode: "105L121V02",
  planNumber: "ICICIPRU283",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Pinnacle Super",
  productCode: "105L121V03",
  planNumber: "ICICIPRU284",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Invest Easy",
  productCode: "105L124V01",
  planNumber: "ICICIPRU285",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Elite Life",
  productCode: "105L125V01",
  planNumber: "ICICIPRU286",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Elite Life",
  productCode: "105L125V02",
  planNumber: "ICICIPRU287",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Elite Wealth",
  productCode: "105L126V01",
  planNumber: "ICICIPRU288",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Elite Wealth",
  productCode: "105L126V02",
  planNumber: "ICICIPRU289",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Wealth Builder",
  productCode: "105L129V01",
  planNumber: "ICICIPRU290",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Shubh Retirement",
  productCode: "105L130V01",
  planNumber: "ICICIPRU291",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Shubh Retirement - SP",
  productCode: "105L131V01",
  planNumber: "ICICIPRU292",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Easy Retirement",
  productCode: "105L133V02",
  planNumber: "ICICIPRU293",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Loan Protect Plus",
  productCode: "105N150V01",
  planNumber: "ICICIPRU294",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Easy Retirement SP",
  productCode: "105L138V02",
  planNumber: "ICICIPRU295",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru iProtect Smart",
  productCode: "105N151V01",
  planNumber: "ICICIPRU296",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI pru Wealth Builder II",
  productCode: "105L139V01",
  planNumber: "ICICIPRU297",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Elite Wealth II",
  productCode: "105L140V01",
  planNumber: "ICICIPRU298",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Elite Life II",
  productCode: "105L141V01",
  planNumber: "ICICIPRU299",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Wealth Protector",
  productCode: "105L143V01",
  planNumber: "ICICIPRU300",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Assured Savings Insurance Plan",
  productCode: "105N144V01",
  planNumber: "ICICIPRU301",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Smart Life",
  productCode: "105L145V01",
  planNumber: "ICICIPRU302",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Life Time Classic",
  productCode: "105L155V01",
  planNumber: "ICICIPRU303",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Elite Life Super",
  productCode: "105L156V01",
  planNumber: "ICICIPRU304",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Elite Wealth Super",
  productCode: "105L157V01",
  planNumber: "ICICIPRU305",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Loan Protect Plus",
  productCode: "105N150V02",
  planNumber: "ICICIPRU306",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru iProtect Smart",
  productCode: "105N151V02",
  planNumber: "ICICIPRU307",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICIPru iProtect Smart",
  productCode: "105N151V03",
  planNumber: "ICICIPRU308",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru POS iProtect Smart",
  productCode: "105N173V01",
  planNumber: "ICICIPRU309",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru1 Wealth",
  productCode: "105L175V01",
  planNumber: "ICICIPRU310",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru POS Life Raksha",
  productCode: "105N174V01",
  planNumber: "ICICIPRU311",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Smart Life",
  productCode: "105L145V02",
  planNumber: "ICICIPRU312",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Life Time Classic",
  productCode: "105L155V02",
  planNumber: "ICICIPRU313",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Elite Life Super",
  productCode: "105L156V02",
  planNumber: "ICICIPRU314",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Elite Wealth Super",
  productCode: "105L157V02",
  planNumber: "ICICIPRU315",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru iCare II",
  productCode: "105N140V02",
  planNumber: "ICICIPRU316",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICIPru iProtect Smart",
  productCode: "105N151V04",
  planNumber: "ICICIPRU317",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Smart Life",
  productCode: "105L145V03",
  planNumber: "ICICIPRU318",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Assured Savings Insurance Plan",
  productCode: "105N144V02",
  planNumber: "ICICIPRU319",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Signature",
  productCode: "105L177V01",
  planNumber: "ICICIPRU320",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Smart Life",
  productCode: "105L145V04",
  planNumber: "ICICIPRU321",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Life Time Classic",
  productCode: "105L155V03",
  planNumber: "ICICIPRU322",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Elite Life Super",
  productCode: "105L156V03",
  planNumber: "ICICIPRU323",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Elite Wealth Super",
  productCode: "105L157V03",
  planNumber: "ICICIPRU324",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Assured Savings Insurance Plan",
  productCode: "105N144V03",
  planNumber: "ICICIPRU325",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Signature",
  productCode: "105L177V02",
  planNumber: "ICICIPRU326",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Smart Life",
  productCode: "105L145V05",
  planNumber: "ICICIPRU327",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Life Time Classic",
  productCode: "105L155V04",
  planNumber: "ICICIPRU328",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru1 Wealth",
  productCode: "105L175V02",
  planNumber: "ICICIPRU329",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Sarv Jana Suraksha",
  productCode: "105N081V04",
  planNumber: "ICICIPRU330",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Heart/Cancer Protect",
  productCode: "105N154V02",
  planNumber: "ICICIPRU331",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru POS iProtect Smart",
  productCode: "105N173V02",
  planNumber: "ICICIPRU332",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICIPru iProtect Smart",
  productCode: "105N151V05",
  planNumber: "ICICIPRU333",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Lakshya",
  productCode: "105N179V01",
  planNumber: "ICICIPRU334",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Cash Advantage",
  productCode: "105N132V02",
  planNumber: "ICICIPRU335",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Savings Suraksha",
  productCode: "105N135V02",
  planNumber: "ICICIPRU336",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Assured Savings Insurance Plan",
  productCode: "105N144V04",
  planNumber: "ICICIPRU337",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Assured Savings Insurance Plan",
  productCode: "105N144V05",
  planNumber: "ICICIPRU338",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICIPru iProtect Smart",
  productCode: "105N151V06",
  planNumber: "ICICIPRU339",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Assured Savings Insurance Plan",
  productCode: "105N144V06",
  planNumber: "ICICIPRU340",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Pension Plan",
  productCode: "105N181V01",
  planNumber: "ICICIPRU341",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Income For Tomorrow",
  productCode: "105N182V01",
  planNumber: "ICICIPRU342",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Assured Savings Insurance Plan",
  productCode: "105N144V07",
  planNumber: "ICICIPRU343",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Income For Tomorrow",
  productCode: "105N182V02",
  planNumber: "ICICIPRU344",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Assured Savings Insurance Plan",
  productCode: "105N144V08",
  planNumber: "ICICIPRU345",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Saral Pension",
  productCode: "105N184V01",
  planNumber: "ICICIPRU346",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Life Time Classic",
  productCode: "105L155V05",
  planNumber: "ICICIPRU347",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Pension Plan",
  productCode: "105N181V02",
  planNumber: "ICICIPRU348",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Signature",
  productCode: "105L177V03",
  planNumber: "ICICIPRU349",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru1 Wealth",
  productCode: "105L175V03",
  planNumber: "ICICIPRU350",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Smart Life",
  productCode: "105L145V06",
  planNumber: "ICICIPRU351",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Life Time Classic",
  productCode: "105L155V06",
  planNumber: "ICICIPRU352",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Income For Tomorrow (Long-term)",
  productCode: "105N185V01",
  planNumber: "ICICIPRU353",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Income For Tomorrow (Long-term)",
  productCode: "105N185V02",
  planNumber: "ICICIPRU354",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Income For Tomorrow",
  productCode: "105N182V03",
  planNumber: "ICICIPRU355",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Income For Tomorrow (Long-term)",
  productCode: "105N185V03",
  planNumber: "ICICIPRU356",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Saral Pension",
  productCode: "105N184V02",
  planNumber: "ICICIPRU357",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Pension Plan Flexi",
  productCode: "105N187V01",
  planNumber: "ICICIPRU358",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Pension Plan Flexi",
  productCode: "105N187V02",
  planNumber: "ICICIPRU359",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Saral Pension",
  productCode: "105N184V03",
  planNumber: "ICICIPRU360",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Income For Tomorrow (Long-term)",
  productCode: "105N185V04",
  planNumber: "ICICIPRU361",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Income For Tomorrow",
  productCode: "105N182V04",
  planNumber: "ICICIPRU362",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Pension Plan Flexi",
  productCode: "105N187V03",
  planNumber: "ICICIPRU363",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Saral Pension",
  productCode: "105N184V04",
  planNumber: "ICICIPRU364",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Income For Tomorrow (Long-term)",
  productCode: "105N185V05",
  planNumber: "ICICIPRU365",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Income For Tomorrow",
  productCode: "105N182V05",
  planNumber: "ICICIPRU366",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Income For Tomorrow (Long-term)",
  productCode: "105N185V06",
  planNumber: "ICICIPRU367",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Income For Tomorrow",
  productCode: "105N182V06",
  planNumber: "ICICIPRU368",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Life Time Classic",
  productCode: "105L155V07",
  planNumber: "ICICIPRU369",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Signature",
  productCode: "105L177V04",
  planNumber: "ICICIPRU370",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Smart Life",
  productCode: "105L145V07",
  planNumber: "ICICIPRU371",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Saral Pension",
  productCode: "105N184V05",
  planNumber: "ICICIPRU372",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Income For Tomorrow (Long-term)",
  productCode: "105N185V07",
  planNumber: "ICICIPRU373",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Income For Tomorrow (Long-term)",
  productCode: "105N185V08",
  planNumber: "ICICIPRU374",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru EzyGrow",
  productCode: "105L189V01",
  planNumber: "ICICIPRU375",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Pension Plan Flexi",
  productCode: "105N187V04",
  planNumber: "ICICIPRU376",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Income For Tomorrow (Long-term)",
  productCode: "105N185V09",
  planNumber: "ICICIPRU377",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Gold",
  productCode: "105N190V01",
  planNumber: "ICICIPRU378",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Income For Tomorrow (Long-term)",
  productCode: "105N185V10",
  planNumber: "ICICIPRU379",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru EzyGrow",
  productCode: "105L189V02",
  planNumber: "ICICIPRU380",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru iProtect Smart",
  productCode: "105N151V07",
  planNumber: "ICICIPRU381",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Income For Tomorrow (Long-term)",
  productCode: "105N185V11",
  planNumber: "ICICIPRU382",
  providerCode: "ICICI_PRU",
},
{
  productName: "iShield (Combi with Lombard)",
  productCode: "ICIHLIP24028V012324",
  planNumber: "ICICIPRU383",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Income For Tomorrow (Long-term)",
  productCode: "105N185V12",
  planNumber: "ICICIPRU384",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Life Time Classic",
  productCode: "105L155V08",
  planNumber: "ICICIPRU385",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Signature",
  productCode: "105L177V05",
  planNumber: "ICICIPRU386",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Protect N Gain",
  productCode: "105L191V01",
  planNumber: "ICICIPRU387",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru GIFT Pro",
  productCode: "105N201V01",
  planNumber: "ICICIPRU388",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru GIFT Pro",
  productCode: "105N201V02",
  planNumber: "ICICIPRU389",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru iProtect Smart",
  productCode: "105N151V08",
  planNumber: "ICICIPRU390",
  providerCode: "ICICI_PRU",
},
{
  productName: "iShield (Combi with Lombard)",
  productCode: "ICIHLIP24082V022324",
  planNumber: "ICICIPRU391",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Income For Tomorrow (Long-term)",
  productCode: "105N185V13",
  planNumber: "ICICIPRU392",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Assured Savings Insurance Plan",
  productCode: "105N144V09",
  planNumber: "ICICIPRU393",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Income For Tomorrow",
  productCode: "105N182V07",
  planNumber: "ICICIPRU394",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru EzyGrow",
  productCode: "105L189V03",
  planNumber: "ICICIPRU395",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Income For Tomorrow (Long-term)",
  productCode: "105N185V14",
  planNumber: "ICICIPRU396",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru iProtect Smart",
  productCode: "105N151V09",
  planNumber: "ICICIPRU397",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Guaranteed Income For Tomorrow",
  productCode: "105N182V08",
  planNumber: "ICICIPRU398",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Saral Pension",
  productCode: "105N184V06",
  planNumber: "ICICIPRU399",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru iProtect Smart",
  productCode: "105N151V10",
  planNumber: "ICICIPRU400",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Protect N Gain",
  productCode: "105L191V02",
  planNumber: "ICICIPRU401",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Protect N Gain",
  productCode: "105L191V03",
  planNumber: "ICICIPRU402",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Protect N Gain",
  productCode: "105L191V04",
  planNumber: "ICICIPRU403",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Protect N Gain",
  productCode: "105L191V05",
  planNumber: "ICICIPRU404",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Platinum",
  productCode: "105L192V01",
  planNumber: "ICICIPRU405",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru GIFT Pro",
  productCode: "105N201V03",
  planNumber: "ICICIPRU406",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru1 Wealth",
  productCode: "105L175V04",
  planNumber: "ICICIPRU407",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Gold",
  productCode: "105N190V03",
  planNumber: "ICICIPRU408",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Gift Select",
  productCode: "105N223V01",
  planNumber: "ICICIPRU409",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Signature",
  productCode: "105L177V08",
  planNumber: "ICICIPRU410",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Signature Pension",
  productCode: "105L194V01",
  planNumber: "ICICIPRU411",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Immediate Annuity",
  productCode: "105N009V25",
  planNumber: "ICICIPRU412",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Immediate Annuity",
  productCode: "105N009V24",
  planNumber: "ICICIPRU413",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Immediate Annuity",
  productCode: "105N009V23",
  planNumber: "ICICIPRU414",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Unit Linked Superannuation Plus",
  productCode: "105L200V01",
  planNumber: "ICICIPRU415",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Super Protect - Credit",
  productCode: "105N176V02",
  planNumber: "ICICIPRU416",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Shubh Raksha Credit",
  productCode: "105N159V02",
  planNumber: "ICICIPRU417",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Unit Linked Superannuation",
  productCode: "105L136V02",
  planNumber: "ICICIPRU418",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Suraksha Plus Superannuation",
  productCode: "105N148V02",
  planNumber: "ICICIPRU419",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Super Protect Life",
  productCode: "105N180V01",
  planNumber: "ICICIPRU420",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Immediate Annuity",
  productCode: "105N009V22",
  planNumber: "ICICIPRU421",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Immediate Annuity",
  productCode: "105N009V21",
  planNumber: "ICICIPRU422",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Unit Linked Employee Benefit Plan",
  productCode: "105L137V03",
  planNumber: "ICICIPRU423",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Insurance Scheme for Pradhan Mantri Jeevan Jyoti Bima Yojana",
  productCode: "105G146V01",
  planNumber: "ICICIPRU424",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Suraksha Plus",
  productCode: "105N147V02",
  planNumber: "ICICIPRU425",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Term Plus",
  productCode: "105N119V07",
  planNumber: "ICICIPRU426",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Loan Secure",
  productCode: "105N152V03",
  planNumber: "ICICIPRU427",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Shubh Raksha Credit",
  productCode: "105N159V01",
  planNumber: "ICICIPRU428",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Shubh Raksha One",
  productCode: "105N158V02",
  planNumber: "ICICIPRU429",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Shubh Raksha Life",
  productCode: "105N160V02",
  planNumber: "ICICIPRU430",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Super Protect - Credit",
  productCode: "105N176V01",
  planNumber: "ICICIPRU431",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Immediate Annuity",
  productCode: "105N009V06",
  planNumber: "ICICIPRU432",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Immediate Annuity",
  productCode: "105N009V07",
  planNumber: "ICICIPRU433",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Term Insurance",
  productCode: "105N019V01",
  planNumber: "ICICIPRU434",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Term Insurance",
  productCode: "105N019V02",
  planNumber: "ICICIPRU435",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Gratuity",
  productCode: "105L023V01",
  planNumber: "ICICIPRU436",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Gratuity",
  productCode: "105L023V02",
  planNumber: "ICICIPRU437",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Gratuity",
  productCode: "105L023V03",
  planNumber: "ICICIPRU438",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Superannuation Plan",
  productCode: "105L024V01",
  planNumber: "ICICIPRU439",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Superannuation",
  productCode: "105L024V02",
  planNumber: "ICICIPRU440",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Term Insurance with Profit Sharing",
  productCode: "105N030V01",
  planNumber: "ICICIPRU441",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Leave Encashment Plan",
  productCode: "105L039V01",
  planNumber: "ICICIPRU442",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Home Assure",
  productCode: "105N044V01",
  planNumber: "ICICIPRU443",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Gratuity Plus",
  productCode: "105L045V01",
  planNumber: "ICICIPRU444",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Gratuity Plus",
  productCode: "105L045V02",
  planNumber: "ICICIPRU445",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Gratuity Plus",
  productCode: "105L045V03",
  planNumber: "ICICIPRU446",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Gratuity Platinum",
  productCode: "105L046V01",
  planNumber: "ICICIPRU447",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Gratuity Platinum",
  productCode: "105L046V02",
  planNumber: "ICICIPRU448",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Gratuity Platinum",
  productCode: "105L046V03",
  planNumber: "ICICIPRU449",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Superannuation plus",
  productCode: "105L048V01",
  planNumber: "ICICIPRU450",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Superannuation plus",
  productCode: "105L048V02",
  planNumber: "ICICIPRU451",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Superannuation Platinum",
  productCode: "105L049V01",
  planNumber: "ICICIPRU452",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Superannuation Platinum",
  productCode: "105L049V02",
  planNumber: "ICICIPRU453",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Credit Assure",
  productCode: "105N066V01",
  planNumber: "ICICIPRU454",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru New Group Superannuation",
  productCode: "105L069V01",
  planNumber: "ICICIPRU455",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru New Group Superannuation Plus",
  productCode: "105L070V01",
  planNumber: "ICICIPRU456",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru New Group Superannuation Platinum",
  productCode: "105L071V01",
  planNumber: "ICICIPRU457",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group leave Encashment",
  productCode: "105L079V01",
  planNumber: "ICICIPRU458",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group leave Encashment",
  productCode: "105L079V02",
  planNumber: "ICICIPRU459",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group leave Encashment Plus",
  productCode: "105L080V01",
  planNumber: "ICICIPRU460",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group leave Encashment Plus",
  productCode: "105L080V02",
  planNumber: "ICICIPRU461",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Superannuation Suraksha",
  productCode: "105N089V01",
  planNumber: "ICICIPRU462",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Gratuity Suraksha",
  productCode: "105N090V01",
  planNumber: "ICICIPRU463",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Leave Encashment Suraksha",
  productCode: "105N091V01",
  planNumber: "ICICIPRU464",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Structured Annuity",
  productCode: "105N107V01",
  planNumber: "ICICIPRU465",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Term Plus",
  productCode: "105N119V01",
  planNumber: "ICICIPRU466",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Term Plus",
  productCode: "105N119V02",
  planNumber: "ICICIPRU467",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Loan Secure",
  productCode: "105N152V01",
  planNumber: "ICICIPRU468",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI pru Structured Annuity - Government Scheme",
  productCode: "105N128V01",
  planNumber: "ICICIPRU469",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Super Annuation Suraksha",
  productCode: "105N134V01",
  planNumber: "ICICIPRU470",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Term Plus",
  productCode: "105N119V03",
  planNumber: "ICICIPRU471",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Suraksha Plus",
  productCode: "105N147V01",
  planNumber: "ICICIPRU472",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Suraksha Plus Superannuation",
  productCode: "105N148V01",
  planNumber: "ICICIPRU473",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Unit Linked Superannuation",
  productCode: "105L136V01",
  planNumber: "ICICIPRU474",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Unit Linked Employee Benefit Plan",
  productCode: "105L137V01",
  planNumber: "ICICIPRU475",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Term Plus",
  productCode: "105N119V04",
  planNumber: "ICICIPRU476",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICIPru Immediate Annuity",
  productCode: "105N009V08",
  planNumber: "ICICIPRU477",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Loan Secure",
  productCode: "105N152V02",
  planNumber: "ICICIPRU478",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICIPru Immediate Annuity",
  productCode: "105N009V09",
  planNumber: "ICICIPRU479",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICIPru Immediate Annuity",
  productCode: "105N009V10",
  planNumber: "ICICIPRU480",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Shubh Raksha One",
  productCode: "105N158V01",
  planNumber: "ICICIPRU481",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Shubh Raksha Life",
  productCode: "105N160V01",
  planNumber: "ICICIPRU482",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICIPru Immediate Annuity",
  productCode: "105N009V11",
  planNumber: "ICICIPRU483",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICIPru Immediate Annuity",
  productCode: "105N009V12",
  planNumber: "ICICIPRU484",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICIPru Immediate Annuity",
  productCode: "105N009V13",
  planNumber: "ICICIPRU485",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Unit Linked Employee Benefit Plan",
  productCode: "105L137V02",
  planNumber: "ICICIPRU486",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICIPru Immediate Annuity",
  productCode: "105N009V14",
  planNumber: "ICICIPRU487",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Term Plus",
  productCode: "105N119V05",
  planNumber: "ICICIPRU488",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Immediate Annuity",
  productCode: "105N009V15",
  planNumber: "ICICIPRU489",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Term Plus",
  productCode: "105N119V06",
  planNumber: "ICICIPRU490",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Immediate Annuity",
  productCode: "105N009V16",
  planNumber: "ICICIPRU491",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Immediate Annuity",
  productCode: "105N009V17",
  planNumber: "ICICIPRU492",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Immediate Annuity",
  productCode: "105N009V18",
  planNumber: "ICICIPRU493",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Immediate Annuity",
  productCode: "105N009V19",
  planNumber: "ICICIPRU494",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Immediate Annuity",
  productCode: "105N009V20",
  planNumber: "ICICIPRU495",
  providerCode: "ICICI_PRU",
},
{
  productName: "ICICI Pru Group Nischit Aay Yojna",
  productCode: "105N203V01",
  planNumber: "ICICIPRU496",
  providerCode: "ICICI_PRU",
}

  ];