export const indiafirstProducts = [
    
  //INDIAFIRST Products
  {
    productName: "IndiaFirst Life Elite Term Plan",
    productCode: "143N070V01",
    planNumber: "IF-LI-001",
    providerCode: "INDIAFIRST",
    productType: "Term Insurance",
  },
  {
    productName: "IndiaFirst Life Super Protection Plan",
    productCode: "143N075V01",
    planNumber: "IF-LI-002",
    providerCode: "INDIAFIRST",
    productType: "Term Insurance",
  },
  {
    productName: "IndiaFirst Life Plan",
    productCode: "143N007V03",
    planNumber: "IF-LI-003",
    providerCode: "INDIAFIRST",
    productType: "Term Insurance",
  },
  {
    productName: "IndiaFirst Life Saral Jeevan Bima Plan",
    productCode: "143N061V01",
    planNumber: "IF-LI-004",
    providerCode: "INDIAFIRST",
    productType: "Term Insurance",
  },
  {
    productName: "IndiaFirst Life Protect Shield Plus Plan",
    productCode: "143N078V01",
    planNumber: "IF-LI-005",
    providerCode: "INDIAFIRST",
    productType: "Term Insurance",
  },
  {
    productName: "IndiaFirst Life Assured Income For Milestones Plan",
    productCode: "143N101V01",
    planNumber: "IF-LI-006",
    providerCode: "INDIAFIRST",
    productType: "Savings  Plan",
  },
  {
    productName: "IndiaFirst Life Guarantee Of Life Dreams Plan",
    productCode: "143N080V03",
    planNumber: "IF-LI-007",
    providerCode: "INDIAFIRST",
    productType: "Savings  Plan",
  },
  {
    productName: "IndiaFirst Life Growth of Life Dreams Plus Plan",
    productCode: "143N093V02",
    planNumber: "IF-LI-008",
    providerCode: "INDIAFIRST",
    productType: "Savings  Plan",
  },
  {
    productName: "IndiaFirst Life Long Guaranteed Income Plan",
    productCode: "143N054V06",
    planNumber: "IF-LI-009",
    providerCode: "INDIAFIRST",
    productType: "Savings  Plan",
  },
  {
    productName: "IndiaFirst Life Fortune Plus Plan",
    productCode: "143N065V03",
    planNumber: "IF-LI-010",
    providerCode: "INDIAFIRST",
    productType: "Savings  Plan",
  },
  {
    productName: "IndiaFirst Life Mahajeevan Plus Plan",
    productCode: "143N059V03",
    planNumber: "IF-LI-011",
    providerCode: "INDIAFIRST",
    productType: "Savings  Plan",
  },
  {
    productName: "IndiaFirst Life Cash Back Plan",
    productCode: "143N024V05",
    planNumber: "IF-LI-012",
    providerCode: "INDIAFIRST",
    productType: "Savings  Plan",
  },
  {
    productName: "IndiaFirst Life Mahajeevan Plan",
    productCode: "143N018V05",
    planNumber: "IF-LI-013",
    providerCode: "INDIAFIRST",
    productType: "Savings  Plan",
  },
  {
    productName: "IndiaFirst Simple Benefit Plan",
    productCode: "143N019V03",
    planNumber: "IF-LI-014",
    providerCode: "INDIAFIRST",
    productType: "Savings  Plan",
  },
  {
    productName: "IndiaFirst Life Guaranteed Monthly Income Plan",
    productCode: "143N047V01",
    planNumber: "IF-LI-015",
    providerCode: "INDIAFIRST",
    productType: "Savings  Plan",
  },
  {
    productName: "IndiaFirst Life Smart Pay Plan",
    productCode: "143N051V04",
    planNumber: "IF-LI-016",
    providerCode: "INDIAFIRST",
    productType: "Savings  Plan",
  },
  {
    productName: "IndiaFirst Life Saral Bachat Bima Plan",
    productCode: "143N063V02",
    planNumber: "IF-LI-017",
    providerCode: "INDIAFIRST",
    productType: "Savings  Plan",
  },
  {
    productName: "IndiaFirst Life Micro Bachat Plan",
    productCode: "143N052V02",
    planNumber: "IF-LI-018",
    providerCode: "INDIAFIRST",
    productType: "Savings  Plan",
  },
  {
    productName: "IndiaFirst Life Guaranteed Benefit Plan",
    productCode: "143N056V09",
    planNumber: "IF-LI-019",
    providerCode: "INDIAFIRST",
    productType: "Savings  Plan",
  },
  {
    productName: "IndiaFirst Life CSC Shubhlabh Plan",
    productCode: "143N023V01",
    planNumber: "IF-LI-020",
    providerCode: "INDIAFIRST",
    productType: "Savings  Plan",
  },
  {
    productName:
      "IndiaFirst Life “INSURANCE KHATA” Plan (MicroInsuranceProduct)",
    productCode: "143N057V03",
    planNumber: "IF-LI-021",
    providerCode: "INDIAFIRST",
    productType: "Savings  Plan",
  },
  {
    productName: "IndiaFirst Life POS Cash Back Plan",
    productCode: "143N034V01",
    planNumber: "IF-LI-022",
    providerCode: "INDIAFIRST",
    productType: "Savings  Plan",
  },
  {
    productName: "IndiaFirst Life Radiance Smart Invest Plan",
    productCode: "143L067V01",
    planNumber: "IF-LI-023",
    providerCode: "INDIAFIRST",
    productType: "ULIP Plans",
  },
  {
    productName: "IndiaFirst Life Wealth Maximizer Plan",
    productCode: "143L029V05",
    planNumber: "IF-LI-024",
    providerCode: "INDIAFIRST",
    productType: "ULIP Plans",
  },
  {
    productName: "IndiaFirst Life Money Balance Plan",
    productCode: "143L017V07",
    planNumber: "IF-LI-025",
    providerCode: "INDIAFIRST",
    productType: "ULIP Plans",
  },
  {
    productName: "IndiaFirst Smart Save Plan",
    productCode: "143L010V04",
    planNumber: "IF-LI-026",
    providerCode: "INDIAFIRST",
    productType: "ULIP Plans",
  },
  {
    productName: "IndiaFirst Life Guaranteed Single Premium Plan",
    productCode: "143N068V04",
    planNumber: "IF-LI-027",
    providerCode: "INDIAFIRST",
    productType: "Guaranteed Returns Plans",
  },
  {
    productName: "IndiaFirst Life Little Champ Plan",
    productCode: "143N035V02",
    planNumber: "IF-LI-028",
    providerCode: "INDIAFIRST",
    productType: "Child Insurance Plans",
  },
  {
    productName: "IndiaFirst LIfe Smart Retirement Plan",
    productCode: "143L076V01",
    planNumber: "IF-LI-029",
    providerCode: "INDIAFIRST",
    productType: "Retirement & Pension Plans",
  },
  {
    productName: "IndiaFirst Guaranteed Retirement Plan",
    productCode: "143N026V02",
    planNumber: "IF-LI-030",
    providerCode: "INDIAFIRST",
    productType: "Retirement & Pension Plans",
  },
  {
    productName: "IndiaFirst Life Guaranteed Annuity Pension Plan",
    productCode: "143N050V07",
    planNumber: "IF-LI-031",
    providerCode: "INDIAFIRST",
    productType: "Retirement & Pension Plans",
  },
  {
    productName: "IndiaFirst Life Guaranteed Pension Plan",
    productCode: "143N066V05",
    planNumber: "IF-LI-032",
    providerCode: "INDIAFIRST",
    productType: "Retirement & Pension Plans",
  },
  {
    productName: "IndiaFirst Life Saral Pension Plan",
    productCode: "143N062V01",
    planNumber: "IF-LI-033",
    providerCode: "INDIAFIRST",
    productType: "Retirement & Pension Plans",
  },
  {
    productName: "IndiaFirst Life Group Living Benefits Plan",
    productCode: "143N040V02",
    planNumber: "IF-LI-034",
    providerCode: "INDIAFIRST",
    productType: "Group & Corporate Life Insurance Plans",
  },
  {
    productName: "IndiaFirst Group Term Plan",
    productCode: "143N006V06",
    planNumber: "IF-LI-035",
    providerCode: "INDIAFIRST",
    productType: "Group & Corporate Life Insurance Plans",
  },
  {
    productName: "Group Credit Life Plus Plan",
    productCode: "143N036V02",
    planNumber: "IF-LI-036",
    providerCode: "INDIAFIRST",
    productType: "Group & Corporate Life Insurance Plans",
  },
  {
    productName: "IndiaFirst Group Micro Insurance Plan",
    productCode: "143N053V03",
    planNumber: "IF-LI-037",
    providerCode: "INDIAFIRST",
    productType: "Group & Corporate Life Insurance Plans",
  },
  {
    productName: "IndiaFirst Life Group Loan Protect Plan",
    productCode: "143N055V02",
    planNumber: "IF-LI-038",
    providerCode: "INDIAFIRST",
    productType: "Group & Corporate Life Insurance Plans",
  },
  {
    productName: "IndiaFirst Life Group HospiCare Plan",
    productCode: "143N039V02",
    planNumber: "IF-LI-039",
    providerCode: "INDIAFIRST",
    productType: "Group & Corporate Life Insurance Plans",
  },
  {
    productName: "IndiaFirst Life Group Critical Illness Rider Plan",
    productCode: "143B002V02",
    planNumber: "IF-LI-040",
    providerCode: "INDIAFIRST",
    productType: "Group & Corporate Life Insurance Plans",
  },
  {
    productName: "IndiaFirst Life Group Additional Benefit Rider Plan",
    productCode: "143B018V02",
    planNumber: "IF-LI-041",
    providerCode: "INDIAFIRST",
    productType: "Group & Corporate Life Insurance Plans",
  },
  {
    productName: "Group Disability Rider",
    productCode: "143B004V02",
    planNumber: "IF-LI-042",
    providerCode: "INDIAFIRST",
    productType: "Group & Corporate Life Insurance Plans",
  },
  {
    productName: "Unit Linked Superannuation Plan",
    productCode: "143L060V01",
    planNumber: "IF-LI-043",
    providerCode: "INDIAFIRST",
    productType: "Group & Corporate Life Insurance Plans",
  },
  {
    productName: "Superannuation Plan",
    productCode: "143N020V03",
    planNumber: "IF-LI-044",
    providerCode: "INDIAFIRST",
    productType: "Group & Corporate Life Insurance Plans",
  },
  {
    productName: "New Corporate Benefit Plan",
    productCode: "143N022V02",
    planNumber: "IF-LI-045",
    providerCode: "INDIAFIRST",
    productType: "Group & Corporate Life Insurance Plans",
  },
  {
    productName: "IndiaFirst Employee Benefit Plan",
    productCode: "143L013V02",
    planNumber: "IF-LI-046",
    providerCode: "INDIAFIRST",
    productType: "Group & Corporate Life Insurance Plans",
  },
  {
    productName: "IndiaFirst Life TULIP Plan",
    productCode: "ILTP",
    planNumber: "IF-LI-047",
    providerCode: "INDIAFIRST",
  },
{
    productName: "IndiaFirst Life Guaranteed Income Plan",
    productCode: "ILGIP",
    planNumber: "IF-LI-048",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "25K Salary Term Insurance Plan",
    productCode: "2STIP",
    planNumber: "IF-LI-049",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "30K Salary Term Insurance Plan",
    productCode: "3STIP",
    planNumber: "IF-LI-050",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "50K Salary Term Insurance Plan",
    productCode: "5STIP",
    planNumber: "IF-LI-051",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Pradhan Mantri Jeevan Jyoti Bima Yojana",
    productCode: "IPMJJBY",
    planNumber: "IF-LI-052",
    providerCode: "INDIAFIRST",
  }
  
  

];