export const licProducts = [
  {
    productName: 'Single Premium Endowment Plan',
    productCode: '512N283V03',
    planNumber: '717',
    providerCode: 'LIC',
    productType: 'Endowment'
  },
  {
    productName: "LIC's New Endowment Plan",
    productCode: '512N277V03',
    planNumber: '714',
    providerCode: 'LIC',
    productType: 'Endowment'
  },
  {
    productName: "LIC's New Jeevan Anand",
    productCode: '512N279V03',
    planNumber: '715',
    providerCode: 'LIC',
    productType: 'Savings + Whole Life'
  },
  {
    productName: 'LIC Jeevan Lakshya',
    productCode: '512N297V03',
    planNumber: '733',
    providerCode: 'LIC',
    productType: 'Child Saving Plan'
  },
  {
    productName: 'LIC Jeevan Labh',
    productCode: '512N304V03',
    planNumber: '736',
    providerCode: 'LIC',
    productType: 'Endowment Savings Plan'
  },
  {
    productName: 'LIC Amritbaal',
    productCode: '512N365V02',
    planNumber: '774',
    providerCode: 'LIC',
    productType: 'Child Saving Plan'
  },
  {
    productName: 'LIC Bima Jyoti',
    productCode: '512N339V03',
    planNumber: '760',
    providerCode: 'LIC',
    productType: 'Savings Plan'
  },
  {
    productName: 'LIC Nav Jeevan Shree',
    productCode: '512N387V02',
    planNumber: '912',
    providerCode: 'LIC',
    productType: 'Savings Plan'
  },
  {
    productName: 'LIC Bima Lakshmi',
    productCode: '512N389V01',
    planNumber: '881',
    providerCode: 'LIC',
    productType: 'Women Savings Plan'
  },
  {
    productName: 'LIC New Jeevan Sathi Single Premium',
    productCode: '512N393V01',
    planNumber: '888',
    providerCode: 'LIC',
    productType: 'Joint Life Savings Plan'
  },
  {
    productName: 'LIC New Jeevan Sathi-Limited Premium',
    productCode: '512N394V01',
    planNumber: '889',
    providerCode: 'LIC',
    productType: 'Joint Life Savings Plan'
  },

  //Whole Life Plans

  {
    productName: "LIC Jeevan Umang",
    productCode: "512N312V03",
    planNumber: "745",
    providerCode: "LIC",
    productType: "Savings + Whole Life",
  },
  {
    productName: "LIC Jeevan Utsav",
    productCode: "512N363V02",
    planNumber: "771",
    providerCode: "LIC",
    productType: "Whole Life Insurance Plan",
  },
  {
    productName: "LIC Jeevan Utsav Single Premium",
    productCode: "512N392V01",
    planNumber: "883",
    providerCode: "LIC",
    productType: "Whole Life Insurance Plan",
  },

  //Money back Plans

  {
    productName: "LIC Bima Shree",
    productCode: "512N316V03",
    planNumber: "748",
    providerCode: "LIC",
    productType: "Money Back Savings Plan",
  },
  {
    productName: "LIC New Money Back Plan 20 Years",
    productCode: "512N280V03",
    planNumber: "720",
    providerCode: "LIC",
    productType: "Money Back Plan",
  },
  {
    productName: "LIC New Money Back Plan 25 Years",
    productCode: "512N278V03",
    planNumber: "721",
    providerCode: "LIC",
    productType: "Money Back Plan",
  },
  {
    productName: "LIC New Children's Money Back Plan",
    productCode: "512N296V03",
    planNumber: "732",
    providerCode: "LIC",
    productType: "Childrens Money Back Plan",
  },
  {
    productName: "LIC Jeevan Tarun",
    productCode: "512N299V03",
    planNumber: "734",
    providerCode: "LIC",
    productType: "Childrens Money Back Plan",
  },

  //Term Assurance Plan
  {
    productName: "LIC Digi Term",
    productCode: "512N356V02",
    planNumber: "876",
    providerCode: "LIC",
    productType: "Term Assurance Plan",
  },
  {
    productName: "LIC Digi Credit Life",
    productCode: "512N358V01",
    planNumber: "878",
    providerCode: "LIC",
    productType: "Credit Life Term Assurance Plan",
  },
  {
    productName: "LIC Yuva Credit Life",
    productCode: "512N357V01",
    planNumber: "877",
    providerCode: "LIC",
    productType: "Credit Life Term Assurance Plan",
  },
  {
    productName: "LIC Yuva Term",
    productCode: "512N355V02",
    planNumber: "875",
    providerCode: "LIC",
    productType: "Term Assurance Plan",
  },
  {
    productName: "LIC New Tech-Term",
    productCode: "512N351V02",
    planNumber: "954",
    providerCode: "LIC",
    productType: "Term Assurance Plan",
  },
  {
    productName: "LIC New Jeevan Amar",
    productCode: "512N350V02",
    planNumber: "955",
    providerCode: "LIC",
    productType: "Term Assurance Plan",
  },
  {
    productName: "LIC Saral Jeevan Bima",
    productCode: "512N341V01",
    planNumber: "859",
    providerCode: "LIC",
    productType: "Term Assurance Plan",
  },
  {
    productName: "LIC Bima Kavach",
    productCode: "512N360V01",
    planNumber: "887",
    providerCode: "LIC",
    productType: "Term Assurance Plan",
  },

  //Pension Plans
  {
    productName: "LIC New Pension Plus",
    productCode: "512L347V01",
    planNumber: "867",
    providerCode: "LIC",
    productType: "Pension Plan",
  },
  {
    productName: "LIC Jeevan Akshay VII",
    productCode: "512N337V07",
    planNumber: "857",
    providerCode: "LIC",
    productType: "Immediate Annuity Pension Plan",
  },
  {
    productName: "LIC New Jeevan Shanti",
    productCode: "512N338V08",
    planNumber: "858",
    providerCode: "LIC",
    productType: "Deferred Annuity Pension Plan",
  },
  {
    productName: "LIC Saral Pension",
    productCode: "512N342V05",
    planNumber: "862",
    providerCode: "LIC",
    productType: "Immediate Annuity Pension Plan",
  },
  {
    productName: "LIC Smart Pension",
    productCode: "512N386V01",
    planNumber: "879",
    providerCode: "LIC",
    productType: "Immediate Annuity Pension Plan",
  },

  //ULIP

  {
    productName: "LIC Index Plus",
    productCode: "512L354V01",
    planNumber: "873",
    providerCode: "LIC",
    productType: "ULIP",
  },
  {
    productName: "LIC Nivesh Plus",
    productCode: "512L317V02",
    planNumber: "749",
    providerCode: "LIC",
    productType: "ULIP",
  },
  {
    productName: "LIC SIIP (Systematic Investment Insurance Plan)",
    productCode: "512L334V02",
    planNumber: "752",
    providerCode: "LIC",
    productType: "ULIP",
  },
  {
    productName: "LIC Protection Plus",
    productCode: "512L361V01",
    planNumber: "886",
    providerCode: "LIC",
    productType: "ULIP",
  },

  //Micro Insurance Plan

  {
    productName: "LIC Micro Bachat",
    productCode: "512N329V03",
    planNumber: "751",
    providerCode: "LIC",
    productType: "Micro Insurance Endowment Plan",
  },
  {
    productName: "LIC Jan Suraksha",
    productCode: "512N388V01",
    planNumber: "880",
    providerCode: "LIC",
    productType: "Micro Insurance Endowment Plan",
  },

  //Plans Withdraw During the 2026-2027

  {
    productName: "LIC's Nav Jeevan Shree - Single Premium",
    productCode: "512N390V01",
    planNumber: "911",
    providerCode: "LIC",
    productType: "Withdrawn",
  },

  //Plans Withdraw During 2025-2026

  {
    productName: "LIC's Jeevan Akshay VII",
    productCode: "512N337V06",
    planNumber: "857",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Jeevan Shanti",
    productCode: "512N338V07",
    planNumber: "758",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Nav Jeevan Shree",
    productCode: "512N387V01",
    planNumber: "912",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Endowment Plus",
    productCode: "512L301V03",
    planNumber: "735",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Bima Ratna",
    productCode: "512N345V02",
    planNumber: "764",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Azad",
    productCode: "512N348V02",
    planNumber: "768",
    providerCode: "LIC",
    productType: "Withdrawn",
  },

  //Plans Withdraw During 2024-2025

  {
    productName: "LIC's Dhan Vriddhi",
    productCode: "512N362V02",
    planNumber: "869",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Jeevan Shanti",
    productCode: "512N338V06",
    planNumber: "858",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Dhara - II",
    productCode: "512N364V01",
    planNumber: "872",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Saral Pension",
    productCode: "512N342V04",
    planNumber: "862",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Akshay VII",
    productCode: "512N337V06",
    planNumber: "857",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Nivesh Plus",
    productCode: "512L317V01",
    planNumber: "849",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's SIIP",
    productCode: "512L334V01",
    planNumber: "852",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Pension Plus",
    productCode: "512L347V01",
    planNumber: "867",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Index Plus",
    productCode: "512L354V01",
    planNumber: "873",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Endowment Plus",
    productCode: "512L301V02",
    planNumber: "935",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Bhagya Lakshmi Plan",
    productCode: "512N292V04",
    planNumber: "939",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Jeevan Mangal Plan",
    productCode: "512N287V04",
    planNumber: "940",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Micro Bachat",
    productCode: "512N329V02",
    planNumber: "951",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Bima Ratna",
    productCode: "512N345V02",
    planNumber: "860",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Bima Ratna",
    productCode: "512N345V01",
    planNumber: "864",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Dhan Sanchay",
    productCode: "512N346V01",
    planNumber: "865",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Azad",
    productCode: "512N348V01",
    planNumber: "868",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Endowment Plan",
    productCode: "512N277V02",
    planNumber: "914",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Lakshya",
    productCode: "512N297V02",
    planNumber: "933",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Labh",
    productCode: "512N304V00",// same 736 so i chnaged it to "512N304V00" from "512N304V03"
    planNumber: "936",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Aadhaar Stambh",
    productCode: "512N310V03",
    planNumber: "943",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Aadhaar Shila",
    productCode: "512N309V03",
    planNumber: "944",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Utsav",
    productCode: "512N363V01",
    planNumber: "871",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Umang",
    productCode: "512N312V02",
    planNumber: "945",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Dhan Rekha",
    productCode: "512N343V01",
    planNumber: "863",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Bima Bachat",
    productCode: "512N284V02",
    planNumber: "916",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Money Back Plan 20 Years",
    productCode: "512N280V02",
    planNumber: "920",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Money Back Plan 25 Years",
    productCode: "512N278V02",
    planNumber: "921",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Children's Money Back Plan",
    productCode: "512N296V02",
    planNumber: "932",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Tarun",
    productCode: "512N299V02",
    planNumber: "934",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Shiromani",
    productCode: "512N315V02",
    planNumber: "947",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Bima Shree",
    productCode: "512N316V02",
    planNumber: "948",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Tech-Term",
    productCode: "512N351V01",
    planNumber: "954",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Jeevan Amar",
    productCode: "512N350V01",
    planNumber: "955",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Linked Accidental Death Benefit Rider",
    productCode: "512A211V02",
    planNumber: "",
    providerCode: "LIC",
    productType: "Rider",
  },
  {
    productName: "LIC's Accident Benefit Rider",
    productCode: "512B203V03",
    planNumber: "",
    providerCode: "LIC",
    productType: "Rider",
  },
  {
    productName: "LIC's Premium Waiver Benefit Rider",
    productCode: "512B204V03",
    planNumber: "",
    providerCode: "LIC",
    productType: "Rider",
  },
  {
    productName: "LIC's New Critical Illness Benefit Rider",
    productCode: "512A212V02",
    planNumber: "",
    providerCode: "LIC",
    productType: "Rider",
  },
  {
    productName: "LIC's New Term Assurance Rider",
    productCode: "512B210V01",
    planNumber: "",
    providerCode: "LIC",
    productType: "Rider",
  },
  {
    productName: "LIC's Premium Waiver Benefit Rider (with Auto Cover)",
    productCode: "Not Available (Old Rider Version)",
    planNumber: "",
    providerCode: "LIC",
    productType: "Rider",
  },
  {
    productName: "LIC's Cancer Cover",
    productCode: "-",
    planNumber: "905",
    providerCode: "LIC",
    productType: "Health",
  },
  {
    productName: "LIC's Arogya Rakshak",
    productCode: "-",
    planNumber: "906",
    providerCode: "LIC",
    productType: "Health",
  },
  {
    productName: "LIC's Jeevan Akshay VII",
    productCode: "512N337V05",
    planNumber: "857",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Jeevan Shanti",
    productCode: "512N338V05",
    planNumber: "858",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Kiran",
    productCode: "512N353V01",
    planNumber: "870",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Digi Term",
    productCode: "512N356V01",
    planNumber: "876",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Yuva Term",
    productCode: "512N355V01",
    planNumber: "875",
    providerCode: "LIC",
    productType: "Withdrawn",
  },

  //Plans Withdraw During 2023-2024

  {
    productName: "LIC's Cancer Cover",
    productCode: "512N314V02",
    planNumber: "905",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Dhan Varsha",
    productCode: "512N349V01",
    planNumber: "866",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New One Year Renewable Group Term Assurance Plan-I",
    productCode: "512N275V02",
    planNumber: "",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New One Year Renewal Group Term Assurance Plan-II",
    productCode: "512N276V02",
    planNumber: "",
    providerCode: "LIC",
    productType: "Withdrawn",
  },

  //Plans Withdraw during 2022-2023

  {
    productName: "LIC's Tech Term",
    productCode: "512N333V01",
    planNumber: "854",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Amar",
    productCode: "512N332V01",
    planNumber: "855",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Akshay VII",
    productCode: "512N337V02",
    planNumber: "857",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Pradhan Mantri Vaya Vandana Yojana (Modified-2020)",
    productCode: "512G336V01",
    planNumber: "856",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Akshay VII",
    productCode: "512N337V04",
    planNumber: "857",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Jeevan Shanti",
    productCode: "512N338V02",
    planNumber: "858",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Jeevan Shanti",
    productCode: "512N338V04",
    planNumber: "858",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Bachat Plus",
    productCode: "512N340V01",
    planNumber: "861",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Saral Pension",
    productCode: "512N342V02",
    planNumber: "862",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Saral Pension",
    productCode: "512N342V03",
    planNumber: "862",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Aadhaar Stambh",
    productCode: "512N310V02",
    planNumber: "943",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Aadhaar Shila",
    productCode: "512N309V02",
    planNumber: "944",
    providerCode: "LIC",
    productType: "Withdrawn",
  },

  //Plans Withdraw During 2021-2022

  {
    productName: "LIC's Jeevan Akshay VII",
    productCode: "512N337V01",
    planNumber: "857",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Jeevan Shanti",
    productCode: "512N338V04",
    planNumber: "858",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Bima Jyoti",
    productCode: "512N339V01",
    planNumber: "860",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Saral Pension",
    productCode: "512N342V01",
    planNumber: "862",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Arogya",
    productCode: "512N266V03",
    planNumber: "904",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Bhagya Lakshmi",
    productCode: "512N292V03",
    planNumber: "939",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Jeevan Mangal",
    productCode: "512N287V03",
    planNumber: "940",
    providerCode: "LIC",
    productType: "Withdrawn",
  },

  //Plans Withdraw During 2020-2021

  {
    productName: "LIC's Jeevan Shanti",
    productCode: "512N328V01",
    planNumber: "850",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Arogya",
    productCode: "512N266V02",
    planNumber: "904",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Cancer Cover",
    productCode: "512N314V02",
    planNumber: "905",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Critical Illness Benefit Rider",
    productCode: "512A212V01",
    planNumber: "",
    providerCode: "LIC",
    productType: "Withdrawn",
  },

  //Plans Withdraw During 2019-2020

  {
    productName: "LIC's Jeevan Akshay_VI",
    productCode: "512N234V06",
    planNumber: "189",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Endowment Plan",
    productCode: "512N277V01",
    planNumber: "814",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Jeevan Anand",
    productCode: "512N279V01",
    planNumber: "815",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Bima Bachat",
    productCode: "512N284V01",
    planNumber: "816",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Single Premium Endowment Plan",
    productCode: "512N283V01",
    planNumber: "817",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Jeevan Nidhi",
    productCode: "512N271V02",
    planNumber: "818",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Money Back Plan – 20 Years",
    productCode: "512N280V01",
    planNumber: "820",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Money Back Plan – 25 Years",
    productCode: "512N278V01",
    planNumber: "821",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Anmol Jeevan II",
    productCode: "512N285V01",
    planNumber: "822",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Amulya Jeevan II",
    productCode: "512N286V01",
    planNumber: "823",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's e-Term",
    productCode: "512N288V01",
    planNumber: "825",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Rakshak",
    productCode: "512N289V01",
    planNumber: "827",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Limited Premium Endowment Plan",
    productCode: "512N293V01",
    planNumber: "830",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Children's Money Back",
    productCode: "512N296V01",
    planNumber: "832",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Lakshya",
    productCode: "512N297V01",
    planNumber: "833",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Tarun",
    productCode: "512N299V01",
    planNumber: "834",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Endowment Plus",
    productCode: "512L301V01",
    planNumber: "835",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Labh",
    productCode: "512N304V01",
    planNumber: "836",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Pragati",
    productCode: "512N306V01",
    planNumber: "838",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Bhagya Lakshmi",
    productCode: "512N292V02",
    planNumber: "839",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Jeevan Mangal",
    productCode: "512N287V02",
    planNumber: "840",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Pradhan Mantri Vaya Vandana Yojana",
    productCode: "512G311V02",
    planNumber: "842",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Aadhaar Stambh",
    productCode: "512N310V01",
    planNumber: "843",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Aadhaar Shila",
    productCode: "512N309V01",
    planNumber: "844",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Umang",
    productCode: "512N312V01",
    planNumber: "845",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Utkarsh",
    productCode: "512N313V01",
    planNumber: "846",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Shiromani",
    productCode: "512N315V01",
    planNumber: "847",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Bima Shree",
    productCode: "512N316V01",
    planNumber: "848",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Shanti",
    productCode: "512N328V02",
    planNumber: "850",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Shanti",
    productCode: "512N328V02",
    planNumber: "851",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Jeevan Amar",
    productCode: "512N337V01",
    planNumber: "853",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Premium Waiver Benefit Rider",
    productCode: "512B204V02",
    planNumber: "",
    providerCode: "LIC",
    productType: "Withdrawn",
  },

  //Plans Withdraw During 2018-2019

  {
    productName: "Pradhan Mantri Vaya Vandana Yojana",
    productCode: "512G311V01",
    planNumber: "842",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Children's Money Back",
    productCode: "512N296V01",
    planNumber: "832",
    providerCode: "LIC",
    productType: "Withdrawn",
  },

  //Riders

  {
    productName: "LICs Accident Benefit Rider",
    productCode: "512B203V03",
    planNumber: "",
    providerCode: "LIC",
    productType: "Rider",
  },
  {
    productName: "LICs Premium Waiver Benefit Rider",
    productCode: "512B204V02",
    planNumber: "",
    providerCode: "LIC",
    productType: "Rider",
  },
  {
    productName: "LICs Accidental Death and Disability Benefit Rider",
    productCode: "512B209V02",
    planNumber: "",
    providerCode: "LIC",
    productType: "Rider",
  },
  {
    productName: "LIC's New Term Assurance Rider",
    productCode: "512B210V02",
    planNumber: "",
    providerCode: "LIC",
    productType: "Rider",
  },
  {
    productName: "LIC's Linked Accidental Death Benefit Rider",
    productCode: "512A211V02",
    planNumber: "",
    providerCode: "LIC",
    productType: "Rider",
  },
  {
    productName: "LIC's Critical Illness Health Rider",
    productCode: "512B227V01",
    planNumber: "",
    providerCode: "LIC",
    productType: "Rider",
  },
  {
    productName: "LIC's Female Critical Illness Benefit Rider",
    productCode: "512B226V01",
    planNumber: "",
    providerCode: "LIC",
    productType: "Rider",
  },
  // --- Legacy LIC Products (Auto-generated) ---
  {
    productName: "AADHAR Shila",
    productCode: "LEGACY-844",
    planNumber: "844",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "AADHAR stambh",
    productCode: "LEGACY-843",
    planNumber: "843",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Amritbaal",
    productCode: "LEGACY-874",
    planNumber: "874",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Amulya Jeevan",
    productCode: "LEGACY-177",
    planNumber: "177",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Amulya Jeevan - I",
    productCode: "LEGACY-190",
    planNumber: "190",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Amulya Jeevan-II",
    productCode: "LEGACY-823",
    planNumber: "823",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Anmol Jeevan",
    productCode: "LEGACY-153",
    planNumber: "153",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Anmol Jeevan -1",
    productCode: "LEGACY-164",
    planNumber: "164",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Anmol Jeevan-II",
    productCode: "LEGACY-822",
    planNumber: "822",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Anticipated Endowment 15 Yrs.",
    productCode: "LEGACY-24",
    planNumber: "24",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Anticipated Endowment 20 Yrs.",
    productCode: "LEGACY-25",
    planNumber: "25",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Anticipated Endowment 25 Yrs.",
    productCode: "LEGACY-26",
    planNumber: "26",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Anticipated Whole Life Policy With Profit 20 Yrs.",
    productCode: "LEGACY-85",
    planNumber: "85",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Anticipated Whole Life Policy With Profit 25 Yrs.",
    productCode: "LEGACY-86",
    planNumber: "86",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Asha Deep - I",
    productCode: "LEGACY-110",
    planNumber: "110",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Asha Deep - II",
    productCode: "LEGACY-121",
    planNumber: "121",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Bal Vidya",
    productCode: "LEGACY-135",
    planNumber: "135",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Bhavishya Jeevan Special Endowment",
    productCode: "LEGACY-95",
    planNumber: "95",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Bima Account - I",
    productCode: "LEGACY-805",
    planNumber: "805",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Bima Account - II",
    productCode: "LEGACY-806",
    planNumber: "806",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Bima Bachat",
    productCode: "LEGACY-175",
    planNumber: "175",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Bima Diamond",
    productCode: "LEGACY-841",
    planNumber: "841",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Bima Gold",
    productCode: "LEGACY-174",
    planNumber: "174",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Bima Kiran",
    productCode: "LEGACY-111",
    planNumber: "111",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Bima Nivesh",
    productCode: "LEGACY-132",
    planNumber: "132",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Bima Nivesh 2001",
    productCode: "LEGACY-141",
    planNumber: "141",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Bima Nivesh 2002",
    productCode: "LEGACY-158",
    planNumber: "158",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Bima Nivesh 2004",
    productCode: "LEGACY-166",
    planNumber: "166",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Bima Nivesh 2005",
    productCode: "LEGACY-171",
    planNumber: "171",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Bima Nivesh Triple Cover",
    productCode: "LEGACY-143",
    planNumber: "143",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Bima Platinum",
    productCode: "LEGACY-770",
    planNumber: "770",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Bima Plus",
    productCode: "LEGACY-140",
    planNumber: "140",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Bima Sandesh",
    productCode: "LEGACY-94",
    planNumber: "94",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Bima Shree",
    productCode: "LEGACY-848",
    planNumber: "848",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Cash and Cover",
    productCode: "LEGACY-77",
    planNumber: "77",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Cash and Cover - 78",
    productCode: "LEGACY-78",
    planNumber: "78",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "CDA Limited Whole Life Vesting Age 18",
    productCode: "LEGACY-49",
    planNumber: "49",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "CDA Limited Whole Life Vesting Age 19",
    productCode: "LEGACY-35",
    planNumber: "35",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "CDA Limited Whole Life Vesting Age 20",
    productCode: "LEGACY-36",
    planNumber: "36",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "CDA Limited Whole Life Vesting Age 21",
    productCode: "LEGACY-37",
    planNumber: "37",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "CDA Limited Whole Life Vesting Age 22",
    productCode: "LEGACY-38",
    planNumber: "38",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Child Career Plan(with profits)",
    productCode: "LEGACY-184",
    planNumber: "184",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Child Fortune Plus",
    productCode: "LEGACY-194",
    planNumber: "194",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Child Future Plan",
    productCode: "LEGACY-185",
    planNumber: "185",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Children''''''''s Defered Assurance Vesting Age 18",
    productCode: "LEGACY-50",
    planNumber: "50",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Children''''''''s Defered Assurance Vesting Age 21",
    productCode: "LEGACY-41",
    planNumber: "41",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Children''''s Anticipated Vesting Age 18",
    productCode: "LEGACY-80",
    planNumber: "80",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Children''''s Anticipated Vesting Age 21",
    productCode: "LEGACY-81",
    planNumber: "81",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Children''''s Defered Assurance Vesting Age 19",
    productCode: "LEGACY-39",
    planNumber: "39",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Children''''s Defered Assurance Vesting Age 20",
    productCode: "LEGACY-40",
    planNumber: "40",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Children''''s Money Back Plan",
    productCode: "LEGACY-113",
    planNumber: "113",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Children''s Defered Assurance Vesting Age 22",
    productCode: "LEGACY-42",
    planNumber: "42",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Converted Endowment With Profit 27A",
    productCode: "LEGACY-27A",
    planNumber: "27A",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Converted Endowment Without Profit 27B",
    productCode: "LEGACY-27B",
    planNumber: "27B",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Convertible Term Assurance Policy",
    productCode: "LEGACY-58",
    planNumber: "58",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Convertible Whole Life With Profit",
    productCode: "LEGACY-28",
    planNumber: "28",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Convertible Whole Life Without Profit",
    productCode: "LEGACY-27",
    planNumber: "27",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Deferred Annuity Certain",
    productCode: "LEGACY-61",
    planNumber: "61",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Deferred Annuity Policy",
    productCode: "LEGACY-45",
    planNumber: "45",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Deferred Annuity With ROC.",
    productCode: "LEGACY-116",
    planNumber: "116",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Dhan Varsha",
    productCode: "LEGACY-866",
    planNumber: "866",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Double Endowment Without Profit",
    productCode: "LEGACY-18",
    planNumber: "18",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "e-Term Plan",
    productCode: "LEGACY-825",
    planNumber: "825",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Educational Annuity - Endowment Without Profit",
    productCode: "LEGACY-20",
    planNumber: "20",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Endowment Plus",
    productCode: "LEGACY-802",
    planNumber: "802",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Endowment With Profit",
    productCode: "LEGACY-14",
    planNumber: "14",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Endowment With Profit",
    productCode: "LEGACY-15",
    planNumber: "15",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Endowment Without Profit",
    productCode: "LEGACY-11",
    planNumber: "11",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Endowment Without Profit",
    productCode: "LEGACY-12",
    planNumber: "12",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Fixed Term (Marriage) Endowment Without Profit",
    productCode: "LEGACY-19",
    planNumber: "19",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Flexi Plus",
    productCode: "LEGACY-811",
    planNumber: "811",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Fortune Plus",
    productCode: "LEGACY-187",
    planNumber: "187",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Future Plus",
    productCode: "LEGACY-172",
    planNumber: "172",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Grihalakshmi Policy Without Profit",
    productCode: "LEGACY-67",
    planNumber: "67",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Guaranteed Triple Ben. (20 Yrs. Without Profit)",
    productCode: "LEGACY-22",
    planNumber: "22",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Guaranteed Triple Ben. (25 Yrs. Without Profit)",
    productCode: "LEGACY-23",
    planNumber: "23",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Guaranteed Triple Benefit (15 Yrs. Without Profit)",
    productCode: "LEGACY-46",
    planNumber: "46",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Health Plus",
    productCode: "LEGACY-901",
    planNumber: "901",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Health Protection Plus",
    productCode: "LEGACY-902",
    planNumber: "902",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Immediate Annuity",
    productCode: "LEGACY-44",
    planNumber: "44",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Immediate Annuity Certain",
    productCode: "LEGACY-60",
    planNumber: "60",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Immediate Annuity Plan With ROC",
    productCode: "LEGACY-115",
    planNumber: "115",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Janaraksha Policy With Profit",
    productCode: "LEGACY-87",
    planNumber: "87",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Janata Endowment With Profit",
    productCode: "LEGACY-54",
    planNumber: "54",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Janata Endowment Without Profit",
    productCode: "LEGACY-53",
    planNumber: "53",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Aadhar",
    productCode: "LEGACY-114",
    planNumber: "114",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Aastha",
    productCode: "LEGACY-195",
    planNumber: "195",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Akshay",
    productCode: "LEGACY-97",
    planNumber: "97",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Akshay - II",
    productCode: "LEGACY-163",
    planNumber: "163",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Akshay - III",
    productCode: "LEGACY-170",
    planNumber: "170",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Akshay - IV",
    productCode: "LEGACY-176",
    planNumber: "176",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Akshay - V",
    productCode: "LEGACY-183",
    planNumber: "183",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Akshay - VI",
    productCode: "LEGACY-189",
    planNumber: "189",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Akshay with 30 % return",
    productCode: "LEGACY-97A",
    planNumber: "97A",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Amar",
    productCode: "LEGACY-855",
    planNumber: "855",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Amrit",
    productCode: "LEGACY-186",
    planNumber: "186",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Anand",
    productCode: "LEGACY-149",
    planNumber: "149",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Anand Plan",
    productCode: "LEGACY-915",
    planNumber: "915",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Ankur",
    productCode: "LEGACY-807",
    planNumber: "807",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Anurag",
    productCode: "LEGACY-168",
    planNumber: "168",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Arogya",
    productCode: "LEGACY-903",
    planNumber: "903",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Asha I",
    productCode: "LEGACY-129",
    planNumber: "129",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Asha II",
    productCode: "LEGACY-131",
    planNumber: "131",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Balya",
    productCode: "LEGACY-101",
    planNumber: "101",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Bharati - I",
    productCode: "LEGACY-192",
    planNumber: "192",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Bharati For Women",
    productCode: "LEGACY-160",
    planNumber: "160",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Chhaya",
    productCode: "LEGACY-103",
    planNumber: "103",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Dhara",
    productCode: "LEGACY-96",
    planNumber: "96",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Griha - Double Cover",
    productCode: "LEGACY-104",
    planNumber: "104",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Griha - Triple Cover",
    productCode: "LEGACY-105",
    planNumber: "105",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Kishore",
    productCode: "LEGACY-102",
    planNumber: "102",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Labh",
    productCode: "LEGACY-836",
    planNumber: "836",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Lakshya",
    productCode: "LEGACY-833",
    planNumber: "833",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Madhur",
    productCode: "LEGACY-98",
    planNumber: "98",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Mangal",
    productCode: "LEGACY-99",
    planNumber: "99",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Mitra (Double Cover)",
    productCode: "LEGACY-88",
    planNumber: "88",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Mitra - Triple Cover",
    productCode: "LEGACY-133",
    planNumber: "133",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Nidhi",
    productCode: "LEGACY-169",
    planNumber: "169",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Nischay",
    productCode: "LEGACY-199",
    planNumber: "199",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Plus",
    productCode: "LEGACY-173",
    planNumber: "173",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Pragati",
    productCode: "LEGACY-838",
    planNumber: "838",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Pramukh",
    productCode: "LEGACY-167",
    planNumber: "167",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Raksha",
    productCode: "LEGACY-894",
    planNumber: "894",
    providerCode: "LIC",
    productType: "Term Assurance Plan",
  },
  {
    productName: "Jeevan Rakshak",
    productCode: "LEGACY-827",
    planNumber: "827",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Rekha",
    productCode: "LEGACY-152",
    planNumber: "152",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Saathi",
    productCode: "LEGACY-89",
    planNumber: "89",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Saathi Plus",
    productCode: "LEGACY-197",
    planNumber: "197",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Samridhi 12",
    productCode: "LEGACY-154",
    planNumber: "154",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Samridhi 15",
    productCode: "LEGACY-155",
    planNumber: "155",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Samridhi 20",
    productCode: "LEGACY-156",
    planNumber: "156",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Samridhi 25",
    productCode: "LEGACY-157",
    planNumber: "157",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Sanchay 12 Yrs",
    productCode: "LEGACY-123",
    planNumber: "123",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Sanchay 15 Yrs",
    productCode: "LEGACY-124",
    planNumber: "124",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Sanchay 20 Yrs",
    productCode: "LEGACY-125",
    planNumber: "125",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Sanchay 25 Yrs",
    productCode: "LEGACY-126",
    planNumber: "126",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Sangam",
    productCode: "LEGACY-831",
    planNumber: "831",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Saral",
    productCode: "LEGACY-165",
    planNumber: "165",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Sarita",
    productCode: "LEGACY-117",
    planNumber: "117",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Shagun",
    productCode: "LEGACY-826",
    planNumber: "826",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Shanti",
    productCode: "LEGACY-850",
    planNumber: "850",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Shikhar",
    productCode: "LEGACY-837",
    planNumber: "837",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Shiromani",
    productCode: "LEGACY-847",
    planNumber: "847",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Shree",
    productCode: "LEGACY-112",
    planNumber: "112",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Shree - 1",
    productCode: "LEGACY-162",
    planNumber: "162",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Sneha For Women",
    productCode: "LEGACY-128",
    planNumber: "128",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Sugam",
    productCode: "LEGACY-813",
    planNumber: "813",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Sukanya",
    productCode: "LEGACY-109",
    planNumber: "109",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Surabhi 15 Yrs.",
    productCode: "LEGACY-106",
    planNumber: "106",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Surabhi 20 Yrs.",
    productCode: "LEGACY-107",
    planNumber: "107",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Surabhi 25 Yrs.",
    productCode: "LEGACY-108",
    planNumber: "108",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Suraksha Endowment Type",
    productCode: "LEGACY-122E",
    planNumber: "122E",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Suraksha With Life Cover",
    productCode: "LEGACY-122L",
    planNumber: "122L",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Suraksha Without Life Cover",
    productCode: "LEGACY-122N",
    planNumber: "122N",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Tarang",
    productCode: "LEGACY-178",
    planNumber: "178",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Tarun",
    productCode: "LEGACY-834",
    planNumber: "834",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Umang",
    productCode: "LEGACY-845",
    planNumber: "845",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Utkarsha",
    productCode: "LEGACY-846",
    planNumber: "846",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Vaibhav",
    productCode: "LEGACY-809",
    planNumber: "809",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Varsha",
    productCode: "LEGACY-196",
    planNumber: "196",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Vishwas (Without Profit)",
    productCode: "LEGACY-136",
    planNumber: "136",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Jeevan Vriddhi",
    productCode: "LEGACY-808",
    planNumber: "808",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Joint Life Endowment With Profit",
    productCode: "LEGACY-17",
    planNumber: "17",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Joint Life Endowment Without Profit",
    productCode: "LEGACY-16",
    planNumber: "16",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Komal Jeevan",
    productCode: "LEGACY-159",
    planNumber: "159",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Leasehold Capital Redemption Without Profit",
    productCode: "LEGACY-51",
    planNumber: "51",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "ULIS-LICMF Unit Linked Insurance Scheme - Hybrid",
    productCode: "LEGACY-ULIS",
    planNumber: "ULIS",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Limited Payment  Endowment Without Profit",
    productCode: "LEGACY-47",
    planNumber: "47",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Limited Payment Endowment With Profit",
    productCode: "LEGACY-48",
    planNumber: "48",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Limited Payment Whole Life With Profit",
    productCode: "LEGACY-5",
    planNumber: "5",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Limited Payment Whole Life Without Profit",
    productCode: "LEGACY-3",
    planNumber: "3",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Limited Premium Endowment Plan",
    productCode: "LEGACY-830",
    planNumber: "830",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Market Plus",
    productCode: "LEGACY-181",
    planNumber: "181",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Market Plus - I",
    productCode: "LEGACY-191",
    planNumber: "191",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Marriage / Educational Annuity With Profit",
    productCode: "LEGACY-90",
    planNumber: "90",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Micro Bachat 851",
    productCode: "LEGACY-851",
    planNumber: "851",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Money Back With Profit 12 Yrs.",
    productCode: "LEGACY-73",
    planNumber: "73",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Money Back With Profit 15 Yrs.",
    productCode: "LEGACY-74",
    planNumber: "74",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Money Back With Profit 25 Yrs.",
    productCode: "LEGACY-76",
    planNumber: "76",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Money Plus",
    productCode: "LEGACY-180",
    planNumber: "180",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Money Plus - I",
    productCode: "LEGACY-193",
    planNumber: "193",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Money-back With Profit 20 Years",
    productCode: "LEGACY-75",
    planNumber: "75",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Mortgage Redemption",
    productCode: "LEGACY-52",
    planNumber: "52",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Multipurpose Policy With Profit",
    productCode: "LEGACY-84",
    planNumber: "84",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Multipurpose Policy With Profit",
    productCode: "LEGACY-34",
    planNumber: "34",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Multipurpose Policy Without Profit",
    productCode: "LEGACY-83",
    planNumber: "83",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Multipurpose Without Profit",
    productCode: "LEGACY-33",
    planNumber: "33",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Nav Prabhat for Senior Citizens",
    productCode: "LEGACY-137",
    planNumber: "137",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Navjeevan",
    productCode: "LEGACY-853",
    planNumber: "853",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "New Bima Bachat",
    productCode: "LEGACY-816",
    planNumber: "816",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "New Bima Gold",
    productCode: "LEGACY-179",
    planNumber: "179",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "New Bima Jyoti",
    productCode: "LEGACY-890",
    planNumber: "890",
    providerCode: "LIC",
    productType: "Endowment",
  },
  {
    productName: "New Bima Kiran",
    productCode: "LEGACY-150",
    planNumber: "150",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "New Bima Nivesh",
    productCode: "LEGACY-142",
    planNumber: "142",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "New CDA Policy With Profit",
    productCode: "LEGACY-92",
    planNumber: "92",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "New Children Money Back Plan",
    productCode: "LEGACY-832",
    planNumber: "832",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "New Endomwnt Plan",
    productCode: "LEGACY-814",
    planNumber: "814",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "New Endowment Plus",
    productCode: "LEGACY-835",
    planNumber: "835",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "New Janaraksha Policy",
    productCode: "LEGACY-91",
    planNumber: "91",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "New Jeevan Akshay",
    productCode: "LEGACY-144",
    planNumber: "144",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "New Jeevan Akshay - 1",
    productCode: "LEGACY-146",
    planNumber: "146",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "New Jeevan Anand",
    productCode: "LEGACY-815",
    planNumber: "815",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "NEW JEEVAN AROGYA 2013",
    productCode: "LEGACY-904",
    planNumber: "904",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "New Jeevan Dhara",
    productCode: "LEGACY-145",
    planNumber: "145",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "New Jeevan Dhara  - 1",
    productCode: "LEGACY-148",
    planNumber: "148",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "New Jeevan Nidhi",
    productCode: "LEGACY-812",
    planNumber: "812",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "New Jeevan Nidhi old",
    productCode: "LEGACY-818",
    planNumber: "818",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "New Jeevan Shree",
    productCode: "LEGACY-151",
    planNumber: "151",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "New Jeevan Suraksha - 1",
    productCode: "LEGACY-147",
    planNumber: "147",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "New Money Back 25 Years",
    productCode: "LEGACY-93",
    planNumber: "93",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "New Money Back Plan-20 Years",
    productCode: "LEGACY-820",
    planNumber: "820",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "New Money Back Plan-25 Years",
    productCode: "LEGACY-821",
    planNumber: "821",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Nivesh Plus",
    productCode: "LEGACY-849",
    planNumber: "849",
    providerCode: "LIC",
    productType: "ULIP",
  },
  {
    productName: "Pension Plus",
    productCode: "LEGACY-803",
    planNumber: "803",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Pradhan Mantri Vaya Vandana Yojana",
    productCode: "LEGACY-842",
    planNumber: "842",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Pradhan Mantri Vaya Vandana Yojana (Launch Year 20",
    productCode: "LEGACY-856",
    planNumber: "856",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Profit Plus",
    productCode: "LEGACY-188",
    planNumber: "188",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Progressive Protection Policy With Profit",
    productCode: "LEGACY-79",
    planNumber: "79",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Pure Endowment",
    productCode: "LEGACY-21",
    planNumber: "21",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Samridhi Plus",
    productCode: "LEGACY-804",
    planNumber: "804",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "SIIP  Plan",
    productCode: "LEGACY-852",
    planNumber: "852",
    providerCode: "LIC",
    productType: "ULIP",
  },
  {
    productName: "Single Premium Endowment",
    productCode: "LEGACY-917",
    planNumber: "917",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Single Premium Endowment Plan",
    productCode: "LEGACY-817",
    planNumber: "817",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Single Premium Whole Life With Profit",
    productCode: "LEGACY-8",
    planNumber: "8",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Single Premium Whole Life Without Profit",
    productCode: "LEGACY-7",
    planNumber: "7",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Special Whole Life With Profit",
    productCode: "LEGACY-10",
    planNumber: "10",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Special Whole Life Without Profit",
    productCode: "LEGACY-9",
    planNumber: "9",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Tech-Term",
    productCode: "LEGACY-854",
    planNumber: "854",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Term Assurance",
    productCode: "LEGACY-43",
    planNumber: "43",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "The Centenary Policy With Profit",
    productCode: "LEGACY-66",
    planNumber: "66",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "The Endowment Assurance Policy",
    productCode: "LEGACY-401",
    planNumber: "401",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "The Endowment Assurance Policy - Limited Payment",
    productCode: "LEGACY-400",
    planNumber: "400",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "The Retirement Annuity",
    productCode: "LEGACY-64",
    planNumber: "64",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Two Year Temporary Assurance policy",
    productCode: "LEGACY-100",
    planNumber: "100",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Varishtha Pension Bima Yojana",
    productCode: "LEGACY-161",
    planNumber: "161",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Varishtha Pension Bima Yojna",
    productCode: "LEGACY-828",
    planNumber: "828",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Wealth PLUS",
    productCode: "LEGACY-801",
    planNumber: "801",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Whole Life With Profit",
    productCode: "LEGACY-2",
    planNumber: "2",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Whole Life Without Profit",
    productCode: "LEGACY-1",
    planNumber: "1",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
];
