export const licProducts = [
  {
    productName: 'Single Premium Endowment Plan',
    productCode: '512N283V03',
    planNumber: '717',
    providerCode: 'LIC',
    productType: 'Endowment'
  },
  {
    productName: "LIC's New Endowment Plan",
    productCode: '512N277V03',
    planNumber: '714',
    providerCode: 'LIC',
    productType: 'Endowment'
  },
  {
    productName: "LIC's New Jeevan Anand",
    productCode: '512N279V03',
    planNumber: '715',
    providerCode: 'LIC',
    productType: 'Savings + Whole Life'
  },
  {
    productName: 'LIC Jeevan Lakshya',
    productCode: '512N297V03',
    planNumber: '733',
    providerCode: 'LIC',
    productType: 'Child Saving Plan'
  },
  {
    productName: 'LIC Jeevan Labh',
    productCode: '512N304V03',
    planNumber: '736',
    providerCode: 'LIC',
    productType: 'Endowment Savings Plan'
  },
  {
    productName: 'LIC Amritbaal',
    productCode: '512N365V02',
    planNumber: '774',
    providerCode: 'LIC',
    productType: 'Child Saving Plan'
  },
  {
    productName: 'LIC Bima Jyoti',
    productCode: '512N339V03',
    planNumber: '760',
    providerCode: 'LIC',
    productType: 'Savings Plan'
  },
  {
    productName: 'LIC Nav Jeevan Shree',
    productCode: '512N387V02',
    planNumber: '912',
    providerCode: 'LIC',
    productType: 'Savings Plan'
  },
  {
    productName: 'LIC Bima Lakshmi',
    productCode: '512N389V01',
    planNumber: '881',
    providerCode: 'LIC',
    productType: 'Women Savings Plan'
  },
  {
    productName: 'LIC New Jeevan Sathi Single Premium',
    productCode: '512N393V01',
    planNumber: '888',
    providerCode: 'LIC',
    productType: 'Joint Life Savings Plan'
  },
  {
    productName: 'LIC New Jeevan Sathi-Limited Premium',
    productCode: '512N394V01',
    planNumber: '889',
    providerCode: 'LIC',
    productType: 'Joint Life Savings Plan'
  },

  //Whole Life Plans

  {
    productName: "LIC Jeevan Umang",
    productCode: "512N312V03",
    planNumber: "745",
    providerCode: "LIC",
    productType: "Savings + Whole Life",
  },
  {
    productName: "LIC Jeevan Utsav",
    productCode: "512N363V02",
    planNumber: "771",
    providerCode: "LIC",
    productType: "Whole Life Insurance Plan",
  },
  {
    productName: "LIC Jeevan Utsav Single Premium",
    productCode: "512N392V01",
    planNumber: "883",
    providerCode: "LIC",
    productType: "Whole Life Insurance Plan",
  },

  //Money back Plans

  {
    productName: "LIC Bima Shree",
    productCode: "512N316V03",
    planNumber: "748",
    providerCode: "LIC",
    productType: "Money Back Savings Plan",
  },
  {
    productName: "LIC New Money Back Plan 20 Years",
    productCode: "512N280V03",
    planNumber: "720",
    providerCode: "LIC",
    productType: "Money Back Plan",
  },
  {
    productName: "LIC New Money Back Plan 25 Years",
    productCode: "512N278V03",
    planNumber: "721",
    providerCode: "LIC",
    productType: "Money Back Plan",
  },
  {
    productName: "LIC New Children's Money Back Plan",
    productCode: "512N296V03",
    planNumber: "732",
    providerCode: "LIC",
    productType: "Childrens Money Back Plan",
  },
  {
    productName: "LIC Jeevan Tarun",
    productCode: "512N299V03",
    planNumber: "734",
    providerCode: "LIC",
    productType: "Childrens Money Back Plan",
  },

  //Term Assurance Plan
  {
    productName: "LIC Digi Term",
    productCode: "512N356V02",
    planNumber: "876",
    providerCode: "LIC",
    productType: "Term Assurance Plan",
  },
  {
    productName: "LIC Digi Credit Life",
    productCode: "512N358V01",
    planNumber: "878",
    providerCode: "LIC",
    productType: "Credit Life Term Assurance Plan",
  },
  {
    productName: "LIC Yuva Credit Life",
    productCode: "512N357V01",
    planNumber: "877",
    providerCode: "LIC",
    productType: "Credit Life Term Assurance Plan",
  },
  {
    productName: "LIC Yuva Term",
    productCode: "512N355V02",
    planNumber: "875",
    providerCode: "LIC",
    productType: "Term Assurance Plan",
  },
  {
    productName: "LIC New Tech-Term",
    productCode: "512N351V02",
    planNumber: "954",
    providerCode: "LIC",
    productType: "Term Assurance Plan",
  },
  {
    productName: "LIC New Jeevan Amar",
    productCode: "512N350V02",
    planNumber: "955",
    providerCode: "LIC",
    productType: "Term Assurance Plan",
  },
  {
    productName: "LIC Saral Jeevan Bima",
    productCode: "512N341V01",
    planNumber: "859",
    providerCode: "LIC",
    productType: "Term Assurance Plan",
  },
  {
    productName: "LIC Bima Kavach",
    productCode: "512N360V01",
    planNumber: "887",
    providerCode: "LIC",
    productType: "Term Assurance Plan",
  },

  //Pension Plans
  {
    productName: "LIC New Pension Plus",
    productCode: "512L347V01",
    planNumber: "867",
    providerCode: "LIC",
    productType: "Pension Plan",
  },
  {
    productName: "LIC Jeevan Akshay VII",
    productCode: "512N337V07",
    planNumber: "857",
    providerCode: "LIC",
    productType: "Immediate Annuity Pension Plan",
  },
  {
    productName: "LIC New Jeevan Shanti",
    productCode: "512N338V08",
    planNumber: "858",
    providerCode: "LIC",
    productType: "Deferred Annuity Pension Plan",
  },
  {
    productName: "LIC Saral Pension",
    productCode: "512N342V05",
    planNumber: "862",
    providerCode: "LIC",
    productType: "Immediate Annuity Pension Plan",
  },
  {
    productName: "LIC Smart Pension",
    productCode: "512N386V01",
    planNumber: "879",
    providerCode: "LIC",
    productType: "Immediate Annuity Pension Plan",
  },

  //ULIP

  {
    productName: "LIC Index Plus",
    productCode: "512L354V01",
    planNumber: "873",
    providerCode: "LIC",
    productType: "ULIP",
  },
  {
    productName: "LIC Nivesh Plus",
    productCode: "512L317V02",
    planNumber: "749",
    providerCode: "LIC",
    productType: "ULIP",
  },
  {
    productName: "LIC SIIP (Systematic Investment Insurance Plan)",
    productCode: "512L334V02",
    planNumber: "752",
    providerCode: "LIC",
    productType: "ULIP",
  },
  {
    productName: "LIC Protection Plus",
    productCode: "512L361V01",
    planNumber: "886",
    providerCode: "LIC",
    productType: "ULIP",
  },

  //Micro Insurance Plan

  {
    productName: "LIC Micro Bachat",
    productCode: "512N329V03",
    planNumber: "751",
    providerCode: "LIC",
    productType: "Micro Insurance Endowment Plan",
  },
  {
    productName: "LIC Jan Suraksha",
    productCode: "512N388V01",
    planNumber: "880",
    providerCode: "LIC",
    productType: "Micro Insurance Endowment Plan",
  },

  //Plans Withdraw During the 2026-2027

  {
    productName: "LIC's Nav Jeevan Shree - Single Premium",
    productCode: "512N390V01",
    planNumber: "911",
    providerCode: "LIC",
    productType: "Withdrawn",
  },

  //Plans Withdraw During 2025-2026

  {
    productName: "LIC's Jeevan Akshay VII",
    productCode: "512N337V06",
    planNumber: "857",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Jeevan Shanti",
    productCode: "512N338V07",
    planNumber: "758",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Nav Jeevan Shree",
    productCode: "512N387V01",
    planNumber: "912",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Endowment Plus",
    productCode: "512L301V03",
    planNumber: "735",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Bima Ratna",
    productCode: "512N345V02",
    planNumber: "764",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Azad",
    productCode: "512N348V02",
    planNumber: "768",
    providerCode: "LIC",
    productType: "Withdrawn",
  },

  //Plans Withdraw During 2024-2025

  {
    productName: "LIC's Dhan Vriddhi",
    productCode: "512N362V02",
    planNumber: "869",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Jeevan Shanti",
    productCode: "512N338V06",
    planNumber: "858",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Dhara - II",
    productCode: "512N364V01",
    planNumber: "872",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Saral Pension",
    productCode: "512N342V04",
    planNumber: "862",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Akshay VII",
    productCode: "512N337V06",
    planNumber: "857",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Nivesh Plus",
    productCode: "512L317V01",
    planNumber: "849",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's SIIP",
    productCode: "512L334V01",
    planNumber: "852",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Pension Plus",
    productCode: "512L347V01",
    planNumber: "867",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Index Plus",
    productCode: "512L354V01",
    planNumber: "873",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Endowment Plus",
    productCode: "512L301V02",
    planNumber: "935",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Bhagya Lakshmi Plan",
    productCode: "512N292V04",
    planNumber: "939",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Jeevan Mangal Plan",
    productCode: "512N287V04",
    planNumber: "940",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Micro Bachat",
    productCode: "512N329V02",
    planNumber: "951",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Bima Ratna",
    productCode: "512N345V02",
    planNumber: "860",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Bima Ratna",
    productCode: "512N345V01",
    planNumber: "864",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Dhan Sanchay",
    productCode: "512N346V01",
    planNumber: "865",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Azad",
    productCode: "512N348V01",
    planNumber: "868",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Endowment Plan",
    productCode: "512N277V02",
    planNumber: "914",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Lakshya",
    productCode: "512N297V02",
    planNumber: "933",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Labh",
    productCode: "512N304V00",// same 736 so i chnaged it to "512N304V00" from "512N304V03"
    planNumber: "936",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Aadhaar Stambh",
    productCode: "512N310V03",
    planNumber: "943",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Aadhaar Shila",
    productCode: "512N309V03",
    planNumber: "944",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Utsav",
    productCode: "512N363V01",
    planNumber: "871",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Umang",
    productCode: "512N312V02",
    planNumber: "945",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Dhan Rekha",
    productCode: "512N343V01",
    planNumber: "863",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Bima Bachat",
    productCode: "512N284V02",
    planNumber: "916",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Money Back Plan 20 Years",
    productCode: "512N280V02",
    planNumber: "920",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Money Back Plan 25 Years",
    productCode: "512N278V02",
    planNumber: "921",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Children's Money Back Plan",
    productCode: "512N296V02",
    planNumber: "932",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Tarun",
    productCode: "512N299V02",
    planNumber: "934",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Shiromani",
    productCode: "512N315V02",
    planNumber: "947",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Bima Shree",
    productCode: "512N316V02",
    planNumber: "948",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Tech-Term",
    productCode: "512N351V01",
    planNumber: "954",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Jeevan Amar",
    productCode: "512N350V01",
    planNumber: "955",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Linked Accidental Death Benefit Rider",
    productCode: "512A211V02",
    planNumber: "",
    providerCode: "LIC",
    productType: "Rider",
  },
  {
    productName: "LIC's Accident Benefit Rider",
    productCode: "512B203V03",
    planNumber: "",
    providerCode: "LIC",
    productType: "Rider",
  },
  {
    productName: "LIC's Premium Waiver Benefit Rider",
    productCode: "512B204V03",
    planNumber: "",
    providerCode: "LIC",
    productType: "Rider",
  },
  {
    productName: "LIC's New Critical Illness Benefit Rider",
    productCode: "512A212V02",
    planNumber: "",
    providerCode: "LIC",
    productType: "Rider",
  },
  {
    productName: "LIC's New Term Assurance Rider",
    productCode: "512B210V01",
    planNumber: "",
    providerCode: "LIC",
    productType: "Rider",
  },
  {
    productName: "LIC's Premium Waiver Benefit Rider (with Auto Cover)",
    productCode: "Not Available (Old Rider Version)",
    planNumber: "",
    providerCode: "LIC",
    productType: "Rider",
  },
  {
    productName: "LIC's Cancer Cover",
    productCode: "-",
    planNumber: "905",
    providerCode: "LIC",
    productType: "Health",
  },
  {
    productName: "LIC's Arogya Rakshak",
    productCode: "-",
    planNumber: "906",
    providerCode: "LIC",
    productType: "Health",
  },
  {
    productName: "LIC's Jeevan Akshay VII",
    productCode: "512N337V05",
    planNumber: "857",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Jeevan Shanti",
    productCode: "512N338V05",
    planNumber: "858",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Kiran",
    productCode: "512N353V01",
    planNumber: "870",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Digi Term",
    productCode: "512N356V01",
    planNumber: "876",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Yuva Term",
    productCode: "512N355V01",
    planNumber: "875",
    providerCode: "LIC",
    productType: "Withdrawn",
  },

  //Plans Withdraw During 2023-2024

  {
    productName: "LIC's Cancer Cover",
    productCode: "512N314V02",
    planNumber: "905",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Dhan Varsha",
    productCode: "512N349V01",
    planNumber: "866",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New One Year Renewable Group Term Assurance Plan-I",
    productCode: "512N275V02",
    planNumber: "",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New One Year Renewal Group Term Assurance Plan-II",
    productCode: "512N276V02",
    planNumber: "",
    providerCode: "LIC",
    productType: "Withdrawn",
  },

  //Plans Withdraw during 2022-2023

  {
    productName: "LIC's Tech Term",
    productCode: "512N333V01",
    planNumber: "854",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Amar",
    productCode: "512N332V01",
    planNumber: "855",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Akshay VII",
    productCode: "512N337V02",
    planNumber: "857",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Pradhan Mantri Vaya Vandana Yojana (Modified-2020)",
    productCode: "512G336V01",
    planNumber: "856",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Akshay VII",
    productCode: "512N337V04",
    planNumber: "857",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Jeevan Shanti",
    productCode: "512N338V02",
    planNumber: "858",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Jeevan Shanti",
    productCode: "512N338V04",
    planNumber: "858",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Bachat Plus",
    productCode: "512N340V01",
    planNumber: "861",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Saral Pension",
    productCode: "512N342V02",
    planNumber: "862",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Saral Pension",
    productCode: "512N342V03",
    planNumber: "862",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Aadhaar Stambh",
    productCode: "512N310V02",
    planNumber: "943",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Aadhaar Shila",
    productCode: "512N309V02",
    planNumber: "944",
    providerCode: "LIC",
    productType: "Withdrawn",
  },

  //Plans Withdraw During 2021-2022

  {
    productName: "LIC's Jeevan Akshay VII",
    productCode: "512N337V01",
    planNumber: "857",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Jeevan Shanti",
    productCode: "512N338V04",
    planNumber: "858",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Bima Jyoti",
    productCode: "512N339V01",
    planNumber: "860",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Saral Pension",
    productCode: "512N342V01",
    planNumber: "862",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Arogya",
    productCode: "512N266V03",
    planNumber: "904",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Bhagya Lakshmi",
    productCode: "512N292V03",
    planNumber: "939",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Jeevan Mangal",
    productCode: "512N287V03",
    planNumber: "940",
    providerCode: "LIC",
    productType: "Withdrawn",
  },

  //Plans Withdraw During 2020-2021

  {
    productName: "LIC's Jeevan Shanti",
    productCode: "512N328V01",
    planNumber: "850",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Arogya",
    productCode: "512N266V02",
    planNumber: "904",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Cancer Cover",
    productCode: "512N314V02",
    planNumber: "905",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Critical Illness Benefit Rider",
    productCode: "512A212V01",
    planNumber: "",
    providerCode: "LIC",
    productType: "Withdrawn",
  },

  //Plans Withdraw During 2019-2020

  {
    productName: "LIC's Jeevan Akshay_VI",
    productCode: "512N234V06",
    planNumber: "189",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Endowment Plan",
    productCode: "512N277V01",
    planNumber: "814",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Jeevan Anand",
    productCode: "512N279V01",
    planNumber: "815",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Bima Bachat",
    productCode: "512N284V01",
    planNumber: "816",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Single Premium Endowment Plan",
    productCode: "512N283V01",
    planNumber: "817",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Jeevan Nidhi",
    productCode: "512N271V02",
    planNumber: "818",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Money Back Plan – 20 Years",
    productCode: "512N280V01",
    planNumber: "820",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Money Back Plan – 25 Years",
    productCode: "512N278V01",
    planNumber: "821",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Anmol Jeevan II",
    productCode: "512N285V01",
    planNumber: "822",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Amulya Jeevan II",
    productCode: "512N286V01",
    planNumber: "823",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's e-Term",
    productCode: "512N288V01",
    planNumber: "825",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Rakshak",
    productCode: "512N289V01",
    planNumber: "827",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Limited Premium Endowment Plan",
    productCode: "512N293V01",
    planNumber: "830",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Children's Money Back",
    productCode: "512N296V01",
    planNumber: "832",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Lakshya",
    productCode: "512N297V01",
    planNumber: "833",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Tarun",
    productCode: "512N299V01",
    planNumber: "834",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Endowment Plus",
    productCode: "512L301V01",
    planNumber: "835",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Labh",
    productCode: "512N304V01",
    planNumber: "836",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Pragati",
    productCode: "512N306V01",
    planNumber: "838",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Bhagya Lakshmi",
    productCode: "512N292V02",
    planNumber: "839",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Jeevan Mangal",
    productCode: "512N287V02",
    planNumber: "840",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "Pradhan Mantri Vaya Vandana Yojana",
    productCode: "512G311V02",
    planNumber: "842",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Aadhaar Stambh",
    productCode: "512N310V01",
    planNumber: "843",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Aadhaar Shila",
    productCode: "512N309V01",
    planNumber: "844",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Umang",
    productCode: "512N312V01",
    planNumber: "845",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Utkarsh",
    productCode: "512N313V01",
    planNumber: "846",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Shiromani",
    productCode: "512N315V01",
    planNumber: "847",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Bima Shree",
    productCode: "512N316V01",
    planNumber: "848",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Shanti",
    productCode: "512N328V02",
    planNumber: "850",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Jeevan Shanti",
    productCode: "512N328V02",
    planNumber: "851",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Jeevan Amar",
    productCode: "512N337V01",
    planNumber: "853",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's Premium Waiver Benefit Rider",
    productCode: "512B204V02",
    planNumber: "",
    providerCode: "LIC",
    productType: "Withdrawn",
  },

  //Plans Withdraw During 2018-2019

  {
    productName: "Pradhan Mantri Vaya Vandana Yojana",
    productCode: "512G311V01",
    planNumber: "842",
    providerCode: "LIC",
    productType: "Withdrawn",
  },
  {
    productName: "LIC's New Children's Money Back",
    productCode: "512N296V01",
    planNumber: "832",
    providerCode: "LIC",
    productType: "Withdrawn",
  },

  //Riders

  {
    productName: "LICs Accident Benefit Rider",
    productCode: "512B203V03",
    planNumber: "",
    providerCode: "LIC",
    productType: "Rider",
  },
  {
    productName: "LICs Premium Waiver Benefit Rider",
    productCode: "512B204V02",
    planNumber: "",
    providerCode: "LIC",
    productType: "Rider",
  },
  {
    productName: "LICs Accidental Death and Disability Benefit Rider",
    productCode: "512B209V02",
    planNumber: "",
    providerCode: "LIC",
    productType: "Rider",
  },
  {
    productName: "LIC's New Term Assurance Rider",
    productCode: "512B210V02",
    planNumber: "",
    providerCode: "LIC",
    productType: "Rider",
  },
  {
    productName: "LIC's Linked Accidental Death Benefit Rider",
    productCode: "512A211V02",
    planNumber: "",
    providerCode: "LIC",
    productType: "Rider",
  },
  {
    productName: "LIC's Critical Illness Health Rider",
    productCode: "512B227V01",
    planNumber: "",
    providerCode: "LIC",
    productType: "Rider",
  },
  {
    productName: "LIC's Female Critical Illness Benefit Rider",
    productCode: "512B226V01",
    planNumber: "",
    providerCode: "LIC",
    productType: "Rider",
  },
];