export const pnbProducts = [
      //PNB METLIFE

  {
    productName: "PNB MetLife Group Term Life Plus",
    productCode: "117N049V04",
    planNumber: "PM001",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Loan & Life Suraksha",
    productCode: "117N080V03",
    planNumber: "PM002",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Unit Linked Employee Benefit Plan",
    productCode: "117L084V03",
    planNumber: "PM003",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Traditional Employee Benefits Plan",
    productCode: "117N085V02",
    planNumber: "PM004",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Bachat Yojna",
    productCode: "117N120V01",
    planNumber: "PM005",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Retirement Savings Plan",
    productCode: "117N060V01",
    planNumber: "PM006",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Complete Care Plus",
    productCode: "117N093V04",
    planNumber: "PM007",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Pradhan Mantri Jeevan Jyoti Bima Yojana",
    productCode: "117N105V01",
    planNumber: "PM008",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Immediate Annuity Plan",
    productCode: "117N072V01",
    planNumber: "PM009",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Mera Wealth Plan",
    productCode: "117L098V07",
    planNumber: "PM010",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Complete Loan Protection Plan",
    productCode: "117N104V01",
    planNumber: "PM011",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife POS Suraksha",
    productCode: "117N143V01",
    planNumber: "PM012",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Bima Yojna",
    productCode: "117N120V01",
    planNumber: "PM013",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Aajeevan Suraksha Plan",
    productCode: "117N128V01",
    planNumber: "PM014",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Super Saver Plan",
    productCode: "117N131V06",
    planNumber: "PM015",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Guaranteed Future Plan",
    productCode: "117N124V16",
    planNumber: "PM016",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Smart Platinum Plus",
    productCode: "117L125V06",
    planNumber: "PM017",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Mera Term Plan Plus",
    productCode: "117N126V04",
    planNumber: "PM018",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Group Flexi Term Plus",
    productCode: "117N127V01",
    planNumber: "PM019",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Saral Jeevan Bima",
    productCode: "117N129V01",
    planNumber: "PM020",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Century Plan",
    productCode: "117N130V01",
    planNumber: "PM021",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Saral Pension Plan",
    productCode: "117N132V01",
    planNumber: "PM022",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Guaranteed Goal Plan",
    productCode: "117N131V06",
    planNumber: "PM023",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Group Secured Gain",
    productCode: "117N136V01",
    planNumber: "PM024",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Goal Ensuring Multiplier",
    productCode: "117L133V05",
    planNumber: "PM025",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Grand Assured Income Plan",
    productCode: "117N134V08",
    planNumber: "PM026",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Genius Plan",
    productCode: "117N135V04",
    planNumber: "PM027",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife TULIP",
    productCode: "117L137V01",
    planNumber: "PM028",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Smart Invest Pension Plan",
    productCode: "117L138V01",
    planNumber: "PM029",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Long Income For Tomorrow",
    productCode: "117N140V01",
    planNumber: "PM030",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife GROW Plan",
    productCode: "117L145V01",
    planNumber: "PM031",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Smart Goal Ensuring Multiplier",
    productCode: "117L139V02",
    planNumber: "PM032",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Dhan Suraksha Yojna",
    productCode: "117N168V01",
    planNumber: "PM033",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Smart Invest Pension Plan Pro",
    productCode: "117L138V04",
    planNumber: "PM034",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Group Protection Plan",
    productCode: "117N161V01",
    planNumber: "PM035",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife DigiProtect Term Plan",
    productCode: "117N141V01",
    planNumber: "PM036",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife RISE Plan",
    productCode: "117N169V01",
    planNumber: "PM037",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Smart Platinum Pro",
    productCode: "117L142V02",
    planNumber: "PM038",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Term with Unit Linked Insurance Plan (TULIP)",
    productCode: "117L136V03",
    planNumber: "PM039",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Accidental Death Benefit Plus Rider",
    productCode: "117B020V04",
    planNumber: "PM040",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Serious Illness Rider",
    productCode: "117B021V04",
    planNumber: "PM041",
    providerCode: "PNB_METLIFE",
  },
  {
    productName:
      "PNB MetLife Group Accidental Permanent & Total Disability Plus Rider",
    productCode: "117B016V02",
    planNumber: "PM042",
    providerCode: "PNB_METLIFE",
  },
   {
    productName: "PNB MetLife Money Back Plan",
    productCode: "117N081V03",
    planNumber: "PM043",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Linked Accidental Death Benefit Rider",
    productCode: "117A024V01",
    planNumber: "PM044",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Goal Ensuring Multiplier with Value Fund",
    productCode: "117L133V08",
    planNumber: "PM045",
    providerCode: "PNB_METLIFE",
  },
 
];