export const sbiProducts = [
    
  // SBI Life Insurance Products
  {
    productName: "SBI Life - Smart Term Plan",
    productCode: "LI001",
    planNumber: "SBILIFE001",
    providerCode: "SBI_LIFE",
  },
  {
    productName: "SBI Life - eShield Next",
    productCode: "LI002",
    planNumber: "SBILIFE002",
    providerCode: "SBI_LIFE",
  },
  {
    productName: "SBI Life - Elite Life Insurance",
    productCode: "LI003",
    planNumber: "SBILIFE003",
    providerCode: "SBI_LIFE",
  },
  {
    productName: "SBI Life - Endowment Plan",
    productCode: "LI004",
    planNumber: "SBILIFE004",
    providerCode: "SBI_LIFE",
  },
  {
    productName: "SBI Life - Advantage Plan",
    productCode: "LI005",
    planNumber: "SBILIFE005",
    providerCode: "SBI_LIFE",
  },
  {
    productName: "SBI Life - Smart Goal Assure",
    productCode: "LI006",
    planNumber: "SBILIFE006",
    providerCode: "SBI_LIFE",
  },
  {
    productName: "SBI Life - Guaranteed Plan",
    productCode: "LI007",
    planNumber: "SBILIFE007",
    providerCode: "SBI_LIFE",
  },
  {
    productName: "SBI Life - Super Retirement Plan",
    productCode: "LI008",
    planNumber: "SBILIFE008",
    providerCode: "SBI_LIFE",
  },
  {
    productName: "SBI Life - Immediate Annuity Plan",
    productCode: "LI009",
    planNumber: "SBILIFE009",
    providerCode: "SBI_LIFE",
  },
  {
    productName: "SBI Life - Smart Child Plan",
    productCode: "LI010",
    planNumber: "SBILIFE010",
    providerCode: "SBI_LIFE",
  },
  {
    productName: "SBI Life - Junior Insurance Plan",
    productCode: "LI011",
    planNumber: "SBILIFE011",
    providerCode: "SBI_LIFE",
  },
  {
    productName: "SBI Life - Health Gain Plus",
    productCode: "LI012",
    planNumber: "SBILIFE012",
    providerCode: "SBI_LIFE",
  },
  {
    productName: "SBI Life - Saral Jeevan Bima",
    productCode: "LI013",
    planNumber: "SBILIFE013",
    providerCode: "SBI_LIFE",
  },
  {
    productName: "SBI Life - Dignity Plan",
    productCode: "LI014",
    planNumber: "SBILIFE014",
    providerCode: "SBI_LIFE",
  },
  {
    productName: "SBI Life - Smart Fortune Builder",
    productCode: "111L142V01",
    planNumber: "SBILIFE028",
    providerCode: "SBI_LIFE",
  },
  {
    productName: "SBI Life - Smart Wealth Builder",
    productCode: "111L095V02",
    planNumber: "SBILIFE029",
    providerCode: "SBI_LIFE",
  },
   {
    productName: "SBI Life - eWealth Plus",
    productCode: "111L147V01",
    planNumber: "SBILIFE032",
    providerCode: "SBI_LIFE",
  },
  {
    productName: "SBI Life - Smart Platina Plus",
    productCode: "111N133V06",
    planNumber: "SBILIFE033",
    providerCode: "SBI_LIFE",
  },
  {
    productName: "SBI Life - Smart Annuity Plus",
    productCode: "111N134V10",
    planNumber: "SBILIFE034",
    providerCode: "SBI_LIFE",
  },
  {
    productName: "SBI Life - Smart Platina Advantage",
    productCode: "111N175V02",
    planNumber: "SBILIFE035",
    providerCode: "SBI_LIFE",
  },
  {
    productName: "SBI Life - Smart Shield Premier",
    productCode: "111N145V01",
    planNumber: "SBILIFE036",
    providerCode: "SBI_LIFE",
  },
  {
    productName: "SBI Life - Smart Elite Plus",
    productCode: "111L146V01",
    planNumber: "SBILIFE037",
    providerCode: "SBI_LIFE",
  },
  {
    productName: "SBI Life - Smart Scholar Plus",
    productCode: "111L144V01",
    planNumber: "SBILIFE038",
    providerCode: "SBI_LIFE",
  },
  {
    productName: "SBI Life - Smart Platina Supreme",
    productCode: "111N171V03",
    planNumber: "SBILIFE039",
    providerCode: "SBI_LIFE",
  },
  {
    productName: "SBI Life - Poorna Suraksha",
    productCode: "111N110V01",
    planNumber: "SBILIFE040",
    providerCode: "SBI_LIFE",
  },
  {
    productName: "SBI Life - Smart Bachat",
    productCode: "111N108V01",
    planNumber: "SBILIFE041",
    providerCode: "SBI_LIFE",
  },
  {
    productName: "SBI Life - Sampoorn Cancer Suraksha",
    productCode: "111N109V03",
    planNumber: "SBILIFE042",
    providerCode: "SBI_LIFE",
  },
  {
    productName: "SBI Life - Annuity Plus",
    productCode: "111N083V09",
    planNumber: "SBILIFE043",
    providerCode: "SBI_LIFE",
  },
 
];