export const shriramProducts = [
  //SHRIRAM LIFE INSURANCE - ACTIVE POLICIES
  {
    productName: "Shriram Life Flexi Shield Plan",
    productCode: "128N098V01",
    planNumber: "SLA001",
    providerCode: "SHRIRAM",
    productType: "Term/Protection Plans",
  },
  {
    productName: "Shriram Life Cashback Term Plan",
    productCode: "128N045V04",
    planNumber: "SLA002",
    providerCode: "SHRIRAM",
    productType: "Term/Protection Plans",
  },
  {
    productName: "Shriram Life Family Protection Plan",
    productCode: "128N061V02",
    planNumber: "SLA003",
    providerCode: "SHRIRAM",
    productType: "Term/Protection Plans",
  },
  {
    productName: "Shriram Life Smart Protection Plan",
    productCode: "128N069V05",
    planNumber: "SLA004",
    providerCode: "SHRIRAM",
    productType: "Term/Protection Plans",
  },
  {
    productName: "Shriram Life Saral Jeevan Bima",
    productCode: "128N091V01",
    planNumber: "SLA005",
    providerCode: "SHRIRAM",
    productType: "Term/Protection Plans",
  },
  {
    productName: "Shriram Life My Spouse Term Plan",
    productCode: "128N085V01",
    planNumber: "SLA006",
    providerCode: "SHRIRAM",
    productType: "Term/Protection Plans",
  },
  {
    productName: "Shriram Life Comprehensive Cancer Care Plan",
    productCode: "128N070V02",
    planNumber: "SLA007",
    providerCode: "SHRIRAM",
    productType: "Term/Protection Plans",
  },
  {
    productName: "Shriram Life Assured Income Plan",
    productCode: "128N053V05",
    planNumber: "SLA008",
    providerCode: "SHRIRAM",
    productType: "Savings Plans",
  },
  {
    productName: "Shriram Life Super Income Plan",
    productCode: "128N087V04",
    planNumber: "SLA009",
    providerCode: "SHRIRAM",
    productType: "Savings Plans",
  },
  {
    productName: "Shriram Life Assured Savings Plan",
    productCode: "128N089V04",
    planNumber: "SLA010",
    providerCode: "SHRIRAM",
    productType: "Savings Plans",
  },
  {
    productName: "Shriram Life Early Cash Plan",
    productCode: "128N093V04",
    planNumber: "SLA011",
    providerCode: "SHRIRAM",
    productType: "Savings Plans",
  },
  {
    productName: "Shriram Life Premier Assured Benefit",
    productCode: "128N094V06",
    planNumber: "SLA012",
    providerCode: "SHRIRAM",
    productType: "Savings Plans",
  },
  {
    productName: "Shriram New Shri Life Plan",
    productCode: "128N047V03",
    planNumber: "SLA013",
    providerCode: "SHRIRAM",
    productType: "Savings Plans",
  },
  {
    productName: "Shriram Life Sunishchit Laabh",
    productCode: "128N126V02",
    planNumber: "SLA014",
    providerCode: "SHRIRAM",
    productType: "Savings Plans",
  },
  {
    productName: "Shriram Life Wealth Pro",
    productCode: "128L096V01",
    planNumber: "SLA015",
    providerCode: "SHRIRAM",
    productType: "ULIP / Investment Plans",
  },
  {
    productName: "Shriram Life Growth Plus",
    productCode: "128L066V03",
    planNumber: "SLA016",
    providerCode: "SHRIRAM",
    productType: "ULIP / Investment Plans",
  },
  {
    productName: "Shriram Life Fortune Builder",
    productCode: "128L038V03",
    planNumber: "SLA017",
    providerCode: "SHRIRAM",
    productType: "ULIP / Investment Plans",
  },
  {
    productName: "Shriram Life Golden Jubilee Plan",
    productCode: "128L095V01",
    planNumber: "SLA018",
    providerCode: "SHRIRAM",
    productType: "ULIP / Investment Plans",
  },
  {
    productName: "Shriram Life Saral Pension",
    productCode: "-",
    planNumber: "SLA019",
    providerCode: "SHRIRAM",
    productType: "Retirement Plans",
  },
  {
    productName: "Shriram Life Pension Plus",
    productCode: "128L065V03",
    planNumber: "SLA020",
    providerCode: "SHRIRAM",
    productType: "Retirement Plans",
  },
  {
    productName: "Shriram Life Immediate Annuity Plus",
    productCode: "128N063V09",
    planNumber: "SLA021",
    providerCode: "SHRIRAM",
    productType: "Retirement Plans",
  },
  {
    productName: "Shriram Life Deferred Annuity Plan",
    productCode: "128N105V03",
    planNumber: "SLA022",
    providerCode: "SHRIRAM",
    productType: "Retirement Plans",
  },
  {
    productName: "Shriram Life New Shri Vidya Plan",
    productCode: "128N051V03",
    planNumber: "SLA023",
    providerCode: "SHRIRAM",
    productType: "Child Plans",
  },
  {
    productName: "Shriram Life Assured Income Plan",
    productCode: "128N093V06",
    planNumber: "SLA024",
    providerCode: "SHRIRAM",
    productType: "Child Plans",
  },
  {
    productName: "Shriram Life Early Cash Plan",
    productCode: "128N093V01",
    planNumber: "SLA025",
    providerCode: "SHRIRAM",
    productType: "Child Plans",
  },
  {
    productName: "Shriram Life Sujana",
    productCode: "128N086V01",
    planNumber: "SLA026",
    providerCode: "SHRIRAM",
    productType: "Micro Insurance",
  },
  {
    productName: "Shriram Life Jana Sahay Plan",
    productCode: "128N062V01",
    planNumber: "SLA027",
    providerCode: "SHRIRAM",
    productType: "Micro Insurance",
  },
  {
    productName: "Group Term Life Insurance Plan",
    productCode: "128N042V05",
    planNumber: "SLA028",
    providerCode: "SHRIRAM",
    productType: "Group / Employee Benefit Plans",
  },
  {
    productName: "Group Term Life Insurance in lieu of EDLI",
    productCode: "128N040V02",
    planNumber: "SLA029",
    providerCode: "SHRIRAM",
    productType: "Group / Employee Benefit Plans",
  },
  {
    productName: "Group Life Protector SP",
    productCode: "128N044V04",
    planNumber: "SLA030",
    providerCode: "SHRIRAM",
    productType: "Group / Employee Benefit Plans",
  },
  {
    productName: "Group Traditional Employee Benefit Plan",
    productCode: "128N054V02",
    planNumber: "SLA031",
    providerCode: "SHRIRAM",
    productType: "Group / Employee Benefit Plans",
  },
  {
    productName: "New Group Gratuity Plan",
    productCode: "128L043V01",
    planNumber: "SLA032",
    providerCode: "SHRIRAM",
    productType: "Group / Employee Benefit Plans",
  },
  {
    productName: "Group Superannuation Plan",
    productCode: "128N064V02",
    planNumber: "SLA033",
    providerCode: "SHRIRAM",
    productType: "Group / Employee Benefit Plans",
  },
  {
    productName: "Accident Benefit Rider",
    productCode: "128B001V03",
    planNumber: "SLA034",
    providerCode: "SHRIRAM",
    productType: "Riders",
  },
  {
    productName: "Family Income Benefit Rider",
    productCode: "128B002V03",
    planNumber: "SLA035",
    providerCode: "SHRIRAM",
    productType: "Riders",
  },
  {
    productName: "Critical Illness Plus Rider",
    productCode: "128B016V02",
    planNumber: "SLA036",
    providerCode: "SHRIRAM",
    productType: "Riders",
  },
  {
    productName: "Critical Illness Care Rider (ULIP)",
    productCode: "128A014V01",
    planNumber: "SLA037",
    providerCode: "SHRIRAM",
    productType: "Riders",
  },
  {
    productName: "Critical Illness Woman Rider",
    productCode: "128B009V03",
    planNumber: "SLA038",
    providerCode: "SHRIRAM",
    productType: "Riders",
  },
  {
    productName: "Extra Insurance Cover Rider",
    productCode: "-",
    planNumber: "SLA039",
    providerCode: "SHRIRAM",
    productType: "Riders",
  },
  {
    productName: "Accidental Death & Disability Income Rider",
    productCode: "128A013V01",
    planNumber: "SLA040",
    providerCode: "SHRIRAM",
    productType: "Riders",
  },

  //SHRIRAM LIFE INSURANCE - INACTIVE / WITHDRAWN POLICIES
  {
    productName: "Shriram Life POS Assured Savings Plan",
    productCode: "128N089V01",
    planNumber: "SLI001",
    providerCode: "SHRIRAM",
    productType: "Inactive",
  },
  {
    productName: "Shriram Life Online Term Plan",
    productCode: "128N072V01",
    planNumber: "SLA041",
    providerCode: "SHRIRAM",
    productType: "Term/Protection Plans",
  },
  {
    productName: "Shriram Life Smart Protection Plan SP",
    productCode: "-",
    planNumber: "SLA042",
    providerCode: "SHRIRAM",
    productType: "Term/Protection Plans",
  },
  {
    productName: "Corona Rakshak Policy",
    productCode: "-",
    planNumber: "SLA043",
    providerCode: "SHRIRAM",
    productType: "Term/Protection Plans",
  },
];
