  export const sudProducts = [
  //SUD Products
  {
    productName: "SUD Life Sarva Suraksha Bima",
    productCode: "142N103V01",
    planNumber: "SUD-LI-001",
    providerCode: "SUD",
    productType: "Term Insurance Plans",
  },
  {
    productName: "SUD Life Assured Term Plan",
    productCode: "142N102V01",
    planNumber: "SUD-LI-002",
    providerCode: "SUD",
    productType: "Term Insurance Plans",
  },
  {
    productName: "SUD Life Smart Term Return of Premium Plan",
    productCode: "142N097V01",
    planNumber: "SUD-LI-003",
    providerCode: "SUD",
    productType: "Term Insurance Plans",
  },
  {
    productName: "SUD Life Smart Term Plan",
    productCode: "142N096V01",
    planNumber: "SUD-LI-004",
    providerCode: "SUD",
    productType: "Term Insurance Plans",
  },
  {
    productName: "SUD Life Saral Jeevan Bima",
    productCode: "142N079V01",
    planNumber: "SUD-LI-005",
    providerCode: "SUD",
    productType: "Term Insurance Plans",
  },
  {
    productName: "SUD Life e-Lifeline",
    productCode: "142N092V02",
    planNumber: "SUD-LI-006",
    providerCode: "SUD",
    productType: "Term Insurance Plans",
  },
  {
    productName: "SUD Life Simple Term Plan",
    productCode: "142N095V01",
    planNumber: "SUD-LI-007",
    providerCode: "SUD",
    productType: "Term Insurance Plans",
  },
  {
    productName: "SUD Life E-Wealth Royale Plan",
    productCode: "142L082V03",
    planNumber: "SUD-LI-008",
    providerCode: "SUD",
    productType: "ULIP - Market-Linked-Plans",
  },
  {
    productName: "SUD Life Star TULIP",
    productCode: "142L091V01",
    planNumber: "SUD-LI-009",
    providerCode: "SUD",
    productType: "ULIP - Market-Linked-Plans",
  },
  {
    productName: "SUD LIFE Wealth Creator",
    productCode: "142L077V01",
    planNumber: "SUD-LI-010",
    providerCode: "SUD",
    productType: "ULIP - Market-Linked-Plans",
  },
  {
    productName: "SUD Life Wealth Builder Plan",
    productCode: "142L042V05",
    planNumber: "SUD-LI-011",
    providerCode: "SUD",
    productType: "ULIP - Market-Linked-Plans",
  },
  {
    productName: "SUD Life Immediate Annuity Plus",
    productCode: "142N048V08",
    planNumber: "SUD-LI-012",
    providerCode: "SUD",
    productType: "Retirement Plans",
  },
  {
    productName: "SUD Life Saral Pension",
    productCode: "142N081V02",
    planNumber: "SUD-LI-013",
    providerCode: "SUD",
    productType: "Retirement Plans",
  },
  {
    productName: "SUD Life Retirement Royale",
    productCode: "142L099V02",
    planNumber: "SUD-LI-014",
    providerCode: "SUD",
    productType: "Retirement Plans",
  },
  {
    productName: "SUD Life Pension Plus",
    productCode: "142L093V02",
    planNumber: "SUD-LI-015",
    providerCode: "SUD",
    productType: "Retirement Plans",
  },
  {
    productName: "SUD Life Smart Guaranteed Pension Plan",
    productCode: "142N123V01",
    planNumber: "SUD-LI-016",
    providerCode: "SUD",
    productType: "Retirement Plans",
  },
  {
    productName: "SUD Life Smart Healthcare",
    productCode: "142N089V01",
    planNumber: "SUD-LI-017",
    providerCode: "SUD",
    productType: "Health Plans",
  },
  {
    productName: "SUD Life Health Assure",
    productCode: "142N098V01",
    planNumber: "SUD-LI-018",
    providerCode: "SUD",
    productType: "Health Plans",
  },
  {
    productName: "SUD Life Smart Income Plan",
    productCode: "142N126V01",
    planNumber: "SUD-LI-019",
    providerCode: "SUD",
    productType: "Savings Plans",
  },
  {
    productName: "SUD Life Century Star",
    productCode: "142N075V04",
    planNumber: "SUD-LI-020",
    providerCode: "SUD",
    productType: "Savings Plans",
  },
  {
    productName: "SUD Life Guaranteed Money Back Plan",
    productCode: "142N036V06",
    planNumber: "SUD-LI-021",
    providerCode: "SUD",
    productType: "Savings Plans",
  },
  {
    productName: "SUD Life Century Plus",
    productCode: "142N074V05",
    planNumber: "SUD-LI-022",
    providerCode: "SUD",
    productType: "Savings Plans",
  },
  {
    productName: "SUD Life Samriddhi",
    productCode: "142N057V02",
    planNumber: "SUD-LI-023",
    providerCode: "SUD",
    productType: "Savings Plans",
  },
  {
    productName: "POS – SUD Life Sanchay",
    productCode: "142N058V05",
    planNumber: "SUD-LI-024",
    providerCode: "SUD",
    productType: "Savings Plans",
  },
  {
    productName: "SUD Life Century Gold",
    productCode: "142N087V04",
    planNumber: "SUD-LI-025",
    providerCode: "SUD",
    productType: "Savings Plans",
  },
  {
    productName: "SUD Life Century Royale",
    productCode: "142N083V05",
    planNumber: "SUD-LI-026",
    providerCode: "SUD",
    productType: "Savings Plans",
  },
  {
    productName: "SUD Life Fortune Royale",
    productCode: "142N086V03",
    planNumber: "SUD-LI-027",
    providerCode: "SUD",
    productType: "Savings Plans",
  },
  {
    productName: "SUD Life Guarantee Royale",
    productCode: "142N122V01",
    planNumber: "SUD-LI-028",
    providerCode: "SUD",
    productType: "Savings Plans",
  },
  {
    productName: "SUD Life Century Income",
    productCode: "142N100V03",
    planNumber: "SUD-LI-029",
    providerCode: "SUD",
    productType: "Savings Plans",
  },
  {
    productName: "SUD Life Centurion",
    productCode: "142N101V02",
    planNumber: "SUD-LI-030",
    providerCode: "SUD",
    productType: "Savings Plans",
  },
  {
    productName: "SUD Life Assured Returns Plan",
    productCode: "142N127V01",
    planNumber: "SUD-LI-031",
    providerCode: "SUD",
    productType: "Savings Plans",
  },
  {
    productName: "SUD Life Sampoorna Loan Suraksha Plus",
    productCode: "142N084V02",
    planNumber: "SUD-LI-032",
    providerCode: "SUD",
    productType: "Credit Life Plans",
  },
  {
    productName: "SUD Life Pradhan Mantri Jeevan Jyoti Bima Yojana",
    productCode: "142G047V02",
    planNumber: "SUD-LI-033",
    providerCode: "SUD",
    productType: "Group Term Plans",
  },
  {
    productName: "SUD Life Group Term Insurance Plus",
    productCode: "142N046V04",
    planNumber: "SUD-LI-034",
    providerCode: "SUD",
    productType: "Group Term Plans",
  },
  {
    productName: "SUD Life Group Micro Term Insurance Plan",
    productCode: "142N094V01",
    planNumber: "SUD-LI-035",
    providerCode: "SUD",
    productType: "Group Term Plans",
  },
  {
    productName: "SUD Life Group Retirement Benefit Plan",
    productCode: "142L049V01",
    planNumber: "SUD-LI-036",
    providerCode: "SUD",
    productType: "Group Retirement Plans",
  },
  {
    productName: "SUD Life Group Employee Benefit Plus",
    productCode: "142N090V01",
    planNumber: "SUD-LI-037",
    providerCode: "SUD",
    productType: "Group Employee Benefit Plans",
  },
  {
    productName: "SUD Life Fortune Plus",
    productCode: "142N124V01",
    planNumber: "SUD-LI-038",
    providerCode: "SUD",
    productType: "Savings Plans",
  },
  {
    productName: "SUD Life Aadarsh",
    productCode: "142N054V04",
    planNumber: "SUD-LI-039",
    providerCode: "SUD",
    productType: "Savings Plans",
  },
  {
    productName: "SUD Life Term Inusrance for Women",
    productCode: "SLTIFW",
    planNumber: "SUD-LI-040",
    providerCode: "SUD",
  },
  {
    productName: "SUD Life International Wealth Creator",
    productCode: "SLIWC",
    planNumber: "SUD-LI-041",
    providerCode: "SUD",
  },
 {
  productName: "SUD Life Wealth Builder Plan",
  productCode: "142L042V03",
  planNumber: "SUD-LI-042",
  providerCode: "SUD",
},
{
  productName: "POS – SUD Life Sanchay",
  productCode: "142N058V02",
  planNumber: "SUD-LI-043",
  providerCode: "SUD",
},
{
  productName: "POS – SUD Life Sanchay",
  productCode: "142N058V03",
  planNumber: "SUD-LI-044",
  providerCode: "SUD",
},
{
  productName: "Star Union Dai-ichi's Guaranteed Money Back Plan",
  productCode: "142N036V05",
  planNumber: "SUD-LI-045",
  providerCode: "SUD",
},
{
  productName: "SUD Accidental and Total and Permanent Disability Benefit Rider",
  productCode: "142B005V01",
  planNumber: "SUD-LI-046",
  providerCode: "SUD",
},
{
  productName: "SUD Life Aadarsh",
  productCode: "142N054V03",
  planNumber: "SUD-LI-047",
  providerCode: "SUD",
},
{
  productName: "SUD Life Aadarsh",
  productCode: "142N054V02",
  planNumber: "SUD-LI-048",
  providerCode: "SUD",
},
{
  productName: "SUD Life Aadarsh",
  productCode: "142N054V01",
  planNumber: "SUD-LI-049",
  providerCode: "SUD",
},
{
  productName: "SUD Life Aarogyam Plan",
  productCode: "142N051V01",
  planNumber: "SUD-LI-050",
  providerCode: "SUD",
},
{
  productName: "SUD Life Aashirwaad",
  productCode: "142N053V01",
  planNumber: "SUD-LI-051",
  providerCode: "SUD",
},
{
  productName: "SUD Life Abhay",
  productCode: "142N072V01",
  planNumber: "SUD-LI-052",
  providerCode: "SUD",
},
{
  productName: "SUD Life Assured Income Plan",
  productCode: "142N045V03",
  planNumber: "SUD-LI-053",
  providerCode: "SUD",
},
{
  productName: "SUD Life Assured Income Plan",
  productCode: "142N045V01",
  planNumber: "SUD-LI-054",
  providerCode: "SUD",
},
{
  productName: "SUD Life Bright Child",
  productCode: "142N039V01",
  planNumber: "SUD-LI-055",
  providerCode: "SUD",
},
{
  productName: "SUD Life Centurion",
  productCode: "142N101V01",
  planNumber: "SUD-LI-056",
  providerCode: "SUD",
},
{
  productName: "SUD Life Century Gold",
  productCode: "142N087V02",
  planNumber: "SUD-LI-057",
  providerCode: "SUD",
},
{
  productName: "SUD Life Century Income",
  productCode: "142N100V02",
  planNumber: "SUD-LI-058",
  providerCode: "SUD",
},
{
  productName: "SUD Life Century Income",
  productCode: "142N100V01",
  planNumber: "SUD-LI-059",
  providerCode: "SUD",
},
{
  productName: "SUD Life Century Plus",
  productCode: "142N074V02",
  planNumber: "SUD-LI-060",
  providerCode: "SUD",
},
{
  productName: "SUD Life Century Plus",
  productCode: "142N074V03",
  planNumber: "SUD-LI-061",
  providerCode: "SUD",
},
{
  productName: "SUD Life Century Plus",
  productCode: "142N074V01",
  planNumber: "SUD-LI-062",
  providerCode: "SUD",
},
{
  productName: "SUD Life Century Royale",
  productCode: "142N083V04",
  planNumber: "SUD-LI-063",
  providerCode: "SUD",
},
{
  productName: "SUD Life Century Royale",
  productCode: "142N083V03",
  planNumber: "SUD-LI-064",
  providerCode: "SUD",
},
{
  productName: "SUD Life Century Royale",
  productCode: "142N083V02",
  planNumber: "SUD-LI-065",
  providerCode: "SUD",
},
{
  productName: "SUD Life Century Royale",
  productCode: "142N083V01",
  planNumber: "SUD-LI-066",
  providerCode: "SUD",
},
{
  productName: "SUD Life Century Star",
  productCode: "142N075V02",
  planNumber: "SUD-LI-067",
  providerCode: "SUD",
},
{
  productName: "SUD Life Century Star",
  productCode: "142N075V01",
  planNumber: "SUD-LI-068",
  providerCode: "SUD",
},
{
  productName: "SUD Life COVID - 19 Benefit Rider - Traditional",
  productCode: "142B023V01",
  planNumber: "SUD-LI-069",
  providerCode: "SUD",
},
{
  productName: "SUD Life Critical Illness Benefit Rider",
  productCode: "142C004V02",
  planNumber: "SUD-LI-070",
  providerCode: "SUD",
},
{
  productName: "SUD Life Defined benefit Endowment Plan",
  productCode: "142N023V01",
  planNumber: "SUD-LI-071",
  providerCode: "SUD",
},
{
  productName: "SUD Life Defined Growth Endowment Insurance Plan",
  productCode: "142N027V01",
  planNumber: "SUD-LI-072",
  providerCode: "SUD",
},
{
  productName: "SUD Life Dhan Suraksha 3",
  productCode: "142L024V01",
  planNumber: "SUD-LI-073",
  providerCode: "SUD",
},
{
  productName: "SUD Life Dhan Suraksha Plus",
  productCode: "142L041V01",
  planNumber: "SUD-LI-074",
  providerCode: "SUD",
},
{
  productName: "SUD Life Dhan Suraksha Premium 3",
  productCode: "142L025V01",
  planNumber: "SUD-LI-075",
  providerCode: "SUD",
},
{
  productName: "SUD Life Elite Assure Plan",
  productCode: "142N040V01",
  planNumber: "SUD-LI-076",
  providerCode: "SUD",
},
{
  productName: "SUD Life Elite Assure Plus",
  productCode: "142N059V02",
  planNumber: "SUD-LI-077",
  providerCode: "SUD",
},
{
  productName: "SUD Life Elite Assure Plus",
  productCode: "142N059V01",
  planNumber: "SUD-LI-078",
  providerCode: "SUD",
},
{
  productName: "SUD Life e-Wealth Royale",
  productCode: "142L082V02",
  planNumber: "SUD-LI-079",
  providerCode: "SUD",
},
{
  productName: "SUD Life e-Wealth Royale",
  productCode: "142L082V01",
  planNumber: "SUD-LI-080",
  providerCode: "SUD",
},
{
  productName: "SUD Life Fortune Royale",
  productCode: "142N086V01",
  planNumber: "SUD-LI-081",
  providerCode: "SUD",
},
{
  productName: "SUD Life Immediate Annuity Plan",
  productCode: "142N006V02",
  planNumber: "SUD-LI-082",
  providerCode: "SUD",
},
{
  productName: "SUD Life Immediate Annuity Plus",
  productCode: "142N048V05",
  planNumber: "SUD-LI-083",
  providerCode: "SUD",
},
{
  productName: "SUD Life Immediate Annuity Plus",
  productCode: "142N048V04",
  planNumber: "SUD-LI-084",
  providerCode: "SUD",
},
{
  productName: "SUD Life Immediate Annuity Plus",
  productCode: "142N048V02",
  planNumber: "SUD-LI-085",
  providerCode: "SUD",
},
{
  productName: "SUD Life Immediate Annuity Plus",
  productCode: "142N048V01",
  planNumber: "SUD-LI-086",
  providerCode: "SUD",
},
{
  productName: "SUD Life Jeevan Ashray",
  productCode: "142N044V02",
  planNumber: "SUD-LI-087",
  providerCode: "SUD",
},
{
  productName: "SUD Life Jeevan Safar",
  productCode: "142N005V01",
  planNumber: "SUD-LI-088",
  providerCode: "SUD",
},
{
  productName: "SUD Life Jeevan Safar Plus",
  productCode: "142N043V01",
  planNumber: "SUD-LI-089",
  providerCode: "SUD",
},
{
  productName: "SUD Life Prabhat tara 3",
  productCode: "142L026V01",
  planNumber: "SUD-LI-090",
  providerCode: "SUD",
},
{
  productName: "SUD Life Protect Shield Plus",
  productCode: "142N088V02",
  planNumber: "SUD-LI-091",
  providerCode: "SUD",
},
{
  productName: "SUD Life Pure Term Assurance Plan",
  productCode: "142N012V01",
  planNumber: "SUD-LI-092",
  providerCode: "SUD",
},
{
  productName: "SUD Life Retirement Royale",
  productCode: "142L099V01",
  planNumber: "SUD-LI-093",
  providerCode: "SUD",
},
{
  productName: "SUD Life Samriddhi",
  productCode: "142N057V01",
  planNumber: "SUD-LI-094",
  providerCode: "SUD",
},
{
  productName: "SUD Life Suraksha Kavach Plan",
  productCode: "142N030V01",
  planNumber: "SUD-LI-095",
  providerCode: "SUD",
},
{
  productName: "SUD Life Wealth Builder Plan",
  productCode: "142L042V01",
  planNumber: "SUD-LI-096",
  providerCode: "SUD",
},
{
  productName: "SUD Life's Premier Protection Plan",
  productCode: "142N013V02",
  planNumber: "SUD-LI-097",
  providerCode: "SUD",
},
{
  productName: "SUD Life Immediate Annuity Plus",
  productCode: "142N048V06",
  planNumber: "SUD-LI-098",
  providerCode: "SUD",
},
{
  productName: "SUD Life Century Gold",
  productCode: "142N087V01",
  planNumber: "SUD-LI-099",
  providerCode: "SUD",
},
{
  productName: "SUD Life Century Star",
  productCode: "142N075V03",
  planNumber: "SUD-LI-100",
  providerCode: "SUD",
},
{
  productName: "SUD Life Wealth Builder Plan",
  productCode: "142L042V02",
  planNumber: "SUD-LI-101",
  providerCode: "SUD",
},
{
  productName: "POS – SUD Life Sanchay",
  productCode: "142N058V01",
  planNumber: "SUD-LI-102",
  providerCode: "SUD",
},
{
  productName: "SUD Life Elite Assure Plus",
  productCode: "142N059V03",
  planNumber: "SUD-LI-103",
  providerCode: "SUD",
}

];