  export const sudProducts = [
  //SUD Products
  {
    productName: "SUD Life Sarva Suraksha Bima",
    productCode: "142N103V01",
    planNumber: "SUD-LI-001",
    providerCode: "SUD",
    productType: "Term Insurance Plans",
  },
  {
    productName: "SUD Life Assured Term Plan",
    productCode: "142N102V01",
    planNumber: "SUD-LI-002",
    providerCode: "SUD",
    productType: "Term Insurance Plans",
  },
  {
    productName: "SUD Life Smart Term Return of Premium Plan",
    productCode: "142N097V01",
    planNumber: "SUD-LI-003",
    providerCode: "SUD",
    productType: "Term Insurance Plans",
  },
  {
    productName: "SUD Life Smart Term Plan",
    productCode: "142N096V01",
    planNumber: "SUD-LI-004",
    providerCode: "SUD",
    productType: "Term Insurance Plans",
  },
  {
    productName: "SUD Life Saral Jeevan Bima",
    productCode: "142N079V01",
    planNumber: "SUD-LI-005",
    providerCode: "SUD",
    productType: "Term Insurance Plans",
  },
  {
    productName: "SUD Life e-Lifeline",
    productCode: "142N092V02",
    planNumber: "SUD-LI-006",
    providerCode: "SUD",
    productType: "Term Insurance Plans",
  },
  {
    productName: "SUD Life Simple Term Plan",
    productCode: "142N095V01",
    planNumber: "SUD-LI-007",
    providerCode: "SUD",
    productType: "Term Insurance Plans",
  },
  {
    productName: "SUD Life E-Wealth Royale Plan",
    productCode: "142L082V03",
    planNumber: "SUD-LI-008",
    providerCode: "SUD",
    productType: "ULIP - Market-Linked-Plans",
  },
  {
    productName: "SUD Life Star TULIP",
    productCode: "142L091V01",
    planNumber: "SUD-LI-009",
    providerCode: "SUD",
    productType: "ULIP - Market-Linked-Plans",
  },
  {
    productName: "SUD LIFE Wealth Creator",
    productCode: "142L077V01",
    planNumber: "SUD-LI-010",
    providerCode: "SUD",
    productType: "ULIP - Market-Linked-Plans",
  },
  {
    productName: "SUD Life Wealth Builder Plan",
    productCode: "142L042V05",
    planNumber: "SUD-LI-011",
    providerCode: "SUD",
    productType: "ULIP - Market-Linked-Plans",
  },
  {
    productName: "SUD Life Immediate Annuity Plus",
    productCode: "142N048V08",
    planNumber: "SUD-LI-012",
    providerCode: "SUD",
    productType: "Retirement Plans",
  },
  {
    productName: "SUD Life Saral Pension",
    productCode: "142N081V02",
    planNumber: "SUD-LI-013",
    providerCode: "SUD",
    productType: "Retirement Plans",
  },
  {
    productName: "SUD Life Retirement Royale",
    productCode: "142L099V02",
    planNumber: "SUD-LI-014",
    providerCode: "SUD",
    productType: "Retirement Plans",
  },
  {
    productName: "SUD Life Pension Plus",
    productCode: "142L093V02",
    planNumber: "SUD-LI-015",
    providerCode: "SUD",
    productType: "Retirement Plans",
  },
  {
    productName: "SUD Life Smart Guaranteed Pension Plan",
    productCode: "142N123V01",
    planNumber: "SUD-LI-016",
    providerCode: "SUD",
    productType: "Retirement Plans",
  },
  {
    productName: "SUD Life Smart Healthcare",
    productCode: "142N089V01",
    planNumber: "SUD-LI-017",
    providerCode: "SUD",
    productType: "Health Plans",
  },
  {
    productName: "SUD Life Health Assure",
    productCode: "142N098V01",
    planNumber: "SUD-LI-018",
    providerCode: "SUD",
    productType: "Health Plans",
  },
  {
    productName: "SUD Life Smart Income Plan",
    productCode: "142N126V01",
    planNumber: "SUD-LI-019",
    providerCode: "SUD",
    productType: "Savings Plans",
  },
  {
    productName: "SUD Life Century Star",
    productCode: "142N075V04",
    planNumber: "SUD-LI-020",
    providerCode: "SUD",
    productType: "Savings Plans",
  },
  {
    productName: "SUD Life Guaranteed Money Back Plan",
    productCode: "142N036V06",
    planNumber: "SUD-LI-021",
    providerCode: "SUD",
    productType: "Savings Plans",
  },
  {
    productName: "SUD Life Century Plus",
    productCode: "142N074V05",
    planNumber: "SUD-LI-022",
    providerCode: "SUD",
    productType: "Savings Plans",
  },
  {
    productName: "SUD Life Samriddhi",
    productCode: "142N057V02",
    planNumber: "SUD-LI-023",
    providerCode: "SUD",
    productType: "Savings Plans",
  },
  {
    productName: "POS – SUD Life Sanchay",
    productCode: "142N058V05",
    planNumber: "SUD-LI-024",
    providerCode: "SUD",
    productType: "Savings Plans",
  },
  {
    productName: "SUD Life Century Gold",
    productCode: "142N087V04",
    planNumber: "SUD-LI-025",
    providerCode: "SUD",
    productType: "Savings Plans",
  },
  {
    productName: "SUD Life Century Royale",
    productCode: "142N083V05",
    planNumber: "SUD-LI-026",
    providerCode: "SUD",
    productType: "Savings Plans",
  },
  {
    productName: "SUD Life Fortune Royale",
    productCode: "142N086V03",
    planNumber: "SUD-LI-027",
    providerCode: "SUD",
    productType: "Savings Plans",
  },
  {
    productName: "SUD Life Guarantee Royale",
    productCode: "142N122V01",
    planNumber: "SUD-LI-028",
    providerCode: "SUD",
    productType: "Savings Plans",
  },
  {
    productName: "SUD Life Century Income",
    productCode: "142N100V03",
    planNumber: "SUD-LI-029",
    providerCode: "SUD",
    productType: "Savings Plans",
  },
  {
    productName: "SUD Life Centurion",
    productCode: "142N101V02",
    planNumber: "SUD-LI-030",
    providerCode: "SUD",
    productType: "Savings Plans",
  },
  {
    productName: "SUD Life Assured Returns Plan",
    productCode: "142N127V01",
    planNumber: "SUD-LI-031",
    providerCode: "SUD",
    productType: "Savings Plans",
  },
  {
    productName: "SUD Life Sampoorna Loan Suraksha Plus",
    productCode: "142N084V02",
    planNumber: "SUD-LI-032",
    providerCode: "SUD",
    productType: "Credit Life Plans",
  },
  {
    productName: "SUD Life Pradhan Mantri Jeevan Jyoti Bima Yojana",
    productCode: "142G047V02",
    planNumber: "SUD-LI-033",
    providerCode: "SUD",
    productType: "Group Term Plans",
  },
  {
    productName: "SUD Life Group Term Insurance Plus",
    productCode: "142N046V04",
    planNumber: "SUD-LI-034",
    providerCode: "SUD",
    productType: "Group Term Plans",
  },
  {
    productName: "SUD Life Group Micro Term Insurance Plan",
    productCode: "142N094V01",
    planNumber: "SUD-LI-035",
    providerCode: "SUD",
    productType: "Group Term Plans",
  },
  {
    productName: "SUD Life Group Retirement Benefit Plan",
    productCode: "142L049V01",
    planNumber: "SUD-LI-036",
    providerCode: "SUD",
    productType: "Group Retirement Plans",
  },
  {
    productName: "SUD Life Group Employee Benefit Plus",
    productCode: "142N090V01",
    planNumber: "SUD-LI-037",
    providerCode: "SUD",
    productType: "Group Employee Benefit Plans",
  },
  {
    productName: "SUD Life Fortune Plus",
    productCode: "142N124V01",
    planNumber: "SUD-LI-038",
    providerCode: "SUD",
    productType: "Savings Plans",
  },
  {
    productName: "SUD Life Aadarsh",
    productCode: "142N054V04",
    planNumber: "SUD-LI-039",
    providerCode: "SUD",
    productType: "Savings Plans",
  },
];