export const tataaiaProducts = [
     {
    productName: "Tata AIA Sampoorna Raksha Promise",
    productCode: "110N176V12",
    planNumber: "TATA001",
    providerCode: "TATA_AIA",
    productType: "Term Insurance",
  },
  {
    productName: "Tata AIA Maha Raksha Supreme Select",
    productCode: "110N171V15",
    planNumber: "TATA002",
    providerCode: "TATA_AIA",
    productType: "Term Insurance",
  },
  {
    productName: "Tata AIA Smart Sampoorna Raksha Supreme",
    productCode: "110L179V02",
    planNumber: "TATA003",
    providerCode: "TATA_AIA",
    productType: "ULIP & Wealth Plans",
  },
  {
    productName: "Tata AIA Fortune Guarantee Plus",
    productCode: "110N158V14",
    planNumber: "TATA004",
    providerCode: "TATA_AIA",
    productType: "Saving Plans",
  },
  {
    productName: "Tata AIA Guaranteed Return Insurance Plan",
    productCode: "110N152V15",
    planNumber: "TATA005",
    providerCode: "TATA_AIA",
    productType: "Saving Plans",
  },
  {
    productName: "Tata AIA Smart Value Income Plan",
    productCode: "110N162V03",
    planNumber: "TATA006",
    providerCode: "TATA_AIA",
    productType: "Saving Plans",
  },
  {
    productName: "Tata AIA Smart Fortune Plus",
    productCode: "110L177V01",
    planNumber: "TATA007",
    providerCode: "TATA_AIA",
    productType: "ULIP & Wealth Plans",
  },
  {
    productName: "Tata AIA Smart SIP",
    productCode: "110L174V02",
    planNumber: "TATA008",
    providerCode: "TATA_AIA",
    productType: "ULIP & Wealth Plans",
  },
  {
    productName: "Tata AIA Fortune Pro",
    productCode: "110L112V07",
    planNumber: "TATA009",
    providerCode: "TATA_AIA",
    productType: "ULIP & Wealth Plans",
  },
  {
    productName: "Tata AIA Smart Pension Secure",
    productCode: "110L182V09",
    planNumber: "TATA010",
    providerCode: "TATA_AIA",
    productType: "Retirement & Pension Plans",
  },
  {
    productName: "Tata AIA Fortune Guarantee Pension",
    productCode: "110N161V13",
    planNumber: "TATA011",
    providerCode: "TATA_AIA",
    productType: "Retirement & Pension Plans",
  },
  {
    productName: "Tata AIA Shubh Family Protect",
    productCode: "110N176V08",
    planNumber: "TATA012",
    providerCode: "TATA_AIA",
    productType: "Term Insurance",
  },
  {
    productName: "Tata AIA Fortune Guarantee Supreme",
    productCode: "110N163V12",
    planNumber: "TATA013",
    providerCode: "TATA_AIA",
    productType: "Saving Plans",
  },
  {
    productName: "Tata AIA Fortune Guarantee Secure",
    productCode: "110N206V03",
    planNumber: "TATA014",
    providerCode: "TATA_AIA",
    productType: "Saving Plans",
  },
  {
    productName: "Tata AIA Life Insurance Fortune Guarantee",
    productCode: "110N120V12",
    planNumber: "TATA015",
    providerCode: "TATA_AIA",
    productType: "Saving Plans",
  },
  {
    productName: "Tata AIA Smart Income Plus",
    productCode: "110N126V05",
    planNumber: "TATA016",
    providerCode: "TATA_AIA",
    productType: "Saving Plans",
  },
  {
    productName: "Tata AIA iSIP (i Systematic Insurance Plan)",
    productCode: "110L164V10",
    planNumber: "TATA017",
    providerCode: "TATA_AIA",
    productType: "ULIP & Wealth Plans",
  },
  {
    productName:
      "Tata AIA Shubh Muhurat Solution (Combination of Fortune Guarantee Secure + Smart Fortune Plus)",
    productCode: "110N206V02 + 110L177V01",
    planNumber: "TATA018",
    providerCode: "TATA_AIA",
    productType: "Child Marriage Planning / Savings",
  },
  {
    productName: "Tata AIA Smart Sampoorna Raksha Pro",
    productCode: "110L172V03",
    planNumber: "TATA019",
    providerCode: "TATA_AIA",
    productType: "ULIP & Wealth Plans",
  },
  {
    productName: "Tata AIA Life Insurance Wealth Pro",
    productCode: "110L111V05",
    planNumber: "TATA020",
    providerCode: "TATA_AIA",
    productType: "ULIP & Wealth Plans",
  },
  {
    productName: "Tata AIA Life Insurance Wealth Maxima",
    productCode: "110L114V05",
    planNumber: "TATA021",
    providerCode: "TATA_AIA",
    productType: "ULIP & Wealth Plans",
  },
  {
    productName: "Tata AIA Shubh Flexi Pension Plan",
    productCode: "110N209V02",
    planNumber: "TATA022",
    providerCode: "TATA_AIA",
    productType: "Retirement & Pension Plans",
  },
  {
    productName: "Tata AIA Life Insurance Saral Pension",
    productCode: "110N159V09",
    planNumber: "TATA023",
    providerCode: "TATA_AIA",
    productType: "Retirement & Pension Plans",
  },
  {
    productName: "TATA AIA Fortune Guarantee Retirement Ready",
    productCode: "110N175V04",
    planNumber: "TATA024",
    providerCode: "TATA_AIA",
    productType: "Retirement & Pension Plans",
  },
  {
    productName: "Tata AIA Sampoorna Care",
    productCode: "110N186V01",
    planNumber: "TATA025",
    providerCode: "TATA_AIA",
    productType: "Health Plans",
  },
  {
    productName: "Tata AIA Health SIP",
    productCode: "110L184V01",
    planNumber: "TATA026",
    providerCode: "TATA_AIA",
    productType: "Health Plans",
  },
  {
    productName: "Tata AIA Health Pro",
    productCode: "110L180V01",
    planNumber: "TATA027",
    providerCode: "TATA_AIA",
    productType: "Health Plans",
  },
];