export const tataaiaProducts = [
     {
    productName: "Tata AIA Sampoorna Raksha Promise",
    productCode: "110N176V12",
    planNumber: "TATA001",
    providerCode: "TATA_AIA",
    productType: "Term Insurance",
  },
  {
    productName: "Tata AIA Maha Raksha Supreme Select",
    productCode: "110N171V15",
    planNumber: "TATA002",
    providerCode: "TATA_AIA",
    productType: "Term Insurance",
  },
  {
    productName: "Tata AIA Smart Sampoorna Raksha Supreme",
    productCode: "110L179V02",
    planNumber: "TATA003",
    providerCode: "TATA_AIA",
    productType: "ULIP & Wealth Plans",
  },
  {
    productName: "Tata AIA Fortune Guarantee Plus",
    productCode: "110N158V14",
    planNumber: "TATA004",
    providerCode: "TATA_AIA",
    productType: "Saving Plans",
  },
  {
    productName: "Tata AIA Guaranteed Return Insurance Plan",
    productCode: "110N152V15",
    planNumber: "TATA005",
    providerCode: "TATA_AIA",
    productType: "Saving Plans",
  },
  {
    productName: "Tata AIA Smart Value Income Plan",
    productCode: "110N162V03",
    planNumber: "TATA006",
    providerCode: "TATA_AIA",
    productType: "Saving Plans",
  },
  {
    productName: "Tata AIA Smart Fortune Plus",
    productCode: "110L177V01",
    planNumber: "TATA007",
    providerCode: "TATA_AIA",
    productType: "ULIP & Wealth Plans",
  },
  {
    productName: "Tata AIA Smart SIP",
    productCode: "110L174V02",
    planNumber: "TATA008",
    providerCode: "TATA_AIA",
    productType: "ULIP & Wealth Plans",
  },
  {
    productName: "Tata AIA Fortune Pro",
    productCode: "110L112V07",
    planNumber: "TATA009",
    providerCode: "TATA_AIA",
    productType: "ULIP & Wealth Plans",
  },
  {
    productName: "Tata AIA Smart Pension Secure",
    productCode: "110L182V09",
    planNumber: "TATA010",
    providerCode: "TATA_AIA",
    productType: "Retirement & Pension Plans",
  },
  {
    productName: "Tata AIA Fortune Guarantee Pension",
    productCode: "110N161V13",
    planNumber: "TATA011",
    providerCode: "TATA_AIA",
    productType: "Retirement & Pension Plans",
  },
  {
    productName: "Tata AIA Shubh Family Protect",
    productCode: "110N176V08",
    planNumber: "TATA012",
    providerCode: "TATA_AIA",
    productType: "Term Insurance",
  },
  {
    productName: "Tata AIA Fortune Guarantee Supreme",
    productCode: "110N163V12",
    planNumber: "TATA013",
    providerCode: "TATA_AIA",
    productType: "Saving Plans",
  },
  {
    productName: "Tata AIA Fortune Guarantee Secure",
    productCode: "110N206V03",
    planNumber: "TATA014",
    providerCode: "TATA_AIA",
    productType: "Saving Plans",
  },
  {
    productName: "Tata AIA Life Insurance Fortune Guarantee",
    productCode: "110N120V12",
    planNumber: "TATA015",
    providerCode: "TATA_AIA",
    productType: "Saving Plans",
  },
  {
    productName: "Tata AIA Smart Income Plus",
    productCode: "110N126V05",
    planNumber: "TATA016",
    providerCode: "TATA_AIA",
    productType: "Saving Plans",
  },
  {
    productName: "Tata AIA iSIP (i Systematic Insurance Plan)",
    productCode: "110L164V10",
    planNumber: "TATA017",
    providerCode: "TATA_AIA",
    productType: "ULIP & Wealth Plans",
  },
  {
    productName:
      "Tata AIA Shubh Muhurat Solution (Combination of Fortune Guarantee Secure + Smart Fortune Plus)",
    productCode: "110N206V02 + 110L177V01",
    planNumber: "TATA018",
    providerCode: "TATA_AIA",
    productType: "Child Marriage Planning / Savings",
  },
  {
    productName: "Tata AIA Smart Sampoorna Raksha Pro",
    productCode: "110L172V03",
    planNumber: "TATA019",
    providerCode: "TATA_AIA",
    productType: "ULIP & Wealth Plans",
  },
  {
    productName: "Tata AIA Life Insurance Wealth Pro",
    productCode: "110L111V05",
    planNumber: "TATA020",
    providerCode: "TATA_AIA",
    productType: "ULIP & Wealth Plans",
  },
  {
    productName: "Tata AIA Life Insurance Wealth Maxima",
    productCode: "110L114V05",
    planNumber: "TATA021",
    providerCode: "TATA_AIA",
    productType: "ULIP & Wealth Plans",
  },
  {
    productName: "Tata AIA Shubh Flexi Pension Plan",
    productCode: "110N209V02",
    planNumber: "TATA022",
    providerCode: "TATA_AIA",
    productType: "Retirement & Pension Plans",
  },
  {
    productName: "Tata AIA Life Insurance Saral Pension",
    productCode: "110N159V09",
    planNumber: "TATA023",
    providerCode: "TATA_AIA",
    productType: "Retirement & Pension Plans",
  },
  {
    productName: "TATA AIA Fortune Guarantee Retirement Ready",
    productCode: "110N175V04",
    planNumber: "TATA024",
    providerCode: "TATA_AIA",
    productType: "Retirement & Pension Plans",
  },
  {
    productName: "Tata AIA Sampoorna Care",
    productCode: "110N186V01",
    planNumber: "TATA025",
    providerCode: "TATA_AIA",
    productType: "Health Plans",
  },
  {
    productName: "Tata AIA Health SIP",
    productCode: "110L184V01",
    planNumber: "TATA026",
    providerCode: "TATA_AIA",
    productType: "Health Plans",
  },
  {
    productName: "Tata AIA Health Pro",
    productCode: "110L180V01",
    planNumber: "TATA027",
    providerCode: "TATA_AIA",
    productType: "Health Plans",
  },
  {
    productName: "Tata AIA Shubh Flexi Income Plan",
    productCode: "TASFIP",
    planNumber: "TATA028",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Smart Wealth Plus",
    productCode: "TASWP",
    planNumber: "TATA029",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Param Raksha Life Pro+",
    productCode: "TAPRLP",
    planNumber: "TATA030",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Premier SIP",
    productCode: "TAPS",
    planNumber: "TATA031",
    providerCode: "TATA_AIA",
  },
{
    productName: "Tata AIA Shubh Rakshak",
    productCode: "TASR",
    planNumber: "TATA032",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Shubh Rakshak Select",
    productCode: "TASRS",
    planNumber: "TATA033",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Maha Raksha Supreme Select – S",
    productCode: "TAMRSS-S",
    planNumber: "TATA034",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Sampoorna Raksha Supreme Credit Protect",
    productCode: "TASRSCP",
    planNumber: "TATA035",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Guaranteed Monthly Income Plan",
    productCode: "TAGMIP",
    planNumber: "TATA036",
    providerCode: "TATA_AIA",
  },
   {
    productName: "Tata AIA Smart Sampoorna Raksha Plus",
    productCode: "TASSRP",
    planNumber: "TATA037",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Smart Sampoorna Raksha Flexi",
    productCode: "SSRF",
    planNumber: "TATA038",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Param Raksha Life Maxima +",
    productCode: "TAPRLM+",
    planNumber: "TATA039",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Param Raksha Life Advantage +",
    productCode: "TAPRLA+",
    planNumber: "TATA040",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Param Raksha Life Pro",
    productCode: "TAPRLP",
    planNumber: "TATA041",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Param Raksha Life Growth +",
    productCode: "TAPRLG+",
    planNumber: "TATA042",
    providerCode: "TATA_AIA",
  },
   {
    productName: "Tata AIA Param Raksha Life Pro Advance",
    productCode: "TAPRLPA",
    planNumber: "TATA043",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Shubh Invest Protect",
    productCode: "TASIP",
    planNumber: "TATA044",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Shubh Health Criti",
    productCode: "TASHC",
    planNumber: "TATA045",
    providerCode: "TATA_AIA",
  },
   {
    productName: "Tata AIA Pro-Fit",
    productCode: "TAPF",
    planNumber: "TATA046",
    providerCode: "TATA_AIA",
  },
   {
    productName: "Tata AIA Shubh Health Plus",
    productCode: "TASHP",
    planNumber: "TATA047",
    providerCode: "TATA_AIA",
  },
{
    productName: "Tata AIA VitaHealth",
    productCode: "TAV",
    planNumber: "TATA048",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Shubh Health Pro",
    productCode: "TASHP",
    planNumber: "TATA049",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Vitality Protect Advance",
    productCode: "TAVPA",
    planNumber: "TATA050",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Capital Guarantee Solution",
    productCode: "TACGS",
    planNumber: "TATA051",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Capital Guarantee Income Solution",
    productCode: "TACGIS",
    planNumber: "TATA052",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Capital Guarantee & Immediate Income Solution",
    productCode: "TACG&IIS",
    planNumber: "TATA053",
    providerCode: "TATA_AIA",
  },
   {
    productName: "Tata AIA Capital Guarantee Advanced Solution",
    productCode: "TACGAS",
    planNumber: "TATA054",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Fortune Guarantee Plus (Employee Offer)",
    productCode: "TAFGP(EO)",
    planNumber: "TATA055",
    providerCode: "TATA_AIA",
  }
];