import { PrismaClient } from '@prisma/client';
import { seedPolicyStatuses } from './policyStatus.seed';
import { seedPremiumModes } from './premiumMode.seed';
import { seedInsuranceProviders } from './insuranceProvider.seed';
import { seedLicBranches } from './licBranch.seed';
import { seedAgencies } from './agency.seed';
import { seedProductCategories } from './productCategory.seed';
import { seedProducts } from './product.seed';
import { seedAdvisors } from './advisor.seed';
import { seedRiders } from './rider.seed';
import { seedPaymentStatuses } from './paymentStatus.seed';
import { seedProductAttributes } from './productattributemaster.seed';
import { seedProductAttributeValues } from './productattributevalue.seed';
import { seedLoanStatuses } from './loanStatus.seed';
import { seedLIC714SumAssuredRebates } from "../masterData/rebates/lic714";
import { seedLIC715SumAssuredRebates } from "../masterData/rebates/lic715";
import { seedLIC717SumAssuredRebates } from "../masterData/rebates/lic717";
import { seedLIC717ModeRebates } from "../masterData/moderebates/lic717";
import { seedLIC751SumAssuredRebates } from "../masterData/rebates/lic751";
import { seedLIC748SumAssuredRebates } from "../masterData/rebates/lic748";
import { seedPaymentModes } from './paymentModes.seed';

export const runSeeders = async (prisma: PrismaClient) => {
  await seedPolicyStatuses(prisma);
  await seedPremiumModes(prisma);
  await seedInsuranceProviders(prisma);
  await seedLicBranches(prisma);
  await seedAgencies(prisma);
  await seedProductCategories(prisma);
  await seedProductAttributes(prisma);
  await seedProducts(prisma);
  await seedProductAttributeValues(prisma);
  await seedAdvisors(prisma);
  await seedRiders(prisma);
  await seedPaymentStatuses(prisma);
  await seedLoanStatuses(prisma);
  await seedLIC714SumAssuredRebates(prisma);
  await seedLIC715SumAssuredRebates(prisma);
  await seedLIC717SumAssuredRebates(prisma);
  await seedLIC717ModeRebates(prisma);
  await seedLIC751SumAssuredRebates(prisma);
  await seedLIC748SumAssuredRebates(prisma);
  await seedPaymentModes(prisma);
};
