export const providersData = [
  { name: 'Aditya Birla Sun Life Insurance Company Limited', type: 'Insurance', code: 'ABSLI' },
  { name: 'Aegon Life Insurance Company Limited', type: 'Insurance', code: 'AEGON' },
  { name: 'Aviva Life Insurance Company', type: 'Insurance', code: 'AVIVA' },
  { name: 'Axis Max Life Insurance Limited', type: 'Insurance', code: 'AXIS_MAX' },
  { name: 'Bajaj Allianz Life Insurance Company', type: 'Insurance', code: 'BAJAJ_ALLIANZ' },
  { name: 'Bharti AXA Life Insurance Company', type: 'Insurance', code: 'BHARTI_AXA' },
  { name: 'Canara HSBC Life Insurance Company Limited', type: 'Insurance', code: 'CANARA_HSBC' },
  { name: 'DHFL Pramerica Life Insurance Company', type: 'Insurance', code: 'DHFL_PRAMERICA' },
  { name: 'Digit Life Insurance', type: 'Insurance', code: 'DIGIT' },
  { name: 'Edelweiss Tokio Life Insurance Company', type: 'Insurance', code: 'EDELWEISS_TOKIO' },
  { name: 'Exide Life Insurance Company', type: 'Insurance', code: 'EXIDE' },
  { name: 'Future Generali India Life Insurance Company', type: 'Insurance', code: 'FUTURE_GENERALI' },
  { name: 'HDFC Life Insurance Company Limited', type: 'Insurance', code: 'HDFC_LIFE' },
  { name: 'ICICI Prudential Life Insurance Company Limited', type: 'Insurance', code: 'ICICI_PRU' },
  { name: 'Ageas Federal Life Insurance Company Limited', type: 'Insurance', code: 'AGEAS_FEDERAL' },
  { name: 'IndiaFirst Life Insurance Company', type: 'Insurance', code: 'INDIAFIRST' },
  { name: 'Kotak Life Insurance', type: 'Insurance', code: 'KOTAK' },
  { name: 'Life Insurance Corporation of India', type: 'Insurance', code: 'LIC' },
  { name: 'Max Life Insurance Company', type: 'Insurance', code: 'MAX_LIFE' },
  { name: 'PNB MetLife India Insurance Company Limited', type: 'Insurance', code: 'PNB_METLIFE' },
  { name: 'Postal Life Insurance', type: 'Insurance', code: 'PLI' },
  { name: 'Reliance Nippon Life Insurance Company', type: 'Insurance', code: 'RELIANCE_NIPPON' },
  { name: 'Sahara India Life Insurance Company', type: 'Insurance', code: 'SAHARA' },
  { name: 'SBI Life Insurance Company Limited', type: 'Insurance', code: 'SBI_LIFE' },
  { name: 'Shriram Life Insurance Company', type: 'Insurance', code: 'SHRIRAM' },
  { name: 'Star Union Dai-ichi Life Insurance Company', type: 'Insurance', code: 'SUD' },
  { name: 'Tata AIA Life Insurance Company Limited', type: 'Insurance', code: 'TATA_AIA' },
  { name: 'Unit Trust of India', type: 'Insurance', code: 'UTI' },
];