export const productsData = [
  // LIC Products
  {
    productName: "Single Premium Endowment Plan",
    productCode: "SPEP",
    planNumber: "717",
    providerCode: "LIC",
  },
  {
    productName: "LICs New Jeevan Anand",
    productCode: "LNJA",
    planNumber: "715",
    providerCode: "LIC",
  },
  {
    productName: "LIC Jeevan Labh",
    productCode: "LJL",
    planNumber: "736",
    providerCode: "LIC",
  },
  // Aditya Birla Sun Life Insurance Products
  {
    productName: "ABSLI DigiShield Plan",
    productCode: "ADP",
    planNumber: "ABSLI001",
    providerCode: "ABSLI",
  },
  {
    productName: "ABSLI Salaried Term Plan",
    productCode: "ASTP",
    planNumber: "ABSLI002",
    providerCode: "ABSLI",
  },
  // ICICI Pru Products
  {
    productName: "ICICI Pru Signature Secure",
    productCode: "105L210V01",
    planNumber: "ICICIPRU001",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Protect N Gain Whole Life",
    productCode: "105L208V01",
    planNumber: "ICICIPRU002",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru iProtect Care",
    productCode: "105N209V02",
    planNumber: "ICICIPRU003",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru SmartKid 360",
    productCode: "105N225V02",
    planNumber: "ICICIPRU004",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Wealth Elite Pro",
    productCode: "105L207V01",
    planNumber: "ICICIPRU005",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Wealth Forever",
    productCode: "105N206V01",
    planNumber: "ICICIPRU006",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru iProtect Smart Plus",
    productCode: "105N205V05",
    planNumber: "ICICIPRU007",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Gift Select",
    productCode: "105N233V05",
    planNumber: "ICICIPRU008",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Smart Goal Assure",
    productCode: "105L199V01",
    planNumber: "ICICIPRU009",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru iProtect Super",
    productCode: "105N197V03",
    planNumber: "ICICIPRU010",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Saral Jeevan Bima",
    productCode: "105N183V03",
    planNumber: "ICICIPRU011",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI PRU Signature Assure",
    productCode: "105L196V01",
    planNumber: "ICICIPRU012",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru iProtect Smart Return of Premium",
    productCode: "105N195V02",
    planNumber: "ICICIPRU013",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Guaranteed Pension Plan",
    productCode: "105N181V05",
    planNumber: "ICICIPRU014",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Signature Pension",
    productCode: "105L194V03",
    planNumber: "ICICIPRU015",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru iProtect Supreme",
    productCode: "105N193V03",
    planNumber: "ICICIPRU016",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Savings Suraksha",
    productCode: "105N135V05",
    planNumber: "ICICIPRU017",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Assured Savings Insurance Plan",
    productCode: "105N144V13",
    planNumber: "ICICIPRU018",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru iProtect Smart",
    productCode: "105N151V16",
    planNumber: "ICICIPRU019",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Sarv Jana Suraksha",
    productCode: "105N081V06",
    planNumber: "ICICIPRU020",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Future Perfect",
    productCode: "105N153V05",
    planNumber: "ICICIPRU021",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Life Time Classic",
    productCode: "105L155V10",
    planNumber: "ICICIPRU022",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru1 Wealth",
    productCode: "105L175V10",
    planNumber: "ICICIPRU023",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Signature",
    productCode: "105L177V12",
    planNumber: "ICICIPRU024",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Guaranteed Income For Tomorrow",
    productCode: "105N182V13",
    planNumber: "ICICIPRU025",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Saral Pension",
    productCode: "105N184V09",
    planNumber: "ICICIPRU026",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Guaranteed Income For Tomorrow (Long-term)",
    productCode: "105N185V17",
    planNumber: "ICICIPRU027",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Guaranteed Pension Plan Flexi",
    productCode: "105N185V03",
    planNumber: "ICICIPRU028",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Sukh Samruddhi",
    productCode: "105N188V03",
    planNumber: "ICICIPRU029",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Ezy Grow",
    productCode: "105L202V02",
    planNumber: "ICICIPRU030",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Gold",
    productCode: "105N190V06",
    planNumber: "ICICIPRU031",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Protect N Gain",
    productCode: "105L191V06",
    planNumber: "ICICIPRU032",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru GIFT Pro",
    productCode: "105N201V05",
    planNumber: "ICICIPRU033",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Gold Pension Savings",
    productCode: "105N202V03",
    planNumber: "ICICIPRU034",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Platinum",
    productCode: "105L192V04",
    planNumber: "ICICIPRU035",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Wish",
    productCode: "105N198V01",
    planNumber: "ICICIPRU036",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Smart Insurance Plan Plus",
    productCode: "105L204V03",
    planNumber: "ICICIPRU037",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru GIFT Assure",
    productCode: "105N224V02",
    planNumber: "ICICIPRU038",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Group Unit Linked Superannuation Plus",
    productCode: "105L200V02",
    planNumber: "ICICIPRU039",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Immediate Annuity",
    productCode: "105N009V26",
    planNumber: "ICICIPRU040",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Group Unit Linked Superannuation",
    productCode: "105L136V03",
    planNumber: "ICICIPRU041",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Group Suraksha Plus Superannuation",
    productCode: "105N148V03",
    planNumber: "ICICIPRU042",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Group Unit Linked Employee Benefit Plan",
    productCode: "105L137V04",
    planNumber: "ICICIPRU043",
    providerCode: "ICICI_PRU",
  },
  {
    productName:
      "ICICI Pru Group Insurance Scheme for Pradhan Mantri Jeevan Jyoti Bima Yojana",
    productCode: "105G146V02",
    planNumber: "ICICIPRU044",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Group Suraksha Plus",
    productCode: "105N147V03",
    planNumber: "ICICIPRU045",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Group Term Plus",
    productCode: "105N119V08",
    planNumber: "ICICIPRU046",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Group Loan Secure",
    productCode: "105N152V04",
    planNumber: "ICICIPRU047",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Shubh Raksha Credit",
    productCode: "105N159V03",
    planNumber: "ICICIPRU048",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Shubh Raksha One",
    productCode: "105N158V03",
    planNumber: "ICICIPRU049",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Shubh Raksha Life",
    productCode: "105N160V03",
    planNumber: "ICICIPRU050",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Super Protect - Credit",
    productCode: "105N176V03",
    planNumber: "ICICIPRU051",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Super Protect life",
    productCode: "105N180V02",
    planNumber: "ICICIPRU052",
    providerCode: "ICICI_PRU",
  },
  {
    productName: "ICICI Pru Group Nischit Aay Yojna",
    productCode: "105N203V02",
    planNumber: "ICICIPRU053",
    providerCode: "ICICI_PRU",
  },

  //SUD Products
  {
    productName: "SUD Life Sarva Suraksha Bima",
    productCode: "142N103V01",
    planNumber: "SUD-LI-001",
    providerCode: "SUD",
  },
  {
    productName: "SUD Life Assured Term Plan",
    productCode: "142N102V01",
    planNumber: "SUD-LI-002",
    providerCode: "SUD",
  },
  {
    productName: "SUD Life Smart Term Return of Premium Plan",
    productCode: "142N097V01",
    planNumber: "SUD-LI-003",
    providerCode: "SUD",
  },
  {
    productName: "SUD Life Smart Term Plan",
    productCode: "142N096V01",
    planNumber: "SUD-LI-004",
    providerCode: "SUD",
  },
  {
    productName: "SUD Life Saral Jeevan Bima",
    productCode: "142N079V01",
    planNumber: "SUD-LI-005",
    providerCode: "SUD",
  },
  {
    productName: "SUD Life e-Lifeline",
    productCode: "142N092V02",
    planNumber: "SUD-LI-006",
    providerCode: "SUD",
  },
  {
    productName: "SUD Life Simple Term Plan",
    productCode: "142N095V01",
    planNumber: "SUD-LI-007",
    providerCode: "SUD",
  },
  {
    productName: "SUD Life E-Wealth Royale Plan",
    productCode: "142L082V03",
    planNumber: "SUD-LI-008",
    providerCode: "SUD",
  },
  {
    productName: "SUD Life Star TULIP",
    productCode: "142L091V01",
    planNumber: "SUD-LI-009",
    providerCode: "SUD",
  },
  {
    productName: "SUD LIFE Wealth Creator",
    productCode: "142L077V01",
    planNumber: "SUD-LI-010",
    providerCode: "SUD",
  },
  {
    productName: "SUD Life Wealth Builder Plan",
    productCode: "142L042V05",
    planNumber: "SUD-LI-011",
    providerCode: "SUD",
  },
  {
    productName: "SUD Life Immediate Annuity Plus",
    productCode: "142N048V08",
    planNumber: "SUD-LI-012",
    providerCode: "SUD",
  },
  {
    productName: "SUD Life Saral Pension",
    productCode: "142N081V02",
    planNumber: "SUD-LI-013",
    providerCode: "SUD",
  },
  {
    productName: "SUD Life Retirement Royale",
    productCode: "142L099V02",
    planNumber: "SUD-LI-014",
    providerCode: "SUD",
  },
  {
    productName: "SUD Life Pension Plus",
    productCode: "142L093V02",
    planNumber: "SUD-LI-015",
    providerCode: "SUD",
  },
  {
    productName: "SUD Life Smart Guaranteed Pension Plan",
    productCode: "142N123V01",
    planNumber: "SUD-LI-016",
    providerCode: "SUD",
  },
  {
    productName: "SUD Life Smart Healthcare",
    productCode: "142N089V01",
    planNumber: "SUD-LI-017",
    providerCode: "SUD",
  },
  {
    productName: "SUD Life Health Assure",
    productCode: "142N098V01",
    planNumber: "SUD-LI-018",
    providerCode: "SUD",
  },
  {
    productName: "SUD Life Smart Income Plan",
    productCode: "142N126V01",
    planNumber: "SUD-LI-019",
    providerCode: "SUD",
  },
  {
    productName: "SUD Life Century Star",
    productCode: "142N075V04",
    planNumber: "SUD-LI-020",
    providerCode: "SUD",
  },
  {
    productName: "SUD Life Guaranteed Money Back Plan",
    productCode: "142N036V06",
    planNumber: "SUD-LI-021",
    providerCode: "SUD",
  },
  {
    productName: "SUD Life Century Plus",
    productCode: "142N074V05",
    planNumber: "SUD-LI-022",
    providerCode: "SUD",
  },
  {
    productName: "SUD Life Samriddhi",
    productCode: "142N057V02",
    planNumber: "SUD-LI-023",
    providerCode: "SUD",
  },
  {
    productName: "POS – SUD Life Sanchay",
    productCode: "142N058V05",
    planNumber: "SUD-LI-024",
    providerCode: "SUD",
  },
  {
    productName: "SUD Life Century Gold",
    productCode: "142N087V04",
    planNumber: "SUD-LI-025",
    providerCode: "SUD",
  },
  {
    productName: "SUD Life Century Royale",
    productCode: "142N083V05",
    planNumber: "SUD-LI-026",
    providerCode: "SUD",
  },
  {
    productName: "SUD Life Fortune Royale",
    productCode: "142N086V03",
    planNumber: "SUD-LI-027",
    providerCode: "SUD",
  },
  {
    productName: "SUD Life Guarantee Royale",
    productCode: "142N122V01",
    planNumber: "SUD-LI-028",
    providerCode: "SUD",
  },
  {
    productName: "SUD Life Century Income",
    productCode: "142N100V03",
    planNumber: "SUD-LI-029",
    providerCode: "SUD",
  },
  {
    productName: "SUD Life Centurion",
    productCode: "142N101V02",
    planNumber: "SUD-LI-030",
    providerCode: "SUD",
  },
  {
    productName: "SUD Life Assured Returns Plan",
    productCode: "142N127V01",
    planNumber: "SUD-LI-031",
    providerCode: "SUD",
  },
  {
    productName: "SUD Life Sampoorna Loan Suraksha Plus",
    productCode: "142N084V02",
    planNumber: "SUD-LI-032",
    providerCode: "SUD",
  },
  {
    productName: "SUD Life Pradhan Mantri Jeevan Jyoti Bima Yojana",
    productCode: "142G047V02",
    planNumber: "SUD-LI-033",
    providerCode: "SUD",
  },
  {
    productName: "SUD Life Group Term Insurance Plus",
    productCode: "142N046V04",
    planNumber: "SUD-LI-034",
    providerCode: "SUD",
  },
  {
    productName: "SUD Life Group Micro Term Insurance Plan",
    productCode: "142N094V01",
    planNumber: "SUD-LI-035",
    providerCode: "SUD",
  },
  {
    productName: "SUD Life Group Retirement Benefit Plan",
    productCode: "142L049V01",
    planNumber: "SUD-LI-036",
    providerCode: "SUD",
  },
  {
    productName: "SUD Life Group Employee Benefit Plus",
    productCode: "142N090V01",
    planNumber: "SUD-LI-037",
    providerCode: "SUD",
  },
  {
    productName: "SUD Life Fortune Plus",
    productCode: "142N124V01",
    planNumber: "SUD-LI-038",
    providerCode: "SUD",
  },
  {
    productName: "SUD Life Aadarsh",
    productCode: "142N054V04",
    planNumber: "SUD-LI-039",
    providerCode: "SUD",
  },

  //INDIAFIRST Products
  {
    productName: "IndiaFirst Life Elite Term Plan",
    productCode: "143N070V01",
    planNumber: "IF-LI-001",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Life Super Protection Plan",
    productCode: "143N075V01",
    planNumber: "IF-LI-002",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Life Plan",
    productCode: "143N007V03",
    planNumber: "IF-LI-003",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Life Saral Jeevan Bima Plan",
    productCode: "143N061V01",
    planNumber: "IF-LI-004",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Life Protect Shield Plus Plan",
    productCode: "143N078V01",
    planNumber: "IF-LI-005",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Life Assured Income For Milestones Plan",
    productCode: "143N101V01",
    planNumber: "IF-LI-006",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Life Guarantee Of Life Dreams Plan",
    productCode: "143N080V03",
    planNumber: "IF-LI-007",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Life Growth of Life Dreams Plus Plan",
    productCode: "143N093V02",
    planNumber: "IF-LI-008",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Life Long Guaranteed Income Plan",
    productCode: "143N054V06",
    planNumber: "IF-LI-009",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Life Fortune Plus Plan",
    productCode: "143N065V03",
    planNumber: "IF-LI-010",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Life Mahajeevan Plus Plan",
    productCode: "143N059V03",
    planNumber: "IF-LI-011",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Life Cash Back Plan",
    productCode: "143N024V05",
    planNumber: "IF-LI-012",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Life Mahajeevan Plan",
    productCode: "143N018V05",
    planNumber: "IF-LI-013",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Simple Benefit Plan",
    productCode: "143N019V03",
    planNumber: "IF-LI-014",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Life Guaranteed Monthly Income Plan",
    productCode: "143N047V01",
    planNumber: "IF-LI-015",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Life Smart Pay Plan",
    productCode: "143N051V04",
    planNumber: "IF-LI-016",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Life Saral Bachat Bima Plan",
    productCode: "143N063V02",
    planNumber: "IF-LI-017",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Life Micro Bachat Plan",
    productCode: "143N052V02",
    planNumber: "IF-LI-018",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Life Guaranteed Benefit Plan",
    productCode: "143N056V09",
    planNumber: "IF-LI-019",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Life CSC Shubhlabh Plan",
    productCode: "143N023V01",
    planNumber: "IF-LI-020",
    providerCode: "INDIAFIRST",
  },
  {
    productName:
      "IndiaFirst Life “INSURANCE KHATA” Plan (MicroInsuranceProduct)",
    productCode: "143N057V03",
    planNumber: "IF-LI-021",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Life POS Cash Back Plan",
    productCode: "143N034V01",
    planNumber: "IF-LI-022",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Life Radiance Smart Invest Plan",
    productCode: "143L067V01",
    planNumber: "IF-LI-023",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Life Wealth Maximizer Plan",
    productCode: "143L029V05",
    planNumber: "IF-LI-024",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Life Money Balance Plan",
    productCode: "143L017V07",
    planNumber: "IF-LI-025",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Smart Save Plan",
    productCode: "143L010V04",
    planNumber: "IF-LI-026",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Life Guaranteed Single Premium Plan",
    productCode: "143N068V04",
    planNumber: "IF-LI-027",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Life Little Champ Plan",
    productCode: "143N035V02",
    planNumber: "IF-LI-028",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst LIfe Smart Retirement Plan",
    productCode: "143L076V01",
    planNumber: "IF-LI-029",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Guaranteed Retirement Plan",
    productCode: "143N026V02",
    planNumber: "IF-LI-030",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Life Guaranteed Annuity Pension Plan",
    productCode: "143N050V07",
    planNumber: "IF-LI-031",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Life Guaranteed Pension Plan",
    productCode: "143N066V05",
    planNumber: "IF-LI-032",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Life Saral Pension Plan",
    productCode: "143N062V01",
    planNumber: "IF-LI-033",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Life Group Living Benefits Plan",
    productCode: "143N040V02",
    planNumber: "IF-LI-034",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Group Term Plan",
    productCode: "143N006V06",
    planNumber: "IF-LI-035",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "Group Credit Life Plus Plan",
    productCode: "143N036V02",
    planNumber: "IF-LI-036",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Group Micro Insurance Plan",
    productCode: "143N053V03",
    planNumber: "IF-LI-037",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Life Group Loan Protect Plan",
    productCode: "143N055V02",
    planNumber: "IF-LI-038",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Life Group HospiCare Plan",
    productCode: "143N039V02",
    planNumber: "IF-LI-039",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Life Group Critical Illness Rider Plan",
    productCode: "143B002V02",
    planNumber: "IF-LI-040",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Life Group Additional Benefit Rider Plan",
    productCode: "143B018V02",
    planNumber: "IF-LI-041",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "Group Disability Rider",
    productCode: "143B004V02",
    planNumber: "IF-LI-042",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "Unit Linked Superannuation Plan",
    productCode: "143L060V01",
    planNumber: "IF-LI-043",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "Superannuation Plan",
    productCode: "143N020V03",
    planNumber: "IF-LI-044",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "New Corporate Benefit Plan",
    productCode: "143N022V02",
    planNumber: "IF-LI-045",
    providerCode: "INDIAFIRST",
  },
  {
    productName: "IndiaFirst Employee Benefit Plan",
    productCode: "143L013V02",
    planNumber: "IF-LI-046",
    providerCode: "INDIAFIRST",
  },

  // TATA_AIA
  {
    productName: "Tata AIA Sampoorna Raksha Promise",
    productCode: "110N176V12",
    planNumber: "TATA001",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Maha Raksha Supreme Select",
    productCode: "110N171V15",
    planNumber: "TATA002",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Smart Sampoorna Raksha Supreme",
    productCode: "110L179V02",
    planNumber: "TATA003",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Fortune Guarantee Plus",
    productCode: "110N158V14",
    planNumber: "TATA004",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Guaranteed Return Insurance Plan",
    productCode: "110N152V15",
    planNumber: "TATA005",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Smart Value Income Plan",
    productCode: "110N162V03",
    planNumber: "TATA006",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Smart Fortune Plus",
    productCode: "110L177V01",
    planNumber: "TATA007",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Smart SIP",
    productCode: "110L174V02",
    planNumber: "TATA008",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Fortune Pro",
    productCode: "110L112V07",
    planNumber: "TATA009",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Smart Pension Secure",
    productCode: "110L182V09",
    planNumber: "TATA010",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Fortune Guarantee Pension",
    productCode: "110N161V13",
    planNumber: "TATA011",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Shubh Family Protect",
    productCode: "110N176V08",
    planNumber: "TATA012",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Fortune Guarantee Supreme",
    productCode: "110N163V12",
    planNumber: "TATA013",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Fortune Guarantee Secure",
    productCode: "110N206V03",
    planNumber: "TATA014",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Life Insurance Fortune Guarantee",
    productCode: "110N120V12",
    planNumber: "TATA015",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Smart Income Plus",
    productCode: "110N126V05",
    planNumber: "TATA016",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA iSIP (i Systematic Insurance Plan)",
    productCode: "110L164V10",
    planNumber: "TATA017",
    providerCode: "TATA_AIA",
  },
  {
    productName:
      "Tata AIA Shubh Muhurat Solution (Combination of Fortune Guarantee Secure + Smart Fortune Plus)",
    productCode: "110N206V02 + 110L177V01",
    planNumber: "TATA018",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Smart Sampoorna Raksha Pro",
    productCode: "110L172V03",
    planNumber: "TATA019",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Life Insurance Wealth Pro",
    productCode: "110L111V05",
    planNumber: "TATA020",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Life Insurance Wealth Maxima",
    productCode: "110L114V05",
    planNumber: "TATA021",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Shubh Flexi Pension Plan",
    productCode: "110N209V02",
    planNumber: "TATA022",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Life Insurance Saral Pension",
    productCode: "110N159V09",
    planNumber: "TATA023",
    providerCode: "TATA_AIA",
  },
  {
    productName: "TATA AIA Fortune Guarantee Retirement Ready",
    productCode: "110N175V04",
    planNumber: "TATA024",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Sampoorna Care",
    productCode: "110N186V01",
    planNumber: "TATA025",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Health SIP",
    productCode: "110L184V01",
    planNumber: "TATA026",
    providerCode: "TATA_AIA",
  },
  {
    productName: "Tata AIA Health Pro",
    productCode: "110L180V01",
    planNumber: "TATA027",
    providerCode: "TATA_AIA",
  },

  {
    productName: "Accident Suraksha",
    productCode: "GCIPAIP18040V021718",
    planNumber: "FG001",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName:
      "Arogya Sanjeevani Policy, Generali Central Insurance Company Limited",
    productCode: "GCIHLIP20160V011920",
    planNumber: "FG002",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Aarogya Bima",
    productCode: "GCIHLIP23052V032223",
    planNumber: "FG003",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Advantage Top-Up",
    productCode: "GCIHLIP23053V032223",
    planNumber: "FG004",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Criticare",
    productCode: "GCIHLIP22104V022122",
    planNumber: "FG005",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Health Suraksha",
    productCode: "GCIHLIP25017V052425",
    planNumber: "FG006",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Hospicash",
    productCode: "GCIHLIP22105V022122",
    planNumber: "FG007",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Varishta Bima",
    productCode: "GCIHLIP24138V042324",
    planNumber: "FG008",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Health Total",
    productCode: "GCIHLIP25037V062425",
    planNumber: "FG009",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName:
      "Saral Suraksha Bima, Generali Central Insurance Company Limited",
    productCode: "GCIPAIP21623V012021",
    planNumber: "FG010",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Sukshma Hospi-Cash (Micro-Insurance Product)",
    productCode: "GCIHMIP22106V032122",
    planNumber: "FG011",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Surakshit Loan Bima",
    productCode: "GCIHLIP22112V032122",
    planNumber: "FG012",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Health Elite",
    productCode: "GCIHLIP22234V012122",
    planNumber: "FG013",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Health Absolute",
    productCode: "GCIHLIP26043V032526",
    planNumber: "FG014",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName:
      "HIV & Disability Suraksha, Generali Central Insurance Company Limited",
    productCode: "GCIHLIP23198V012223",
    planNumber: "FG015",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "D.I.Y HEALTH",
    productCode: "GCIHLIP24025V012324",
    planNumber: "FG016",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Surrogacy Health Cover",
    productCode: "GCIHLIP24147V012324",
    planNumber: "FG017",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Health PowHER",
    productCode: "GCIHLIP24180V012324",
    planNumber: "FG018",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Health Vital",
    productCode: "GCIHLIP25038V022425",
    planNumber: "FG019",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName:
      "Corona Kavach Policy, Generali Central Insurance Company Limited",
    productCode: "GCIHLIP21076V012021",
    planNumber: "FG020",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName:
      "Corona Rakshak Policy, Generali Central Insurance Company Limited",
    productCode: "GCIHLIP21075V012021",
    planNumber: "FG021",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Health Protect – Group",
    productCode: "GCIHLGP22109V032122",
    planNumber: "FG022",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Poorna Suraksha – Group",
    productCode: "GCIHLGP26042V052526",
    planNumber: "FG023",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Group Health Insurance (Revised)",
    productCode: "GCIHLGP21165V022021",
    planNumber: "FG024",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Group Health Insurance (Small and Mid-Size groups)",
    productCode: "GCIHLGP21164V022021",
    planNumber: "FG025",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName:
      "Group Arogya Sanjeevani Policy, Generali Central Insurance Company Limited",
    productCode: "GCIHLGP21490V012021",
    planNumber: "FG026",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Alpa Bima – Group",
    productCode: "GCIHLGP22108V022122",
    planNumber: "FG027",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Advantage Top-Up – Group",
    productCode: "GCIHLGP21154V022021",
    planNumber: "FG028",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Travel Suraksha",
    productCode: "IRDA/NL-HLT/GCI/P-T/V.I/76/13-14",
    planNumber: "FG029",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Shubh Yatra",
    productCode: "GCITIDP20115V011920",
    planNumber: "FG030",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Easy Travel Schengen",
    productCode: "IRDAI/HLT/GCI/P-T/V.I/2/16-17",
    planNumber: "FG031",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Easy Travel Worldwide",
    productCode: "IRDAI/HLT/GCI/P-T/V. I/1/16-17",
    planNumber: "FG032",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Travel Suraksha – Schengen Travel",
    productCode: "IRDA/NL-HLT/GCI/P-T/V.II/78/13-14",
    planNumber: "FG033",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Travel Suraksha Select",
    productCode: "IRDAI/HLT/GCI/P-T/V.I/30/16-17",
    planNumber: "FG034",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Student Suraksha",
    productCode: "GCITIDP21520V022021",
    planNumber: "FG035",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Jet Set Secure",
    productCode: "GCITIOP24165V012324",
    planNumber: "FG036",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Motor Protect Private Car Package Policy",
    productCode: "IRDAN132RPMT0001V06201213",
    planNumber: "FG037",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Motor Protect Two-Wheeler Package Policy",
    productCode: "IRDAN132RPMT0016V03200708",
    planNumber: "FG038",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Motor Protect Commercial Vehicle Package Policy",
    productCode: "IRDAN132RPMT0015V03200708",
    planNumber: "FG039",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Standalone Motor Secure OD Private Car Policy",
    productCode: "IRDAN132RPMT0001V02201920",
    planNumber: "FG040",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Standalone Motor Protect OD Two Wheeler Policy",
    productCode: "IRDAN132RPMT0002V02201920",
    planNumber: "FG041",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Home Secure Policy",
    productCode: "IRDAN132RPMS0005V02200809",
    planNumber: "FG042",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "GC Bharat Griha Raksha",
    productCode: "IRDAN132RPPR0005V02202021",
    planNumber: "FG043",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Standard Fire & Special Perils Policy",
    productCode: "IRDAN132RPPR0002V01200708",
    planNumber: "FG044",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Fire Suraksha Policy",
    productCode: "IRDAN132RPPR0084V01202425",
    planNumber: "FG045",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "GC Bharat Laghu Udyam Suraksha",
    productCode: "IRDAN132RPPR0003V02202021",
    planNumber: "FG046",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "GC Bharat Sookshma Udyam Suraksha",
    productCode: "IRDAN132RPPR0004V02202021",
    planNumber: "FG047",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Marine Insurance – Cargo (Retail)",
    productCode: "IRDAN132RPMR0013V01200708",
    planNumber: "FG048",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Business Suraksha",
    productCode: "IRDAN132RPMS0005V01200910",
    planNumber: "FG049",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Public Liability Policy – Industrial Risks",
    productCode: "IRDAN132RPLB0018V01202223",
    planNumber: "FG050",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Cyber Risks Insurance",
    productCode: "IRDAN132CPLB0023V01201920",
    planNumber: "FG051",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Personal Cyber Risks Policy",
    productCode: "IRDAN132RPLB0001V01202021",
    planNumber: "FG052",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Contractors All Risk Insurance",
    productCode: "IRDAN132RPEN0006V02200708",
    planNumber: "FG053",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Industrial All Risk Policy",
    productCode: "IRDAN132CPPR0004V01200708",
    planNumber: "FG054",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Group Personal Accident (Revised)",
    productCode: "GCIHLGP21545V022021",
    planNumber: "FG055",
    providerCode: "FUTURE_GENERALI",
  },
  {
    productName: "Employee Compensation Insurance Policy",
    productCode: "IRDAN132RPMS0003V02201213",
    planNumber: "FG056",
    providerCode: "FUTURE_GENERALI",
  },
  //CANARA HSBC LIFE INSURANCE
  {
    productName: "Canara HSBC Life Insurance Alpha Wealth",
    productCode: "136L088V02",
    planNumber: "CH001",
    providerCode: "CANARA_HSBC",
  },
  {
    productName: "Canara HSBC Life Insurance EZ Pension",
    productCode: "136L094V01",
    planNumber: "CH002",
    providerCode: "CANARA_HSBC",
  },
  {
    productName: "Canara HSBC Life Insurance Group Advantage Term Plus",
    productCode: "136N077V02",
    planNumber: "CH003",
    providerCode: "CANARA_HSBC",
  },
  {
    productName: "Canara HSBC Life Insurance Group Asset Secure",
    productCode: "136N082V02",
    planNumber: "CH004",
    providerCode: "CANARA_HSBC",
  },
  {
    productName: "Canara HSBC Life Insurance Group Secure",
    productCode: "136N024V07",
    planNumber: "CH005",
    providerCode: "CANARA_HSBC",
  },
  {
    productName: "Canara HSBC Life Insurance Group Secure Plus",
    productCode: "136N090V01",
    planNumber: "CH006",
    providerCode: "CANARA_HSBC",
  },
  {
    productName: "Canara HSBC Life Insurance Group Term Edge Plan",
    productCode: "136N070V02",
    planNumber: "CH007",
    providerCode: "CANARA_HSBC",
  },
  {
    productName: "Canara HSBC Life Insurance Group Traditional Plan",
    productCode: "136N014V03",
    planNumber: "CH008",
    providerCode: "CANARA_HSBC",
  },
  {
    productName: "Canara HSBC Life Insurance Guaranteed Assured Income",
    productCode: "136N097V04",
    planNumber: "CH009",
    providerCode: "CANARA_HSBC",
  },
  {
    productName: "Canara HSBC Life Insurance Guaranteed Fortune Plan",
    productCode: "136N084V04",
    planNumber: "CH010",
    providerCode: "CANARA_HSBC",
  },
  {
    productName: "Canara HSBC Life Insurance Guaranteed Suraksha Kavach",
    productCode: "136N078V03",
    planNumber: "CH011",
    providerCode: "CANARA_HSBC",
  },
  {
    productName: "Canara HSBC Life Insurance IncomeNow",
    productCode: "136N121V01",
    planNumber: "CH012",
    providerCode: "CANARA_HSBC",
  },
  {
    productName: "Canara HSBC Life Insurance Legacy Builder",
    productCode: "136L095V01",
    planNumber: "CH013",
    providerCode: "CANARA_HSBC",
  },
  {
    productName: "Canara HSBC Life Insurance Pension4Life",
    productCode: "136N071V11",
    planNumber: "CH014",
    providerCode: "CANARA_HSBC",
  },
  {
    productName:
      "Canara HSBC Life Insurance Pradhan Mantri Jeevan Jyoti Bima Yojana",
    productCode: "136G046V01",
    planNumber: "CH015",
    providerCode: "CANARA_HSBC",
  },
  {
    productName: "Canara HSBC Life Insurance Promise2Protect",
    productCode: "136N091V01",
    planNumber: "CH016",
    providerCode: "CANARA_HSBC",
  },
  {
    productName: "Canara HSBC Life Insurance Promise4Future",
    productCode: "136N119V01",
    planNumber: "CH017",
    providerCode: "CANARA_HSBC",
  },
  {
    productName: "Canara HSBC Life Insurance Promise4Growth",
    productCode: "136L089V02",
    planNumber: "CH018",
    providerCode: "CANARA_HSBC",
  },
  {
    productName: "Canara HSBC Life Insurance Promise4Growth Plus",
    productCode: "136L093V01",
    planNumber: "CH019",
    providerCode: "CANARA_HSBC",
  },
  {
    productName: "Canara HSBC Life Insurance Promise4Life",
    productCode: "136N120V01",
    planNumber: "CH020",
    providerCode: "CANARA_HSBC",
  },
  {
    productName: "Canara HSBC Life Insurance Promise4Wealth",
    productCode: "136L096V01",
    planNumber: "CH021",
    providerCode: "CANARA_HSBC",
  },
  {
    productName: "Canara HSBC Life Insurance Sampoorna Kavach Plan",
    productCode: "136N022V03",
    planNumber: "CH022",
    providerCode: "CANARA_HSBC",
  },
  {
    productName: "Canara HSBC Life Insurance Saral Jeevan Bima",
    productCode: "136N075V02",
    planNumber: "CH023",
    providerCode: "CANARA_HSBC",
  },
  {
    productName: "Canara HSBC Life Insurance Saral Pension",
    productCode: "136N076V03",
    planNumber: "CH024",
    providerCode: "CANARA_HSBC",
  },
  {
    productName: "Canara HSBC Life Insurance SecureInvest",
    productCode: "136L092V02",
    planNumber: "CH025",
    providerCode: "CANARA_HSBC",
  },
  {
    productName: "Canara HSBC Life Insurance Smart Guaranteed Pension",
    productCode: "136N086V03",
    planNumber: "CH026",
    providerCode: "CANARA_HSBC",
  },
  {
    productName: "Canara HSBC Life Insurance Wealth Edge",
    productCode: "136L085V04",
    planNumber: "CH027",
    providerCode: "CANARA_HSBC",
  },
  {
    productName: "Canara HSBC Life Insurance Young Term Plan",
    productCode: "136N087V03",
    planNumber: "CH028",
    providerCode: "CANARA_HSBC",
  },
  {
    productName: "Canara HSBC Life Insurance iSelect Guaranteed Future",
    productCode: "136N081V07",
    planNumber: "CH029",
    providerCode: "CANARA_HSBC",
  },
  {
    productName: "Canara HSBC Life Insurance iSelect Guaranteed Future Plus",
    productCode: "136N098V04",
    planNumber: "CH030",
    providerCode: "CANARA_HSBC",
  },
  {
    productName: "Canara HSBC Life Insurance iSelect Smart360 Term Plan",
    productCode: "136N080V02",
    planNumber: "CH031",
    providerCode: "CANARA_HSBC",
  },
  //PNB METLIFE
  {
    productName: "PNB MetLife Group Term Life Plus",
    productCode: "117N049V04",
    planNumber: "PM001",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Loan & Life Suraksha",
    productCode: "117N080V03",
    planNumber: "PM002",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Unit Linked Employee Benefit Plan",
    productCode: "117L084V03",
    planNumber: "PM003",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Traditional Employee Benefits Plan",
    productCode: "117N085V02",
    planNumber: "PM004",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Bachat Yojna",
    productCode: "117N120V01",
    planNumber: "PM005",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Retirement Savings Plan",
    productCode: "117N060V01",
    planNumber: "PM006",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Complete Care Plus",
    productCode: "117N093V04",
    planNumber: "PM007",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Pradhan Mantri Jeevan Jyoti Bima Yojana",
    productCode: "117N105V01",
    planNumber: "PM008",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Immediate Annuity Plan",
    productCode: "117N072V01",
    planNumber: "PM009",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Mera Wealth Plan",
    productCode: "117L098V07",
    planNumber: "PM010",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Complete Loan Protection Plan",
    productCode: "117N104V01",
    planNumber: "PM011",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife POS Suraksha",
    productCode: "117N143V01",
    planNumber: "PM012",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Bima Yojna",
    productCode: "117N120V01",
    planNumber: "PM013",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Aajeevan Suraksha Plan",
    productCode: "117N128V01",
    planNumber: "PM014",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Super Saver Plan",
    productCode: "117N131V06",
    planNumber: "PM015",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Guaranteed Future Plan",
    productCode: "117N124V16",
    planNumber: "PM016",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Smart Platinum Plus",
    productCode: "117L125V06",
    planNumber: "PM017",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Mera Term Plan Plus",
    productCode: "117N126V04",
    planNumber: "PM018",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Group Flexi Term Plus",
    productCode: "117N127V01",
    planNumber: "PM019",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Saral Jeevan Bima",
    productCode: "117N129V01",
    planNumber: "PM020",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Century Plan",
    productCode: "117N130V01",
    planNumber: "PM021",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Saral Pension Plan",
    productCode: "117N132V01",
    planNumber: "PM022",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Guaranteed Goal Plan",
    productCode: "117N131V06",
    planNumber: "PM023",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Group Secured Gain",
    productCode: "117N136V01",
    planNumber: "PM024",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Goal Ensuring Multiplier",
    productCode: "117L133V05",
    planNumber: "PM025",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Grand Assured Income Plan",
    productCode: "117N134V08",
    planNumber: "PM026",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Genius Plan",
    productCode: "117N135V04",
    planNumber: "PM027",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife TULIP",
    productCode: "117L137V01",
    planNumber: "PM028",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Smart Invest Pension Plan",
    productCode: "117L138V01",
    planNumber: "PM029",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Long Income For Tomorrow",
    productCode: "117N140V01",
    planNumber: "PM030",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife GROW Plan",
    productCode: "117L145V01",
    planNumber: "PM031",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Smart Goal Ensuring Multiplier",
    productCode: "117L139V02",
    planNumber: "PM032",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Dhan Suraksha Yojna",
    productCode: "117N168V01",
    planNumber: "PM033",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Smart Invest Pension Plan Pro",
    productCode: "117L138V04",
    planNumber: "PM034",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Group Protection Plan",
    productCode: "117N161V01",
    planNumber: "PM035",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife DigiProtect Term Plan",
    productCode: "117N141V01",
    planNumber: "PM036",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife RISE Plan",
    productCode: "117N169V01",
    planNumber: "PM037",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Smart Platinum Pro",
    productCode: "117L142V02",
    planNumber: "PM038",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Term with Unit Linked Insurance Plan (TULIP)",
    productCode: "117L136V03",
    planNumber: "PM039",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Accidental Death Benefit Plus Rider",
    productCode: "117B020V04",
    planNumber: "PM040",
    providerCode: "PNB_METLIFE",
  },
  {
    productName: "PNB MetLife Serious Illness Rider",
    productCode: "117B021V04",
    planNumber: "PM041",
    providerCode: "PNB_METLIFE",
  },
  {
    productName:
      "PNB MetLife Group Accidental Permanent & Total Disability Plus Rider",
    productCode: "117B016V02",
    planNumber: "PM042",
    providerCode: "PNB_METLIFE",
  },
  //AXIS MAX LIFE
  {
    productName: "Axis Max Life Smart Term Plan Plus",
    productCode: "104N127V05",
    planNumber: "AX001",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Smart Secure Plus Plan",
    productCode: "104N118V13",
    planNumber: "AX002",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Smart Term with Additional Returns",
    productCode: "104L128V01",
    planNumber: "AX003",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Flexi Wealth Plan",
    productCode: "104L115V04",
    planNumber: "AX004",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Platinum Wealth Plan",
    productCode: "104L090V07",
    planNumber: "AX005",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Fast Track Super",
    productCode: "104L082V05",
    planNumber: "AX006",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Flexi Wealth Advantage Plan",
    productCode: "104L121V04",
    planNumber: "AX007",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Guaranteed LifeTime Income Plan",
    productCode: "104N076V22",
    planNumber: "AX008",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Saral Pension Plan",
    productCode: "104N119V04",
    planNumber: "AX009",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Online Savings Plan",
    productCode: "104L098V06",
    planNumber: "AX010",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Smart Wealth Advantage Guarantee Plan",
    productCode: "104N124V17",
    planNumber: "AX011",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Smart Wealth Advantage Growth PAR Plan",
    productCode: "104N135V03",
    planNumber: "AX012",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Smart Wealth Income Plan",
    productCode: "104N120V04",
    planNumber: "AX013",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Smart Wealth Plan",
    productCode: "104N116V15",
    planNumber: "AX014",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Savings Advantage Plan",
    productCode: "104N111V04",
    planNumber: "AX015",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Smart Wealth Advantage Guarantee ELITE",
    productCode: "104N138V04",
    planNumber: "AX016",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Smart Value Income & Benefit Enhancer Plan",
    productCode: "104N159V04",
    planNumber: "AX017",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Monthly Income Advantage Plan",
    productCode: "104N091V07",
    planNumber: "AX018",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Secure Earnings & Wellness Advantage Plan",
    productCode: "104N136V03",
    planNumber: "AX019",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Axis Max Life Group Saral Suraksha Plan",
    productCode: "104N114V03",
    planNumber: "AX020",
    providerCode: "AXIS_MAX",
  },
  {
    productName: "Niva Bupa ReAssure",
    productCode: "NBHHLIP23107V022223",
    planNumber: "AX021",
    providerCode: "NIVA_BUPA",
  },
  //RELIANCE NIPPON LIFE (INDUSIND NIPPON LIFE)
  {
    productName: "Reliance Nippon Life Digi-Term Insurance Plan",
    productCode: "121N135V03",
    planNumber: "RN001",
    providerCode: "RELIANCE_NIPPON",
  },
  {
    productName: "Reliance Nippon Life Protection Plus",
    productCode: "121N137V01",
    planNumber: "RN002",
    providerCode: "RELIANCE_NIPPON",
  },
  {
    productName: "Reliance Nippon Life Super Suraksha Plus",
    productCode: "121N144V01",
    planNumber: "RN003",
    providerCode: "RELIANCE_NIPPON",
  },
  {
    productName: "Reliance Nippon Life Saral Jeevan Bima",
    productCode: "121N141V01",
    planNumber: "RN004",
    providerCode: "RELIANCE_NIPPON",
  },
  {
    productName: "Reliance Nippon Life Guaranteed Advantage Income Plan",
    productCode: "121N150V01",
    planNumber: "RN005",
    providerCode: "RELIANCE_NIPPON",
  },
  {
    productName: "Reliance Nippon Life Nishchit Samrudhi Plus",
    productCode: "121N156V03",
    planNumber: "RN006",
    providerCode: "RELIANCE_NIPPON",
  },
  {
    productName: "Reliance Nippon Life Super Endowment Plan",
    productCode: "121N110V02",
    planNumber: "RN007",
    providerCode: "RELIANCE_NIPPON",
  },
  {
    productName: "Reliance Nippon Life Increasing Income Insurance Plan",
    productCode: "121N115V02",
    planNumber: "RN008",
    providerCode: "RELIANCE_NIPPON",
  },
  {
    productName: "Reliance Nippon Life Bluechip Savings Plan",
    productCode: "121N103V01",
    planNumber: "RN009",
    providerCode: "RELIANCE_NIPPON",
  },
  {
    productName: "Reliance Nippon Life Smart Total Advantage Return",
    productCode: "121N128V02",
    planNumber: "RN010",
    providerCode: "RELIANCE_NIPPON",
  },
  {
    productName: "Reliance Nippon Life Fixed Money Back Plan",
    productCode: "121N108V02",
    planNumber: "RN011",
    providerCode: "RELIANCE_NIPPON",
  },
  {
    productName: "Reliance Nippon Life Prosperity Plus",
    productCode: "121L134V03",
    planNumber: "RN012",
    providerCode: "RELIANCE_NIPPON",
  },
  {
    productName: "Reliance Nippon Life Classic Plan II",
    productCode: "121L114V02",
    planNumber: "RN013",
    providerCode: "RELIANCE_NIPPON",
  },
  {
    productName: "Reliance Nippon Life Smart Savings Insurance Plan",
    productCode: "121L117V02",
    planNumber: "RN014",
    providerCode: "RELIANCE_NIPPON",
  },
  {
    productName: "Reliance Nippon Life Premier Wealth Insurance Plan",
    productCode: "121L120V02",
    planNumber: "RN015",
    providerCode: "RELIANCE_NIPPON",
  },
  {
    productName: "Reliance Nippon Life Smart Pension Plan",
    productCode: "121L122V02",
    planNumber: "RN016",
    providerCode: "RELIANCE_NIPPON",
  },
  {
    productName: "Reliance Nippon Life Nishchit Pension",
    productCode: "121N158V03",
    planNumber: "RN017",
    providerCode: "RELIANCE_NIPPON",
  },
  {
    productName: "Reliance Nippon Life Immediate Annuity Plan",
    productCode: "121N126V03",
    planNumber: "RN018",
    providerCode: "RELIANCE_NIPPON",
  },
  {
    productName: "Reliance Nippon Life Saral Pension Plan",
    productCode: "121N141V01",
    planNumber: "RN019",
    providerCode: "RELIANCE_NIPPON",
  },
  {
    productName: "Reliance Nippon Life Child Plan",
    productCode: "121N107V02",
    planNumber: "RN020",
    providerCode: "RELIANCE_NIPPON",
  },
  {
    productName: "Reliance Nippon Life Education Plan",
    productCode: "121N106V02",
    planNumber: "RN021",
    providerCode: "RELIANCE_NIPPON",
  },
  {
    productName: "Reliance Nippon Life Group Term Assurance Plus",
    productCode: "121N093V02",
    planNumber: "RN022",
    providerCode: "RELIANCE_NIPPON",
  },
];
