export const productsData = [
  // LIC Products
  { productName: 'Single Premium Endowment Plan', productCode: '512N283V03', planNumber: '717', providerCode: 'LIC' },
  { productName: 'LIC\'s New Endowment Plan', productCode: '512N277V03', planNumber: '714', providerCode: 'LIC' },
  { productName: 'LIC\'s New Jeevan Anand', productCode: '512N279V03', planNumber: '715', providerCode: 'LIC' },
  { productName: 'LIC Jeevan Lakshya', productCode: '512N297V03', planNumber: '733', providerCode: 'LIC' },
  { productName: 'LIC Jeevan Labh', productCode: '512N304V03', planNumber: '736', providerCode: 'LIC' },
  { productName: 'LIC Amritbaal', productCode: '512N365V02', planNumber: '774', providerCode: 'LIC' },
  { productName: 'LIC Bima Jyoti', productCode: '512N339V03', planNumber: '760', providerCode: 'LIC' },
  { productName: 'LIC Nav Jeevan Shree', productCode: '512N387V02', planNumber: '912', providerCode: 'LIC' },
  { productName: 'LIC Bima Lakshmi', productCode: '512N389V01', planNumber: '881', providerCode: 'LIC' },
  { productName: 'LIC New Jeevan Sathi – Single Premium', productCode: '512N393V01', planNumber: '888', providerCode: 'LIC' },
  { productName: 'LIC New Jeevan Sathi – Limited Premium', productCode: '512N394V01', planNumber: '889', providerCode: 'LIC' },
  { productName: 'LIC Jeevan Umang', productCode: '512N312V03', planNumber: '745', providerCode: 'LIC' },
  { productName: 'LIC Jeevan Utsav', productCode: '512N363V02', planNumber: '771', providerCode: 'LIC' },
  { productName: 'LIC Jeevan Utsav Single Premium', productCode: '512N392V01', planNumber: '883', providerCode: 'LIC' },
  { productName: 'LIC Bima Shree', productCode: '512N316V03', planNumber: '748', providerCode: 'LIC' },
  { productName: 'LIC New Money Back Plan – 20 Years', productCode: '512N280V03', planNumber: '720', providerCode: 'LIC' },
  { productName: 'LIC New Money Back Plan – 25 Years', productCode: '512N278V03', planNumber: '721', providerCode: 'LIC' },
  { productName: 'LIC New Children\'s Money Back Plan', productCode: '512N296V03', planNumber: '732', providerCode: 'LIC' },
  { productName: 'LIC Jeevan Tarun', productCode: '512N299V03', planNumber: '734', providerCode: 'LIC' },

  //Term Assurance Plans
  { productName: 'LIC Digi Term', productCode: '512N356V02', planNumber: '876', providerCode: 'LIC' },
  { productName: 'LIC Digi Credit Life', productCode: '512N358V01', planNumber: '878', providerCode: 'LIC' },
  { productName: 'LIC Yuva Credit Life', productCode: '512N357V01', planNumber: '877', providerCode: 'LIC' },
  { productName: 'LIC Yuva Term', productCode: '512N355V02', planNumber: '875', providerCode: 'LIC' },
  { productName: 'LIC New Tech-Term', productCode: '512N351V02', planNumber: '954', providerCode: 'LIC' },
  { productName: 'LIC New Jeevan Amar', productCode: '512N350V02', planNumber: '955', providerCode: 'LIC' },
  { productName: 'LIC Saral Jeevan Bima', productCode: '512N341V01', planNumber: '859', providerCode: 'LIC' },
  { productName: 'LIC Bima Kavach', productCode: '512N360V01', planNumber: '887', providerCode: 'LIC' },

  //Pension Plans
  { productName: 'LIC New Pension Plus', productCode: '512L347V01', planNumber: '867', providerCode: 'LIC' },
  { productName: 'LIC Jeevan Akshay VII', productCode: '512N337V07', planNumber: '857', providerCode: 'LIC' },
  { productName: 'LIC New Jeevan Shanti', productCode: '512N338V08', planNumber: '858', providerCode: 'LIC' },
  { productName: 'LIC Saral Pension', productCode: '512N342V05', planNumber: '862', providerCode: 'LIC' },
  { productName: 'LIC Smart Pension', productCode: '512N386V01', planNumber: '879', providerCode: 'LIC' },

  //Unit Linked Plans
  { productName: 'LIC Index Plus', productCode: '512L354V01', planNumber: '873', providerCode: 'LIC' },
  { productName: 'LIC Nivesh Plus', productCode: '512L317V02', planNumber: '849', providerCode: 'LIC' },
  { productName: 'LIC SIIP (Systematic Investment Insurance Plan)', productCode: '512L334V02', planNumber: '752', providerCode: 'LIC' },
  { productName: 'LIC Protection Plus', productCode: '512L361V01', planNumber: '886', providerCode: 'LIC' },

  //Micro Insurance Plans
  { productName: 'LIC Micro Bachat', productCode: '512N329V03', planNumber: '751', providerCode: 'LIC' },
  { productName: 'LIC Jan Suraksha', productCode: '512N388V01', planNumber: '880', providerCode: 'LIC' },

  //Plans Withdrawn during 2026-27
  { productName: 'LIC\'s Nav Jeevan Shree - Single Premium', productCode: '512N390V01', planNumber: '911', providerCode: 'LIC' },

  // Plans Withdrawn during 2025-26
  { productName: 'LIC\'s Jeevan Akshay VII', productCode: '512N337V06', planNumber: '857', providerCode: 'LIC' },
  { productName: 'lIC\'s New Jeevan Shanti', productCode: '512N338V07', planNumber: '758', providerCode: 'LIC' },
  { productName: 'LIC\'s Nav Jeevan Shree', productCode: '512N387V01', planNumber: '912', providerCode: 'LIC' },
  { productName: 'LIC\'s New Endowment Plus', productCode: '512L301V03', planNumber: '735', providerCode: 'LIC' },
  { productName: 'LIC\'s Bima Ratna', productCode: '512N345V02', planNumber: '764', providerCode: 'LIC' },
  { productName: 'LIC\'s Jeevan Azad', productCode: '512N348V02', planNumber: '768', providerCode: 'LIC' },

  //Plans Withdrawn during 2024-25
  { productName: 'LIC\'s Dhan Vriddhi', productCode: '512N362V02', planNumber: '869', providerCode: 'LIC' },
  { productName: 'LIC\'s New Jeevan Shanti', productCode: '512N338V06', planNumber: '858', providerCode: 'LIC' },
  { productName: 'LIC\'s Jeevan Dhara - II', productCode: '512N364V01', planNumber: '872', providerCode: 'LIC' },
  { productName: 'LIC\'s Saral Pension', productCode: '512N342V04', planNumber: '862', providerCode: 'LIC' },
  { productName: 'LIC\'s Jeevan Akshay VII', productCode: '512N337V06', planNumber: '857', providerCode: 'LIC' },
  { productName: 'LIC\'s Nivesh Plus', productCode: '512L317V01', planNumber: '849', providerCode: 'LIC' },
  { productName: 'LIC\'s SIIP', productCode: '512L334V01', planNumber: '852', providerCode: 'LIC' },
  { productName: 'LIC\'s New Pension Plus', productCode: '512L347V01', planNumber: '867', providerCode: 'LIC' },
  { productName: 'LIC\'s Index Plus', productCode: '512L354V01', planNumber: '873', providerCode: 'LIC' },
  { productName: 'LIC\'s New Endowment Plus', productCode: '512L301V02', planNumber: '935', providerCode: 'LIC' },
  { productName: 'LIC\'s Bhagya Lakshmi Plan', productCode: '512N292V04', planNumber: '939', providerCode: 'LIC' },
  { productName: 'LIC\'s New Jeevan Mangal Plan', productCode: '512N287V04', planNumber: '940', providerCode: 'LIC' },
  { productName: 'LIC\'s Micro Bachat', productCode: '512N329V02', planNumber: '951', providerCode: 'LIC' },
  { productName: 'LIC\'s Bima Ratna', productCode: '512N345V02', planNumber: '860', providerCode: 'LIC' },
  { productName: 'LIC\'s Bima Ratna', productCode: '512N345V01', planNumber: '864', providerCode: 'LIC' },
  { productName: 'LIC\'s Dhan Sanchay', productCode: '512N346V01', planNumber: '865', providerCode: 'LIC' },
  { productName: 'LIC\'s Jeevan Azad', productCode: '512N348V01', planNumber: '868', providerCode: 'LIC' },
  { productName: 'LIC\'s New Endowment Plan', productCode: '512N277V02', planNumber: '914', providerCode: 'LIC' },
  { productName: 'LIC\'s Jeevan Lakshya', productCode: '512N297V02', planNumber: '933', providerCode: 'LIC' },
  { productName: 'LIC\'s Jeevan Labh', productCode: '512N304V03', planNumber: '936', providerCode: 'LIC' },
  { productName: 'LIC\'s Aadhaar Stambh', productCode: '512N310V03', planNumber: '943', providerCode: 'LIC' },
  { productName: 'LIC\'s Aadhaar Shila', productCode: '512N309V03', planNumber: '944', providerCode: 'LIC' },
  { productName: 'LIC\'s Jeevan Utsav', productCode: '512N363V01', planNumber: '871', providerCode: 'LIC' },
  { productName: 'LIC\'s Jeevan Umang', productCode: '512N312V02', planNumber: '945', providerCode: 'LIC' },
  { productName: 'LIC\'s Dhan Rekha', productCode: '512N343V01', planNumber: '863', providerCode: 'LIC' },
  { productName: 'LIC\'s New Bima Bachat', productCode: '512N284V02', planNumber: '916', providerCode: 'LIC' },
  { productName: 'LIC\'s New Money Back Plan – 20 Years', productCode: '512N280V02', planNumber: '920', providerCode: 'LIC' },
  { productName: 'LIC\'s New Money Back Plan – 25 Years', productCode: '512N278V02', planNumber: '921', providerCode: 'LIC' },
  { productName: 'LIC\'s New Children\'s Money Back Plan', productCode: '512N296V02', planNumber: '932', providerCode: 'LIC' },
  { productName: 'LIC\'s Jeevan Tarun', productCode: '512N299V02', planNumber: '934', providerCode: 'LIC' },
  { productName: 'LIC\'s Jeevan Shiromani', productCode: '512N315V02', planNumber: '947', providerCode: 'LIC' },
  { productName: 'LIC\'s Bima Shree', productCode: '512N316V02', planNumber: '948', providerCode: 'LIC' },
  { productName: 'LIC\'s New Tech-Term', productCode: '512N351V01', planNumber: '954', providerCode: 'LIC' },
  { productName: 'LIC\'s New Jeevan Amar', productCode: '512N350V01', planNumber: '955', providerCode: 'LIC' },
  { productName: 'LIC\'s Linked Accidental Death Benefit Rider', productCode: '512A211V02', planNumber: '-', providerCode: 'LIC' },
  { productName: 'LIC\'s Accident Benefit Rider', productCode: '512B203V03', planNumber: '-', providerCode: 'LIC' },
  { productName: 'LIC\'s Premium Waiver Benefit Rider', productCode: '512B204V03', planNumber: '-', providerCode: 'LIC' },
  { productName: 'LIC\'s New Critical Illness Benefit Rider', productCode: '512A212V02', planNumber: '-', providerCode: 'LIC' },
  { productName: 'LIC\'s New Term Assurance Rider', productCode: '512B210V01', planNumber: '-', providerCode: 'LIC' },
  { productName: 'LIC\'s Premium Waiver Benefit Rider (with Auto Cover)', productCode: 'Not Available (Old Rider Version)', planNumber: '-', providerCode: 'LIC' },
  { productName: 'LIC\'s Cancer Cover', productCode: '-', planNumber: '905', providerCode: 'LIC' },
  { productName: 'LIC\'s Arogya Rakshak', productCode: '-', planNumber: '906', providerCode: 'LIC' },
  { productName: 'LIC\'s Jeevan Akshay VII', productCode: '512N337V05', planNumber: '857', providerCode: 'LIC' },
  { productName: 'LIC\'s New Jeevan Shanti', productCode: '512N338V05', planNumber: '858', providerCode: 'LIC' },
  { productName: 'LIC\'s Jeevan Kiran', productCode: '512N353V01', planNumber: '870', providerCode: 'LIC' },
  { productName: 'LIC\'s Digi Term', productCode: '512N356V01', planNumber: '876', providerCode: 'LIC' },
  { productName: 'LIC\'s Yuva Term', productCode: '512N355V01', planNumber: '875', providerCode: 'LIC' },
  //Plans Withdrawn during 2023-24
  { productName: 'LIC\'s Cancer Cover', productCode: '512N314V02', planNumber: '905', providerCode: 'LIC' },
  { productName: 'LIC\'s Dhan Varsha', productCode: '512N349V01', planNumber: '866', providerCode: 'LIC' },
  { productName: 'LIC\'s New One Year Renewable Group Term Assurance Plan-I', productCode: '512N275V02', planNumber: '-', providerCode: 'LIC' },
  { productName: 'LIC\'s New One Year Renewal Group Term Assurance Plan-II', productCode: '512N276V02', planNumber: '-', providerCode: 'LIC' },

  //Plans Withdrawn during 2022-23
  { productName: 'LIC\'s Tech Term', productCode: '512N333V01', planNumber: '854', providerCode: 'LIC' },
  { productName: 'LIC\'s Jeevan Amar', productCode: '512N332V01', planNumber: '855', providerCode: 'LIC' },
  { productName: 'LIC\'s Jeevan Akshay VII', productCode: '512N337V02', planNumber: '857', providerCode: 'LIC' },
  { productName: 'Pradhan Mantri Vaya Vandana Yojana (Modified-2020)', productCode: '512G336V01', planNumber: '856', providerCode: 'LIC' },
  { productName: 'LIC\'s Jeevan Akshay VII', productCode: '512N337V04', planNumber: '857', providerCode: 'LIC' },
  { productName: 'LIC\'s New Jeevan Shanti', productCode: '512N338V02', planNumber: '858', providerCode: 'LIC' },
  { productName: 'LIC\'s Bachat Plus', productCode: '512N340V01', planNumber: '861', providerCode: 'LIC' },
  { productName: 'LIC\'s Saral Pension', productCode: '512N342V02', planNumber: '862', providerCode: 'LIC' },
  { productName: 'LIC\'s Saral Pension', productCode: '512N342V03', planNumber: '862', providerCode: 'LIC' },
  { productName: 'LIC\'s Aadhaar Stambh', productCode: '512N310V02', planNumber: '943', providerCode: 'LIC' },
  { productName: 'LIC\'s Aadhaar Shila', productCode: '512N309V02', planNumber: '944', providerCode: 'LIC' },

  //Plans Withdrawn during 2021-22
  { productName: 'LIC\'s Jeevan Akshay VII', productCode: '512N337V01', planNumber: '857', providerCode: 'LIC' },
  { productName: 'LIC\'s New Jeevan Shanti', productCode: '512N338V04', planNumber: '858', providerCode: 'LIC' },
  { productName: 'LIC\'s Bima Jyoti', productCode: '512N339V01', planNumber: '860', providerCode: 'LIC' },
  { productName: 'LIC\'s Saral Pension', productCode: '512N342V01', planNumber: '862', providerCode: 'LIC' },
  { productName: 'LIC\'s Jeevan Arogya', productCode: '512N266V03', planNumber: '904', providerCode: 'LIC' },
  { productName: 'LIC\'s Bhagya Lakshmi', productCode: '512N292V03', planNumber: '939', providerCode: 'LIC' },
  { productName: 'LIC\'s New Jeevan Mangal', productCode: '512N287V03', planNumber: '940', providerCode: 'LIC' },

  //Plans Withdrawn during 2020-21
  { productName: 'LIC\'s Jeevan Shanti', productCode: '512N328V01', planNumber: '850', providerCode: 'LIC' },
  { productName: 'LIC\'s Jeevan Arogya', productCode: '512N266V02', planNumber: '904', providerCode: 'LIC' },
  { productName: 'LIC\'s Cancer Cover', productCode: '512N314V02', planNumber: '905', providerCode: 'LIC' },
  { productName: 'LIC\'s New Critical Illness Benefit Rider', productCode: '512A212V01', planNumber: '-', providerCode: 'LIC' },

  //Plans Withdrawn during 2019-20
  { productName: 'LIC\'s Jeevan Akshay_VI', productCode: '512N234V06', planNumber: '189', providerCode: 'LIC' },
  { productName: 'LIC\'s New Endowment Plan', productCode: '512N277V01', planNumber: '814', providerCode: 'LIC' },
  { productName: 'LIC\'s New Jeevan Anand', productCode: '512N279V01', planNumber: '815', providerCode: 'LIC' },
  { productName: 'LIC\'s New Bima Bachat', productCode: '512N284V01', planNumber: '816', providerCode: 'LIC' },
  { productName: 'LIC\'s Single Premium Endowment Plan', productCode: '512N283V01', planNumber: '817', providerCode: 'LIC' },
  { productName: 'LIC\'s New Jeevan Nidhi', productCode: '512N271V02', planNumber: '818', providerCode: 'LIC' },
  { productName: 'LIC\'s New Money Back Plan – 20 Years', productCode: '512N280V01', planNumber: '820', providerCode: 'LIC' },
  { productName: 'LIC\'s New Money Back Plan – 25 Years', productCode: '512N278V01', planNumber: '821', providerCode: 'LIC' },
  { productName: 'LIC\'s Anmol Jeevan II', productCode: '512N285V01', planNumber: '822', providerCode: 'LIC' },
  { productName: 'LIC\'s Amulya Jeevan II', productCode: '512N286V01', planNumber: '823', providerCode: 'LIC' },
  { productName: 'LIC\'s e-Term', productCode: '512N288V01', planNumber: '825', providerCode: 'LIC' },
  { productName: 'LIC\'s Jeevan Rakshak', productCode: '512N289V01', planNumber: '827', providerCode: 'LIC' },
  { productName: 'LIC\'s Limited Premium Endowment Plan', productCode: '512N293V01', planNumber: '830', providerCode: 'LIC' },
  { productName: 'LIC\'s New Children\'s Money Back', productCode: '512N296V01', planNumber: '832', providerCode: 'LIC' },
  { productName: 'LIC\'s Jeevan Lakshya', productCode: '512N297V01', planNumber: '833', providerCode: 'LIC' },
  { productName: 'LIC\'s Jeevan Tarun', productCode: '512N299V01', planNumber: '834', providerCode: 'LIC' },
  { productName: 'LIC\'s New Endowment Plus', productCode: '512L301V01', planNumber: '835', providerCode: 'LIC' },
  { productName: 'LIC\'s Jeevan Labh', productCode: '512N304V01', planNumber: '836', providerCode: 'LIC' },
  { productName: 'LIC\'s Jeevan Pragati', productCode: '512N306V01', planNumber: '838', providerCode: 'LIC' },
  { productName: 'LIC\'s Bhagya Lakshmi', productCode: '512N292V02', planNumber: '839', providerCode: 'LIC' },
  { productName: 'LIC\'s New Jeevan Mangal', productCode: '512N287V02', planNumber: '840', providerCode: 'LIC' },
  { productName: 'Pradhan Mantri Vaya Vandana Yojana', productCode: '512G311V02', planNumber: '842', providerCode: 'LIC' },
  { productName: 'LIC\'s Jeevan Shiromani', productCode: '512N315V01', planNumber: '847', providerCode: 'LIC' },
  { productName: 'LIC\'s Bima Shree', productCode: '512N316V01', planNumber: '848', providerCode: 'LIC' },
  { productName: 'LIC\'s Jeevan Shanti', productCode: '512N328V02', planNumber: '850', providerCode: 'LIC' },
  { productName: 'LIC\'s New Jeevan Amar', productCode: '512N337V01', planNumber: '853', providerCode: 'LIC' },
  { productName: 'LIC\'s Premium Waiver Benefit Rider', productCode: '512B204V02', planNumber: '-', providerCode: 'LIC' },

  //Plans Withdrawn during 2018-19
  { productName: 'Pradhan Mantri Vaya Vandana Yojana', productCode: '512G311V01', planNumber: '842', providerCode: 'LIC' },
  { productName: 'LIC\'s Aadhaar Stambh', productCode: '512N310V01', planNumber: '843', providerCode: 'LIC' },
  { productName: 'LIC\'s Aadhaar Shila', productCode: '512N309V01', planNumber: '844', providerCode: 'LIC' },
  { productName: 'LIC\'s Jeevan Umang', productCode: '512N312V01', planNumber: '845', providerCode: 'LIC' },
  { productName: 'LIC\'s Jeevan Utkarsh', productCode: '512N313V01', planNumber: '846', providerCode: 'LIC' },

  // Aditya Birla Sun Life Insurance Products
  { productName: 'ABSLI DigiShield Plan', productCode: '109N108V02', planNumber: 'ABSLI001', providerCode: 'ABSLI' },
  { productName: 'ABSLI Salaried Term Plan', productCode: '109N126V01', planNumber: 'ABSLI002', providerCode: 'ABSLI' },
  { productName: 'ABSLI Super Term Plan', productCode: '109N115V00', planNumber: 'ABSLI003', providerCode: 'ABSLI' },
  { productName: 'ABSLI Life Shield Plan', productCode: '109N147V01', planNumber: 'ABSLI004', providerCode: 'ABSLI' },
  { productName: 'ABSLI Saral Jeevan Bima', productCode: '109N112V03', planNumber: 'ABSLI005', providerCode: 'ABSLI' },
  { productName: 'ABSLI Protect @ Ease', productCode: '109N113V00', planNumber: 'ABSLI006', providerCode: 'ABSLI' },
  { productName: 'ABSLI Assured Income Plan', productCode: '109N080V01', planNumber: 'ABSLI007', providerCode: 'ABSLI' },
  { productName: 'ABSLI Assured Savings Plan', productCode: '109N097V02', planNumber: 'ABSLI008', providerCode: 'ABSLI' },
  { productName: 'ABSLI Nishchit Aayush Plan', productCode: '109N129V01', planNumber: 'ABSLI009', providerCode: 'ABSLI' },
  { productName: 'ABSLI Guaranteed Milestone Plan', productCode: '109N136V02', planNumber: 'ABSLI010', providerCode: 'ABSLI' },
  { productName: 'ABSLI Vision LifeIncome Plus', productCode: '109N105V02', planNumber: 'ABSLI011', providerCode: 'ABSLI' },
  { productName: 'ABSLI Vision Endowment Plus', productCode: '109N077V02', planNumber: 'ABSLI012', providerCode: 'ABSLI' },
  { productName: 'ABSLI Vision Star Plan', productCode: '109N079V02', planNumber: 'ABSLI013', providerCode: 'ABSLI' },
  { productName: 'ABSLI Income Suraksha Plan', productCode: '109N099V01', planNumber: 'ABSLI014', providerCode: 'ABSLI' },
  { productName: 'ABSLI Bachat Plus', productCode: '109N119V00', planNumber: 'ABSLI015', providerCode: 'ABSLI' },
  { productName: 'ABSLI Anmol Akshaya Plan', productCode: '109N149V01', planNumber: 'ABSLI016', providerCode: 'ABSLI' },
  { productName: 'ABSLI Sukanya Kanya Plan', productCode: '109N083V01', planNumber: 'ABSLI017', providerCode: 'ABSLI' },
  { productName: 'ABSLI Vision MoneyBack Plus Plan', productCode: '109N095V02', planNumber: 'ABSLI018', providerCode: 'ABSLI' },
  { productName: 'ABSLI Monthly Income Plan', productCode: 'To Be Verified', planNumber: 'ABSLI019', providerCode: 'ABSLI' },
  { productName: 'ABSLI Dream Endowment Plan', productCode: '109N076V02', planNumber: 'ABSLI020', providerCode: 'ABSLI' },
  { productName: 'ABSLI SecurePlus Plan', productCode: '109N094V02', planNumber: 'ABSLI021', providerCode: 'ABSLI' },
  { productName: 'ABSLI Wealth Smart Plus', productCode: '109L082V01', planNumber: 'ABSLI022', providerCode: 'ABSLI' },
  { productName: 'ABSLI Salaried Suraksha ULIP', productCode: '109L090V02', planNumber: 'ABSLI023', providerCode: 'ABSLI' },
  { productName: 'ABSLI Fortune Wealth Plan', productCode: '109L090V02', planNumber: 'ABSLI024', providerCode: 'ABSLI' },
  { productName: 'ABSLI Platinum Gain Plan', productCode: '109L072V02', planNumber: 'ABSLI025', providerCode: 'ABSLI' },
  { productName: 'ABSLI Wealth Aspire Plan', productCode: '109L067V02', planNumber: 'ABSLI026', providerCode: 'ABSLI' },
  { productName: 'ABSLI Wealth Secure Plan', productCode: '109L070V02', planNumber: 'ABSLI027', providerCode: 'ABSLI' },
  { productName: 'ABSLI Wealth Max Plan', productCode: '109L071V02', planNumber: 'ABSLI028', providerCode: 'ABSLI' },
  { productName: 'ABSLI Wealth Infinia', productCode: '109L069V02', planNumber: 'ABSLI029', providerCode: 'ABSLI' },
  { productName: 'ABSLI Wealth Assure Plus', productCode: '109L134V01', planNumber: 'ABSLI030', providerCode: 'ABSLI' },
  { productName: 'ABSLI Wealth Creator Plan', productCode: '109L063V02', planNumber: 'ABSLI031', providerCode: 'ABSLI' },
  { productName: 'ABSLI Wealth Premier Plan', productCode: '109L066V02', planNumber: 'ABSLI032', providerCode: 'ABSLI' },
  { productName: 'ABSLI Dream Plan', productCode: '109L135V01', planNumber: 'ABSLI033', providerCode: 'ABSLI' },
  { productName: 'ABSLI Flexi Save Plus Plan', productCode: '109L075V02', planNumber: 'ABSLI034', providerCode: 'ABSLI' },
  { productName: 'ABSLI Wealth Plus', productCode: '109L068V02', planNumber: 'ABSLI035', providerCode: 'ABSLI' },
  { productName: 'ABSLI Wealth Protect Plan', productCode: '109L058V00', planNumber: 'ABSLI036', providerCode: 'ABSLI' },
  { productName: 'ABSLI Wealth 25 Plan', productCode: '109L062V02', planNumber: 'ABSLI037', providerCode: 'ABSLI' },
  { productName: 'ABSLI Wealth Advantage Plan', productCode: '109L074V02', planNumber: 'ABSLI038', providerCode: 'ABSLI' },
  { productName: 'ABSLI Wealth Insurance Plan', productCode: '109L106V02', planNumber: 'ABSLI039', providerCode: 'ABSLI' },
  { productName: 'ABSLI Empower Pension ULIP Plan', productCode: '109L065V02', planNumber: 'ABSLI040', providerCode: 'ABSLI' },
  { productName: 'ABSLI Future Gain Plan', productCode: '109L078V02', planNumber: 'ABSLI041', providerCode: 'ABSLI' },
  { productName: 'ABSLI Vision Plan', productCode: '109L037V03', planNumber: 'ABSLI042', providerCode: 'ABSLI' },
  { productName: 'ABSLI Foresight Plan', productCode: '109L038V02', planNumber: 'ABSLI043', providerCode: 'ABSLI' },
  { productName: 'ABSLI Children\'s Future Plan', productCode: '109L042V02', planNumber: 'ABSLI044', providerCode: 'ABSLI' },
  { productName: 'ABSLI Children\'s Dream Plan', productCode: '109N067V03', planNumber: 'ABSLI045', providerCode: 'ABSLI' },
  { productName: 'ABSLI Children\'s Future Solutions Plan', productCode: '109N086V03', planNumber: 'ABSLI046', providerCode: 'ABSLI' },
  { productName: 'ABSLI Guaranteed Annuity Plus', productCode: '109N132V17', planNumber: 'ABSLI047', providerCode: 'ABSLI' },
  { productName: 'ABSLI Empower Pension Plan', productCode: '109L078V03', planNumber: 'ABSLI048', providerCode: 'ABSLI' },
  { productName: 'ABSLI Saral Pension', productCode: '109N144V02', planNumber: 'ABSLI049', providerCode: 'ABSLI' },
  { productName: 'ABSLI Nishchit Pension Plan', productCode: '109N151V04', planNumber: 'ABSLI050', providerCode: 'ABSLI' },
  { productName: 'ABSLI Immediate Annuity Plan', productCode: '109N056V06', planNumber: 'ABSLI051', providerCode: 'ABSLI' },
  { productName: 'ABSLI Pension Plus Plan', productCode: '109L026V04', planNumber: 'ABSLI052', providerCode: 'ABSLI' },
  { productName: 'ABSLI Retirement Fund Plan', productCode: '109N043V02', planNumber: 'ABSLI053', providerCode: 'ABSLI' },
  { productName: 'ABSLI Dream Pension Plan', productCode: '109N050V02', planNumber: 'ABSLI054', providerCode: 'ABSLI' },
  { productName: 'ABSLI Empower Pension ULIP Plan', productCode: '109L094V02', planNumber: 'ABSLI055', providerCode: 'ABSLI' },
  { productName: 'ABSLI SecureLife Pension Plan', productCode: '109L016V03', planNumber: 'ABSLI056', providerCode: 'ABSLI' },
  { productName: 'ABSLI Flexi SecureLife Retirement Plan', productCode: '109L022V03', planNumber: 'ABSLI057', providerCode: 'ABSLI' },
  { productName: 'ABSLI Forever Life Pension Plan', productCode: '109N046V03', planNumber: 'ABSLI058', providerCode: 'ABSLI' },
  { productName: 'ABSLI Sunrise Pension Plan', productCode: '109N052V02', planNumber: 'ABSLI059', providerCode: 'ABSLI' },
  { productName: 'ABSLI Immediate Annuity Plan', productCode: 'To Verify', planNumber: 'ABSLI060', providerCode: 'ABSLI' },
  { productName: 'Group Protection Solutions', productCode: 'To Verify', planNumber: 'ABSLI061', providerCode: 'ABSLI' },
  { productName: 'Group Credit Life Plan', productCode: '109N087V01', planNumber: 'ABSLI062', providerCode: 'ABSLI' },
  { productName: 'Group Gratuity Plan', productCode: '109N061V01', planNumber: 'ABSLI063', providerCode: 'ABSLI' },
  { productName: 'Group Superannuation Plan', productCode: '109N060V01', planNumber: 'ABSLI064', providerCode: 'ABSLI' },
  { productName: 'Group Leave Encashment Plan', productCode: 'To verify', planNumber: 'ABSLI065', providerCode: 'ABSLI' },
  { productName: 'Group Term Insurance Plan', productCode: '109N088V01', planNumber: 'ABSLI066', providerCode: 'ABSLI' },

  
  // ICICI Pru Products
    { productName: 'ICICI Pru Signature Secure', productCode: '105L210V01', planNumber: 'ICICIPRU001', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Protect N Gain Whole Life', productCode: '105L208V01', planNumber: 'ICICIPRU002', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru iProtect Care', productCode: '105N209V02', planNumber: 'ICICIPRU003', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru SmartKid 360', productCode: '105N225V02', planNumber: 'ICICIPRU004', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Wealth Elite Pro', productCode: '105L207V01', planNumber: 'ICICIPRU005', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Wealth Forever', productCode: '105N206V01', planNumber: 'ICICIPRU006', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru iProtect Smart Plus', productCode: '105N205V05', planNumber: 'ICICIPRU007', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Gift Select', productCode: '105N233V05', planNumber: 'ICICIPRU008', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Smart Goal Assure', productCode: '105L199V01', planNumber: 'ICICIPRU009', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru iProtect Super', productCode: '105N197V03', planNumber: 'ICICIPRU010', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Saral Jeevan Bima', productCode: '105N183V03', planNumber: 'ICICIPRU011', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI PRU Signature Assure', productCode: '105L196V01', planNumber: 'ICICIPRU012', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru iProtect Smart Return of Premium', productCode: '105N195V02', planNumber: 'ICICIPRU013', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Guaranteed Pension Plan', productCode: '105N181V05', planNumber: 'ICICIPRU014', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Signature Pension', productCode: '105L194V03', planNumber: 'ICICIPRU015', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru iProtect Supreme', productCode: '105N193V03', planNumber: 'ICICIPRU016', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Savings Suraksha', productCode: '105N135V05', planNumber: 'ICICIPRU017', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Assured Savings Insurance Plan', productCode: '105N144V13', planNumber: 'ICICIPRU018', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru iProtect Smart', productCode: '105N151V16', planNumber: 'ICICIPRU019', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Sarv Jana Suraksha', productCode: '105N081V06', planNumber: 'ICICIPRU020', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Future Perfect', productCode: '105N153V05', planNumber: 'ICICIPRU021', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Life Time Classic', productCode: '105L155V10', planNumber: 'ICICIPRU022', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru1 Wealth', productCode: '105L175V10', planNumber: 'ICICIPRU023', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Signature', productCode: '105L177V12', planNumber: 'ICICIPRU024', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Guaranteed Income For Tomorrow', productCode: '105N182V13', planNumber: 'ICICIPRU025', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Saral Pension', productCode: '105N184V09', planNumber: 'ICICIPRU026', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Guaranteed Income For Tomorrow (Long-term)', productCode: '105N185V17', planNumber: 'ICICIPRU027', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Guaranteed Pension Plan Flexi', productCode: '105N185V03', planNumber: 'ICICIPRU028', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Sukh Samruddhi', productCode: '105N188V03', planNumber: 'ICICIPRU029', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Ezy Grow', productCode: '105L202V02', planNumber: 'ICICIPRU030', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Gold', productCode: '105N190V06', planNumber: 'ICICIPRU031', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Protect N Gain', productCode: '105L191V06', planNumber: 'ICICIPRU032', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru GIFT Pro', productCode: '105N201V05', planNumber: 'ICICIPRU033', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Gold Pension Savings', productCode: '105N202V03', planNumber: 'ICICIPRU034', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Platinum', productCode: '105L192V04', planNumber: 'ICICIPRU035', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Wish', productCode: '105N198V01', planNumber: 'ICICIPRU036', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Smart Insurance Plan Plus', productCode: '105L204V03', planNumber: 'ICICIPRU037', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru GIFT Assure', productCode: '105N224V02', planNumber: 'ICICIPRU038', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Group Unit Linked Superannuation Plus', productCode: '105L200V02', planNumber: 'ICICIPRU039', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Immediate Annuity', productCode: '105N009V26', planNumber: 'ICICIPRU040', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Group Unit Linked Superannuation', productCode: '105L136V03', planNumber: 'ICICIPRU041', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Group Suraksha Plus Superannuation', productCode: '105N148V03', planNumber: 'ICICIPRU042', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Group Unit Linked Employee Benefit Plan', productCode: '105L137V04', planNumber: 'ICICIPRU043', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Group Insurance Scheme for Pradhan Mantri Jeevan Jyoti Bima Yojana', productCode: '105G146V02', planNumber: 'ICICIPRU044', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Group Suraksha Plus', productCode: '105N147V03', planNumber: 'ICICIPRU045', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Group Term Plus', productCode: '105N119V08', planNumber: 'ICICIPRU046', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Group Loan Secure', productCode: '105N152V04', planNumber: 'ICICIPRU047', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Shubh Raksha Credit', productCode: '105N159V03', planNumber: 'ICICIPRU048', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Shubh Raksha One', productCode: '105N158V03', planNumber: 'ICICIPRU049', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Shubh Raksha Life', productCode: '105N160V03', planNumber: 'ICICIPRU050', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Super Protect - Credit', productCode: '105N176V03', planNumber: 'ICICIPRU051', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Super Protect life', productCode: '105N180V02', planNumber: 'ICICIPRU052', providerCode: 'ICICI_PRU' },
    { productName: 'ICICI Pru Group Nischit Aay Yojna', productCode: '105N203V02', planNumber: 'ICICIPRU053', providerCode: 'ICICI_PRU' },

    //SUD Products 
    { productName: 'SUD Life Sarva Suraksha Bima', productCode: '142N103V01', planNumber: 'SUD-LI-001', providerCode: 'SUD' },
    { productName: 'SUD Life Assured Term Plan', productCode: '142N102V01', planNumber: 'SUD-LI-002', providerCode: 'SUD' },
    { productName: 'SUD Life Smart Term Return of Premium Plan', productCode: '142N097V01', planNumber: 'SUD-LI-003', providerCode: 'SUD' },
    { productName: 'SUD Life Smart Term Plan', productCode: '142N096V01', planNumber: 'SUD-LI-004', providerCode: 'SUD' },
    { productName: 'SUD Life Saral Jeevan Bima', productCode: '142N079V01', planNumber: 'SUD-LI-005', providerCode: 'SUD' },
    { productName: 'SUD Life e-Lifeline', productCode: '142N092V02', planNumber: 'SUD-LI-006', providerCode: 'SUD' },
    { productName: 'SUD Life Simple Term Plan', productCode: '142N095V01', planNumber: 'SUD-LI-007', providerCode: 'SUD' },
    { productName: 'SUD Life E-Wealth Royale Plan', productCode: '142L082V03', planNumber: 'SUD-LI-008', providerCode: 'SUD' },
    { productName: 'SUD Life Star TULIP', productCode: '142L091V01', planNumber: 'SUD-LI-009', providerCode: 'SUD' },
    { productName: 'SUD LIFE Wealth Creator', productCode: '142L077V01', planNumber: 'SUD-LI-010', providerCode: 'SUD' },
    { productName: 'SUD Life Wealth Builder Plan', productCode: '142L042V05', planNumber: 'SUD-LI-011', providerCode: 'SUD' },
    { productName: 'SUD Life Immediate Annuity Plus', productCode: '142N048V08', planNumber: 'SUD-LI-012', providerCode: 'SUD' },
    { productName: 'SUD Life Saral Pension', productCode: '142N081V02', planNumber: 'SUD-LI-013', providerCode: 'SUD' },
    { productName: 'SUD Life Retirement Royale', productCode: '142L099V02', planNumber: 'SUD-LI-014', providerCode: 'SUD' },
    { productName: 'SUD Life Pension Plus', productCode: '142L093V02', planNumber: 'SUD-LI-015', providerCode: 'SUD' },
    { productName: 'SUD Life Smart Guaranteed Pension Plan', productCode: '142N123V01', planNumber: 'SUD-LI-016', providerCode: 'SUD' },
    { productName: 'SUD Life Smart Healthcare', productCode: '142N089V01', planNumber: 'SUD-LI-017', providerCode: 'SUD' },
    { productName: 'SUD Life Health Assure', productCode: '142N098V01', planNumber: 'SUD-LI-018', providerCode: 'SUD' },
    { productName: 'SUD Life Smart Income Plan', productCode: '142N126V01', planNumber: 'SUD-LI-019', providerCode: 'SUD' },
    { productName: 'SUD Life Century Star', productCode: '142N075V04', planNumber: 'SUD-LI-020', providerCode: 'SUD' },
    { productName: 'SUD Life Guaranteed Money Back Plan', productCode: '142N036V06', planNumber: 'SUD-LI-021', providerCode: 'SUD' },
    { productName: 'SUD Life Century Plus', productCode: '142N074V05', planNumber: 'SUD-LI-022', providerCode: 'SUD' },
    { productName: 'SUD Life Samriddhi', productCode: '142N057V02', planNumber: 'SUD-LI-023', providerCode: 'SUD' },
    { productName: 'POS – SUD Life Sanchay', productCode: '142N058V05', planNumber: 'SUD-LI-024', providerCode: 'SUD' },
    { productName: 'SUD Life Century Gold', productCode: '142N087V04', planNumber: 'SUD-LI-025', providerCode: 'SUD' },
    { productName: 'SUD Life Century Royale', productCode: '142N083V05', planNumber: 'SUD-LI-026', providerCode: 'SUD' },
    { productName: 'SUD Life Fortune Royale', productCode: '142N086V03', planNumber: 'SUD-LI-027', providerCode: 'SUD' },
    { productName: 'SUD Life Guarantee Royale', productCode: '142N122V01', planNumber: 'SUD-LI-028', providerCode: 'SUD' },
    { productName: 'SUD Life Century Income', productCode: '142N100V03', planNumber: 'SUD-LI-029', providerCode: 'SUD' },
    { productName: 'SUD Life Centurion', productCode: '142N101V02', planNumber: 'SUD-LI-030', providerCode: 'SUD' },
    { productName: 'SUD Life Assured Returns Plan', productCode: '142N127V01', planNumber: 'SUD-LI-031', providerCode: 'SUD' },
    { productName: 'SUD Life Sampoorna Loan Suraksha Plus', productCode: '142N084V02', planNumber: 'SUD-LI-032', providerCode: 'SUD' },
    { productName: 'SUD Life Pradhan Mantri Jeevan Jyoti Bima Yojana', productCode: '142G047V02', planNumber: 'SUD-LI-033', providerCode: 'SUD' },
    { productName: 'SUD Life Group Term Insurance Plus', productCode: '142N046V04', planNumber: 'SUD-LI-034', providerCode: 'SUD' },
    { productName: 'SUD Life Group Micro Term Insurance Plan', productCode: '142N094V01', planNumber: 'SUD-LI-035', providerCode: 'SUD' },
    { productName: 'SUD Life Group Retirement Benefit Plan', productCode: '142L049V01', planNumber: 'SUD-LI-036', providerCode: 'SUD' },
    { productName: 'SUD Life Group Employee Benefit Plus', productCode: '142N090V01', planNumber: 'SUD-LI-037', providerCode: 'SUD' },
    { productName: 'SUD Life Fortune Plus', productCode: '142N124V01', planNumber: 'SUD-LI-038', providerCode: 'SUD' },
    { productName: 'SUD Life Aadarsh', productCode: '142N054V04', planNumber: 'SUD-LI-039', providerCode: 'SUD' },

    //INDIAFIRST Products
    { productName: 'IndiaFirst Life Elite Term Plan', productCode: '143N070V01', planNumber: 'IF-LI-001', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Life Super Protection Plan', productCode: '143N075V01', planNumber: 'IF-LI-002', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Life Plan', productCode: '143N007V03', planNumber: 'IF-LI-003', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Life Saral Jeevan Bima Plan', productCode: '143N061V01', planNumber: 'IF-LI-004', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Life Protect Shield Plus Plan', productCode: '143N078V01', planNumber: 'IF-LI-005', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Life Assured Income For Milestones Plan', productCode: '143N101V01', planNumber: 'IF-LI-006', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Life Guarantee Of Life Dreams Plan', productCode: '143N080V03', planNumber: 'IF-LI-007', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Life Growth of Life Dreams Plus Plan', productCode: '143N093V02', planNumber: 'IF-LI-008', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Life Long Guaranteed Income Plan', productCode: '143N054V06', planNumber: 'IF-LI-009', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Life Fortune Plus Plan', productCode: '143N065V03', planNumber: 'IF-LI-010', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Life Mahajeevan Plus Plan', productCode: '143N059V03', planNumber: 'IF-LI-011', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Life Cash Back Plan', productCode: '143N024V05', planNumber: 'IF-LI-012', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Life Mahajeevan Plan', productCode: '143N018V05', planNumber: 'IF-LI-013', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Simple Benefit Plan', productCode: '143N019V03', planNumber: 'IF-LI-014', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Life Guaranteed Monthly Income Plan', productCode: '143N047V01', planNumber: 'IF-LI-015', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Life Smart Pay Plan', productCode: '143N051V04', planNumber: 'IF-LI-016', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Life Saral Bachat Bima Plan', productCode: '143N063V02', planNumber: 'IF-LI-017', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Life Micro Bachat Plan', productCode: '143N052V02', planNumber: 'IF-LI-018', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Life Guaranteed Benefit Plan', productCode: '143N056V09', planNumber: 'IF-LI-019', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Life CSC Shubhlabh Plan', productCode: '143N023V01', planNumber: 'IF-LI-020', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Life “INSURANCE KHATA” Plan (MicroInsuranceProduct)', productCode: '143N057V03', planNumber: 'IF-LI-021', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Life POS Cash Back Plan', productCode: '143N034V01', planNumber: 'IF-LI-022', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Life Radiance Smart Invest Plan', productCode: '143L067V01', planNumber: 'IF-LI-023', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Life Wealth Maximizer Plan', productCode: '143L029V05', planNumber: 'IF-LI-024', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Life Money Balance Plan', productCode: '143L017V07', planNumber: 'IF-LI-025', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Smart Save Plan', productCode: '143L010V04', planNumber: 'IF-LI-026', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Life Guaranteed Single Premium Plan', productCode: '143N068V04', planNumber: 'IF-LI-027', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Life Little Champ Plan', productCode: '143N035V02', planNumber: 'IF-LI-028', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst LIfe Smart Retirement Plan', productCode: '143L076V01', planNumber: 'IF-LI-029', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Guaranteed Retirement Plan', productCode: '143N026V02', planNumber: 'IF-LI-030', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Life Guaranteed Annuity Pension Plan', productCode: '143N050V07', planNumber: 'IF-LI-031', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Life Guaranteed Pension Plan', productCode: '143N066V05', planNumber: 'IF-LI-032', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Life Saral Pension Plan', productCode: '143N062V01', planNumber: 'IF-LI-033', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Life Group Living Benefits Plan', productCode: '143N040V02', planNumber: 'IF-LI-034', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Group Term Plan', productCode: '143N006V06', planNumber: 'IF-LI-035', providerCode: 'INDIAFIRST' },
    { productName: 'Group Credit Life Plus Plan', productCode: '143N036V02', planNumber: 'IF-LI-036', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Group Micro Insurance Plan', productCode: '143N053V03', planNumber: 'IF-LI-037', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Life Group Loan Protect Plan', productCode: '143N055V02', planNumber: 'IF-LI-038', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Life Group HospiCare Plan', productCode: '143N039V02', planNumber: 'IF-LI-039', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Life Group Critical Illness Rider Plan', productCode: '143B002V02', planNumber: 'IF-LI-040', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Life Group Additional Benefit Rider Plan', productCode: '143B018V02', planNumber: 'IF-LI-041', providerCode: 'INDIAFIRST' },
    { productName: 'Group Disability Rider', productCode: '143B004V02', planNumber: 'IF-LI-042', providerCode: 'INDIAFIRST' },
    { productName: 'Unit Linked Superannuation Plan', productCode: '143L060V01', planNumber: 'IF-LI-043', providerCode: 'INDIAFIRST' },
    { productName: 'Superannuation Plan', productCode: '143N020V03', planNumber: 'IF-LI-044', providerCode: 'INDIAFIRST' },
    { productName: 'New Corporate Benefit Plan', productCode: '143N022V02', planNumber: 'IF-LI-045', providerCode: 'INDIAFIRST' },
    { productName: 'IndiaFirst Employee Benefit Plan', productCode: '143L013V02', planNumber: 'IF-LI-046', providerCode: 'INDIAFIRST' },

    // TATA_AIA
    { productName: 'Tata AIA Sampoorna Raksha Promise', productCode: '110N176V12', planNumber: 'TATA001', providerCode: 'TATA_AIA' },
    { productName: 'Tata AIA Maha Raksha Supreme Select', productCode: '110N171V15', planNumber: 'TATA002', providerCode: 'TATA_AIA' },
    { productName: 'Tata AIA Smart Sampoorna Raksha Supreme', productCode: '110L179V02', planNumber: 'TATA003', providerCode: 'TATA_AIA' },
    { productName: 'Tata AIA Fortune Guarantee Plus', productCode: '110N158V14', planNumber: 'TATA004', providerCode: 'TATA_AIA' },
    { productName: 'Tata AIA Guaranteed Return Insurance Plan', productCode: '110N152V15', planNumber: 'TATA005', providerCode: 'TATA_AIA' },
    { productName: 'Tata AIA Smart Value Income Plan', productCode: '110N162V03', planNumber: 'TATA006', providerCode: 'TATA_AIA' },
    { productName: 'Tata AIA Smart Fortune Plus', productCode: '110L177V01', planNumber: 'TATA007', providerCode: 'TATA_AIA' },
    { productName: 'Tata AIA Smart SIP', productCode: '110L174V02', planNumber: 'TATA008', providerCode: 'TATA_AIA' },
    { productName: 'Tata AIA Fortune Pro', productCode: '110L112V07', planNumber: 'TATA009', providerCode: 'TATA_AIA' },
    { productName: 'Tata AIA Smart Pension Secure', productCode: '110L182V09', planNumber: 'TATA010', providerCode: 'TATA_AIA' },
    { productName: 'Tata AIA Fortune Guarantee Pension', productCode: '110N161V13', planNumber: 'TATA011', providerCode: 'TATA_AIA' },
    { productName: 'Tata AIA Shubh Family Protect', productCode: '110N176V08', planNumber: 'TATA012', providerCode: 'TATA_AIA' },
    { productName: 'Tata AIA Fortune Guarantee Supreme', productCode: '110N163V12', planNumber: 'TATA013', providerCode: 'TATA_AIA' },
    { productName: 'Tata AIA Fortune Guarantee Secure', productCode: '110N206V03', planNumber: 'TATA014', providerCode: 'TATA_AIA' },
    { productName: 'Tata AIA Life Insurance Fortune Guarantee', productCode: '110N120V12', planNumber: 'TATA015', providerCode: 'TATA_AIA' },
    { productName: 'Tata AIA Smart Income Plus', productCode: '110N126V05', planNumber: 'TATA016', providerCode: 'TATA_AIA' },
    { productName: 'Tata AIA iSIP (i Systematic Insurance Plan)', productCode: '110L164V10', planNumber: 'TATA017', providerCode: 'TATA_AIA' },
    { productName: 'Tata AIA Shubh Muhurat Solution (Combination of Fortune Guarantee Secure + Smart Fortune Plus)', productCode: '110N206V02 + 110L177V01', planNumber: 'TATA018', providerCode: 'TATA_AIA' },
    { productName: 'Tata AIA Smart Sampoorna Raksha Pro', productCode: '110L172V03', planNumber: 'TATA019', providerCode: 'TATA_AIA' },
    { productName: 'Tata AIA Life Insurance Wealth Pro', productCode: '110L111V05', planNumber: 'TATA020', providerCode: 'TATA_AIA' },
    { productName: 'Tata AIA Life Insurance Wealth Maxima', productCode: '110L114V05', planNumber: 'TATA021', providerCode: 'TATA_AIA' },
    { productName: 'Tata AIA Shubh Flexi Pension Plan', productCode: '110N209V02', planNumber: 'TATA022', providerCode: 'TATA_AIA' },
    { productName: 'Tata AIA Life Insurance Saral Pension', productCode: '110N159V09', planNumber: 'TATA023', providerCode: 'TATA_AIA' },
    { productName: 'TATA AIA Fortune Guarantee Retirement Ready', productCode: '110N175V04', planNumber: 'TATA024', providerCode: 'TATA_AIA' },
    { productName: 'Tata AIA Sampoorna Care', productCode: '110N186V01', planNumber: 'TATA025', providerCode: 'TATA_AIA' },
    { productName: 'Tata AIA Health SIP', productCode: '110L184V01', planNumber: 'TATA026', providerCode: 'TATA_AIA' },
    { productName: 'Tata AIA Health Pro', productCode: '110L180V01', planNumber: 'TATA027', providerCode: 'TATA_AIA' },
    
  // Bharti AXA Products
  { productName: 'Bharti AXA Life eProtect', productCode: 'BAXAL001', planNumber: 'BAXAL001', providerCode: 'BHARTI_AXA' },
  { productName: 'Bharti AXA Life Smart Jeevan', productCode: 'BAXAL002', planNumber: 'BAXAL002', providerCode: 'BHARTI_AXA' },
  { productName: 'Bharti AXA Life Flexi Term Plan', productCode: 'BAXAL003', planNumber: 'BAXAL003', providerCode: 'BHARTI_AXA' },
  { productName: 'Bharti AXA Life Smart Swadhan Neo', productCode: 'BAXAL004', planNumber: 'BAXAL004', providerCode: 'BHARTI_AXA' },
  { productName: 'Bharti AXA Life Future Invest', productCode: 'BAXAL005', planNumber: 'BAXAL005', providerCode: 'BHARTI_AXA' },
  { productName: 'Bharti AXA Life Wealth Maxima', productCode: 'BAXAL006', planNumber: 'BAXAL006', providerCode: 'BHARTI_AXA' },
  { productName: 'Bharti AXA Life Grow Wealth', productCode: 'BAXAL007', planNumber: 'BAXAL007', providerCode: 'BHARTI_AXA' },
  { productName: 'Bharti AXA Life Wealth Secure', productCode: 'BAXAL008', planNumber: 'BAXAL008', providerCode: 'BHARTI_AXA' },
  { productName: 'Bharti AXA Life Guaranteed Income Pro', productCode: 'BAXAL009', planNumber: 'BAXAL009', providerCode: 'BHARTI_AXA' },
  { productName: 'Bharti AXA Life Secure Income Plan', productCode: 'BAXAL010', planNumber: 'BAXAL010', providerCode: 'BHARTI_AXA' },
  { productName: 'Bharti AXA Life Monthly Advantage Plan', productCode: 'BAXAL011', planNumber: 'BAXAL011', providerCode: 'BHARTI_AXA' },
  { productName: 'Bharti AXA Life Super Endowment Plan', productCode: 'BAXAL012', planNumber: 'BAXAL012', providerCode: 'BHARTI_AXA' },
  { productName: 'Bharti AXA Life Elite Advantage', productCode: 'BAXAL013', planNumber: 'BAXAL013', providerCode: 'BHARTI_AXA' },
  { productName: 'Bharti AXA Life Shining Stars', productCode: 'BAXAL014', planNumber: 'BAXAL014', providerCode: 'BHARTI_AXA' },
  { productName: 'Bharti AXA Life Child Advantage Plan', productCode: 'BAXAL015', planNumber: 'BAXAL015', providerCode: 'BHARTI_AXA' },
  { productName: 'Bharti AXA Life Pension Maximiser', productCode: 'BAXAL016', planNumber: 'BAXAL016', providerCode: 'BHARTI_AXA' },
  { productName: 'Bharti AXA Life Retire Smart', productCode: 'BAXAL017', planNumber: 'BAXAL017', providerCode: 'BHARTI_AXA' },
  { productName: 'Bharti AXA Life Group Term Insurance', productCode: 'BAXAL018', planNumber: 'BAXAL018', providerCode: 'BHARTI_AXA' },
  { productName: 'Bharti AXA Life Group Credit Shield', productCode: 'BAXAL019', planNumber: 'BAXAL019', providerCode: 'BHARTI_AXA' },
  { productName: 'Bharti AXA Life Critical Illness & Disability Shield', productCode: 'BAXAL020', planNumber: 'BAXAL020', providerCode: 'BHARTI_AXA' },

  // Kotak Life Insurance Products
  { productName: 'Kotak e-Term', productCode: 'KLI-001', planNumber: 'KLI-001', providerCode: 'KOTAK' },
  { productName: 'Kotak Signature Term Plan', productCode: 'KLI-002', planNumber: 'KLI-002', providerCode: 'KOTAK' },
  { productName: 'Kotak Gen2Gen Protect', productCode: 'KLI-003', planNumber: 'KLI-003', providerCode: 'KOTAK' },
  { productName: 'Kotak e-Invest Plus', productCode: 'KLI-004', planNumber: 'KLI-004', providerCode: 'KOTAK' },
  { productName: 'Kotak T.U.L.I.P', productCode: 'KLI-005', planNumber: 'KLI-005', providerCode: 'KOTAK' },
  { productName: 'Kotak Invest Maxima', productCode: 'KLI-006', planNumber: 'KLI-006', providerCode: 'KOTAK' },
  { productName: 'Kotak Single Invest Advantage', productCode: 'KLI-007', planNumber: 'KLI-007', providerCode: 'KOTAK' },
  { productName: 'Kotak Platinum', productCode: 'KLI-008', planNumber: 'KLI-008', providerCode: 'KOTAK' },
  { productName: 'Kotak Wealth Optima', productCode: 'KLI-009', planNumber: 'KLI-009', providerCode: 'KOTAK' },
  { productName: 'Kotak Classic Endowment Plan', productCode: 'KLI-010', planNumber: 'KLI-010', providerCode: 'KOTAK' },
  { productName: 'Kotak Premier Endowment Plan', productCode: 'KLI-011', planNumber: 'KLI-011', providerCode: 'KOTAK' },
  { productName: 'Kotak Assured Income Accelerator', productCode: 'KLI-012', planNumber: 'KLI-012', providerCode: 'KOTAK' },
  { productName: 'Kotak e-Invest Retire Rich', productCode: 'KLI-013', planNumber: 'KLI-013', providerCode: 'KOTAK' },
  { productName: 'Kotak Confident Retirement Builder', productCode: 'KLI-014', planNumber: 'KLI-014', providerCode: 'KOTAK' },
  { productName: 'Kotak Confident Retirement Savings Plan', productCode: 'KLI-015', planNumber: 'KLI-015', providerCode: 'KOTAK' },
  { productName: 'Kotak e-Invest Rising Star', productCode: 'KLI-016', planNumber: 'KLI-016', providerCode: 'KOTAK' },
  { productName: 'Kotak Gen2Gen Income', productCode: 'KLI-017', planNumber: 'KLI-017', providerCode: 'KOTAK' },
  { productName: 'Kotak Personal Accident Insurance', productCode: 'KLI-018', planNumber: 'KLI-018', providerCode: 'KOTAK' },

  // Zurich Kotak General Insurance Products
  { productName: 'Zurich Kotak Health Care', productCode: 'ZKG-001', planNumber: 'ZKG-001', providerCode: 'ZURICH_KOTAK' },
  { productName: 'Zurich Kotak Health Premium', productCode: 'ZKG-002', planNumber: 'ZKG-002', providerCode: 'ZURICH_KOTAK' },
  { productName: 'Zurich Kotak Secure Shield', productCode: 'ZKG-003', planNumber: 'ZKG-003', providerCode: 'ZURICH_KOTAK' },
  { productName: 'Zurich Kotak Health Super Top-up', productCode: 'ZKG-004', planNumber: 'ZKG-004', providerCode: 'ZURICH_KOTAK' },
  { productName: 'Zurich Kotak Accident Care', productCode: 'ZKG-005', planNumber: 'ZKG-005', providerCode: 'ZURICH_KOTAK' },
  { productName: 'Zurich Kotak Corona Kavach', productCode: 'ZKG-006', planNumber: 'ZKG-006', providerCode: 'ZURICH_KOTAK' },
  { productName: 'Zurich Kotak Covid-19 Secure', productCode: 'ZKG-007', planNumber: 'ZKG-007', providerCode: 'ZURICH_KOTAK' },
  { productName: 'Zurich Kotak Car Secure - Comprehensive', productCode: 'ZKG-008', planNumber: 'ZKG-008', providerCode: 'ZURICH_KOTAK' },
  { productName: 'Zurich Kotak Car Secure - Third Party', productCode: 'ZKG-009', planNumber: 'ZKG-009', providerCode: 'ZURICH_KOTAK' },
  { productName: 'Zurich Kotak Stand-Alone Own Damage', productCode: 'ZKG-010', planNumber: 'ZKG-010', providerCode: 'ZURICH_KOTAK' },
  { productName: 'Zurich Kotak Two Wheeler Secure - Comprehensive', productCode: 'ZKG-011', planNumber: 'ZKG-011', providerCode: 'ZURICH_KOTAK' },
  { productName: 'Zurich Kotak Two Wheeler Secure - Third Party', productCode: 'ZKG-012', planNumber: 'ZKG-012', providerCode: 'ZURICH_KOTAK' },
  { productName: 'Zurich Kotak Commercial Vehicle - Passenger', productCode: 'ZKG-013', planNumber: 'ZKG-013', providerCode: 'ZURICH_KOTAK' },
  { productName: 'Zurich Kotak Commercial Vehicle - Goods', productCode: 'ZKG-014', planNumber: 'ZKG-014', providerCode: 'ZURICH_KOTAK' },
  { productName: 'Zurich Kotak Home Secure', productCode: 'ZKG-015', planNumber: 'ZKG-015', providerCode: 'ZURICH_KOTAK' },
  { productName: 'Zurich Kotak Group Health Care', productCode: 'ZKG-016', planNumber: 'ZKG-016', providerCode: 'ZURICH_KOTAK' },
  { productName: 'Zurich Kotak Group Secure Shield', productCode: 'ZKG-017', planNumber: 'ZKG-017', providerCode: 'ZURICH_KOTAK' },
  { productName: 'Zurich Kotak Group Accident Protect', productCode: 'ZKG-018', planNumber: 'ZKG-018', providerCode: 'ZURICH_KOTAK' },
  { productName: 'Zurich Kotak Group Smart Cash', productCode: 'ZKG-019', planNumber: 'ZKG-019', providerCode: 'ZURICH_KOTAK' },

  // Digit Life Insurance Products
  { productName: 'Digit Glow Term Life Insurance', productCode: 'DL-001', planNumber: 'DL-001', providerCode: 'DIGIT' },
  { productName: 'Digit Glow Plus Term Life Insurance', productCode: 'DL-002', planNumber: 'DL-002', providerCode: 'DIGIT' },
  { productName: 'Digit Glow Lite Term Life Insurance', productCode: 'DL-003', planNumber: 'DL-003', providerCode: 'DIGIT' },
  { productName: 'Digit Glow Term Life Insurance – Increasing Cover', productCode: 'DL-004', planNumber: 'DL-004', providerCode: 'DIGIT' },
  { productName: 'Digit Glow Term Life Insurance – Whole Life Option', productCode: 'DL-005', planNumber: 'DL-005', providerCode: 'DIGIT' },
  { productName: 'Digit ICON Guaranteed Returns Savings Plan – Income Benefit', productCode: 'DL-006', planNumber: 'DL-006', providerCode: 'DIGIT' },
  { productName: 'Digit ICON Guaranteed Returns Savings Plan – Lumpsum Benefit', productCode: 'DL-007', planNumber: 'DL-007', providerCode: 'DIGIT' },
  { productName: 'Digit ICON Guaranteed Returns Savings Plan – Income + Lumpsum', productCode: 'DL-008', planNumber: 'DL-008', providerCode: 'DIGIT' },
  { productName: 'Digit ICON Guaranteed Returns Savings Plan – Whole Life Benefit', productCode: 'DL-009', planNumber: 'DL-009', providerCode: 'DIGIT' },
  { productName: 'Single Premium Guaranteed Income Plan', productCode: 'DL-010', planNumber: 'DL-010', providerCode: 'DIGIT' },
  { productName: 'Guaranteed Pension Plan', productCode: 'DL-011', planNumber: 'DL-011', providerCode: 'DIGIT' },
  { productName: 'Unit Linked Pension Plan (ULPP)', productCode: 'DL-012', planNumber: 'DL-012', providerCode: 'DIGIT' },
  { productName: 'Digit Life ULIP Plan – Growth Fund', productCode: 'DL-013', planNumber: 'DL-013', providerCode: 'DIGIT' },
  { productName: 'Digit Life ULIP Plan – Balanced Fund', productCode: 'DL-014', planNumber: 'DL-014', providerCode: 'DIGIT' },
  { productName: 'Digit Life ULIP Plan – Debt Fund', productCode: 'DL-015', planNumber: 'DL-015', providerCode: 'DIGIT' },
  { productName: 'Digit Life Group Term Life Insurance', productCode: 'DL-016', planNumber: 'DL-016', providerCode: 'DIGIT' },
  { productName: 'Digit Life Group Long Term Plan', productCode: 'DL-017', planNumber: 'DL-017', providerCode: 'DIGIT' },
  { productName: 'Digit Life Group Micro Term Life Insurance', productCode: 'DL-018', planNumber: 'DL-018', providerCode: 'DIGIT' },
  { productName: 'Digit Life Endowment Plan', productCode: 'DL-019', planNumber: 'DL-019', providerCode: 'DIGIT' },
  { productName: 'Digit Life Money Back Plan', productCode: 'DL-020', planNumber: 'DL-020', providerCode: 'DIGIT' },
  { productName: 'Digit Life Child Education Plan', productCode: 'DL-021', planNumber: 'DL-021', providerCode: 'DIGIT' },
  { productName: 'Digit Life Child ULIP Plan', productCode: 'DL-022', planNumber: 'DL-022', providerCode: 'DIGIT' },
  { productName: 'Digit Life Whole Life Insurance Plan', productCode: 'DL-023', planNumber: 'DL-023', providerCode: 'DIGIT' },
  { productName: 'Digit Life Critical Illness Rider', productCode: 'DL-024', planNumber: 'DL-024', providerCode: 'DIGIT' },
  { productName: 'Digit Life Accidental Death Benefit Rider', productCode: 'DL-025', planNumber: 'DL-025', providerCode: 'DIGIT' },
  { productName: 'Digit Life Waiver of Premium Rider', productCode: 'DL-026', planNumber: 'DL-026', providerCode: 'DIGIT' },
  { productName: 'Digit Life Terminal Illness Benefit Rider', productCode: 'DL-027', planNumber: 'DL-027', providerCode: 'DIGIT' },
  { productName: 'Digit Life Guaranteed Income Plan', productCode: 'DL-028', planNumber: 'DL-028', providerCode: 'DIGIT' },
  { productName: 'Digit Life Single Premium Guaranteed Income Plan', productCode: 'DL-029', planNumber: 'DL-029', providerCode: 'DIGIT' },
  { productName: 'Digit Glow Term Life Insurance – NRI Plan', productCode: 'DL-030', planNumber: 'DL-030', providerCode: 'DIGIT' },
  { productName: 'Digit Life Group Long Term Plan – Credit Linked', productCode: 'DL-031', planNumber: 'DL-031', providerCode: 'DIGIT' },
  { productName: 'Digit ICON Guaranteed Returns – Customised Anniversary Payout', productCode: 'DL-032', planNumber: 'DL-032', providerCode: 'DIGIT' },
  { productName: 'Digit Life Retirement Income Plan', productCode: 'DL-033', planNumber: 'DL-033', providerCode: 'DIGIT' },
  { productName: 'Digit Life Joint Life Term Plan', productCode: 'DL-034', planNumber: 'DL-034', providerCode: 'DIGIT' },
  { productName: 'Digit Life Return of Premium Term Plan', productCode: 'DL-035', planNumber: 'DL-035', providerCode: 'DIGIT' },

  // DHFL Pramerica Life Insurance Products
  { productName: 'Pramerica Life U-Protect Plan', productCode: 'PL-TERM-001', planNumber: 'PL-TERM-001', providerCode: 'DHFL_PRAMERICA' },
  { productName: 'Pramerica Life TruShield Term Plan', productCode: 'PL-TERM-002', planNumber: 'PL-TERM-002', providerCode: 'DHFL_PRAMERICA' },
  { productName: 'Pramerica Life Saral Jeevan Bima', productCode: 'PL-TERM-003', planNumber: 'PL-TERM-003', providerCode: 'DHFL_PRAMERICA' },
  { productName: 'Pramerica Life Family Income Plan', productCode: 'PL-TERM-004', planNumber: 'PL-TERM-004', providerCode: 'DHFL_PRAMERICA' },
  { productName: 'Pramerica Life Family First Plan', productCode: 'PL-TERM-005', planNumber: 'PL-TERM-005', providerCode: 'DHFL_PRAMERICA' },
  { productName: 'Pramerica Life Secure Savings Plan', productCode: 'PL-SAV-001', planNumber: 'PL-SAV-001', providerCode: 'DHFL_PRAMERICA' },
  { productName: 'Pramerica Life Smart Income Plan', productCode: 'PL-SAV-002', planNumber: 'PL-SAV-002', providerCode: 'DHFL_PRAMERICA' },
  { productName: 'Pramerica Life Smart Assure', productCode: 'PL-SAV-003', planNumber: 'PL-SAV-003', providerCode: 'DHFL_PRAMERICA' },
  { productName: 'Pramerica Life Flexi Cash Plan', productCode: 'PL-SAV-004', planNumber: 'PL-SAV-004', providerCode: 'DHFL_PRAMERICA' },
  { productName: 'Pramerica Life Smart Cash Protect', productCode: 'PL-SAV-005', planNumber: 'PL-SAV-005', providerCode: 'DHFL_PRAMERICA' },
  { productName: 'Pramerica Life Roz Sanchay', productCode: 'PL-SAV-006', planNumber: 'PL-SAV-006', providerCode: 'DHFL_PRAMERICA' },
  { productName: 'Pramerica Life Magnum Assure', productCode: 'PL-SAV-007', planNumber: 'PL-SAV-007', providerCode: 'DHFL_PRAMERICA' },
  { productName: 'Pramerica Life Flexi Income Plan', productCode: 'PL-SAV-008', planNumber: 'PL-SAV-008', providerCode: 'DHFL_PRAMERICA' },
  { productName: 'Pramerica Life Signature Wealth', productCode: 'PL-SAV-009', planNumber: 'PL-SAV-009', providerCode: 'DHFL_PRAMERICA' },
  { productName: 'Pramerica Life RockSolid Future', productCode: 'PL-SAV-010', planNumber: 'PL-SAV-010', providerCode: 'DHFL_PRAMERICA' },
  { productName: 'Pramerica Life Wealth Maximiser', productCode: 'PL-SAV-011', planNumber: 'PL-SAV-011', providerCode: 'DHFL_PRAMERICA' },
  { productName: 'Pramerica Life Wealth+ Ace', productCode: 'PL-ULIP-001', planNumber: 'PL-ULIP-001', providerCode: 'DHFL_PRAMERICA' },
  { productName: 'Pramerica Life Smart Wealth+', productCode: 'PL-ULIP-002', planNumber: 'PL-ULIP-002', providerCode: 'DHFL_PRAMERICA' },
  { productName: 'Pramerica Life Super Investment Plan', productCode: 'PL-ULIP-003', planNumber: 'PL-ULIP-003', providerCode: 'DHFL_PRAMERICA' },
  { productName: 'Pramerica Life Smart Invest', productCode: 'PL-ULIP-004', planNumber: 'PL-ULIP-004', providerCode: 'DHFL_PRAMERICA' },
  { productName: 'Pramerica Life Wealth Enhancer', productCode: 'PL-ULIP-005', planNumber: 'PL-ULIP-005', providerCode: 'DHFL_PRAMERICA' },
  { productName: 'Pramerica Life Wealth Maximiser (ULIP)', productCode: 'PL-ULIP-006', planNumber: 'PL-ULIP-006', providerCode: 'DHFL_PRAMERICA' },
  { productName: 'Pramerica Life Cancer + Heart Shield', productCode: 'PL-HLTH-001', planNumber: 'PL-HLTH-001', providerCode: 'DHFL_PRAMERICA' },
  { productName: 'Pramerica Life Rakshak Smart', productCode: 'PL-CHLD-001', planNumber: 'PL-CHLD-001', providerCode: 'DHFL_PRAMERICA' },
  { productName: 'Pramerica Life Rakshak Gold', productCode: 'PL-CHLD-002', planNumber: 'PL-CHLD-002', providerCode: 'DHFL_PRAMERICA' },
  { productName: 'Pramerica Life Smart Fee Protect Plan', productCode: 'PL-CHLD-003', planNumber: 'PL-CHLD-003', providerCode: 'DHFL_PRAMERICA' },
  { productName: 'Pramerica Life Saral Pension', productCode: 'PL-RET-001', planNumber: 'PL-RET-001', providerCode: 'DHFL_PRAMERICA' },
  { productName: 'Pramerica Life NextGen Pension Plan', productCode: 'PL-RET-002', planNumber: 'PL-RET-002', providerCode: 'DHFL_PRAMERICA' },
  { productName: 'Pramerica Life Aajeevan Samriddhi', productCode: 'PL-RET-003', planNumber: 'PL-RET-003', providerCode: 'DHFL_PRAMERICA' },
  { productName: 'Pramerica Life Group Total Protection', productCode: 'PL-GRP-001', planNumber: 'PL-GRP-001', providerCode: 'DHFL_PRAMERICA' },
  { productName: 'Pramerica Life Group Credit Shield', productCode: 'PL-GRP-002', planNumber: 'PL-GRP-002', providerCode: 'DHFL_PRAMERICA' },
  { productName: 'Pramerica Life Group Term Plan', productCode: 'PL-GRP-003', planNumber: 'PL-GRP-003', providerCode: 'DHFL_PRAMERICA' },
  { productName: 'Pramerica Life Sarv Suraksha (Group Micro)', productCode: 'PL-GRP-004', planNumber: 'PL-GRP-004', providerCode: 'DHFL_PRAMERICA' },
];
